### ISSUE TITLE
ActiveAdmin prevents migration because of one filter

### ISSUE THREAD

**Issue by vitali-raikov** [activeadmin/activeadmin#1360]
It appears that this filter:

``` ruby
filter :user, :label => 'User', :collection => User.all.map(&:email)
```

Prevents migration, it just fails on the first table with this error:

``` sql
Mysql2::Error: Table 'adv_development.users' doesn't exist: SHOW FULL FIELDS FROM
```

I made this filter to achieve user selection in dropdown in filter and it works quite well, it's just I have to disable this filter before migration, then I can enable it again.

Ruby vesrion: ruby 1.9.3p0
Rails version:  Rails 3.2.2

Here is the full trace of why is it failing.

``` text
vitali@vitali-desktop:~/advertstar$ rake db:migrate --trace
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
Mysql2::Error: Table 'adv_development.users' doesn't exist: SHOW FULL FIELDS FROM `users`
/usr/lib/ruby/gems/1.9.1/gems/activerecord-3.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:243:in `query'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-3.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:243:in `block in execute'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-3.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
/usr/lib/ruby/gems/1.9.1/gems/activesupport-3.2.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-3.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-3.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:243:in `execute'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-3.2.2/lib/active_record/connection_adapters/mysql2_adapter.rb:211:in `execute'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-3.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:257:in `execute_and_free'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-3.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:424:in `columns'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-3.2.2/lib/active_record/connection_adapters/schema_cache.rb:12:in `block in initialize'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-3.2.2/lib/active_record/model_schema.rb:228:in `yield'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-3.2.2/lib/active_record/model_schema.rb:228:in `default'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-3.2.2/lib/active_record/model_schema.rb:228:in `columns'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-3.2.2/lib/active_record/model_schema.rb:237:in `columns_hash'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-3.2.2/lib/active_record/locking/optimistic.rb:129:in `locking_enabled?'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-3.2.2/lib/active_record/relation.rb:170:in `exec_queries'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-3.2.2/lib/active_record/relation.rb:160:in `block in to_a'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-3.2.2/lib/active_record/explain.rb:33:in `logging_query_plan'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-3.2.2/lib/active_record/relation.rb:159:in `to_a'
/usr/lib/ruby/gems/1.9.1/gems/activerecord-3.2.2/lib/active_record/relation/delegation.rb:6:in `map'
/home/vitali/advertstar/app/admin/webmaster_sites.rb:6:in `block in <top (required)>'
/usr/lib/ruby/gems/1.9.1/gems/activeadmin-0.4.4/lib/active_admin/dsl.rb:13:in `instance_eval'
/usr/lib/ruby/gems/1.9.1/gems/activeadmin-0.4.4/lib/active_admin/dsl.rb:13:in `run_registration_block'
/usr/lib/ruby/gems/1.9.1/gems/activeadmin-0.4.4/lib/active_admin/namespace.rb:178:in `parse_registration_block'
/usr/lib/ruby/gems/1.9.1/gems/activeadmin-0.4.4/lib/active_admin/namespace.rb:54:in `register'
/usr/lib/ruby/gems/1.9.1/gems/activeadmin-0.4.4/lib/active_admin/application.rb:99:in `register'
/usr/lib/ruby/gems/1.9.1/gems/activeadmin-0.4.4/lib/active_admin.rb:74:in `register'
/home/vitali/advertstar/app/admin/webmaster_sites.rb:2:in `<top (required)>'
/usr/lib/ruby/gems/1.9.1/gems/activesupport-3.2.2/lib/active_support/dependencies.rb:245:in `load'
/usr/lib/ruby/gems/1.9.1/gems/activesupport-3.2.2/lib/active_support/dependencies.rb:245:in `block in load'
/usr/lib/ruby/gems/1.9.1/gems/activesupport-3.2.2/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/lib/ruby/gems/1.9.1/gems/activesupport-3.2.2/lib/active_support/dependencies.rb:245:in `load'
/usr/lib/ruby/gems/1.9.1/gems/activeadmin-0.4.4/lib/active_admin/application.rb:161:in `block in load!'
/usr/lib/ruby/gems/1.9.1/gems/activeadmin-0.4.4/lib/active_admin/application.rb:161:in `each'
/usr/lib/ruby/gems/1.9.1/gems/activeadmin-0.4.4/lib/active_admin/application.rb:161:in `load!'
/usr/lib/ruby/gems/1.9.1/gems/activeadmin-0.4.4/lib/active_admin/application.rb:187:in `routes'
/usr/lib/ruby/gems/1.9.1/gems/activeadmin-0.4.4/lib/active_admin.rb:78:in `routes'
/home/vitali/advertstar/config/routes.rb:3:in `block in <top (required)>'
/usr/lib/ruby/gems/1.9.1/gems/actionpack-3.2.2/lib/action_dispatch/routing/route_set.rb:276:in `instance_exec'
/usr/lib/ruby/gems/1.9.1/gems/actionpack-3.2.2/lib/action_dispatch/routing/route_set.rb:276:in `eval_block'
/usr/lib/ruby/gems/1.9.1/gems/actionpack-3.2.2/lib/action_dispatch/routing/route_set.rb:254:in `draw'
/home/vitali/advertstar/config/routes.rb:1:in `<top (required)>'
/usr/lib/ruby/gems/1.9.1/gems/activesupport-3.2.2/lib/active_support/dependencies.rb:245:in `load'
/usr/lib/ruby/gems/1.9.1/gems/activesupport-3.2.2/lib/active_support/dependencies.rb:245:in `block in load'
/usr/lib/ruby/gems/1.9.1/gems/activesupport-3.2.2/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/lib/ruby/gems/1.9.1/gems/activesupport-3.2.2/lib/active_support/dependencies.rb:245:in `load'
/usr/lib/ruby/gems/1.9.1/gems/railties-3.2.2/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
/usr/lib/ruby/gems/1.9.1/gems/railties-3.2.2/lib/rails/application/routes_reloader.rb:40:in `each'
/usr/lib/ruby/gems/1.9.1/gems/railties-3.2.2/lib/rails/application/routes_reloader.rb:40:in `load_paths'
/usr/lib/ruby/gems/1.9.1/gems/railties-3.2.2/lib/rails/application/routes_reloader.rb:16:in `reload!'
/usr/lib/ruby/gems/1.9.1/gems/railties-3.2.2/lib/rails/application.rb:108:in `reload_routes!'
/usr/lib/ruby/gems/1.9.1/gems/activeadmin-0.4.4/lib/active_admin/reloader.rb:34:in `reload!'
/usr/lib/ruby/gems/1.9.1/gems/activeadmin-0.4.4/lib/active_admin/reloader.rb:61:in `block in attach!'
/usr/lib/ruby/gems/1.9.1/gems/activesupport-3.2.2/lib/active_support/callbacks.rb:429:in `_run__2003460589266378899__prepare__2730696565760933600__callbacks'
/usr/lib/ruby/gems/1.9.1/gems/activesupport-3.2.2/lib/active_support/callbacks.rb:405:in `__run_callback'
/usr/lib/ruby/gems/1.9.1/gems/activesupport-3.2.2/lib/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
/usr/lib/ruby/gems/1.9.1/gems/activesupport-3.2.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/lib/ruby/gems/1.9.1/gems/actionpack-3.2.2/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
/usr/lib/ruby/gems/1.9.1/gems/actionpack-3.2.2/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
/usr/lib/ruby/gems/1.9.1/gems/railties-3.2.2/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
/usr/lib/ruby/gems/1.9.1/gems/railties-3.2.2/lib/rails/initializable.rb:30:in `instance_exec'
/usr/lib/ruby/gems/1.9.1/gems/railties-3.2.2/lib/rails/initializable.rb:30:in `run'
/usr/lib/ruby/gems/1.9.1/gems/railties-3.2.2/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/lib/ruby/gems/1.9.1/gems/railties-3.2.2/lib/rails/initializable.rb:54:in `each'
/usr/lib/ruby/gems/1.9.1/gems/railties-3.2.2/lib/rails/initializable.rb:54:in `run_initializers'
/usr/lib/ruby/gems/1.9.1/gems/railties-3.2.2/lib/rails/application.rb:136:in `initialize!'
/usr/lib/ruby/gems/1.9.1/gems/railties-3.2.2/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/vitali/advertstar/config/environment.rb:5:in `<top (required)>'
/usr/lib/ruby/gems/1.9.1/gems/activesupport-3.2.2/lib/active_support/dependencies.rb:251:in `require'
/usr/lib/ruby/gems/1.9.1/gems/activesupport-3.2.2/lib/active_support/dependencies.rb:251:in `block in require'
/usr/lib/ruby/gems/1.9.1/gems/activesupport-3.2.2/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/lib/ruby/gems/1.9.1/gems/activesupport-3.2.2/lib/active_support/dependencies.rb:251:in `require'
/usr/lib/ruby/gems/1.9.1/gems/railties-3.2.2/lib/rails/application.rb:103:in `require_environment!'
/usr/lib/ruby/gems/1.9.1/gems/railties-3.2.2/lib/rails/application.rb:292:in `block (2 levels) in initialize_tasks'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:176:in `block in invoke_prerequisites'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `each'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/usr/lib/ruby/gems/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/usr/bin/rake:19:in `load'
/usr/bin/rake:19:in `<main>'
Tasks: TOP => db:migrate => environment
```

Any help regarding this issue is highly appreciated.

**Comment by alexander-lazarov** [comment]
I had a similar problem, but I couldn't figure out how to fix it by wrapping the problem code with a proc,. That's why I used an ugly fix - begin/rescue construction to suppress the exception from bubbling up and halting the database migration. Not the best code in the world, but couldn't fix it better. Hope it helps someone.

```ruby
ActiveAdmin.register Entry do
  belongs_to :event
  navigation_menu :event

  scope :all, default: true

  # The code in the rescue block is executed during DB migrations
  # this raises an exception because event_class table might not be created
  # yet so this is an (ugly) workaround to make db:migrate task work.
  # For more info see https://github.com/activeadmin/activeadmin/issues/1360
  begin
    EventClass.all.each do |event_class|
      curr = proc { event_class.event.id == @event.id }
      scope event_class.name + ' - ' + event_class.event.name,
            if: curr do |scope|
        scope.where(event_class_id: event_class.id)
      end
    end
  rescue ActiveRecord::StatementInvalid
  end
end
```

**Comment by ollieh-m** [comment]
@latortuga Thanks very much for your explanation. I'm trying to clarify whether active admin treats collections for inputs in the same way? i.e. if an input collection is not in a proc will it only be evaluated once?
