### ISSUE TITLE
Support regular arrays for table_for

### ISSUE THREAD

**Issue by hron84** [activeadmin/activeadmin#1713]
I trying to use `table_for` with an array of Resque::Worker objects, but I get a ton of errors, like:

```
ActionView::Template::Error (undefined method `to_key' for #<Worker laptop.local:14236:*>):
    1: insert_tag active_admin_application.view_factory["page"]
  app/admin/dashboards.rb:44
  app/admin/dashboards.rb:42
  app/admin/dashboards.rb:41
  app/admin/dashboards.rb:40
  actionpack (3.1.3) lib/action_controller/record_identifier.rb:76:in `record_key_for_dom_id'
  actionpack (3.1.3) lib/action_controller/record_identifier.rb:57:in `dom_id'
  arbre (1.0.1) lib/arbre/element.rb:175:in `send'
  arbre (1.0.1) lib/arbre/element.rb:175:in `method_missing'
  activeadmin (0.5.0) lib/active_admin/views/components/table_for.rb:88:in `build_table_body'
  activeadmin (0.5.0) lib/active_admin/views/components/table_for.rb:88:in `each'
  activeadmin (0.5.0) lib/active_admin/views/components/table_for.rb:88:in `build_table_body'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:31:in `build_tag'
  arbre (1.0.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:14:in `tbody'
  activeadmin (0.5.0) lib/active_admin/views/components/table_for.rb:86:in `build_table_body'
  activeadmin (0.5.0) lib/active_admin/views/components/table_for.rb:53:in `build_table'
  activeadmin (0.5.0) lib/active_admin/views/components/table_for.rb:15:in `build'
 [ ... snip ...]
```

I tried to create monkey-patch for this in Resque::Worker but I gave up because AA code strongly assumes the object is an AR object.

Example code:

``` ruby
ActiveAdmin.register_page "Dashboard" do
  content :title => proc{ I18n.t("active_admin.dashboard") } do
    columns do
      column do
        panel "Resque workers" do
          if Resque.workers.size > 0
            table_for Resque.workers do |t|
              t.column(:host)   { |worker| host = worker.to_s.split(/:/).first; link_to host, "/tasks/workers/#{worker}" }
              t.column(:pid)    { |worker| worker.to_s.split(/:/)[1]   }
              t.column(:queues) { |worker| worker.to_s.split(/:/).last.split(',').map { |q| link_to q, "/tasks/queues/#{q}" }.join }
              t.column(:status) do |worker|
                data = worker.processing || {}
                if data['queue']
                  code { data['payload']['class'] }
                  small { link_to "/tasks/working/#{worker}", data['run_at'] }
                else
                  code { "Waiting for a job ..." }
                end
              end
            end
          end
        end
      end
    end
  end
end
```

**Comment by darrenterhune** [comment]
This is old.... but people still stuck pre 1.0.0 in older rails you can just build the table manually:

```ruby
table do
  thead do
    tr do
      th 'Name'
      th 'Email'
    end
  end
  tbody do
    User.limit(10).each do |user|
      tr do
        td do
          user.name
        end
        td do
          user.email
        end
      end
    end
  end
end
```

**Comment by hron84** [comment]
@darrenterhune in this way IIRC we will lose classes and stuff that needed to be applied to tables look natural with other AA tables.

**Comment by darrenterhune** [comment]
@hron84 your original post you have a table inside a panel, so it's not going to look the same as an index table. That said there's nothing stopping you from applying the AA classes and ids just by passing args to `table` like this:

``` ruby
table id: 'index_table_users', class: 'index_table index' do
end
```
```html
<table border="0" cellspacing="0" cellpadding="0" id="index_table_users" class="index_table index">
</table>
```

If you look at the html generated by AA for other tables (styled how you want), you can just copy the styles and apply to your manual table.

Sure this isn't perfect, but at least you can accomplish what your after.

**Comment by hron84** [comment]
True. My complaints are not four you, but for the developers.
