### ISSUE TITLE
getting "We're sorry, but something went wrong." from heroku

### ISSUE THREAD

**Issue by murtyk** [activeadmin/activeadmin#1784]
Following advice on the net, I added the following to staging.rb:

<b> config.assets.compile = true</b>

and in config/application.rb:

<b>config.assets.initialize_on_precompile = false</b>

and moved sass-rails gem out of asset group.

I am still getting the error. The last few lines of heroku log:

2012-11-24T21:32:25+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/controllers/controller.rb:86:in `start'
2012-11-24T21:32:25+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/rack-1.4.1/lib/rack/etag.rb:23:in`call'
2012-11-24T21:32:25+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.7/lib/action_dispatch/middleware/head.rb:14:in `call'
2012-11-24T21:32:25+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.7/lib/active_support/callbacks.rb:405:in`__run_callback'
2012-11-24T21:32:25+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
2012-11-24T21:32:25+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/server.rb:159:in`start'
2012-11-24T21:32:25+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/railties-3.2.7/lib/rails/application.rb:220:in `call'
2012-11-24T21:32:25+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/backends/base.rb:63:in`start'
2012-11-24T21:32:25+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/thin-1.5.0/lib/thin/runner.rb:152:in `run!'
2012-11-24T21:32:25+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.7/lib/action_dispatch/middleware/request_id.rb:22:in`call'
2012-11-24T21:32:25+00:00 heroku[router]: at=info method=GET path=/admin/login host=xmsrps.herokuapp.com fwd= dyno=web.1 queue=0 wait=0ms connect=1ms service=83ms status=500 bytes=643
2012-11-24T21:32:25+00:00 app[web.1]: 
2012-11-24T21:32:25+00:00 app[web.1]: 
2012-11-24T21:32:25+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/bin/thin:19:in `<main>'
2012-11-24T21:32:25+00:00 app[web.1]:   vendor/bundle/ruby/1.9.1/bin/thin:19:in`load'

**Comment by Praveen-Invoscape** [comment]
I am also have this same issue anyone help me....

**Comment by obnoxiousVeges** [comment]
this thread is old, but same.
