### ISSUE TITLE
new version seems to be breaking with "uninitialized constant DashboardController"

### ISSUE THREAD

**Issue by arun057** [activeadmin/activeadmin#2053]
```
ActionController::RoutingError - uninitialized constant DashboardController:
  (gem) actionpack-3.2.11/lib/action_controller/metal/exceptions.rb:11:in `initialize'
  (gem) actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:57:in `rescue in controller'
  (gem) actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:52:in `controller'
  (gem) actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:32:in `call'
  (gem) journey-1.0.4/lib/journey/router.rb:68:in `block in call'
  (gem) journey-1.0.4/lib/journey/router.rb:56:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/routing/route_set.rb:601:in `call'
  (gem) rack-webconsole-0.1.4/lib/rack/webconsole/assets.rb:26:in `call'
  (gem) rack-webconsole-0.1.4/lib/rack/webconsole.rb:79:in `call'
  (gem) bullet-4.5.0/lib/bullet/rack.rb:11:in `call'
  (gem) meta_request-0.2.3/lib/meta_request/middlewares/app_request_handler.rb:11:in `call'
  (gem) rack-contrib-1.1.0/lib/rack/contrib/response_headers.rb:17:in `call'
  (gem) meta_request-0.2.3/lib/meta_request/middlewares/headers.rb:16:in `call'
  (gem) meta_request-0.2.3/lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  (gem) warden-1.2.1/lib/warden/manager.rb:35:in `block in call'
  (gem) warden-1.2.1/lib/warden/manager.rb:34:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  (gem) rack-1.4.5/lib/rack/etag.rb:23:in `call'
  (gem) rack-1.4.5/lib/rack/conditionalget.rb:25:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/head.rb:14:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/flash.rb:242:in `call'
  (gem) rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
  (gem) rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/cookies.rb:341:in `call'
  (gem) activerecord-3.2.11/lib/active_record/query_cache.rb:64:in `call'
  (gem) activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `_run__1046923500032580707__call__4520177692257412513__callbacks'
  (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:405:in `__run_callback'
  (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  (gem) activesupport-3.2.11/lib/active_support/callbacks.rb:81:in `run_callbacks'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/reloader.rb:65:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  (gem) better_errors-0.7.2/lib/better_errors/middleware.rb:84:in `protected_app_call'
  (gem) better_errors-0.7.2/lib/better_errors/middleware.rb:79:in `better_errors_call'
  (gem) better_errors-0.7.2/lib/better_errors/middleware.rb:56:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  (gem) railties-3.2.11/lib/rails/rack/logger.rb:32:in `call_app'
  (gem) railties-3.2.11/lib/rails/rack/logger.rb:16:in `block in call'
  (gem) activesupport-3.2.11/lib/active_support/tagged_logging.rb:22:in `tagged'
  (gem) railties-3.2.11/lib/rails/rack/logger.rb:16:in `call'
  (gem) quiet_assets-1.0.2/lib/quiet_assets.rb:18:in `call_with_quiet_assets'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/request_id.rb:22:in `call'
  (gem) rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
  (gem) rack-1.4.5/lib/rack/runtime.rb:17:in `call'
  (gem) activesupport-3.2.11/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  (gem) rack-1.4.5/lib/rack/lock.rb:15:in `call'
  (gem) actionpack-3.2.11/lib/action_dispatch/middleware/static.rb:62:in `call'
  (gem) railties-3.2.11/lib/rails/engine.rb:479:in `call'
  (gem) railties-3.2.11/lib/rails/application.rb:223:in `call'
  (gem) railties-3.2.11/lib/rails/railtie/configurable.rb:30:in `method_missing'
  (gem) unicorn-4.6.2/lib/unicorn/http_server.rb:552:in `process_client'
  (gem) unicorn-4.6.2/lib/unicorn/http_server.rb:632:in `worker_loop'
  (gem) unicorn-4.6.2/lib/unicorn/http_server.rb:500:in `spawn_missing_workers'
  (gem) unicorn-4.6.2/lib/unicorn/http_server.rb:142:in `start'
  (gem) unicorn-4.6.2/bin/unicorn_rails:209:in `<top (required)>
```

**Comment by kkoci** [comment]
@GoodJob Awesome! thanks!
