### ISSUE TITLE
Sidebar shown twice and wrong resource_path obtained for rails 4 in production.

### ISSUE THREAD

**Issue by gauthamns** [activeadmin/activeadmin#2329]
I'm testing activeadmin with Rails 4 and got it working nicely in development. But in production, sidebar is shown twice. And the resource path is generated wrong in case of belongs_to dependency.

```
ActiveAdmin.register Tournament do
end

ActiveAdmin.register ScheduledMatch do
  belongs_to :tournament
end
```

The admin path generated automatically for `ScheduledMatch` by inherited_resources for actions, filter is `admin_tournament_tournament_scheduled_matches_path` instead of `admin_tournament_scheduled_matches_path` (Parent tournament is added twice) because of which it is failing in production. 

The above problems show up only in production and not in development

My Gemfile (According to #2326 )

```
gem 'activeadmin',         github: 'gregbell/active_admin', branch: 'rails4'
gem 'ransack',             github: 'ernie/ransack',         branch: 'rails-4'
gem 'inherited_resources', github: 'josevalim/inherited_resources'
gem 'formtastic',          github: 'justinfrench/formtastic'
```

**Comment by Jwan622** [comment]
So how do I fix this bug? Upgrade activeadmin? To what version?

**Comment by lbrito1** [comment]
I'm in the same situation as @ball-hayden : migrating legacy code from Rails 3 (to 5.0.1) with pluralized activeadmin models. I'm using `1.0.0.pre5`. This issue (duplicate `sidebar`s) affects me whenever `config.eager_load = true`, which is the case of production/staging/etc. 

I have tested singularized filenames with no success.

**Comment by mwlang** [comment]
@lbrito1 use the pre4 version from the master branch:

In your Gemfile:

~~~
gem 'activeadmin', github: 'activeadmin'
~~~

Update your bundle:
~~~
bundle install
bundle list | grep activeadmin
~~~
See: "  * activeadmin (1.0.0.pre4 78324a8)" in output

**Comment by lbrito1** [comment]
Thanks for the answer @mwlang . Indeed, using 1.0.0.pre4 solves the issue, but I am rather reticent on using that snapshot instead of pre5 since there were [quite a lot](https://github.com/activeadmin/activeadmin/compare/v1.0.0.pre4...v1.0.0.pre5) of changes made in between. 

@gvc did a monkeypatch on `ActiveAdmin::Application#register` (pre5 branch) which solves the issue and will post it here shortly.

**Comment by gvc** [comment]
The patch only works on ruby > 2 and assumes that you don't register the same resource with various definitions more than once. Having said that, here it is:

```
module UniqueResourceRegister
  def register(resource, options = {}, &block)
    unless registered_resources.include?(resource)
      registered_resources << resource
      super
    end
  end

  private

  def registered_resources
    @registered_resources ||= []
  end
end

ActiveAdmin::Application.prepend(UniqueResourceRegister)
```

**Comment by davidwparker** [comment]
I'm still having this issue on production.

Gemfile:

```
ruby '2.2.4'
gem 'rails', '4.2.0'
gem 'activeadmin', '~> 1.0.0.pre4'
```

I can't use `gem 'activeadmin', github: 'activeadmin'` (with github:) due to lack of permissions in our deployment area.

It looks as though 1.0.0.pre4 is on rubygems, but it doesn't seem to be using it if it's fixed there?

**Comment by mwlang** [comment]
@davidwparker If your deployment area is restricted, then you'll want to vendor your gems so your dependency on external gem servers is removed.  Take a look at "bundle package" command for this.  If you're using capistrano, also look at setting "bundle_flag" to "--local"  With these options, you can still utilize gems no matter where their sources are.  As long as your development environment can build the vendor cache (and you commit cache to repo), you'll be able to deploy to your servers.

**Comment by phillipoertel** [comment]
I still see this with AA 1.0.1 and 1.1.0 (on Ruby 2.3.3, Rails 4.2.9) when `config.eager_load` is true. Removing `app/admin` from the eager load path didn't help, but the above patch (`UniqueResourceRegister`) did. While it works, it'd be nice to fix this in general.

Here are the backtraces for both requires. I haven't had the time to investigate more. Upgrading to devise 4 had no effect, however.

**First call**

```
/usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/activeadmin-1.0.0/lib/active_admin/application.rb:231:in `block in load'
/usr/local/bundle/gems/activeadmin-1.0.0/lib/active_admin/error.rb:41:in `capture'
/usr/local/bundle/gems/activeadmin-1.0.0/lib/active_admin/application.rb:231:in `load'
/usr/local/bundle/gems/activeadmin-1.0.0/lib/active_admin/application.rb:223:in `block in load!'
/usr/local/bundle/gems/activeadmin-1.0.0/lib/active_admin/application.rb:223:in `each'
/usr/local/bundle/gems/activeadmin-1.0.0/lib/active_admin/application.rb:223:in `load!'
/usr/local/bundle/gems/activeadmin-1.0.0/lib/active_admin/application.rb:245:in `routes'
/usr/local/bundle/gems/activeadmin-1.0.0/lib/active_admin.rb:80:in `routes'
/usr/src/app/config/routes.rb:203:in `block in \u003ctop (required)\u003e'
/usr/local/bundle/gems/actionpack-4.2.9/lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
/usr/local/bundle/gems/actionpack-4.2.9/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
/usr/local/bundle/gems/actionpack-4.2.9/lib/action_dispatch/routing/route_set.rb:410:in `draw'
/usr/src/app/config/routes.rb:1:in `\u003ctop (required)\u003e'
/usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/application/routes_reloader.rb:40:in `each'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/application/routes_reloader.rb:40:in `load_paths'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/application/routes_reloader.rb:16:in `reload!'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/application.rb:170:in `reload_routes!'
/usr/local/bundle/gems/devise-3.5.10/lib/devise/rails.rb:14:in `block in \u003cclass:Engine\u003e'
/usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/lazy_load_hooks.rb:44:in `each'
/usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/application/finisher.rb:55:in `block in \u003cmodule:Finisher\u003e'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/initializable.rb:30:in `run'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
/usr/local/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/local/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each'
/usr/local/lib/ruby/2.3.0/tsort.rb:347:in `call'
/usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
/usr/local/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/application.rb:352:in `initialize!'
/usr/src/app/config/environment.rb:5:in `\u003ctop (required)\u003e'
config.ru:4:in `require'
config.ru:4:in `block in \u003cmain\u003e'
/usr/local/bundle/gems/rack-1.6.8/lib/rack/builder.rb:55:in `instance_eval'
/usr/local/bundle/gems/rack-1.6.8/lib/rack/builder.rb:55:in `initialize'
config.ru:1:in `new'
config.ru:1:in `\u003cmain\u003e'
/usr/local/bundle/gems/unicorn-4.9.0/lib/unicorn.rb:48:in `eval'
/usr/local/bundle/gems/unicorn-4.9.0/lib/unicorn.rb:48:in `block in builder'
/usr/local/bundle/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:768:in `build_app!'
/usr/local/bundle/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:137:in `start'
/usr/local/bundle/gems/unicorn-4.9.0/bin/unicorn:126:in `\u003ctop (required)\u003e'
/usr/local/bundle/bin/unicorn:17:in `load'
/usr/local/bundle/bin/unicorn:17:in `\u003cmain\u003e'
```

**Second call**

```
/usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:360:in `require_or_load'
/usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:317:in `depend_on'
/usr/local/bundle/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:233:in `require_dependency'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/engine.rb:471:in `each'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/engine.rb:471:in `block in eager_load!'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/engine.rb:469:in `each'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/engine.rb:469:in `eager_load!'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/engine.rb:346:in `eager_load!'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/application/finisher.rb:56:in `each'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/application/finisher.rb:56:in `block in \u003cmodule:Finisher\u003e'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/initializable.rb:30:in `run'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
/usr/local/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/local/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each'
/usr/local/lib/ruby/2.3.0/tsort.rb:347:in `call'
/usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
/usr/local/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/bundle/gems/railties-4.2.9/lib/rails/application.rb:352:in `initialize!'
/usr/src/app/config/environment.rb:5:in `\u003ctop (required)\u003e'
config.ru:4:in `require'
config.ru:4:in `block in \u003cmain\u003e'
/usr/local/bundle/gems/rack-1.6.8/lib/rack/builder.rb:55:in `instance_eval'
/usr/local/bundle/gems/rack-1.6.8/lib/rack/builder.rb:55:in `initialize'
config.ru:1:in `new'
config.ru:1:in `\u003cmain\u003e'
/usr/local/bundle/gems/unicorn-4.9.0/lib/unicorn.rb:48:in `eval'
/usr/local/bundle/gems/unicorn-4.9.0/lib/unicorn.rb:48:in `block in builder'
/usr/local/bundle/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:768:in `build_app!'
/usr/local/bundle/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:137:in `start'
/usr/local/bundle/gems/unicorn-4.9.0/bin/unicorn:126:in `\u003ctop (required)\u003e'
/usr/local/bundle/bin/unicorn:17:in `load'
/usr/local/bundle/bin/unicorn:17:in `\u003cmain\u003e'
```

**Comment by davidwparker** [comment]
@phillipoertel -

Since we didn't want to mess with bundle changes, our quickest super bad hack to fix this was to use CSS:

```
.ouradminselector .action_items span.action_item:nth-child(2) {
  display: none;
}
```

It's less than ideal, but it works.

**Comment by phillipoertel** [comment]
@davidwparker Nice hack, didn't think of doing it in CSS :-)

**Comment by thodg** [comment]
Same bug with ActiveAdmin 2.2.0

**Comment by robertoboldi** [comment]
same bug with ActiveAdmin 2.7.0
I put all activeadmin files as plural (because I've seen the autogenerated admin_users.rb. 
putting in singular case the file that was creating the bug solved everything.

**Comment by kirupakaranh** [comment]
I'm still facing this issue with active admin 2.9.0. Renaming file to singular name had no effect

**Comment by svey** [comment]
> If someone else is facing this issue, note that active admin resources can't be under a sub directory inside apps. It must be a top level directory in /app. This is because you cannot exclude a sub directory from eager loading

@kirupakaranh I was able to unlock sub directories by modifying @gvc 's response to keep track of the blocks source location that registers the resource:

```
module UniqueResourceRegister
  def register(resource, options = {}, &block)
    unless registered_blocks.include?(block.source_location)
      registered_blocks << block.source_location
      registered_resources << resource
      super
    end
  end

  private

  def registered_resources
    @registered_resources ||= []
  end

  def registered_blocks
    @registered_blocks ||= []
  end
end

ActiveAdmin::Application.prepend(UniqueResourceRegister)
```
