### ISSUE TITLE
undefined method `per_page_kaminari' for #<ActiveRecord::Relation []>

### ISSUE THREAD

**Issue by redrick** [activeadmin/activeadmin#2537]
As @Daxter told me, creating new issue for [problem from pull](https://github.com/gregbell/active_admin/pull/2535)

so my setup is ruby 2.0.0p247, rails 4.0.0 and my app was generated through [rails-api gem](https://github.com/rails-api/rails-api),  here is Gemfile:

``` ruby
source 'https://rubygems.org'

ruby "2.0.0"

gem 'rails', '4.0.0'

gem 'rails-api'
gem 'mysql2', '0.3.11'

gem 'will_paginate'
gem 'active-resource-pagination'

gem 'active_model_serializers'
gem 'pry'
gem 'pry-rails'

# gem 'cancan'

gem 'ancestry'
gem 'rspec'
gem 'rspec-rails'
gem 'factory_girl_rails'
gem 'migration_comments'
gem 'annotate'
gem 'paperclip'
gem 'fog'
gem 'bcrypt-ruby'
gem 'paper_trail', github: 'airblade/paper_trail', branch: 'master'

gem 'activeresource', require: 'active_resource'

gem 'capistrano'
gem 'rvm-capistrano'
gem 'passenger'

gem 'rack-cors', :require => 'rack/cors'

gem 'redis'
gem 'redis_orm'

gem 'redis_dictionary'

gem 'activeadmin', github: 'gregbell/active_admin'
```

I got simple auth set up with `cancan`, but unable to run `activeadmin` with it, so its commented out + the before_filter in controller, thats hte only way to get it moving, but on fresh install of activeadmin, everything is seemingly functional except `http://localhost:3000/admin/comments`

which gives me:

```
NoMethodError in Admin::CommentsController#index
undefined method `per_page_kaminari' for #<ActiveRecord::Relation []>
```

```
activerecord (4.0.0) lib/active_record/relation/delegation.rb:121:in `method_missing'
activerecord (4.0.0) lib/active_record/relation/delegation.rb:68:in `method_missing'
/Users/Redrick/.rvm/gems/ruby-2.0.0-p247@intranet_server_admin/bundler/gems/active_admin-b869cb14e1d7/lib/active_admin/resource_controller/data_access.rb:275:in `apply_pagination'
/Users/Redrick/.rvm/gems/ruby-2.0.0-p247@intranet_server_admin/bundler/gems/active_admin-b869cb14e1d7/lib/active_admin/resource_controller/data_access.rb:54:in `find_collection'
/Users/Redrick/.rvm/gems/ruby-2.0.0-p247@intranet_server_admin/bundler/gems/active_admin-b869cb14e1d7/lib/active_admin/resource_controller/data_access.rb:34:in `collection'
inherited_resources (1.4.1) lib/inherited_resources/actions.rb:7:in `index'
actionpack (4.0.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.0.0) lib/abstract_controller/base.rb:189:in `process_action'
actionpack (4.0.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.0.0) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (4.0.0) lib/active_support/callbacks.rb:403:in `_run__791921357330997071__process_action__callbacks'
activesupport (4.0.0) lib/active_support/callbacks.rb:80:in `run_callbacks'
actionpack (4.0.0) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (4.0.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.0.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (4.0.0) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.0.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.0.0) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.0.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
activerecord (4.0.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.0.0) lib/abstract_controller/base.rb:136:in `process'
actionpack (4.0.0) lib/abstract_controller/rendering.rb:44:in `process'
actionpack (4.0.0) lib/action_controller/metal.rb:195:in `dispatch'
actionpack (4.0.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.0.0) lib/action_controller/metal.rb:231:in `block in action'
actionpack (4.0.0) lib/action_dispatch/routing/route_set.rb:80:in `call'
actionpack (4.0.0) lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
actionpack (4.0.0) lib/action_dispatch/routing/route_set.rb:48:in `call'
actionpack (4.0.0) lib/action_dispatch/journey/router.rb:71:in `block in call'
actionpack (4.0.0) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.0.0) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.0.0) lib/action_dispatch/routing/route_set.rb:655:in `call'
rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/cookies.rb:486:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/flash.rb:241:in `call'
rack-cors (0.2.8) lib/rack/cors.rb:54:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
rack (1.5.2) lib/rack/etag.rb:23:in `call'
rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
rack (1.5.2) lib/rack/head.rb:11:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
activerecord (4.0.0) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.0.0) lib/active_support/callbacks.rb:373:in `_run__1344401328880704899__call__callbacks'
activesupport (4.0.0) lib/active_support/callbacks.rb:80:in `run_callbacks'
actionpack (4.0.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/reloader.rb:64:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.0.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.0.0) lib/rails/rack/logger.rb:21:in `block in call'
activesupport (4.0.0) lib/active_support/tagged_logging.rb:67:in `block in tagged'
activesupport (4.0.0) lib/active_support/tagged_logging.rb:25:in `tagged'
activesupport (4.0.0) lib/active_support/tagged_logging.rb:67:in `tagged'
railties (4.0.0) lib/rails/rack/logger.rb:21:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.2) lib/rack/runtime.rb:17:in `call'
activesupport (4.0.0) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/static.rb:64:in `call'
railties (4.0.0) lib/rails/engine.rb:511:in `call'
railties (4.0.0) lib/rails/application.rb:97:in `call'
rack (1.5.2) lib/rack/content_length.rb:14:in `call'
thin (1.6.0) lib/thin/connection.rb:82:in `block in pre_process'
thin (1.6.0) lib/thin/connection.rb:80:in `catch'
thin (1.6.0) lib/thin/connection.rb:80:in `pre_process'
thin (1.6.0) lib/thin/connection.rb:55:in `process'
thin (1.6.0) lib/thin/connection.rb:41:in `receive_data'
eventmachine (1.0.3) lib/eventmachine.rb:187:in `run_machine'
eventmachine (1.0.3) lib/eventmachine.rb:187:in `run'
thin (1.6.0) lib/thin/backends/base.rb:73:in `start'
thin (1.6.0) lib/thin/server.rb:162:in `start'
rack (1.5.2) lib/rack/handler/thin.rb:16:in `run'
rack (1.5.2) lib/rack/server.rb:264:in `start'
railties (4.0.0) lib/rails/commands/server.rb:84:in `start'
railties (4.0.0) lib/rails/commands.rb:78:in `block in <top (required)>'
railties (4.0.0) lib/rails/commands.rb:73:in `tap'
railties (4.0.0) lib/rails/commands.rb:73:in `<top (required)>'
script/rails:6:in `require'
script/rails:6:in `<main>'
```

therefore I looked through the code and changed the check on the 
`active_admin/resource_controller/data_access.rb:275:in `apply_pagination'`

if you need more info, I will copy paste you anything, so We can solve it for my sake :)
thx for your time guys :)

**Comment by ChrisCPO** [comment]
I'm getting this issue again, however working on localhost but not when that same branch is pushed to herkou?  It is also happening only on one resource page the other are fine. I do have will paginate installed and have gone through the compatibility steps: https://github.com/activeadmin/activeadmin/blob/master/docs/0-installation.md#gem-compatibility

```ruby 
   NoMethodError (undefined method `per_page_kaminari' 
```

**Comment by varyonic** [comment]
Re-closing as Chris opened separate issue.
