### ISSUE TITLE
Circular dependency detected

### ISSUE THREAD

**Issue by tibo** [activeadmin/activeadmin#2677]
Hello,

I'm working on a rails 4 upgrade and I'm experiencing a runtime error:
Circular dependency detected while autoloading constant AdminUser (RuntimeError)

any idea how can I solve this?

Thanks

**Comment by aug-riedinger** [comment]
I still having the issue with the following gem versions:

```
    activeadmin (1.0.0.pre1)
    rails (4.2.0)
```

Trying to run `rake db:migrate` to set up my environment locally. Here's my stacktrace:

```
rake aborted!
Circular dependency detected while autoloading constant FeaturedPartner
/home/augustin/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:492:in `load_missing_constant'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:184:in `const_missing'
/home/augustin/Workspace/gavoune/app/admin/featured_partner.rb:1:in `<top (required)>'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:457:in `load'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:457:in `block in load_file'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:647:in `new_constants_in'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:456:in `load_file'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:354:in `require_or_load'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:494:in `load_missing_constant'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:184:in `const_missing'
/home/augustin/Workspace/gavoune/app/admin/featured_partner.rb:1:in `<top (required)>'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/augustin/.rvm/gems/ruby-2.2.1/bundler/gems/activeadmin-808bc0f5ee0d/lib/active_admin/application.rb:194:in `block in load'
/home/augustin/.rvm/gems/ruby-2.2.1/bundler/gems/activeadmin-808bc0f5ee0d/lib/active_admin/error.rb:41:in `capture'
/home/augustin/.rvm/gems/ruby-2.2.1/bundler/gems/activeadmin-808bc0f5ee0d/lib/active_admin/application.rb:194:in `load'
/home/augustin/.rvm/gems/ruby-2.2.1/bundler/gems/activeadmin-808bc0f5ee0d/lib/active_admin/application.rb:186:in `block in load!'
/home/augustin/.rvm/gems/ruby-2.2.1/bundler/gems/activeadmin-808bc0f5ee0d/lib/active_admin/application.rb:186:in `each'
/home/augustin/.rvm/gems/ruby-2.2.1/bundler/gems/activeadmin-808bc0f5ee0d/lib/active_admin/application.rb:186:in `load!'
/home/augustin/.rvm/gems/ruby-2.2.1/bundler/gems/activeadmin-808bc0f5ee0d/lib/active_admin/application.rb:208:in `routes'
/home/augustin/.rvm/gems/ruby-2.2.1/bundler/gems/activeadmin-808bc0f5ee0d/lib/active_admin.rb:79:in `routes'
/home/augustin/Workspace/gavoune/config/routes.rb:2:in `block in <top (required)>'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:423:in `instance_exec'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:423:in `eval_block'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:401:in `draw'
/home/augustin/Workspace/gavoune/config/routes.rb:1:in `<top (required)>'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:40:in `each'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:40:in `load_paths'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:16:in `reload!'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:26:in `block in updater'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/file_update_checker.rb:75:in `call'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/file_update_checker.rb:75:in `execute'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:27:in `updater'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `public_send'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `method_missing'
/home/augustin/Workspace/gavoune/config/environment.rb:5:in `<top (required)>'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/application.rb:328:in `require_environment!'
/home/augustin/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/application.rb:443:in `block in run_tasks_blocks'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
```

What can I do?

**Comment by lucianosousa** [comment]
@aug-riedinger same here. did you solve this?

**Comment by aug-riedinger** [comment]
I guessed I moved away from the issue. Can't remember what I did at the end. Sorry :confused:

**Comment by lucianosousa** [comment]
@aug-riedinger Tks for the answer.

Solved here doing this: https://github.com/activeadmin/activeadmin/issues/2334#issuecomment-42626409

Cheers

**Comment by sadaf2605** [comment]
hit this error from v 1.0.0.pre1
