### ISSUE TITLE
active admin doesn't work with simple form

### ISSUE THREAD

**Issue by sashazykov** [activeadmin/activeadmin#2703]
```
wrong number of arguments (6 for 4..5)
Extracted source (around line #1):
1

  insert_tag renderer_for(:new)

simple_form (3.0.0) lib/simple_form/inputs/base.rb:50:in `initialize'
formtastic (2.3.0.rc2) lib/formtastic/helpers/input_helper.rb:241:in `new'
formtastic (2.3.0.rc2) lib/formtastic/helpers/input_helper.rb:241:in `input'
/Users/sashazykov/.rvm/gems/ruby-2.0.0-p247/bundler/gems/active_admin-7ad6ec39d959/lib/active_admin/form_builder.rb:26:in `block in input'
/Users/sashazykov/.rvm/gems/ruby-2.0.0-p247/bundler/gems/active_admin-7ad6ec39d959/lib/active_admin/form_builder.rb:134:in `with_new_form_buffer'
/Users/sashazykov/.rvm/gems/ruby-2.0.0-p247/bundler/gems/active_admin-7ad6ec39d959/lib/active_admin/form_builder.rb:26:in `input'
formtastic (2.3.0.rc2) lib/formtastic/helpers/inputs_helper.rb:329:in `block in fieldset_contents_from_column_list'
formtastic (2.3.0.rc2) lib/formtastic/helpers/inputs_helper.rb:317:in `collect'`
```

**Comment by jibiel** [comment]
I think that nowadays *(2015+)*, the simplest and the most proper way to ensure `SimpleForm`'s compatibility with `Formtastic` (including the `ActiveAdmin` dependency) is to wrap your custom `SimpleForm` inputs in a _namespace_:

```ruby
# If needed, you can namespace your custom inputs in a module and tell `SimpleForm`
# to look for their definitions in this module. This can avoid conflicts with other
# form libraries (like `Formtastic`) that look up the global context to find inputs
# definition too.
    
# app/inputs/custom_inputs/numeric_input.rb
module CustomInputs
  class NumericInput < SimpleForm::Inputs::NumericInput
    def input_html_classes
      super.push 'no-spinner'
    end
  end
end

    
# config/initializers/simple_form.rb
config.custom_inputs_namespaces << 'CustomInputs'
```

Check the [Custom Inputs][1] section of the `SimpleForm` [docs][2] for more details.


  [1]: https://github.com/plataformatec/simple_form#user-content-custom-inputs
  [2]: https://github.com/plataformatec/simple_form
