### ISSUE TITLE
NoMethodError when the model has validation errors

### ISSUE THREAD

**Issue by matstc** [activeadmin/activeadmin#3205]
I am getting NoMethodErrors when saving some models. I think it happens only when my model has validation errors. Saving a valid model or handling the validations differently seems to resolve it. Ideally, Active Admin would handle these cases better and not raise a NoMethodError which results in a 500.

Below is typical stack trace. Let me know if you want more info. I am using Active Admin from master (active_admin-4f445b51c22b).

```
2014-06-12T17:15:35.122381+00:00 app[web.1]: NoMethodError (undefined method `menu_items_url' for #<Admin::MenuItemsController:0x007f38a4282a38>):
2014-06-12T17:15:35.122383+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/routing/polymorphic_routes.rb:142:in `polymorphic_url'
2014-06-12T17:15:35.122385+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/routing/url_for.rb:159:in `url_for'
2014-06-12T17:15:35.122387+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/redirecting.rb:90:in `_compute_redirect_to_location'
2014-06-12T17:15:35.122388+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/turbolinks-2.2.2/lib/turbolinks/xhr_headers.rb:24:in `_compute_redirect_to_location_with_xhr_referer'
2014-06-12T17:15:35.122391+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/redirecting.rb:70:in `redirect_to'
2014-06-12T17:15:35.122393+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/flash.rb:57:in `redirect_to'
2014-06-12T17:15:35.122394+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/instrumentation.rb:61:in `block in redirect_to'
2014-06-12T17:15:35.122396+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/notifications.rb:159:in `block in instrument'
2014-06-12T17:15:35.122397+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2014-06-12T17:15:35.122399+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/notifications.rb:159:in `instrument'
2014-06-12T17:15:35.122401+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/instrumentation.rb:60:in `redirect_to'
2014-06-12T17:15:35.122402+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/responder.rb:140:in `redirect_to'
2014-06-12T17:15:35.122404+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/responder.rb:198:in `navigation_behavior'
2014-06-12T17:15:35.122405+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/responder.rb:167:in `rescue in to_html'
2014-06-12T17:15:35.122407+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/responder.rb:165:in `to_html'
2014-06-12T17:15:35.122408+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/responders-1.1.0/lib/responders/flash_responder.rb:107:in `to_html'
2014-06-12T17:15:35.122410+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/responder.rb:158:in `respond'
2014-06-12T17:15:35.122411+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/responder.rb:151:in `call'
2014-06-12T17:15:35.122413+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/mime_responds.rb:400:in `respond_with'
2014-06-12T17:15:35.122414+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/inherited_resources-1.5.0/lib/inherited_resources/base_helpers.rb:275:in `respond_with_dual_blocks'
2014-06-12T17:15:35.122415+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/inherited_resources-1.5.0/lib/inherited_resources/actions.rb:37:in `create'
2014-06-12T17:15:35.122417+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
2014-06-12T17:15:35.122418+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/abstract_controller/base.rb:189:in `process_action'
2014-06-12T17:15:35.122419+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
2014-06-12T17:15:35.122421+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
2014-06-12T17:15:35.122422+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:113:in `call'
2014-06-12T17:15:35.122423+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:113:in `call'
2014-06-12T17:15:35.122425+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `block in halting'
2014-06-12T17:15:35.122426+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `call'
2014-06-12T17:15:35.122427+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `block in halting'
2014-06-12T17:15:35.122429+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `call'
2014-06-12T17:15:35.122430+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `block in halting'
2014-06-12T17:15:35.122432+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:149:in `call'
2014-06-12T17:15:35.122433+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
2014-06-12T17:15:35.122435+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `call'
2014-06-12T17:15:35.122440+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `block in halting'
2014-06-12T17:15:35.122442+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:229:in `call'
2014-06-12T17:15:35.122443+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:229:in `block in halting'
2014-06-12T17:15:35.122444+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `call'
2014-06-12T17:15:35.122446+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `block in halting'
2014-06-12T17:15:35.122447+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `call'
2014-06-12T17:15:35.122448+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:166:in `block in halting'
2014-06-12T17:15:35.122450+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:86:in `call'
2014-06-12T17:15:35.122451+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:86:in `run_callbacks'
2014-06-12T17:15:35.122452+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
2014-06-12T17:15:35.122454+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
2014-06-12T17:15:35.122455+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
2014-06-12T17:15:35.122457+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/notifications.rb:159:in `block in instrument'
2014-06-12T17:15:35.122458+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2014-06-12T17:15:35.122459+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/notifications.rb:159:in `instrument'
2014-06-12T17:15:35.122461+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
2014-06-12T17:15:35.122462+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
2014-06-12T17:15:35.122463+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
2014-06-12T17:15:35.122465+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/abstract_controller/base.rb:136:in `process'
2014-06-12T17:15:35.122467+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionview-4.1.1/lib/action_view/rendering.rb:30:in `process'
2014-06-12T17:15:35.122468+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal.rb:195:in `dispatch'
2014-06-12T17:15:35.122470+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
2014-06-12T17:15:35.122471+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_controller/metal.rb:231:in `block in action'
2014-06-12T17:15:35.122473+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/routing/route_set.rb:80:in `call'
2014-06-12T17:15:35.122474+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
2014-06-12T17:15:35.122476+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/routing/route_set.rb:48:in `call'
2014-06-12T17:15:35.122477+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/journey/router.rb:71:in `block in call'
2014-06-12T17:15:35.122479+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/journey/router.rb:59:in `each'
2014-06-12T17:15:35.122480+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/journey/router.rb:59:in `call'
2014-06-12T17:15:35.122482+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_
dispatch/routing/route_set.rb:676:in `call'
2014-06-12T17:15:35.122483+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/oink-0.10.1/lib/oink/middleware.rb:17:in `call'
2014-06-12T17:15:35.122485+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.8.1.221/lib/new_relic/rack/error_collector.rb:55:in `call'
2014-06-12T17:15:35.122486+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.8.1.221/lib/new_relic/rack/agent_hooks.rb:32:in `call'
2014-06-12T17:15:35.122487+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.8.1.221/lib/new_relic/rack/browser_monitoring.rb:27:in `call'
2014-06-12T17:15:35.122489+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
2014-06-12T17:15:35.122491+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
2014-06-12T17:15:35.122492+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
2014-06-12T17:15:35.122494+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
2014-06-12T17:15:35.122495+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/conditionalget.rb:35:in `call'
2014-06-12T17:15:35.122500+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
2014-06-12T17:15:35.122502+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
2014-06-12T17:15:35.122503+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/flash.rb:254:in `call'
2014-06-12T17:15:35.122505+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
2014-06-12T17:15:35.122506+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
2014-06-12T17:15:35.122507+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
2014-06-12T17:15:35.122509+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/query_cache.rb:36:in `call'
2014-06-12T17:15:35.122511+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
2014-06-12T17:15:35.122512+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
2014-06-12T17:15:35.122513+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:82:in `run_callbacks'
2014-06-12T17:15:35.122515+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
2014-06-12T17:15:35.122516+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
2014-06-12T17:15:35.122519+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
2014-06-12T17:15:35.122520+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
2014-06-12T17:15:35.122522+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/rack/logger.rb:38:in `call_app'
2014-06-12T17:15:35.122523+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/rack/logger.rb:20:in `block in call'
2014-06-12T17:15:35.122525+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
2014-06-12T17:15:35.122526+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/tagged_logging.rb:26:in `tagged'
2014-06-12T17:15:35.122528+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/tagged_logging.rb:68:in `tagged'
2014-06-12T17:15:35.122529+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/rack/logger.rb:20:in `call'
2014-06-12T17:15:35.122531+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
2014-06-12T17:15:35.122532+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
2014-06-12T17:15:35.122534+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
2014-06-12T17:15:35.122536+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
2014-06-12T17:15:35.122537+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/static.rb:64:in `call'
2014-06-12T17:15:35.122539+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
2014-06-12T17:15:35.122540+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/engine.rb:514:in `call'
2014-06-12T17:15:35.122541+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/application.rb:144:in `call'
2014-06-12T17:15:35.122543+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/configuration.rb:71:in `call'
2014-06-12T17:15:35.122544+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/server.rb:490:in `handle_request'
2014-06-12T17:15:35.122546+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/server.rb:361:in `process_client'
2014-06-12T17:15:35.122547+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/server.rb:254:in `block in run'
2014-06-12T17:15:35.122549+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/thread_pool.rb:92:in `call'
2014-06-12T17:15:35.122550+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/puma-2.8.2/lib/puma/thread_pool.rb:92:in `block in spawn_thread'
```

**Comment by kkanazaw** [comment]
hi, I got a same error. I report my case.

# environment
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
psql (PostgreSQL) 8.4.20

Using rails 4.2.3
Using inherited_resources 1.6.0 from git://github.com/josevalim/inherited_resources.git (at master@eb430c1)
Using activeadmin 1.0.0.pre1 from git://github.com/activeadmin/activeadmin.git (at master@893b46c)

# source

```ruby
class Basicinfo < ActiveRecord::Base
  (...)
  has_one :extrainfo,:primary_key=> "basicinfo_id", :foreign_key => "extrainfo_id"
  (...)

  after_create do
    Extrainfo.create!(extrainfo_id: self.basicinfo_id)
  end
end

class ExtraInfo < ActiveRecord::Base
  # this table is not Rails friendly.
  self.primary_key= "extrainfo_no"
  self.table_name="extrainfo"

  belongs_to :basicinfo, :primary_key => 'basicinfo_id', :foreign_key => 'extrainfo_id', :class_name => "Basicinfo"

end
```

# Situation
1. I create new basicinfo data by activeadmin.
(BasicInfos#after_create#after_create created an extrainfo model)
2. Next, I deleted this basicinfo data by activeadmin.
(dependent: :destroy is not set. so this extrainfo model still have remained.)
3. I try to register another basicinfo data, then I have an error.

```
A NoMethodError occurred in basicinfos#create:
  undefined method `basicinfos_url' for #<Admin::BasicinfosController:0x007f76ae5d57d8>
    /project/shared/bundle/ruby/2.2.0/bundler/gems/inherited_resources-eb430c1ea8c5/lib/inherited_resources/base_helpers.rb:275:in `respond_with_dual_blocks'
```

and Extrainfo.create! failed.
```
D, [2017-10-26T16:23:02.675948 #6145] DEBUG -- :   BEGIN
D, [2017-10-26T16:23:02.679696 #6145] DEBUG -- :   Extrainfo Exists (0.6ms)  SELECT  1 AS one FROM "extrainfo" WHERE "extrainfo"."extrainfo_id" = '2288' LIMIT 1
D, [2017-10-26T16:23:02.681118 #6145] DEBUG -- :   (0.2ms) ROLLBACK
D, [2017-10-26T16:23:02.681668 #6145] DEBUG -- :   (0.2ms)  ROLLBACK
I, [2017-10-26T16:23:02.849815 #6145]  INFO -- : Redirected to
I, [2017-10-26T16:23:03.169771 #6145]  INFO -- : Completed 500 Internal Server Error in 2207ms (ActiveRecord: 128.5ms)
```

In my case, it is resolved by deleting remaining extrainfo model.
