### ISSUE TITLE
Form builder has_many breaks partial when there is a blank line in the block 

### ISSUE THREAD

**Issue by tmichel** [activeadmin/activeadmin#3582]
When building a form using a partial instead of the DSL a `can't modify frozen String` error is raised in some cases.. I used the `active_admin_form_for` helper in my partial. Also I used erb as my templating language.

I'm on the 05778f4b7c8e821d584c7b4b08bcd79c02a0db76 commit. Haven't tested this on `HEAD` yet.

I observed that this error occurres when I leave a blank line in the template. If you don't have any blank line in your `f.has_many` block it works. By blank I mean it is not a `<% %>`.

This works:

``` erb
<% f.has_many :size_runs, allow_destroy: true do |size_run| %>
  <% size_run.input :size_run_type %>
  <% size_run.input :secondary %>
<% end -%>
```

This does not work:

``` erb
<% f.has_many :size_runs, allow_destroy: true do |size_run| %>
  <% size_run.input :size_run_type %>
  <% size_run.input :secondary %>

<% end -%>
```

neither this:

``` erb
<% f.has_many :size_runs, allow_destroy: true do |size_run| %>
  <% size_run.input :size_run_type %>
  <% size_run.input :secondary %>
  <!-- this is a comment -->
<% end -%>
```

Stack trace:

```
RuntimeError - can't modify frozen String:
   () Users/tomi/work/amp-admin/.bundle/.gem/ruby/2.1.0/bundler/gems/active_admin-05778f4b7c8e/lib/active_admin/form_builder.rb:66:in `block in has_many'
  formtastic (3.0.0) lib/formtastic/helpers/inputs_helper.rb:380:in `block (2 levels) in inputs_for_nested_attributes'
   () Users/tomi/work/amp-admin/.bundle/.gem/ruby/2.1.0/bundler/gems/active_admin-05778f4b7c8e/lib/active_admin/form_builder.rb:142:in `block in field_set_and_list_wrapping'
  actionview (4.1.4) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.1.4) lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
  actionview (4.1.4) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  formtastic (3.0.0) lib/formtastic/helpers/fieldset_wrapper.rb:32:in `field_set_and_list_wrapping'
   () Users/tomi/work/amp-admin/.bundle/.gem/ruby/2.1.0/bundler/gems/active_admin-05778f4b7c8e/lib/active_admin/form_builder.rb:141:in `field_set_and_list_wrapping'
  formtastic (3.0.0) lib/formtastic/helpers/inputs_helper.rb:297:in `inputs'
   () Users/tomi/work/amp-admin/.bundle/.gem/ruby/2.1.0/bundler/gems/active_admin-05778f4b7c8e/lib/active_admin/form_builder.rb:20:in `block in inputs'
   () Users/tomi/work/amp-admin/.bundle/.gem/ruby/2.1.0/bundler/gems/active_admin-05778f4b7c8e/lib/active_admin/form_builder.rb:150:in `with_new_form_buffer'
   () Users/tomi/work/amp-admin/.bundle/.gem/ruby/2.1.0/bundler/gems/active_admin-05778f4b7c8e/lib/active_admin/form_builder.rb:20:in `inputs'
  formtastic (3.0.0) lib/formtastic/helpers/inputs_helper.rb:378:in `block in inputs_for_nested_attributes'
  actionview (4.1.4) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.1.4) lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
  actionview (4.1.4) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  actionview (4.1.4) lib/action_view/helpers/form_helper.rb:1860:in `block in fields_for_nested_model'
  actionview (4.1.4) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.1.4) lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
  actionview (4.1.4) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  actionview (4.1.4) lib/action_view/helpers/form_helper.rb:699:in `fields_for'
  actionview (4.1.4) lib/action_view/helpers/form_helper.rb:1859:in `fields_for_nested_model'
  actionview (4.1.4) lib/action_view/helpers/form_helper.rb:1845:in `block in fields_for_with_nested_attributes'
  actionview (4.1.4) lib/action_view/helpers/form_helper.rb:1843:in `fields_for_with_nested_attributes'
  actionview (4.1.4) lib/action_view/helpers/form_helper.rb:1517:in `fields_for'
  formtastic (3.0.0) lib/formtastic/helpers/inputs_helper.rb:396:in `inputs_for_nested_attributes'
   () Users/tomi/work/amp-admin/.bundle/.gem/ruby/2.1.0/bundler/gems/active_admin-05778f4b7c8e/lib/active_admin/form_builder.rb:175:in `block in js_for_has_many'
   () Users/tomi/work/amp-admin/.bundle/.gem/ruby/2.1.0/bundler/gems/active_admin-05778f4b7c8e/lib/active_admin/form_builder.rb:150:in `with_new_form_buffer'
   () Users/tomi/work/amp-admin/.bundle/.gem/ruby/2.1.0/bundler/gems/active_admin-05778f4b7c8e/lib/active_admin/form_builder.rb:175:in `js_for_has_many'
   () Users/tomi/work/amp-admin/.bundle/.gem/ruby/2.1.0/bundler/gems/active_admin-05778f4b7c8e/lib/active_admin/form_builder.rb:101:in `block in has_many'
   () Users/tomi/work/amp-admin/.bundle/.gem/ruby/2.1.0/bundler/gems/active_admin-05778f4b7c8e/lib/active_admin/form_builder.rb:159:in `block in without_wrapper'
   () Users/tomi/work/amp-admin/.bundle/.gem/ruby/2.1.0/bundler/gems/active_admin-05778f4b7c8e/lib/active_admin/form_builder.rb:150:in `with_new_form_buffer'
   () Users/tomi/work/amp-admin/.bundle/.gem/ruby/2.1.0/bundler/gems/active_admin-05778f4b7c8e/lib/active_admin/form_builder.rb:159:in `without_wrapper'
   () Users/tomi/work/amp-admin/.bundle/.gem/ruby/2.1.0/bundler/gems/active_admin-05778f4b7c8e/lib/active_admin/form_builder.rb:92:in `has_many'~~~
```

**Comment by Manidavid** [comment]
Am also getting **can't modify frozen String** error with using form parital, tried using both ``` active_admin_form_for``` and  ```semantic_form_for with builder: ActiveAdmin::FormBuilder```
```
 <%= f.has_many :units, allow_destroy: true, heading: 'Units' do |lu| %>
     <%= lu.input :unit  %>
 <% end %>
```

**Comment by zorab47** [comment]
I am unable to reproduce this with ActiveAdmin 1.2.1 and Rails 5.1. Using the the approach noted in #3916. If this remains an issue, please reopen.

Also worth noting that `active_admin_form_for` is no longer supported from an ERB partial (mentioned by @varyonic in #3916). 

```ruby
<%= semantic_form_for([:admin, resource], builder: ActiveAdmin::FormBuilder) do |f| %>
  <%= f.inputs :name %>

  <%= f.inputs do %>
    <% f.has_many :size_runs, heading: 'Themes', allow_destroy: true, new_record: true do |s| %>
      <% s.input :created_at %>

    <% end -%>
  <% end -%>

  <%= f.actions %>
<% end -%>
```
