### ISSUE TITLE
`columns` works for Page, but not Resource

### ISSUE THREAD

**Issue by seanlinsley** [activeadmin/activeadmin#3711]
Given this configuration:
```ruby
ActiveAdmin.register Client do
  show do
    columns do
      column do
      end
    end
  end
end
```
You get this error:
```
NoMethodError - undefined method `span_size' for #<ActiveAdmin::Views::Panel:0x00000108801778>:
  arbre (1.0.2) lib/arbre/element.rb:182:in `method_missing'
  activeadmin-b794f4b7550d/lib/active_admin/views/components/columns.rb:105:in `block in columns_span_count'
  activeadmin-b794f4b7550d/lib/active_admin/views/components/columns.rb:105:in `columns_span_count'
  activeadmin-b794f4b7550d/lib/active_admin/views/components/columns.rb:91:in `calculate_columns!'
  activeadmin-b794f4b7550d/lib/active_admin/views/components/columns.rb:75:in `add_child'
  arbre (1.0.2) lib/arbre/element/builder_methods.rb:40:in `insert_tag'
  arbre (1.0.2) lib/arbre/element/builder_methods.rb:14:in `panel'
  app/admin/client.rb:22:in `block (3 levels) in <top (required)>'
  arbre (1.0.2) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
  arbre (1.0.2) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.0.2) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  arbre (1.0.2) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.0.2) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  arbre (1.0.2) lib/arbre/element/builder_methods.rb:14:in `columns'
  app/admin/client.rb:21:in `block (2 levels) in <top (required)>'
```

Which isn't what you expect given [the columns DSL on pages like the dashboard](https://github.com/activeadmin/activeadmin/blob/633c1a4f1f7f15759de77691376bea783405118b/lib/generators/active_admin/install/templates/dashboard.rb#L15).

**Comment by kirillplatonov** [comment]
I tried it with ruby 2.1.4, rails 4.1.8 - it works. Which versions you use?

**Comment by bsvineeth** [comment]
Hi @seanlinsley I have created a PR for the above error. It is  https://github.com/activeadmin/activeadmin/pull/3878
