### ISSUE TITLE
Active Admin 1.0.0.pre index page exception on rails 4.1

### ISSUE THREAD

**Issue by ideanl** [activeadmin/activeadmin#3717]
```
Exception: wrong number of arguments (2 for 1)
Showing app/views/active_admin/resource/index.html.arb 

Extracted from source around line #2
  insert_tag renderer_for(:index)

Trace:
lib/active_admin/views/components/site_title.rb:10:in `build'
arbre (1.0.2) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
arbre (1.0.2) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.0.2) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.0.2) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.0.2) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
lib/active_admin/views/header.rb:27:in `build_site_title'
lib/active_admin/views/header.rb:12:in `build'
arbre (1.0.2) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
arbre (1.0.2) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.0.2) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.0.2) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.0.2) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
lib/active_admin/views/pages/base.rb:61:in `build_header'
lib/active_admin/views/pages/base.rb:46:in `block (2 levels) in build_page'
arbre (1.0.2) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.0.2) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.0.2) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.0.2) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.0.2) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.0.2) lib/arbre/element/builder_methods.rb:14:in `div'
lib/active_admin/views/pages/base.rb:44:in `block in build_page'
arbre (1.0.2) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.0.2) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
lib/active_admin/views/pages/base.rb:43:in `build_page'
lib/active_admin/views/pages/base.rb:10:in `build'
arbre (1.0.2) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
arbre (1.0.2) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.0.2) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.0.2) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
app/views/active_admin/resource/index.html.arb:2:in `block in __home_idean__gem_ruby_______bundler_gems_active_admin_c___bedf___b_app_views_active_admin_resource_index_html_arb__5760843236148667_71299140'
arbre (1.0.2) lib/arbre/context.rb:45:in `instance_eval'
arbre (1.0.2) lib/arbre/context.rb:45:in `initialize'
app/views/active_admin/resource/index.html.arb:1:in `new'
app/views/active_admin/resource/index.html.arb:1:in `__home_idean__gem_ruby_______bundler_gems_active_admin_c___bedf___b_app_views_active_admin_resource_index_html_arb__5760843236148667_71299140'
actionview (4.1.0) lib/action_view/template.rb:145:in `block in render'
activesupport (4.1.0) lib/active_support/notifications.rb:161:in `instrument'
actionview (4.1.0) lib/action_view/template.rb:339:in `instrument'
actionview (4.1.0) lib/action_view/template.rb:143:in `render'
actionview (4.1.0) lib/action_view/renderer/template_renderer.rb:55:in `block (2 levels) in render_template'
actionview (4.1.0) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (4.1.0) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.1.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.1.0) lib/active_support/notifications.rb:159:in `instrument'
actionview (4.1.0) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
actionview (4.1.0) lib/action_view/renderer/template_renderer.rb:54:in `block in render_template'
actionview (4.1.0) lib/action_view/renderer/template_renderer.rb:62:in `render_with_layout'
actionview (4.1.0) lib/action_view/renderer/template_renderer.rb:53:in `render_template'
actionview (4.1.0) lib/action_view/renderer/template_renderer.rb:17:in `render'
actionview (4.1.0) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (4.1.0) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (4.1.0) lib/action_view/rendering.rb:99:in `_render_template'
actionpack (4.1.0) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (4.1.0) lib/action_view/rendering.rb:82:in `render_to_body'
actionpack (4.1.0) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
actionpack (4.1.0) lib/action_controller/metal/renderers.rb:32:in `render_to_body'
actionpack (4.1.0) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (4.1.0) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (4.1.0) lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
activesupport (4.1.0) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/lib64/ruby/2.1.0/benchmark.rb:294:in `realtime'
activesupport (4.1.0) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (4.1.0) lib/action_controller/metal/instrumentation.rb:41:in `block in render'
actionpack (4.1.0) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
activerecord (4.1.0) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (4.1.0) lib/action_controller/metal/instrumentation.rb:40:in `render'
actionpack (4.1.0) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
actionpack (4.1.0) lib/action_controller/metal/responder.rb:238:in `default_render'
actionpack (4.1.0) lib/action_controller/metal/responder.rb:165:in `to_html'
responders (1.0.0) lib/responders/flash_responder.rb:104:in `to_html'
actionpack (4.1.0) lib/action_controller/metal/responder.rb:158:in `respond'
actionpack (4.1.0) lib/action_controller/metal/responder.rb:151:in `call'
actionpack (4.1.0) lib/action_controller/metal/mime_responds.rb:400:in `respond_with'
/home/idean/.gem/ruby/2.1.0/bundler/gems/inherited_resources-ad5f8d059e1b/lib/inherited_resources/actions.rb:7:in `index'
actionpack (4.1.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.1.0) lib/abstract_controller/base.rb:189:in `process_action'
actionpack (4.1.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.1.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.1.0) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.0) lib/active_support/callbacks.rb:149:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
activesupport (4.1.0) lib/active_support/callbacks.rb:229:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:229:in `block in halting'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.0) lib/active_support/callbacks.rb:282:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:282:in `block (2 levels) in halting_and_conditional'
activesupport (4.1.0) lib/active_support/core_ext/time/zones.rb:47:in `use_zone'
activesupport (4.1.0) lib/active_support/callbacks.rb:424:in `block in make_lambda'
activesupport (4.1.0) lib/active_support/callbacks.rb:281:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:281:in `block in halting_and_conditional'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.0) lib/active_support/callbacks.rb:229:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:229:in `block in halting'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.0) lib/active_support/callbacks.rb:86:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:86:in `run_callbacks'
actionpack (4.1.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.1.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.1.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (4.1.0) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.1.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.1.0) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.1.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.1.0) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.1.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.1.0) lib/abstract_controller/base.rb:136:in `process'
actionview (4.1.0) lib/action_view/rendering.rb:30:in `process'
actionpack (4.1.0) lib/action_controller/metal.rb:195:in `dispatch'
actionpack (4.1.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.1.0) lib/action_controller/metal.rb:231:in `block in action'
actionpack (4.1.0) lib/action_dispatch/routing/route_set.rb:80:in `call'
actionpack (4.1.0) lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
actionpack (4.1.0) lib/action_dispatch/routing/route_set.rb:48:in `call'
actionpack (4.1.0) lib/action_dispatch/journey/router.rb:71:in `block in call'
actionpack (4.1.0) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.1.0) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.1.0) lib/action_dispatch/routing/route_set.rb:676:in `call'
rack (1.5.2) lib/rack/etag.rb:23:in `call'
rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
rack (1.5.2) lib/rack/head.rb:11:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/flash.rb:254:in `call'
rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.1.0) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.1.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.1.0) lib/active_support/callbacks.rb:82:in `run_callbacks'
actionpack (4.1.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.1.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.1.0) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.1.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.1.0) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.1.0) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.1.0) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
rack (1.5.2) lib/rack/runtime.rb:17:in `call'
activesupport (4.1.0) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/static.rb:64:in `call'
rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
railties (4.1.0) lib/rails/engine.rb:514:in `call'
railties (4.1.0) lib/rails/application.rb:144:in `call'
rack (1.5.2) lib/rack/content_length.rb:14:in `call'
puma (2.7.1) lib/puma/server.rb:486:in `handle_request'
puma (2.7.1) lib/puma/server.rb:357:in `process_client'
puma (2.7.1) lib/puma/server.rb:250:in `block in run'
puma (2.7.1) lib/puma/thread_pool.rb:92:in `call'
puma (2.7.1) lib/puma/thread_pool.rb:92:in `block in spawn_thread'
```

**Comment by ideanl** [comment]
I have partials located inside my app's app/views/admin directory. That exception is shown for the gem in ~/.gems, within the gem's app/views/active_admin directory.

**Comment by timoschilling** [comment]
Which version / git ref of active admin do you use? I ask, while your stacktrace say ```lib/active_admin/views/header.rb:27:in `build_site_title'```, but `build_site_title` is on line [18](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/views/header.rb#L18).

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
