### ISSUE TITLE
ActiveAdmin cleans cookies

### ISSUE THREAD

**Issue by Melancholic** [activeadmin/activeadmin#3836]
Hello!
I am using  ActiveAdmin with custom User model (without Devise) and custom SessionsController. I successfully installed ActiveAdmin, implement the necessary methods, but faced a problem: after the first visit dashboard, the user`s remember_token removed from the cookies (I found it in a browser) that leads to the log out user and redirect to the homepage of the site.

In Rails logs , the following changes to the User model:
```java
D, [2015-03-06T18:08:38.412548 #29316] DEBUG -- :   User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."remember_token" = $1  ORDER BY login ASC LIMIT 1  [["remember_token", "d983c4abdc252ffc04a71260513ace78534a4c2b"]]
D, [2015-03-06T18:08:38.538903 #29316] DEBUG -- :    (0.1ms)  BEGIN
D, [2015-03-06T18:08:38.539994 #29316] DEBUG -- :   SQL (0.2ms)  UPDATE "users" SET "remember_token" = $1, "updated_at" = $2 WHERE "users"."id" = $3  [["remember_token", "5c40d43f2df2a0dfcbd0bc3a40496bf3eb5bf8a7"], ["updated_at", "2015-03-06 14:08:38.539165"], ["id", 22]]
D, [2015-03-06T18:08:38.593651 #29316] DEBUG -- :    (53.4ms)  COMMIT
D, [2015-03-06T18:08:38.594675 #29316] DEBUG -- :   User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."remember_token" = $1  ORDER BY login ASC LIMIT 1  [["remember_token", "da39a3ee5e6b4b0d3255bfef95601890afd80709"]]
```

config/initializers/active_admin.rb

```ruby
ActiveAdmin.setup do |config|
  config.site_title = "Coordinate"
  config.authentication_method = :authenticate_admin_user!
  config.logout_link_path = :sign_out
  config.logout_link_method = :delete
  config.batch_actions = true
end
```

app/controllers/application_controller.rb

```ruby
  def authenticate_admin_user!
    unless current_admin_user
      flash[:error] = "Access error!"
      redirect_to root_path 
    end 
  end 

  def current_admin_user
    return nil if signed_in? && !current_user.admin?
    current_user
  end 
```

app/helpers/sessions_helper.rb

```ruby

def sign_in(user)
    remember_token = User.new_remember_token();
    cookies.permanent[:remember_token] = remember_token;
    user.update_attribute(:remember_token, User.encrypt(remember_token));
    self.current_user=user;
  end 

  def current_user
    remember_token= User.encrypt(cookies[:remember_token]);
    @current_user ||= User.find_by(remember_token: remember_token);
  end 


  def current_user?(user)
    user==current_user;
  end 

  def signed_in?
    !current_user.nil?
  end 

  def sign_out()
    current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token));
    cookies.delete(:remember_token);
    self.current_user=nil;
  end
```
That is, when accessing the controller ActiveAdmin erases cookies and log off the user (I suspect that somewhere is implicitly called sign_out).

Please help in solving this problem.

**Comment by ccallebs** [comment]
I suspect that you're not decrypting the remember_token in the current_user method.

**Comment by Melancholic** [comment]
Yes of course. Here are the contents:
```ruby
  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end 
```
With sessions all right: they are taken from the material railstutorial.org. Within my application to work fine. Problems begin when accessing ActiveAdmin controller.

**Comment by timoschilling** [comment]
Where is your `sign_in` and `sign_out` method is called.
Have you checkt that you don't use this both methods in a wrong way?
Add debug statements on it and test your code.

**Comment by Melancholic** [comment]
Thank you for your response.
I removed the description of the method `sign_out` (stripped of its application log out function) and ActiveAdmin started working normally. To find out what I called an exception, from which I learned that `sign_out` really caused when accessing ActiveAdmin.
Here the top part of full-trace:
```ruby
app/helpers/sessions_helper.rb:27:in `sign_out'
arbre (1.0.3) lib/arbre/element.rb:180:in `method_missing'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/view_helpers/method_or_proc_helper.rb:56:in `public_send'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/view_helpers/method_or_proc_helper.rb:56:in `call_method_or_proc_on'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/view_helpers/method_or_proc_helper.rb:73:in `render_or_call_method_or_proc_on'
arbre (1.0.3) lib/arbre/element.rb:180:in `method_missing'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/namespace.rb:135:in `block in add_logout_button_to_menu'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/view_helpers/method_or_proc_helper.rb:86:in `instance_exec'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/view_helpers/method_or_proc_helper.rb:86:in `render_in_context'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/menu_item.rb:71:in `url'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/menu_item.rb:92:in `real_url?'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/menu_item.rb:78:in `display?'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/menu.rb:73:in `block in items'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/menu.rb:73:in `select'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/menu.rb:73:in `items'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/views/tabbed_navigation.rb:27:in `menu_items'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/views/tabbed_navigation.rb:37:in `build_menu'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/views/tabbed_navigation.rb:22:in `build'
arbre (1.0.3) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
arbre (1.0.3) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.0.3) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.0.3) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.0.3) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/views/header.rb:27:in `build_utility_navigation'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/views/header.rb:14:in `build'
arbre (1.0.3) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
```
So, how can I fix it? Perhaps it should be added to the configuration file skip callbacks?

**Comment by Melancholic** [comment]
Thank you for your response.
I removed the description of the method `sign_out` (stripped of its application log out function) and ActiveAdmin started working normally. To find out what I called an exception, from which I learned that `sign_out` really caused when accessing ActiveAdmin.
Here the top part of full-trace:
```ruby
app/helpers/sessions_helper.rb:27:in `sign_out'
arbre (1.0.3) lib/arbre/element.rb:180:in `method_missing'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/view_helpers/method_or_proc_helper.rb:56:in `public_send'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/view_helpers/method_or_proc_helper.rb:56:in `call_method_or_proc_on'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/view_helpers/method_or_proc_helper.rb:73:in `render_or_call_method_or_proc_on'
arbre (1.0.3) lib/arbre/element.rb:180:in `method_missing'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/namespace.rb:135:in `block in add_logout_button_to_menu'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/view_helpers/method_or_proc_helper.rb:86:in `instance_exec'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/view_helpers/method_or_proc_helper.rb:86:in `render_in_context'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/menu_item.rb:71:in `url'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/menu_item.rb:92:in `real_url?'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/menu_item.rb:78:in `display?'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/menu.rb:73:in `block in items'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/menu.rb:73:in `select'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/menu.rb:73:in `items'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/views/tabbed_navigation.rb:27:in `menu_items'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/views/tabbed_navigation.rb:37:in `build_menu'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/views/tabbed_navigation.rb:22:in `build'
arbre (1.0.3) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
arbre (1.0.3) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.0.3) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.0.3) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.0.3) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/views/header.rb:27:in `build_utility_navigation'
/home/.../.gem/ruby/bundler/gems/activeadmin-19ee89935586/lib/active_admin/views/header.rb:14:in `build'
arbre (1.0.3) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
```
So, how can I fix it? Perhaps it should be added to the configuration file skip callbacks?

**Comment by Melancholic** [comment]
`config.logout_link_path = false` in the configuration file corrects the situation, but this action removes the logout link in the dashboard. There is a better solution?

**Comment by timoschilling** [comment]
Do you have custom menus in your app?

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.

**Comment by Melancholic** [comment]
Sorry for that long to respond.
I wrote above, solved the problem by setting `config.logout_link_path = false` in `config/initializers/active_admin.rb`.

No special settings menu, except for the display order of the resources I have.

**Comment by timoschilling** [comment]
After a second look I have a idea, it could be that `config.logout_link_path = :sign_out` is the problem.
`sign_out` is your method to lockout the user, ActiveAdmin needs the `sign_out_path` (method which returns the url for the lockout) in `config.logout_link_path`. Whats happen is that ActiveAdmin call's `config.logout_link_path` which is `sign_out` to get the path and in `sign_out` kills the user session.

**Comment by Melancholic** [comment]
Indeed , you are right !
Thank you for your help
