### ISSUE TITLE
Cannot start application after optimization

### ISSUE THREAD

**Issue by jhanggi** [activeadmin/activeadmin#3854]
After #3783 was merged in, my application will no longer start up. I'm going to dig a little deeper, but I wanted to get the issue out here in case anyone else is having a similar problem.

Rails 4.1.9
Ruby 2.1.4
At ActiveAdmin c4a21cdcdb2fa1274ce9226208ee1656dee8434a

We are loading activeadmin through an engine and adding paths within the engine onto `ActiveAdmin.application.load_paths`.

My workaround for now is locking to `1.0.0.pre1` instead of tracking from master (which I very much thank you for releasing!).

```
/Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/gems/activesupport-4.1.9/lib/active_support/file_update_checker.rb:128:in `escape': undefined method `gsub' for #<Pathname:0x007f96368efb10> (NoMethodError)
  from /Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/gems/activesupport-4.1.9/lib/active_support/file_update_checker.rb:122:in `block in compile_glob'
  from /Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/gems/activesupport-4.1.9/lib/active_support/file_update_checker.rb:121:in `each'
  from /Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/gems/activesupport-4.1.9/lib/active_support/file_update_checker.rb:121:in `map'
  from /Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/gems/activesupport-4.1.9/lib/active_support/file_update_checker.rb:121:in `compile_glob'
  from /Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/gems/activesupport-4.1.9/lib/active_support/file_update_checker.rb:40:in `initialize'
  from /Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/bundler/gems/activeadmin-c4a21cdcdb2f/lib/active_admin/application.rb:276:in `new'
  from /Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/bundler/gems/activeadmin-c4a21cdcdb2f/lib/active_admin/application.rb:276:in `block in attach_reloader'
  from /Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:36:in `call'
  from /Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
  from /Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
  from /Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:44:in `each'
  from /Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
  from /Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/gems/railties-4.1.9/lib/rails/application/finisher.rb:64:in `block in <module:Finisher>'
  from /Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `instance_exec'
  from /Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `run'
  from /Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/gems/railties-4.1.9/lib/rails/initializable.rb:55:in `block in run_initializers'
  from /Users/jhanggi/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
  from /Users/jhanggi/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
  from /Users/jhanggi/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
  from /Users/jhanggi/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
  from /Users/jhanggi/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:345:in `each'
  from /Users/jhanggi/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:345:in `call'
  from /Users/jhanggi/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
  from /Users/jhanggi/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
  from /Users/jhanggi/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
  from /Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/gems/railties-4.1.9/lib/rails/initializable.rb:54:in `run_initializers'
  from /Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/gems/railties-4.1.9/lib/rails/application.rb:300:in `initialize!'
  from /Users/jhanggi/Documents/workspace/project-website/config/environment.rb:5:in `<top (required)>'
  from /Users/jhanggi/Documents/workspace/project-website/spec/rails_helper.rb:9:in `require'
  from /Users/jhanggi/Documents/workspace/project-website/spec/rails_helper.rb:9:in `<top (required)>'
  from /Users/jhanggi/Documents/workspace/project-website/spec/actions/admin/creates_subscription_summary_spec.rb:1:in `require'
  from /Users/jhanggi/Documents/workspace/project-website/spec/actions/admin/creates_subscription_summary_spec.rb:1:in `<top (required)>'
  from /Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1058:in `load'
  from /Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1058:in `block in load_spec_files'
  from /Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1058:in `each'
  from /Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/gems/rspec-core-3.0.4/lib/rspec/core/configuration.rb:1058:in `load_spec_files'
  from /Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:97:in `setup'
  from /Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:85:in `run'
  from /Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:70:in `run'
  from /Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/gems/rspec-core-3.0.4/lib/rspec/core/runner.rb:38:in `invoke'
  from /Users/jhanggi/.rvm/gems/ruby-2.1.4@project-website/gems/rspec-core-3.0.4/exe/rspec:4:in `<main>'
```

**Comment by timoschilling** [comment]
Can you provide a test setup for that?

**Comment by jhanggi** [comment]
This is a fresh rails 4.1.9 application: https://github.com/jhanggi/active_admin_break_within_engine

I receive the same error when I try to run `rails s`.

I tried to provide discrete commits to see what all I've done for setup. Both of the last two commits break. 

It's when I add the `::ActiveAdmin.application.load_paths.unshift` per https://github.com/activeadmin/activeadmin/wiki/Define-a-resource-inside-an-engine that the error happens. I provided the second commit of moving the dashboard out of the eager load path into `lib` just to also show that does not help.

**Comment by jhanggi** [comment]
I also tried upgrading to Rails 4.2.0 and received the same error.

**Comment by jhanggi** [comment]
I do not receive the error when locking to 1.0.0.pre1 (see branch https://github.com/jhanggi/active_admin_break_within_engine/tree/lock_active_admin_to_pre1)

**Comment by timoschilling** [comment]
Maybe @chancancode can take a look onto that?

**Comment by timoschilling** [comment]
Tray to change this:
```ruby
::ActiveAdmin.application.load_paths.unshift root.join('lib', 'admin')
# to
::ActiveAdmin.application.load_paths.unshift root.join('lib', 'admin').to_s
```

**Comment by jhanggi** [comment]
That seems to do the trick. Thanks for the help!
