### ISSUE TITLE
Can't install in new app

### ISSUE THREAD

**Issue by grimmwerks** [activeadmin/activeadmin#3913]
Just started this app - only a few models, generated and migrated.  Adding ActiveAdmin -- and specifically in the Gemfile as 

gem 'activeadmin', github: 'activeadmin'

I get this:

```
user$ rails g active_admin:install --verbose
      invoke  devise
/Users/user/.rvm/gems/ruby-2.1.0/bundler/gems/activeadmin-f5b1602ed4a3/lib/generators/active_admin/devise/devise_generator.rb:21:in `rescue in install_devise': To use devise you need to specify it in your Gemfile. If you don't want to use devise, run the generator with --skip-users. (ActiveAdmin::GeneratorError)
	from /Users/user/.rvm/gems/ruby-2.1.0/bundler/gems/activeadmin-f5b1602ed4a3/lib/generators/active_admin/devise/devise_generator.rb:18:in `install_devise'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/group.rb:277:in `block in _invoke_for_class_method'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/shell.rb:68:in `with_padding'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/group.rb:266:in `_invoke_for_class_method'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/group.rb:133:in `_invoke_from_option_users'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/railties-4.2.0/lib/rails/generators.rb:157:in `invoke'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/railties-4.2.0/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/user/Documents/__WORK/RAILS/welldata/bin/rails:8:in `<top (required)>'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/user/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
	from /Users/user/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/user/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

Looked on stackoverflow and the only answer that is exactly the same as mine went unresolved:  http://stackoverflow.com/questions/28744530/active-admin-install-error

**Comment by timoschilling** [comment]
Take a closer look to the error message: "To use devise you need to specify it in your Gemfile. If you don't want to use devise, run the generator with --skip-users."
