### ISSUE TITLE
ActionController::RoutingError (No route matches [POST]) -- method there.

### ISSUE THREAD

**Issue by grimmwerks** [activeadmin/activeadmin#3924]
This is driving me a bit nuts. As background I'm trying to change the pulldown of a second resource based upon the resources of a first resource as described here (http://stackoverflow.com/questions/9579402/active-admin-refresh-second-drop-down-based-on-first-drop-down-ruby-on-rails)  but more importantly I see the path in my routes.rb and via rake routes, and test an active admin controller function that works with GET but not with POST and I don't understand.

In my routes.rb I have added this (second line is the the test to show that GET gets to the controller):

```
  post '/change_base_product_sensor_locations', :to =>'admin/products#change_base_product_sensor_locations'
  get "/blurp", :to => "admin/products#blurp"
  resources :products
```

In my rake routes:
```
change_base_product_sensor_locations POST       /change_base_product_sensor_locations(.:format) admin/products#change_base_product_sensor_locations
...
                               blurp GET        /blurp(.:format)                                admin/products#blurp
```

So they're there.  In my controller for admin/product.rb

```
controller do
  def change_base_product_sensor_locations
    @sensor_locations = BaseProduct.find_by_id(params[:base_product_id]).try(:sensor_locations)
    # render :text=>view_context.options_from_collection_for_select(@sensor_locations, :id)
    # puts "GOT IT"
  end

  def blurp
  	render :text => "<h1>Hello Blurp</h1>".html_safe
  end
end
```

and in the form (which shows how I'm calling the post:
```
	f.inputs do
	  #...
	    f.input :base_product, :input_html => {
	        :onchange => remote_request(:post, :change_base_product_sensor_locations, {:base_product_id=>"$('#base_product_id').val()"}, :sensor_location_id)
	    }
	    # f.input :sensor_location
	  #...
	 end
```

When I pull the selection of the base_product it fires, posts to /change_base_product_sensor_locations  and I see output:

```
Started POST "/admin/products/change_base_product_sensor_locations" for ::1 at 2015-04-29 22:05:45 -0400

ActionController::RoutingError (No route matches [POST] "/admin/products/change_base_product_sensor_locations"):
  actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  web-console (2.1.2) lib/web_console/middleware.rb:37:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.0) lib/rails/engine.rb:518:in `call'
  railties (4.2.0) lib/rails/application.rb:164:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  rack (1.6.0) lib/rack/content_length.rb:15:in `call'
  rack (1.6.0) lib/rack/handler/webrick.rb:89:in `service'
  /Users/grimm/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
  /Users/grimm/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
  /Users/grimm/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'


  Rendered /Users/grimm/.rvm/gems/ruby-2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb (0.5ms)
  Rendered /Users/grimm/.rvm/gems/ruby-2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/routing_error.text.erb (5.5ms)
  Rendered /Users/grimm/.rvm/gems/ruby-2.1.0/gems/web-console-2.1.2/lib/web_console/templates/_markup.html.erb (0.4ms)
  Rendered /Users/grimm/.rvm/gems/ruby-2.1.0/gems/web-console-2.1.2/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.5ms)
  Rendered /Users/grimm/.rvm/gems/ruby-2.1.0/gems/web-console-2.1.2/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.3ms)
  Rendered /Users/grimm/.rvm/gems/ruby-2.1.0/gems/web-console-2.1.2/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.3ms)
  Rendered /Users/grimm/.rvm/gems/ruby-2.1.0/gems/web-console-2.1.2/lib/web_console/templates/console.js.erb within layouts/javascript (15.9ms)
  Rendered /Users/grimm/.rvm/gems/ruby-2.1.0/gems/web-console-2.1.2/lib/web_console/templates/main.js.erb within layouts/javascript (0.3ms)
  Rendered /Users/grimm/.rvm/gems/ruby-2.1.0/gems/web-console-2.1.2/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.4ms)
  Rendered /Users/grimm/.rvm/gems/ruby-2.1.0/gems/web-console-2.1.2/lib/web_console/templates/index.html.erb (36.1ms)

```

The crazy thing is if I attempt to go to the silly /blurp as a regular GET:
```
Started GET "/blurp" for ::1 at 2015-04-29 22:06:39 -0400
Processing by Admin::ProductsController#blurp as HTML
  AdminUser Load (0.5ms)  SELECT  "admin_users".* FROM "admin_users" WHERE "admin_users"."id" = $1  ORDER BY "admin_users"."id" ASC LIMIT 1  [["id", 2]]
  Rendered text template (0.0ms)
Completed 200 OK in 4ms (Views: 1.4ms | ActiveRecord: 0.5ms)

```

**Comment by timoschilling** [comment]
Your routes are configuring this path `/change_base_product_sensor_locations` and rake shows this path too. But your request go's to `/admin/products/change_base_product_sensor_locations`.

**Comment by grimmwerks** [comment]
But doesn't the route setting the post:

post '/change_base_product_sensor_locations', :to =>'admin/products#change_base_product_sensor_locations'

And what's happening in terminal:
Started POST "/admin/products/change_base_product_sensor_locations" for ::1 at 2015-04-29 22:05:45 -0400

ActionController::RoutingError (No route matches [POST] "/admin/products/change_base_product_sensor_locations"):

Show that it's actually sending properly?  Like I said I set the same sort of route with /blurp as a get to /admin/products/blurp and it worked PERFECTLY at the method right next to the POST one?

**Comment by timoschilling** [comment]
Yes, you set up '/change_base_product_sensor_locations', but you call "/admin/products/change_base_product_sensor_locations"!

If I take a look on the implementation of `remote_request` on stackoverflow, it need's the complete path and not a relative path.
```ruby
#application_helper.rb
def remote_request(type, path, params={}, target_tag_id)
  "$.#{type}('#{path}',
             {#{params.collect { |p| "#{p[0]}: #{p[1]}" }.join(", ")}},
             function(data) {$('##{target_tag_id}').html(data);}
   );"
end
```

You need to change your route to:
```ruby
post '/admin/products/change_base_product_sensor_locations', :to => 'admin/products#change_base_product_sensor_locations'
```
or your form code to:
```ruby
    f.inputs do
      #...
        f.input :base_product, :input_html => {
            :onchange => remote_request(:post, "/change_base_product_sensor_locations", {:base_product_id=>"$('#base_product_id').val()"}, :sensor_location_id)
        }
        # f.input :sensor_location
      #...
     end
```

**Comment by grimmwerks** [comment]
Yes I've got the application_helper code in as well (sorry, forgot to post).
 
Well - you're right; just changing the form to /change_base_product_sensor_locations did it.  I understand now - since it was calling a function within the product admin controller it already *thought* the 'send channel' so to speak was /admin/products/change_base_product_sensor_location -- so as you say I can either change it to be a root method or change the routes to listen for the actual path /admin/products/ etc -- 

Thanks very much for your help / explanation.
