### ISSUE TITLE
Unable to build menu for namespaces 

### ISSUE THREAD

**Issue by paquettej** [activeadmin/activeadmin#3960]
This issue has 2 parts. I am breaking my app into a few namespaces: admin, product1, product2 (for example). The values used for product1 and product2 are not built or creating within the app, rather they are code names for internal projects within the company. 

It seems there is 1 menu per namespace in active admin. I want to add some links to all menus within the application. I added a block in active_admin.rb to configure the menu for each of my namespaces but this resulted in duplicate root routes for the product1 and product2 namespaces.

Is there a way to have a single menu inherited by each namespace? If not, how can I customize the menus for product1 and product2?

**Comment by seanlinsley** [comment]
I'm sorry, I'm not sure what you're trying to accomplish. Screenshots or example code might help explain.

**Comment by snowmoonsoftware** [comment]
Sorry, here's more details. In my active_admin.rb initializer, I have the following menu structure:

```
  config.namespace :root do |admin|

    # This block will edit the default menu
    admin.build_menu do |menu|
      menu.add label: 'Admin', priority: 0
      menu.add label: 'Unifi', url: '/unifi', priority: 5
      menu.add label: 'Empower', url: '/empower', priority: 5
      menu.add label: 'Help', url: '/help', priority: 25
    end
  end


  config.namespace :unifi do |unifi|

    # This block will edit the default menu
    unifi.build_menu do |menu|
      menu.add label: 'Admin', priority: 0
      menu.add label: 'Unifi', url: '/unifi', priority: 5
      menu.add label: 'Empower', url: '/empower', priority: 5
      menu.add label: 'Raw Data', url: '/metrics', priority: 24
      menu.add label: 'Help', url: '/help', priority: 25
    end
  end

  config.namespace :empower do |empower|

    # This block will edit the default menu
    empower.build_menu do |menu|
      menu.add label: 'Admin', priority: 0
      menu.add label: 'Unifi', url: '/unifi', priority: 5
      menu.add label: 'Empower', url: '/empower', priority: 5
      menu.add label: 'Raw Data', url: '/metrics', priority: 24
      menu.add label: 'Help', url: '/help', priority: 25
    end
  end
```

Given the folders:
```
app\admin\unifi
app\admin\empower
```
where each folder contains a dashboard.rb:

```
ActiveAdmin.register_page 'Dashboard', namespace: 'empower' do
...
end
```

```
ActiveAdmin.register_page 'Dashboard', namespace: 'unifi' do
...
end
````

routes.rb:
```
Metrics::Application.routes.draw do
  get 'help/about'
  get 'help', to: 'help#index'
  get 'help/browsers'
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources :users

  mount Dalli::Ui::Engine, at: 'cache'
end
```


When I start the server, it aborts :
```
/Users/Jeff/snowmoon/metrics/vendor/bundle/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:555:in `add_route': Invalid route name, already in use: 'empower_root'  (ArgumentError)
You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here: 
http://guides.rubyonrails.org/routing.html#restricting-the-routes-created
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1561:in `add_route'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1536:in `decomposed_match'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1517:in `block in match'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1507:in `each'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1507:in `match'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:387:in `root'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1580:in `root'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/bundler/gems/active_admin-48a8674a4566/lib/active_admin/router.rb:27:in `block (3 levels) in define_root_routes'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:881:in `block in namespace'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:816:in `scope'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:881:in `namespace'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/actionpack-4.2.1/lib/action_dispatch/routing/mapper.rb:1455:in `namespace'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/bundler/gems/active_admin-48a8674a4566/lib/active_admin/router.rb:26:in `block (2 levels) in define_root_routes'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/bundler/gems/active_admin-48a8674a4566/lib/active_admin/namespace.rb:239:in `each'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/bundler/gems/active_admin-48a8674a4566/lib/active_admin/namespace.rb:239:in `each'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/bundler/gems/active_admin-48a8674a4566/lib/active_admin/router.rb:22:in `block in define_root_routes'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/bundler/gems/active_admin-48a8674a4566/lib/active_admin/router.rb:21:in `instance_exec'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/bundler/gems/active_admin-48a8674a4566/lib/active_admin/router.rb:21:in `define_root_routes'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/bundler/gems/active_admin-48a8674a4566/lib/active_admin/router.rb:16:in `apply'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/bundler/gems/active_admin-48a8674a4566/lib/active_admin/application.rb:212:in `routes'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/bundler/gems/active_admin-48a8674a4566/lib/active_admin.rb:79:in `routes'
	from /Users/Jeff/snowmoon/metrics/config/routes.rb:7:in `block in <top (required)>'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:410:in `draw'
	from /Users/Jeff/snowmoon/metrics/config/routes.rb:1:in `<top (required)>'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:40:in `each'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/activesupport-4.2.1/lib/active_support/file_update_checker.rb:75:in `call'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/activesupport-4.2.1/lib/active_support/file_update_checker.rb:75:in `execute'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/railties-4.2.1/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/Jeff/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
	from /Users/Jeff/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/Jeff/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
	from /Users/Jeff/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/Jeff/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each'
	from /Users/Jeff/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `call'
	from /Users/Jeff/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/Jeff/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
	from /Users/Jeff/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/railties-4.2.1/lib/rails/railtie.rb:194:in `public_send'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/railties-4.2.1/lib/rails/railtie.rb:194:in `method_missing'
	from /Users/Jeff/snowmoon/metrics/config/environment.rb:5:in `<top (required)>'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/Jeff/snowmoon/metrics/config.ru:3:in `block in <main>'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/rack-1.6.0/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/rack-1.6.0/lib/rack/builder.rb:55:in `initialize'
	from /Users/Jeff/snowmoon/metrics/config.ru:in `new'
	from /Users/Jeff/snowmoon/metrics/config.ru:in `<main>'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/rack-1.6.0/lib/rack/builder.rb:49:in `eval'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/rack-1.6.0/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/rack-1.6.0/lib/rack/builder.rb:40:in `parse_file'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/rack-1.6.0/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/rack-1.6.0/lib/rack/server.rb:208:in `app'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/railties-4.2.1/lib/rails/commands/server.rb:61:in `app'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/rack-1.6.0/lib/rack/server.rb:336:in `wrapped_app'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/railties-4.2.1/lib/rails/commands/server.rb:139:in `log_to_stdout'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/railties-4.2.1/lib/rails/commands/server.rb:78:in `start'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/Jeff/snowmoon/metrics/vendor/bundle/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by timoschilling** [comment]
Maybe this will help you https://github.com/activeadmin/activeadmin/blob/7c18de4cbcf5180749dea0000402b39f9f469784/lib/active_admin/application.rb#L76

**Comment by snowmoonsoftware** [comment]
I am already specifying root_to -- I don't understand how this would help here. Could you provide a little more detail please?

**Comment by timoschilling** [comment]
```ruby
  config.namespace :root do |admin|
    admin.root_to_options as: "admin_root"
    # This block will edit the default menu
    admin.build_menu do |menu|
      ...
    end
  end


  config.namespace :unifi do |unifi|
    unifi.root_to_options as: "unifi_root"
    # This block will edit the default menu
    unifi.build_menu do |menu|
      ...
    end
  end

  config.namespace :empower do |empower|
    empower.root_to_options as: "empower_root"
    # This block will edit the default menu
    empower.build_menu do |menu|
      ...
    end
  end
```

**Comment by snowmoonsoftware** [comment]
```empower.root_to_options as: "empower_root"`` gave me an argument error. I ended up with the following that allows the app to start:

```
  config.namespace :admin do |admin|

    admin.root_to_options= { as: 'admin_root' }
    # This block will edit the default menu
    admin.build_menu do |menu|
      menu.add label: 'Admin', priority: 0
      menu.add label: 'Unifi', url: '/unifi', priority: 5
      menu.add label: 'Empower', url: '/empower', priority: 5
      menu.add label: 'Raw Data', url: '/metrics', priority: 24
      menu.add label: 'Help', url: '/help', priority: 25
    end
  end

  config.namespace :root do |admin|

    # This block will edit the default menu
    admin.build_menu do |menu|
      menu.add label: 'Admin', priority: 0
      menu.add label: 'Unifi', url: '/unifi', priority: 5
      menu.add label: 'Empower', url: '/empower', priority: 5
      menu.add label: 'Raw Data', url: '/metrics', priority: 24
      menu.add label: 'Help', url: '/help', priority: 25
    end
  end


  config.namespace :unifi do |unifi|

    # This block will edit the default menu
    unifi.root_to_options= { as: 'unifi_root' }
    unifi.build_menu do |menu|
      menu.add label: 'Admin', priority: 0
      menu.add label: 'Unifi', url: '/unifi', priority: 5
      menu.add label: 'Empower', url: '/empower', priority: 5
      menu.add label: 'Raw Data', url: '/metrics', priority: 24
      menu.add label: 'Help', url: '/help', priority: 25
    end
  end

  config.namespace :empower do |empower|

    # This block will edit the default menu
    empower.root_to_options= { as: 'empower_root' }
    empower.build_menu do |menu|
      menu.add label: 'Admin', priority: 0
      menu.add label: 'Unifi', url: '/unifi', priority: 5
      menu.add label: 'Empower', url: '/empower', priority: 5
      menu.add label: 'Raw Data', url: '/metrics', priority: 24
      menu.add label: 'Help', url: '/help', priority: 25
    end
  end
```
This gets me the following menus:

Root:
![root-menu](https://cloud.githubusercontent.com/assets/22698/9145446/6ed65bbe-3d22-11e5-89a8-c4e885385231.png)

Empower:
![empower-menu](https://cloud.githubusercontent.com/assets/22698/9145445/6ed3f928-3d22-11e5-8a23-dddf20fa542d.png)

UNIFI:
![unifi-menu](https://cloud.githubusercontent.com/assets/22698/9145447/6ed6e7dc-3d22-11e5-9a9d-8c7cbb19ebdc.png)


Note that in the UNIFI and Empower namespaces, only registered pages show. The menus built in the config are missing.

**Comment by timoschilling** [comment]
Sorry, I have made a syntax mistake. I mean `unifi.root_to_options=` not `unifi.root_to_options`

**Comment by davidwparker** [comment]
I'm having the same issue, but I'm not able to get the app to start. 

Once I add `"namespace: "admins" do` to a subfolder's dashboard.rb, it blows up with the same error:

```
Invalid route name, already in use: 'admins_root'  (ArgumentError)
You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming.
```

I've tried adding `root_to` and `root_to_options=`:
```
config.namespace :superadmin do |superadmin|
      superadmin.root_to_options= {as: "superadmin_root"}
      superadmin.root_to="dashboard#index"
end
```
```
config.namespace :admins do |admins|
      admins.root_to_options= {as: "admins_root"}
      admins.root_to="admins/dashboard#index"
end
```

But I still have the error above where it won't let me start the server.

Note that I tried other things and posted on SO before finding this issue, (http://stackoverflow.com/questions/41841367/multiple-namespaces-on-rails-activeadmin-issues)
