### ISSUE TITLE
undefined method `name' for nil:NilClass

### ISSUE THREAD

**Issue by BlackRabbitt** [activeadmin/activeadmin#3964]
Hello All, I am having a problem with active admin. I am getting the following issue,
```undefined method `name' for nil:NilClass``` around the line ```insert_tag renderer_for(:index)```

With following log,

```
2015-05-26T05:53:56.111071+00:00 app[web.1]: ActionView::Template::Error (undefined method `name' for nil:NilClass):
2015-05-26T05:53:56.111073+00:00 app[web.1]:     1: insert_tag renderer_for(:index)
2015-05-26T05:53:56.111075+00:00 app[web.1]:   app/admin/***.rb:41:in `block (5 levels) in <top (required)>'
2015-05-26T05:53:56.111076+00:00 app[web.1]:   app/admin/***.rb:40:in `block (4 levels) in <top (required)>'
2015-05-26T05:53:56.111078+00:00 app[web.1]:   app/admin/***.rb:39:in `block (3 levels) in <top (required)>'
2015-05-26T05:53:56.111080+00:00 app[web.1]:   app/admin/***.rb:38:in `block (2 levels) in <top (required)>'
2015-05-26T05:53:56.111081+00:00 app[web.1]:
2015-05-26T05:53:56.111083+00:00 app[web.1]:
2015-05-26T05:53:56.111087+00:00 app[web.1]:
2015-05-26T05:53:56.111089+00:00 app[web.1]: ActionView::Template::Error (undefined method `name' for nil:NilClass):
2015-05-26T05:53:56.111091+00:00 app[web.1]:     1: insert_tag renderer_for(:index)
2015-05-26T05:53:56.111092+00:00 app[web.1]:   app/admin/***.rb:41:in `block (5 levels) in <top (required)>'
2015-05-26T05:53:56.111094+00:00 app[web.1]:   app/admin/***.rb:40:in `block (4 levels) in <top (required)>'
2015-05-26T05:53:56.111095+00:00 app[web.1]:   app/admin/***.rb:39:in `block (3 levels) in <top (required)>'
2015-05-26T05:53:56.111097+00:00 app[web.1]:   app/admin/***.rb:38:in `block (2 levels) in <top (required)>'
```

I googled for the issue. Some suggested to pull the activeadmin from master branch. I tried it too.
I updated the gemfile as: 
```gem 'activeadmin', github: 'activeadmin'```
But this didn't helped me too. The issue was same. 

I am using ```rails 4.0.4```

Please can someone help me with this issue.
Best Regards.

**Comment by timoschilling** [comment]
On which action does this happen? Please post the related resource file and a stacktrace with full filename.

**Comment by BlackRabbitt** [comment]
Sorry, My mistake. The ```name``` field in the database was empty.
