### ISSUE TITLE
Missing helper issue when installing after bundle install.

### ISSUE THREAD

**Issue by storycoder** [activeadmin/activeadmin#3997]
Here is what i get in command terminal:

```
$ rails g active_admin:install User
/Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/abstract_controller/helpers.rb:151:in `rescue in block in modules_for_helpers': Missing helper file helpers//users/josephmargolis/documents/tts/rails/joestock_carrierwave/joe_stock/app/helpers/application_helper.rb_helper.rb (AbstractController::Helpers::MissingHelperError)
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/abstract_controller/helpers.rb:148:in `block in modules_for_helpers'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/abstract_controller/helpers.rb:144:in `map!'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/abstract_controller/helpers.rb:144:in `modules_for_helpers'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/action_controller/metal/helpers.rb:93:in `modules_for_helpers'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/abstract_controller/helpers.rb:108:in `helper'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/action_controller/railties/helpers.rb:17:in `inherited'
	from /Users/josephmargolis/Documents/tts/rails/joestock-carrierwave/joestock/app/controllers/application_controller.rb:1:in `<top (required)>'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:457:in `load'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:457:in `block in load_file'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:647:in `new_constants_in'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:456:in `load_file'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:354:in `require_or_load'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:494:in `load_missing_constant'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:184:in `const_missing'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/inflector/methods.rb:261:in `const_get'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/inflector/methods.rb:261:in `block in constantize'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/inflector/methods.rb:259:in `each'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/inflector/methods.rb:259:in `inject'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/inflector/methods.rb:259:in `constantize'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/devise-3.5.1/app/controllers/devise_controller.rb:2:in `<top (required)>'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:457:in `load'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:457:in `block in load_file'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:647:in `new_constants_in'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:456:in `load_file'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:354:in `require_or_load'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:494:in `load_missing_constant'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:184:in `const_missing'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/devise-3.5.1/app/controllers/devise/sessions_controller.rb:1:in `<top (required)>'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:457:in `load'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:457:in `block in load_file'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:647:in `new_constants_in'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:456:in `load_file'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:354:in `require_or_load'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:494:in `load_missing_constant'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:184:in `const_missing'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/bundler/gems/activeadmin-0b4b22871fd3/lib/active_admin/devise.rb:53:in `<module:Devise>'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/bundler/gems/activeadmin-0b4b22871fd3/lib/active_admin/devise.rb:6:in `<module:ActiveAdmin>'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/bundler/gems/activeadmin-0b4b22871fd3/lib/active_admin/devise.rb:5:in `<top (required)>'
	from /Users/josephmargolis/Documents/tts/rails/joestock-carrierwave/joestock/config/routes.rb:3:in `block in <top (required)>'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:410:in `draw'
	from /Users/josephmargolis/Documents/tts/rails/joestock-carrierwave/joestock/config/routes.rb:1:in `<top (required)>'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:40:in `each'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/file_update_checker.rb:75:in `call'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/file_update_checker.rb:75:in `execute'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/josephmargolis/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /Users/josephmargolis/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/josephmargolis/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /Users/josephmargolis/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/josephmargolis/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /Users/josephmargolis/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /Users/josephmargolis/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/josephmargolis/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /Users/josephmargolis/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
	from /Users/josephmargolis/Documents/tts/rails/joestock-carrierwave/joestock/config/environment.rb:5:in `<top (required)>'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/application.rb:92:in `preload'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/application.rb:143:in `serve'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/application.rb:131:in `block in run'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/application.rb:125:in `loop'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/application.rb:125:in `run'
	from /Users/josephmargolis/.rvm/gems/ruby-2.2.1/gems/spring-1.3.6/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/josephmargolis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/josephmargolis/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

**Comment by timoschilling** [comment]
That doesn't look like a ActiveAdmin problem.

The required helper path is wrong:
`helpers//users/josephmargolis/documents/tts/rails/joestock_carrierwave/joe_stock/app/helpers/application_helper.rb_helper.rb`
That should be look like:
`helpers/application_helper.rb`

Please do the following:
1. remove the ActiveAdmin gem
2. run `rails g model Foo`

If that work do the following:
1. Add the devise gem, but not the ActiveAdmin gem
2. run `rails runner 'Devise::SessionsController'`

Please report the results

**Comment by storycoder** [comment]
Thanks will check and get back to you.

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.

**Comment by phil** [comment]
Hi, I believe this issue is connected to a Rails bug https://github.com/rails/rails/issues/18660 

The apparent 'fix' is to ensure the parent directory names of a Rails 4 app are all lowercase. Moving directories to a temporary location, and then back again to their original location, but in lowercase, solves the issue.

**Comment by budree** [comment]
If running on windows, use a cmd console to start your server instead of a git bash (or any bash console).
