### ISSUE TITLE
inherited resources seems to use collection_name instead instance_name

### ISSUE THREAD

**Issue by andreirt** [activeadmin/activeadmin#4005]
I have three nested resources in Active Admin:

    ActiveAdmin.register Point

    ActiveAdmin.register Work do
        belongs_to :point
    end

    ActiveAdmin.register WorkImage, as: 'Image' do
        belongs_to :work

        controller do
            nested_belongs_to :work, :point
        end

    end

In routes.rb, I have:

    namespace :admin do
        resources :points do
            resources :works do
                resources :images
            end
        end
    end

The breadcrumbs are generated correctly, but, when I try to access

    /admin/points/1/works/1/images

I get this error:

    undefined method `points' for #

Instead of accessing 'point', inherited resources is trying to access 'points'. This is the error full trace:
```
activemodel (4.2.2) lib/active_model/attribute_methods.rb:433:in `method_missing'
inherited_resources (1.6.0) lib/inherited_resources/belongs_to_helpers.rb:85:in `evaluate_parent'
inherited_resources (1.6.0) lib/inherited_resources/base_helpers.rb:144:in `block in association_chain'
inherited_resources (1.6.0) lib/inherited_resources/base_helpers.rb:143:in `each'
inherited_resources (1.6.0) lib/inherited_resources/base_helpers.rb:143:in `inject'
inherited_resources (1.6.0) lib/inherited_resources/base_helpers.rb:143:in `association_chain'
inherited_resources (1.6.0) lib/inherited_resources/base_helpers.rb:182:in `end_of_association_chain'
/home/andrei/.bundler/ruby/1.9.1/activeadmin-1fb85de86e53/lib/active_admin/resource_controller/data_access.rb:74:in `scoped_collection'
/home/andrei/.bundler/ruby/1.9.1/activeadmin-1fb85de86e53/lib/active_admin/resource_controller/data_access.rb:56:in `find_collection'
/home/andrei/.bundler/ruby/1.9.1/activeadmin-1fb85de86e53/lib/active_admin/resource_controller/data_access.rb:42:in `collection'
inherited_resources (1.6.0) lib/inherited_resources/actions.rb:7:in `index'
/home/andrei/.bundler/ruby/1.9.1/activeadmin-1fb85de86e53/lib/active_admin/resource_controller/streaming.rb:12:in `index'
app/admin/work_image.rb:79:in `index'
actionpack (4.2.2) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.2) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.2) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.2) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.2) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.2) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.2) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.2) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.2) lib/active_support/callbacks.rb:92:in `_run_callbacks'
activesupport (4.2.2) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
activesupport (4.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.2) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.2) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.2) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.2) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.2) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.2) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.2) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:74:in `call'
actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:43:in `serve'
actionpack (4.2.2) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.2) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.2) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:819:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
rack (1.6.4) lib/rack/etag.rb:24:in `call'
rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.4) lib/rack/head.rb:13:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.2) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
activerecord (4.2.2) lib/active_record/migration.rb:378:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.2) lib/active_support/callbacks.rb:88:in `call'
activesupport (4.2.2) lib/active_support/callbacks.rb:88:in `_run_callbacks'
activesupport (4.2.2) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
activesupport (4.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
web-console (2.1.3) lib/web_console/middleware.rb:37:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.2) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.2) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.4) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
actionpack (4.2.2) lib/action_dispatch/middleware/static.rb:113:in `call'
rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
railties (4.2.2) lib/rails/engine.rb:518:in `call'
railties (4.2.2) lib/rails/application.rb:164:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
rack (1.6.4) lib/rack/content_length.rb:15:in `call'
rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
/usr/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
/usr/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
/usr/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
```

**Comment by timoschilling** [comment]
Is this still a issue?

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
