### ISSUE TITLE
Pagination: undefined method `offset' 

### ISSUE THREAD

**Issue by snowmoonsoftware** [activeadmin/activeadmin#4059]
I am using activeadmin from git, not v0.6. After updating my bundle, pagination no longer works.

![capture](https://cloud.githubusercontent.com/assets/22698/9145832/703f6380-3d25-11e5-84b1-51cb66b862f8.PNG)

Partial stack trace
```
/home/metrics/.rvm/gems/ruby-2.1.2@metrics/bundler/gems/active_admin-040c4647871e/lib/active_admin/views/components/paginated_collection.rb:109:in `build_pagination'
/home/metrics/.rvm/gems/ruby-2.1.2@metrics/bundler/gems/active_admin-040c4647871e/lib/active_admin/views/components/paginated_collection.rb:70:in `block in build_pagination_with_formats'
arbre (1.0.3) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.0.3) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.0.3) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.0.3) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.0.3) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.0.3) lib/arbre/element/builder_methods.rb:14:in `div'
/home/metrics/.rvm/gems/ruby-2.1.2@metrics/bundler/gems/active_admin-040c4647871e/lib/active_admin/views/components/paginated_collection.rb:68:in `build_pagination_with_formats'
/home/metrics/.rvm/gems/ruby-2.1.2@metrics/bundler/gems/active_admin-040c4647871e/lib/active_admin/views/components/paginated_collection.rb:52:in `build'
arbre (1.0.3) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
arbre (1.0.3) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.0.3) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.0.3) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.0.3) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.0.3) lib/arbre/element/builder_methods.rb:14:in `paginated_collection'
/home/metrics/.rvm/gems/ruby-2.1.2@metrics/bundler/gems/active_admin-040c4647871e/lib/active_admin/views/pages/index.rb:132:in `render_index'
/home/metrics/.rvm/gems/ruby-2.1.2@metrics/bundler/gems/active_admin-040c4647871e/lib/active_admin/views/pages/index.rb:50:in `build_collection'
/home/metrics/.rvm/gems/ruby-2.1.2@metrics/bundler/gems/active_admin-040c4647871e/lib/active_admin/views/pages/index.rb:28:in `block in main_content'
```

Gemfile:
```
source 'https://rubygems.org'
source 'https://rails-assets.org'

ruby '2.1.2'
gem 'rails', '~>4.2.0'
gem 'sass-rails', '~> 4.0.2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem 'bootstrap-sass'
gem 'cancan'
gem 'devise'
gem 'figaro'
gem 'mysql2'
gem 'rolify'
gem 'simple_form'
gem 'therubyracer', :platform=>:ruby
gem 'tiny_tds'
gem 'activerecord-sqlserver-adapter', '~> 4.2.0' # must match version of rails
gem 'dalli'
gem 'actionpack-action_caching'
gem 'dalli-ui'

gem 'activeadmin', github: 'gregbell/active_admin'
gem 'draper'
#gem 'activeadmin-axlsx'
gem 'flot-rails', git: 'git://github.com/snowmoonsoftware/flot-rails.git'
gem 'useragent'
gem 'datejs-rails'
gem 'autoprefixer-rails'
gem 'syntax-highlighter-rails'
gem 'font-awesome-rails'

group :production do
#  gem 'newrelic_rpm'
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'#, :platforms=>[:mri_19, :mri_20, :rbx]
  # gem 'rack-mini-profiler'
  # gem 'flamegraph'
  # gem 'stackprof'
  gem 'guard-bundler'
  gem 'guard-rails'
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'rb-fchange', :require=>false
  gem 'rb-fsevent', :require=>false
  gem 'rb-inotify', :require=>false
  gem 'bullet'
  gem 'capistrano'
  gem 'capistrano-rails', '~> 1.1.1'
  gem 'capistrano-bundler', '~> 1.1.2'
  gem 'capistrano-rvm', '~> 0.1.1'
  gem 'capistrano-passenger'
end
group :development, :test do
  gem 'factory_girl_rails'
end
```

GemFile.lock
```
GIT
  remote: git://github.com/gregbell/active_admin.git
  revision: 040c4647871e7e3265a82f950232a0f38696f74e
  specs:
    activeadmin (1.0.0.pre1)
      arbre (~> 1.0, >= 1.0.2)
      bourbon
      coffee-rails
      formtastic (~> 3.1)
      formtastic_i18n
      inherited_resources (~> 1.6)
      jquery-rails
      jquery-ui-rails (~> 5.0)
      kaminari (~> 0.15)
      rails (>= 3.2, < 5.0)
      ransack (~> 1.3)
      sass-rails

GIT
  remote: git://github.com/snowmoonsoftware/flot-rails.git
  revision: f5a5f888a6930abc417d8fdc01422d240ca6fcdb
  specs:
    flot-rails (0.0.4)
      jquery-rails

GEM
  remote: https://rubygems.org/
  remote: https://rails-assets.org/
  specs:
    actionmailer (4.2.3)
      actionpack (= 4.2.3)
      actionview (= 4.2.3)
      activejob (= 4.2.3)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.3)
      actionview (= 4.2.3)
      activesupport (= 4.2.3)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionpack-action_caching (1.1.1)
      actionpack (>= 4.0.0, < 5.0)
    actionview (4.2.3)
      activesupport (= 4.2.3)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    activejob (4.2.3)
      activesupport (= 4.2.3)
      globalid (>= 0.3.0)
    activemodel (4.2.3)
      activesupport (= 4.2.3)
      builder (~> 3.1)
    activerecord (4.2.3)
      activemodel (= 4.2.3)
      activesupport (= 4.2.3)
      arel (~> 6.0)
    activerecord-sqlserver-adapter (4.2.4)
      activerecord (~> 4.2.1)
    activesupport (4.2.3)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    arbre (1.0.3)
      activesupport (>= 3.0.0)
    arel (6.0.3)
    autoprefixer-rails (5.2.1.1)
      execjs
      json
    bcrypt (3.1.10)
    better_errors (2.1.1)
      coderay (>= 1.0.0)
      erubis (>= 2.6.6)
      rack (>= 0.9.0)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bootstrap-sass (3.3.5)
      autoprefixer-rails (>= 5.0.0.1)
      sass (>= 3.2.19)
    bourbon (3.2.4)
      sass (~> 3.2)
      thor
    builder (3.2.2)
    bullet (4.14.7)
      activesupport (>= 3.0.0)
      uniform_notifier (~> 1.9.0)
    cancan (1.6.10)
    capistrano (3.4.0)
      i18n
      rake (>= 10.0.0)
      sshkit (~> 1.3)
    capistrano-bundler (1.1.4)
      capistrano (~> 3.1)
      sshkit (~> 1.2)
    capistrano-passenger (0.1.1)
      capistrano (~> 3.0)
    capistrano-rails (1.1.3)
      capistrano (~> 3.1)
      capistrano-bundler (~> 1.1)
    capistrano-rvm (0.1.2)
      capistrano (~> 3.0)
      sshkit (~> 1.2)
    coderay (1.1.0)
    coffee-rails (4.0.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    colorize (0.7.7)
    dalli (2.7.4)
    dalli-ui (0.1.2)
      dalli (~> 2.7)
      hashie (~> 3.3.1)
      rails (> 4.0)
    datejs-rails (2.0.1)
      railties (>= 3.1)
    debug_inspector (0.0.2)
    devise (3.5.1)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    draper (2.1.0)
      actionpack (>= 3.0)
      activemodel (>= 3.0)
      activesupport (>= 3.0)
      request_store (~> 1.0)
    erubis (2.7.0)
    execjs (2.5.2)
    factory_girl (4.5.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.5.0)
      factory_girl (~> 4.5.0)
      railties (>= 3.0.0)
    ffi (1.9.10)
    figaro (1.1.1)
      thor (~> 0.14)
    font-awesome-rails (4.4.0.0)
      railties (>= 3.2, < 5.0)
    formatador (0.2.5)
    formtastic (3.1.3)
      actionpack (>= 3.2.13)
    formtastic_i18n (0.4.1)
    globalid (0.3.6)
      activesupport (>= 4.1.0)
    guard (2.13.0)
      formatador (>= 0.2.4)
      listen (>= 2.7, <= 4.0)
      lumberjack (~> 1.0)
      nenv (~> 0.1)
      notiffany (~> 0.0)
      pry (>= 0.9.12)
      shellany (~> 0.0)
      thor (>= 0.18.1)
    guard-bundler (2.1.0)
      bundler (~> 1.0)
      guard (~> 2.2)
      guard-compat (~> 1.1)
    guard-compat (1.2.1)
    guard-rails (0.7.1)
      guard (~> 2.11)
      guard-compat (~> 1.0)
    has_scope (0.6.0)
      actionpack (>= 3.2, < 5)
      activesupport (>= 3.2, < 5)
    hashie (3.3.2)
    hike (1.2.3)
    i18n (0.7.0)
    inherited_resources (1.6.0)
      actionpack (>= 3.2, < 5)
      has_scope (~> 0.6.0.rc)
      railties (>= 3.2, < 5)
      responders
    jbuilder (1.5.3)
      activesupport (>= 3.0.0)
      multi_json (>= 1.2.0)
    jquery-rails (4.0.4)
      rails-dom-testing (~> 1.0)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (5.0.5)
      railties (>= 3.2.16)
    json (1.8.3)
    kaminari (0.16.3)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    libv8 (3.16.14.11)
    listen (3.0.3)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    loofah (2.0.2)
      nokogiri (>= 1.5.9)
    lumberjack (1.0.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    method_source (0.8.2)
    mime-types (2.6.1)
    mini_portile (0.6.2)
    minitest (5.8.0)
    multi_json (1.11.2)
    mysql2 (0.3.19)
    nenv (0.2.0)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (2.9.2)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    notiffany (0.0.7)
      nenv (~> 0.1)
      shellany (~> 0.0)
    orm_adapter (0.5.0)
    polyamorous (1.2.0)
      activerecord (>= 3.0)
    pry (0.10.1)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    quiet_assets (1.1.0)
      railties (>= 3.1, < 5.0)
    rack (1.6.4)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.3)
      actionmailer (= 4.2.3)
      actionpack (= 4.2.3)
      actionview (= 4.2.3)
      activejob (= 4.2.3)
      activemodel (= 4.2.3)
      activerecord (= 4.2.3)
      activesupport (= 4.2.3)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.3)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.6)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.2)
      loofah (~> 2.0)
    rails_layout (1.0.26)
    railties (4.2.3)
      actionpack (= 4.2.3)
      activesupport (= 4.2.3)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (10.4.2)
    ransack (1.6.6)
      actionpack (>= 3.0)
      activerecord (>= 3.0)
      activesupport (>= 3.0)
      i18n
      polyamorous (~> 1.2)
    rb-fchange (0.0.6)
      ffi
    rb-fsevent (0.9.5)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    ref (2.0.0)
    request_store (1.2.0)
    responders (2.1.0)
      railties (>= 4.2.0, < 5)
    rolify (4.1.1)
    sass (3.2.19)
    sass-rails (4.0.5)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.2.2)
      sprockets (~> 2.8, < 3.0)
      sprockets-rails (~> 2.0)
    shellany (0.0.1)
    simple_form (3.1.0)
      actionpack (~> 4.0)
      activemodel (~> 4.0)
    slop (3.6.0)
    sprockets (2.12.4)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.3.2)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    sshkit (1.7.1)
      colorize (>= 0.7.0)
      net-scp (>= 1.1.2)
      net-ssh (>= 2.8.0)
    syntax-highlighter-rails (3.0.83.1.1)
      railties
    therubyracer (0.12.2)
      libv8 (~> 3.16.14.0)
      ref
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    tiny_tds (0.6.2)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.1)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    uniform_notifier (1.9.0)
    useragent (0.15.1)
    warden (1.2.3)
      rack (>= 1.0)

PLATFORMS
  ruby

DEPENDENCIES
  actionpack-action_caching
  activeadmin!
  activerecord-sqlserver-adapter (~> 4.2.0)
  autoprefixer-rails
  better_errors
  binding_of_caller
  bootstrap-sass
  bullet
  cancan
  capistrano
  capistrano-bundler (~> 1.1.2)
  capistrano-passenger
  capistrano-rails (~> 1.1.1)
  capistrano-rvm (~> 0.1.1)
  coffee-rails (~> 4.0.0)
  dalli
  dalli-ui
  datejs-rails
  devise
  draper
  factory_girl_rails
  figaro
  flot-rails!
  font-awesome-rails
  guard-bundler
  guard-rails
  jbuilder (~> 1.2)
  jquery-rails
  mysql2
  quiet_assets
  rails (~> 4.2.0)
  rails_layout
  rb-fchange
  rb-fsevent
  rb-inotify
  rolify
  sass-rails (~> 4.0.2)
  simple_form
  syntax-highlighter-rails
  therubyracer
  tiny_tds
  uglifier (>= 1.3.0)
  useragent

```

**Comment by timoschilling** [comment]
What kind of class is the related resource?

**Comment by snowmoonsoftware** [comment]
`collection.first.class` is a `MetricDecorator` (using Draper). The underlying model is an standard active record model class connecting to a secondary SQL Server database.

```
class MetricsDatabase < ActiveRecord::Base
  establish_connection 'metricsdb'
end

class Metric < MetricsDatabase
  self.table_name= 'metric'
...
  end

class MetricDecorator < Draper::Decorator
  delegate_all
...
end
```

This issue seems to be related to using Draper. If I remove the decorator, my view now renders. I tried versions 2.1, 2.0 and 1.4 of Draper to see if it was a change there but all three versions exhibit this behavior.

**Comment by timoschilling** [comment]
What's happen if you use a `MetricsDatabaseDecorator`?

**Comment by snowmoonsoftware** [comment]
There was no change in behavior

**Comment by timoschilling** [comment]
Since you are using `delegate_all`, this sound like a Draper Bug for me.

**Comment by snowmoonsoftware** [comment]
I will raise it over there. Thanks for your assistance

**Comment by varyonic** [comment]
I have the same error, "undefined method: 'offset'" after PR #3848 where this was introduced.  I'll see if I can isolate this further.

**Comment by varyonic** [comment]
I think if you are using scope_to the decorated collection may already be evaluated as an Array so the change to paginated_collection.rb needs to start with 'if !@display_total && collection.respond_to?(:offset)'
