### ISSUE TITLE
Comments have wrong resource type

### ISSUE THREAD

**Issue by snowmoonsoftware** [activeadmin/activeadmin#4077]
I am using the ActiveAdmin master branch and comments are no longer working. My application has the usual Rails mysql-based database and an additional SqlServer database that holds the main models.

```
class MetricsDatabase < ActiveRecord::Base
  establish_connection 'metricsdb'
end
```

```
class Metric < MetricsDatabase
  self.table_name= 'metric'
  ...
end
```

I had to rename the active admin comment because my model has a field ```comment```:

active_admin.rb (initializer)
```
config.comments_registration_name = 'InvestigationComment'
```

Stack trace is below.
```
ActiveRecord::StatementInvalid in Admin::InvestigationCommentsController#create
TinyTds::Error: Invalid object name 'metrics_databases'.: EXEC sp_executesql N'SELECT [metrics_databases].* FROM [metrics_databases] WHERE [metrics_databases].[id] = @0 ORDER BY [metrics_databases].[id] ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY', N'@0 nvarchar(max)', @0 = N'16628189'

Extracted source (around line #336):

334     qo[:as] = (options[:ar_result] || options[:fetch] == :rows) ? :array : :hash
335   end
336   results = handle.each(query_options)
337   columns = lowercase_schema_reflection ? handle.fields.map { |c| c.downcase } : handle.fields
338   options[:ar_result] ? ActiveRecord::Result.new(columns, results) : results
339 end

Rails.root: /home/metrics/apps/metrics
Application Trace | Framework Trace | Full Trace

activerecord-sqlserver-adapter (4.2.4) lib/active_record/connection_adapters/sqlserver/database_statements.rb:336:in `each'
activerecord-sqlserver-adapter (4.2.4) lib/active_record/connection_adapters/sqlserver/database_statements.rb:336:in `handle_to_names_and_values_dblib'
activerecord-sqlserver-adapter (4.2.4) lib/active_record/connection_adapters/sqlserver/database_statements.rb:325:in `handle_to_names_and_values'
activerecord-sqlserver-adapter (4.2.4) lib/active_record/connection_adapters/sqlserver/database_statements.rb:300:in `_raw_select'
activerecord-sqlserver-adapter (4.2.4) lib/active_record/connection_adapters/sqlserver/database_statements.rb:295:in `block in raw_select'
activerecord (4.2.3) lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activerecord (4.2.3) lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
activerecord-sqlserver-adapter (4.2.4) lib/active_record/connection_adapters/sqlserver/database_statements.rb:295:in `raw_select'
activerecord-sqlserver-adapter (4.2.4) lib/active_record/connection_adapters/sqlserver/database_statements.rb:244:in `sp_executesql'
activerecord-sqlserver-adapter (4.2.4) lib/active_record/connection_adapters/sqlserver/database_statements.rb:19:in `exec_query'
activerecord-sqlserver-adapter (4.2.4) lib/active_record/connection_adapters/sqlserver/database_statements.rb:199:in `select'
activerecord (4.2.3) lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
activerecord (4.2.3) lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
activerecord (4.2.3) lib/active_record/querying.rb:39:in `find_by_sql'
activerecord (4.2.3) lib/active_record/statement_cache.rb:107:in `execute'
activerecord (4.2.3) lib/active_record/associations/singular_association.rb:59:in `get_records'
activerecord (4.2.3) lib/active_record/associations/singular_association.rb:63:in `find_target'
activerecord (4.2.3) lib/active_record/associations/association.rb:138:in `load_target'
activerecord (4.2.3) lib/active_record/associations/association.rb:53:in `reload'
activerecord (4.2.3) lib/active_record/associations/singular_association.rb:9:in `reader'
activerecord (4.2.3) lib/active_record/associations/builder/association.rb:115:in `resource'
activemodel (4.2.3) lib/active_model/validator.rb:149:in `block in validate'
activemodel (4.2.3) lib/active_model/validator.rb:148:in `each'
activemodel (4.2.3) lib/active_model/validator.rb:148:in `validate'
activerecord (4.2.3) lib/active_record/validations/presence.rb:5:in `validate'
activesupport (4.2.3) lib/active_support/callbacks.rb:453:in `public_send'
activesupport (4.2.3) lib/active_support/callbacks.rb:453:in `block in make_lambda'
activesupport (4.2.3) lib/active_support/callbacks.rb:190:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:190:in `block in simple'
activesupport (4.2.3) lib/active_support/callbacks.rb:502:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:502:in `block in call'
activesupport (4.2.3) lib/active_support/callbacks.rb:502:in `each'
activesupport (4.2.3) lib/active_support/callbacks.rb:502:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks'
activemodel (4.2.3) lib/active_model/validations.rb:395:in `run_validations!'
activemodel (4.2.3) lib/active_model/validations/callbacks.rb:113:in `block in run_validations!'
activesupport (4.2.3) lib/active_support/callbacks.rb:84:in `run_callbacks'
activemodel (4.2.3) lib/active_model/validations/callbacks.rb:113:in `run_validations!'
activemodel (4.2.3) lib/active_model/validations.rb:334:in `valid?'
activerecord (4.2.3) lib/active_record/validations.rb:58:in `valid?'
activerecord (4.2.3) lib/active_record/validations.rb:83:in `perform_validations'
activerecord (4.2.3) lib/active_record/validations.rb:37:in `save'
activerecord (4.2.3) lib/active_record/attribute_methods/dirty.rb:21:in `save'
activerecord (4.2.3) lib/active_record/transactions.rb:286:in `block (2 levels) in save'
activerecord (4.2.3) lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
activerecord (4.2.3) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
activerecord (4.2.3) lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
activerecord (4.2.3) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
activerecord (4.2.3) lib/active_record/transactions.rb:220:in `transaction'
activerecord (4.2.3) lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
activerecord (4.2.3) lib/active_record/transactions.rb:286:in `block in save'
activerecord (4.2.3) lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
activerecord (4.2.3) lib/active_record/transactions.rb:285:in `save'
/home/metrics/.rvm/gems/ruby-2.2.1@metrics/bundler/gems/activeadmin-4926eef04fd4/lib/active_admin/resource_controller/data_access.rb:159:in `block in save_resource'
activesupport (4.2.3) lib/active_support/core_ext/object/try.rb:77:in `call'
activesupport (4.2.3) lib/active_support/core_ext/object/try.rb:77:in `public_send'
activesupport (4.2.3) lib/active_support/core_ext/object/try.rb:77:in `try!'
activesupport (4.2.3) lib/active_support/core_ext/object/try.rb:63:in `try'
/home/metrics/.rvm/gems/ruby-2.2.1@metrics/bundler/gems/activeadmin-4926eef04fd4/lib/active_admin/callbacks.rb:79:in `block (2 levels) in define_active_admin_callbacks'
/home/metrics/.rvm/gems/ruby-2.2.1@metrics/bundler/gems/activeadmin-4926eef04fd4/lib/active_admin/resource_controller/data_access.rb:158:in `save_resource'
/home/metrics/.rvm/gems/ruby-2.2.1@metrics/bundler/gems/activeadmin-4926eef04fd4/lib/active_admin/resource_controller/data_access.rb:148:in `block in create_resource'
activesupport (4.2.3) lib/active_support/core_ext/object/try.rb:77:in `call'
activesupport (4.2.3) lib/active_support/core_ext/object/try.rb:77:in `public_send'
activesupport (4.2.3) lib/active_support/core_ext/object/try.rb:77:in `try!'
activesupport (4.2.3) lib/active_support/core_ext/object/try.rb:63:in `try'
/home/metrics/.rvm/gems/ruby-2.2.1@metrics/bundler/gems/activeadmin-4926eef04fd4/lib/active_admin/callbacks.rb:79:in `block (2 levels) in define_active_admin_callbacks'
/home/metrics/.rvm/gems/ruby-2.2.1@metrics/bundler/gems/activeadmin-4926eef04fd4/lib/active_admin/resource_controller/data_access.rb:147:in `create_resource'
inherited_resources (1.6.0) lib/inherited_resources/actions.rb:33:in `create'
/home/metrics/.rvm/gems/ruby-2.2.1@metrics/bundler/gems/activeadmin-4926eef04fd4/lib/active_admin/orm/active_record/comments.rb:56:in `create'
actionpack (4.2.3) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.3) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.3) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.3) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.3) lib/active_support/callbacks.rb:115:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:115:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
activesupport (4.2.3) lib/active_support/callbacks.rb:503:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:503:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks'
actionpack (4.2.3) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.3) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.3) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.3) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.3) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.3) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.3) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.3) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.3) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.3) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `call'
actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:45:in `serve'
actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in `call'
bullet (4.14.7) lib/bullet/rack.rb:10:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
rack (1.6.4) lib/rack/etag.rb:24:in `call'
rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
rack (1.6.4) lib/rack/head.rb:13:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.3) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
activerecord (4.2.3) lib/active_record/migration.rb:377:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.3) lib/active_support/callbacks.rb:84:in `run_callbacks'
actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
better_errors (2.1.1) lib/better_errors/middleware.rb:59:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.3) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.3) lib/rails/rack/logger.rb:20:in `call'
quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
request_store (1.2.0) lib/request_store/middleware.rb:8:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.4) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in `call'
rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
railties (4.2.3) lib/rails/engine.rb:518:in `call'
railties (4.2.3) lib/rails/application.rb:165:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
rack (1.6.4) lib/rack/content_length.rb:15:in `call'
rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
/home/metrics/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/home/metrics/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
/home/metrics/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'

Request

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"c5KomhEZ2rFVDUc/c6czU2fBJVnclB6Ohe08zUbVxj8k+9VLeLMipnbM3B5OcVPcqAvCOpw7BBfjCrsNH6DE3g==",
 "active_admin_comment"=>{"resource_type"=>"MetricsDatabase",
 "resource_id"=>"16628189",
 "body"=>"Failed due to oracle error in schema conversion scripts:ORA-00054: resource busy and acquire with NOWAIT specified or timeout expired"},
 "commit"=>"Add Comment"}

```

**Comment by timoschilling** [comment]
Can you set a brake point [here](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/resource_controller/data_access.rb#L159) and inspect `object`.

Then try to create a Comment in the Rails Console by hand:
```ruby
InvestigationComment.create(<attributes from the debug inspect>)
```

**Comment by snowmoonsoftware** [comment]
In ActiveAdmin::Comment, there is the following code:

```
    # @return [String] The name of the record to use for the polymorphic relationship
    def self.resource_type(resource)
      ResourceController::Decorators.undecorate(resource).class.base_class.name.to_s
    end
```

resource.class is ```MetricDecorator```, @object_class is ```Metric```, and resource.class.base_class is ```MetricsDatabase```


At the breakpoint you requested, ```object``` is as follows:

```
0> object.inspect
=> "#<ActiveAdmin::Comment id: nil, namespace: nil, body: \"test\", resource_id: \"16628189\", resource_type: \"MetricsDatabase\", author_id: nil, author_type: nil, created_at: nil, updated_at: nil>"
```


```
result = {ActiveAdmin::Comment} #<ActiveAdmin::Comment:0x00000005261d08>
 @_start_transaction_state = Empty Hash
 @aggregation_cache = Empty Hash
 @association_cache = Empty Hash
 @attributes = {ActiveRecord::AttributeSet} #<ActiveRecord::AttributeSet:0x00000005261cb8>
  @attributes = {ActiveRecord::LazyAttributeHash} #<ActiveRecord::LazyAttributeHash:0x00000005261c90>
   @additional_types = Empty Hash
   @delegate_hash = Hash (3 elements)
    'body' => {ActiveRecord::Attribute::FromUser} #<ActiveRecord::Attribute::FromUser:0x00000005260700>
     @name = "body"
     @type = {ActiveRecord::Type::Text} #<ActiveRecord::Type::Text:0x000000076af458>
     @value = "test"
     @value_before_type_cast = "test"
    'resource_id' => {ActiveRecord::Attribute::FromUser} #<ActiveRecord::Attribute::FromUser:0x00000005260318>
     @name = "resource_id"
     @type = {ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter::MysqlString} #<ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter::MysqlString:0x000000076ad590>
     @value = "16628189"
     @value_before_type_cast = "16628189"
    'resource_type' => {ActiveRecord::Attribute::FromUser} #<ActiveRecord::Attribute::FromUser:0x00000005260098>
     @name = "resource_type"
     @type = {ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter::MysqlString} #<ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter::MysqlString:0x000000076ad590>
     @value = "MetricsDatabase"
     @value_before_type_cast = "MetricsDatabase"
   @materialized = false
   @types = Hash (9 elements)
   @values = Hash (9 elements)
 @changed_attributes = {ActiveSupport::HashWithIndifferentAccess} ActiveSupport::HashWithIndifferentAccess (3 elements)
  'body' = nil
  'resource_id' = nil
  'resource_type' = nil
 @destroyed = false
 @destroyed_by_association = nil
 @marked_for_destruction = false
 @new_record = true
 @original_raw_attributes = Hash (3 elements)
  'body' => test
  'resource_id' => 16628189
  'resource_type' => MetricsDatabase
 @readonly = false
 @transaction_state = nil
 @txn = nil
 @@configurations = Hash (4 elements)
 @@default_timezone = {Symbol} utc
 @@dump_schema_after_migration = true
 @@logger = {ActiveSupport::Logger} #<ActiveSupport::Logger:0x000000032738e8>
 @@maintain_test_schema = true
 @@primary_key_prefix_type = nil
 @@raise_in_transactional_callbacks = false
 @@schema_format = {Symbol} ruby
 @@time_zone_aware_attributes = true
 @@timestamped_migrations = true
```

**Comment by timoschilling** [comment]
Can you do this?
```ruby
InvestigationComment.create(body: "test", resource_id: "16628189", resource_type: "MetricsDatabase")
```

What does `InvestigationComment` look's like?

**Comment by timoschilling** [comment]
The problem seems to be the Model inheritance across different Databases.

**Comment by snowmoonsoftware** [comment]
What namespace is that symbol in? I get 
```
0> ::InvestigationComment.create(body: "test", resource_id: "16628189", resource_type: "MetricsDatabase")
=> uninitialized constant InvestigationComment

0> ActiveAdmin::InvestigationComment.create(body: "test", resource_id: "16628189", resource_type: "MetricsDatabase")
=> uninitialized constant ActiveAdmin::InvestigationComment

0> Admin::InvestigationComment.create(body: "test", resource_id: "16628189", resource_type: "MetricsDatabase")
=> uninitialized constant Admin::InvestigationComment
```

This setup worked using HEAD for quite awhile. It stopped working sometime after March 2015. If it helps, here's a portion of my Gemfile.lock from that time period:

```
-GIT
   remote: git://github.com/gregbell/active_admin.git
-  revision: 9cfc45330e5ad31977b3ac7b2ccc1f8d6146c73f
+  revision: 48a8674a4566fb5a916748f78a38a0b9f2e8e356
```

**Comment by timoschilling** [comment]
I don't know why you can't find `InvestigationComment`, that's a class that you have configured.

That what's your crash came from was introduced in #3762 / #3583.

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
