### ISSUE TITLE
app/assets/javascripts/active_admin/base.js.coffee not compiling in heroku

### ISSUE THREAD

**Issue by cgb37** [activeadmin/activeadmin#4089]
```
remote:        Sprockets::FileNotFound: could not find file: /tmp/build_6eaacafff340dc0bcc347b5166dbce40/vendor/bundle/ruby/2.0.0/bundler/gems/activeadmin-7fd9d87dde1f/app/assets/javascripts/active_admin/base.js.coffee
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/sprockets/loader.rb:95:in `load_from_unloaded'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/sprockets/loader.rb:60:in `block in load'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/sprockets/loader.rb:286:in `fetch_asset_from_dependency_cache'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/sprockets/loader.rb:44:in `load'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/sprockets/cached_environment.rb:47:in `yield'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/sprockets/cached_environment.rb:47:in `load'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/sprockets/bundle.rb:23:in `block in call'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/sprockets/utils.rb:183:in `dfs'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/sprockets/bundle.rb:24:in `call'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/sprockets/loader.rb:126:in `load_from_unloaded'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/sprockets/loader.rb:60:in `block in load'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/sprockets/loader.rb:286:in `fetch_asset_from_dependency_cache'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/sprockets/loader.rb:44:in `load'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/sprockets/cached_environment.rb:47:in `yield'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/sprockets/cached_environment.rb:47:in `load'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/sprockets/base.rb:66:in `find_asset'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/sprockets/manifest.rb:130:in `block in find'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/sprockets/manifest.rb:129:in `each'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/sprockets/manifest.rb:129:in `find'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/sprockets/manifest.rb:162:in `compile'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-rails-2.3.2/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-3.3.2/lib/rake/sprocketstask.rb:147:in `with_logger'
remote:        /tmp/build_45678a7bbc9bcde4c4b19d84f5613394/vendor/bundle/ruby/2.0.0/gems/sprockets-rails-2.3.2/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
remote:        Tasks: TOP => assets:precompile
remote:        (See full trace by running task with --trace)
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:
remote:  !     Push rejected, failed to compile Ruby app
```

**Comment by marcroberts** [comment]
I don't know what's causing this but I've successfully worked around this for now by using the `purge_cache` command of the heroku-repo plugin https://github.com/heroku/heroku-repo to clear out the build cache before pushing.
