### ISSUE TITLE
Tests currently failing on Rails 3.2

### ISSUE THREAD

**Issue by seanlinsley** [activeadmin/activeadmin#4105]
Any idea what caused this @timoschilling?

Some of the tests are about the `active_admin_comments` table missing from the database.

**Comment by seanlinsley** [comment]
Looks like the test Rails app might have been corrupted, from 3fb69f21426a53947bb645170409ca722de7ec15, 86f7303c17747528eb5cbbb451e2a5a4ac8b188f, cdace51b2a5cbcc013eec24e8c1633229d4b7aec.

I'm going to take the nuclear option and purge all of the bundles and test apps from S3.

**Comment by seanlinsley** [comment]
Travis is now re-running for master. Let's see if that fixed it.

**Comment by seanlinsley** [comment]
Well the tests are still failing, but now it's clear why:
```
        gsub    app/models/admin_user.rb
        gsub    config/routes.rb
active_admin/devise/devise_generator.rb:56:in `add_default_user_to_seed': undefined method `existent' for nil:NilClass (NoMethodError)
  from gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  from gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  from gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
  from gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
  from gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
  from gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
  from gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
  from gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
  from gems/thor-0.19.1/lib/thor/group.rb:277:in `block in _invoke_for_class_method'
  from gems/thor-0.19.1/lib/thor/shell.rb:68:in `with_padding'
  from gems/thor-0.19.1/lib/thor/group.rb:266:in `_invoke_for_class_method'
  from gems/thor-0.19.1/lib/thor/group.rb:133:in `_invoke_from_option_users'
  from gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  from gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  from gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
  from gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
  from gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
  from gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
  from gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
  from gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  from gems/railties-3.2.22/lib/rails/generators.rb:171:in `invoke'
  from gems/railties-3.2.22/lib/rails/commands/generate.rb:12:in `<top (required)>'
  from gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
  from gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `block in require'
  from gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
  from gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
  from gems/railties-3.2.22/lib/rails/commands.rb:29:in `<top (required)>'
  from script/rails:6:in `require'
  from script/rails:6:in `<main>'
      insert    config/routes.rb
      remove    public/index.html
        gsub    config/initializers/devise.rb
        rake    db:migrate db:test:prepare
```

**Comment by seanlinsley** [comment]
@timoschilling this is why it's good to not commit directly on master :smile_cat:

**Comment by timoschilling** [comment]
@seanlinsley if have crashed the rails 3.2 teste some month bevor :win

**Comment by timoschilling** [comment]
The reasons above are out of date, so I will close this for now.
I'm open #4131, with informations about the current failure.
