### ISSUE TITLE
Uninitialized constant error after "rails generate active_admin:resource <model_name>"

### ISSUE THREAD

**Issue by giovannioliveira** [activeadmin/activeadmin#4148]
```
/app/admin/test_model.rb:1:in `<top (required)>': uninitialized constant TestModel (NameError)
	from /var/lib/gems/1.9.1/gems/activeadmin-1.0.0.pre2/lib/active_admin/application.rb:209:in `block in load'
	from /var/lib/gems/1.9.1/gems/activeadmin-1.0.0.pre2/lib/active_admin/error.rb:41:in `capture'
	from /var/lib/gems/1.9.1/gems/activeadmin-1.0.0.pre2/lib/active_admin/application.rb:209:in `load'
	from /var/lib/gems/1.9.1/gems/activeadmin-1.0.0.pre2/lib/active_admin/application.rb:201:in `block in load!'
	from /var/lib/gems/1.9.1/gems/activeadmin-1.0.0.pre2/lib/active_admin/application.rb:201:in `each'
	from /var/lib/gems/1.9.1/gems/activeadmin-1.0.0.pre2/lib/active_admin/application.rb:201:in `load!'
	from /var/lib/gems/1.9.1/gems/activeadmin-1.0.0.pre2/lib/active_admin/application.rb:223:in `routes'
	from /var/lib/gems/1.9.1/gems/activeadmin-1.0.0.pre2/lib/active_admin.rb:79:in `routes'
	from <path>//config/routes.rb:3:in `block in <top (required)>'
	from /var/lib/gems/1.9.1/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:434:in `instance_exec'
	from /var/lib/gems/1.9.1/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:434:in `eval_block'
	from /var/lib/gems/1.9.1/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:412:in `draw'
	from <path>/config/routes.rb:1:in `<top (required)>'
	from /var/lib/gems/1.9.1/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /var/lib/gems/1.9.1/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:40:in `each'
	from /var/lib/gems/1.9.1/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /var/lib/gems/1.9.1/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /var/lib/gems/1.9.1/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /var/lib/gems/1.9.1/gems/activesupport-4.2.3/lib/active_support/file_update_checker.rb:75:in `call'
	from /var/lib/gems/1.9.1/gems/activesupport-4.2.3/lib/active_support/file_update_checker.rb:75:in `execute'
	from /var/lib/gems/1.9.1/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /var/lib/gems/1.9.1/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /var/lib/gems/1.9.1/gems/railties-4.2.3/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
	from /var/lib/gems/1.9.1/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `instance_exec'
	from /var/lib/gems/1.9.1/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `run'
	from /var/lib/gems/1.9.1/gems/railties-4.2.3/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/lib/ruby/1.9.1/tsort.rb:150:in `block in tsort_each'
	from /usr/lib/ruby/1.9.1/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
	from /usr/lib/ruby/1.9.1/tsort.rb:219:in `each_strongly_connected_component_from'
	from /usr/lib/ruby/1.9.1/tsort.rb:182:in `block in each_strongly_connected_component'
	from /usr/lib/ruby/1.9.1/tsort.rb:180:in `each'
	from /usr/lib/ruby/1.9.1/tsort.rb:180:in `each_strongly_connected_component'
	from /usr/lib/ruby/1.9.1/tsort.rb:148:in `tsort_each'
	from /var/lib/gems/1.9.1/gems/railties-4.2.3/lib/rails/initializable.rb:54:in `run_initializers'
	from /var/lib/gems/1.9.1/gems/railties-4.2.3/lib/rails/application.rb:352:in `initialize!'
	from <path>/config/environment.rb:5:in `<top (required)>'
	from <path>/config.ru:3:in `block in <main>'
	from /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from <path>/config.ru:in `new'
	from <path>/config.ru:in `<main>'
	from /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
	from /var/lib/gems/1.9.1/gems/railties-4.2.3/lib/rails/commands/server.rb:61:in `app'
	from /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
	from /var/lib/gems/1.9.1/gems/railties-4.2.3/lib/rails/commands/server.rb:139:in `log_to_stdout'
	from /var/lib/gems/1.9.1/gems/railties-4.2.3/lib/rails/commands/server.rb:78:in `start'
	from /var/lib/gems/1.9.1/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /var/lib/gems/1.9.1/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /var/lib/gems/1.9.1/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /var/lib/gems/1.9.1/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /var/lib/gems/1.9.1/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from <path>/bin/rails:8:in `require'
	from <path>/bin/rails:8:in `<top (required)>'
	from /var/lib/gems/1.9.1/gems/spring-1.4.0/lib/spring/client/rails.rb:28:in `load'
	from /var/lib/gems/1.9.1/gems/spring-1.4.0/lib/spring/client/rails.rb:28:in `call'
	from /var/lib/gems/1.9.1/gems/spring-1.4.0/lib/spring/client/command.rb:7:in `call'
	from /var/lib/gems/1.9.1/gems/spring-1.4.0/lib/spring/client.rb:28:in `run'
	from /var/lib/gems/1.9.1/gems/spring-1.4.0/bin/spring:49:in `<top (required)>'
	from /var/lib/gems/1.9.1/gems/spring-1.4.0/lib/spring/binstub.rb:11:in `load'
	from /var/lib/gems/1.9.1/gems/spring-1.4.0/lib/spring/binstub.rb:11:in `<top (required)>'
	from /usr/local/lib/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from <path>/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

**Comment by shishir127** [comment]
@giovannioliveira I believe `TestModel` has to be an already declared Rails model. Or you can rename a model as mentioned in the [guide](https://github.com/activeadmin/activeadmin/blob/master/docs/2-resource-customization.md#rename-the-resource)

**Comment by giovannioliveira** [comment]
Sorry, it was my mistake

**Comment by MeetChavda** [comment]
i haven't already that model still having error like that any solution?
