### ISSUE TITLE
undefined method `group_values' for all registered models

### ISSUE THREAD

**Issue by bontoJR** [activeadmin/activeadmin#4155]
Hello,

I recently updated from Rails 3.x to 4.2 and everything works fine in development/local installation.

I am having a lot of troubles with the production model that crashes the app every time I try  to access the index of a resource:

```rb
ActionView::Template::Error (undefined method `group_values' for nil:NilClass):
    1: insert_tag renderer_for(:index)
  /home/bonto/apps/mac/shared/bundle/ruby/2.2.0/bundler/gems/active_admin-e00143ead12f/lib/active_admin/helpers/collection.rb:11:in `collection_size'
  /home/bonto/apps/mac/shared/bundle/ruby/2.2.0/bundler/gems/active_admin-e00143ead12f/lib/active_admin/helpers/collection.rb:19:in `collection_is_empty?'
  /home/bonto/apps/mac/shared/bundle/ruby/2.2.0/bundler/gems/active_admin-e00143ead12f/lib/active_admin/views/pages/index.rb:46:in `items_in_collection?'
  /home/bonto/apps/mac/shared/bundle/ruby/2.2.0/bundler/gems/active_admin-e00143ead12f/lib/active_admin/views/pages/index.rb:50:in `build_collection'
  /home/bonto/apps/mac/shared/bundle/ruby/2.2.0/bundler/gems/active_admin-e00143ead12f/lib/active_admin/views/pages/index.rb:29:in `block in main_content'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
  arbre (1.0.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:14:in `batch_action_form'
  /home/bonto/apps/mac/shared/bundle/ruby/2.2.0/bundler/gems/active_admin-e00143ead12f/lib/active_admin/views/pages/index.rb:37:in `wrap_with_batch_action_form'
  /home/bonto/apps/mac/shared/bundle/ruby/2.2.0/bundler/gems/active_admin-e00143ead12f/lib/active_admin/views/pages/index.rb:27:in `main_content'
  /home/bonto/apps/mac/shared/bundle/ruby/2.2.0/bundler/gems/active_admin-e00143ead12f/lib/active_admin/views/pages/base.rb:83:in `block (2 levels) in build_main_content_wrapper'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
  arbre (1.0.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:14:in `div'
  /home/bonto/apps/mac/shared/bundle/ruby/2.2.0/bundler/gems/active_admin-e00143ead12f/lib/active_admin/views/pages/base.rb:82:in `block in build_main_content_wrapper'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
  arbre (1.0.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:14:in `div'
  /home/bonto/apps/mac/shared/bundle/ruby/2.2.0/bundler/gems/active_admin-e00143ead12f/lib/active_admin/views/pages/base.rb:81:in `build_main_content_wrapper'
  /home/bonto/apps/mac/shared/bundle/ruby/2.2.0/bundler/gems/active_admin-e00143ead12f/lib/active_admin/views/pages/base.rb:65:in `block in build_page_content'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
  arbre (1.0.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:14:in `div'
  /home/bonto/apps/mac/shared/bundle/ruby/2.2.0/bundler/gems/active_admin-e00143ead12f/lib/active_admin/views/pages/base.rb:64:in `build_page_content'
  /home/bonto/apps/mac/shared/bundle/ruby/2.2.0/bundler/gems/active_admin-e00143ead12f/lib/active_admin/views/pages/base.rb:47:in `block (2 levels) in build_page'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
  arbre (1.0.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:14:in `div'
  /home/bonto/apps/mac/shared/bundle/ruby/2.2.0/bundler/gems/active_admin-e00143ead12f/lib/active_admin/views/pages/base.rb:44:in `block in build_page'
  arbre (1.0.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  /home/bonto/apps/mac/shared/bundle/ruby/2.2.0/bundler/gems/active_admin-e00143ead12f/lib/active_admin/views/pages/base.rb:43:in `build_page'
  /home/bonto/apps/mac/shared/bundle/ruby/2.2.0/bundler/gems/active_admin-e00143ead12f/lib/active_admin/views/pages/base.rb:10:in `build'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
  arbre (1.0.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.0.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  /home/bonto/apps/mac/shared/bundle/ruby/2.2.0/bundler/gems/active_admin-e00143ead12f/app/views/active_admin/resource/index.html.arb:1:in `block in __home_bonto_apps_mac_shared_bundle_ruby_______bundler_gems_active_admin_e_____ead__f_app_views_active_admin_resource_index_html_arb__2158360048009019604_51838040'
  arbre (1.0.1) lib/arbre/context.rb:45:in `instance_eval'
  arbre (1.0.1) lib/arbre/context.rb:45:in `initialize'
  /home/bonto/apps/mac/shared/bundle/ruby/2.2.0/bundler/gems/active_admin-e00143ead12f/app/views/active_admin/resource/index.html.arb:1:in `new'
  /home/bonto/apps/mac/shared/bundle/ruby/2.2.0/bundler/gems/active_admin-e00143ead12f/app/views/active_admin/resource/index.html.arb:1:in `__home_bonto_apps_mac_shared_bundle_ruby_______bundler_gems_active_admin_e_____ead__f_app_views_active_admin_resource_index_html_arb__2158360048009019604_51838040'
  actionpack (4.0.2) lib/action_view/template.rb:143:in `block in render'
  activesupport (4.0.2) lib/active_support/notifications.rb:161:in `instrument'
  actionpack (4.0.2) lib/action_view/template.rb:141:in `render'
  actionpack (4.0.2) lib/action_view/renderer/template_renderer.rb:49:in `block (2 levels) in render_template'
  actionpack (4.0.2) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (4.0.2) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.0.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.0.2) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.0.2) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  actionpack (4.0.2) lib/action_view/renderer/template_renderer.rb:48:in `block in render_template'
  actionpack (4.0.2) lib/action_view/renderer/template_renderer.rb:56:in `render_with_layout'
  actionpack (4.0.2) lib/action_view/renderer/template_renderer.rb:47:in `render_template'
  actionpack (4.0.2) lib/action_view/renderer/template_renderer.rb:17:in `render'
  actionpack (4.0.2) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionpack (4.0.2) lib/action_view/renderer/renderer.rb:23:in `render'
  actionpack (4.0.2) lib/abstract_controller/rendering.rb:127:in `_render_template'
  actionpack (4.0.2) lib/action_controller/metal/streaming.rb:219:in `_render_template'
  actionpack (4.0.2) lib/abstract_controller/rendering.rb:120:in `render_to_body'
  actionpack (4.0.2) lib/action_controller/metal/rendering.rb:33:in `render_to_body'
  actionpack (4.0.2) lib/action_controller/metal/renderers.rb:26:in `render_to_body'
  actionpack (4.0.2) lib/abstract_controller/rendering.rb:97:in `render'
  actionpack (4.0.2) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.0.2) lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
  activesupport (4.0.2) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /home/bonto/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
  activesupport (4.0.2) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.0.2) lib/action_controller/metal/instrumentation.rb:41:in `block in render'
  actionpack (4.0.2) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
  activerecord (4.0.2) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.0.2) lib/action_controller/metal/instrumentation.rb:40:in `render'
  actionpack (4.0.2) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (4.0.2) lib/action_controller/metal/responder.rb:233:in `default_render'
  actionpack (4.0.2) lib/action_controller/metal/responder.rb:161:in `to_html'
  responders (1.0.0) lib/responders/flash_responder.rb:104:in `to_html'
  actionpack (4.0.2) lib/action_controller/metal/responder.rb:154:in `respond'
  actionpack (4.0.2) lib/action_controller/metal/responder.rb:147:in `call'
  actionpack (4.0.2) lib/action_controller/metal/mime_responds.rb:330:in `respond_with'
  inherited_resources (1.4.1) lib/inherited_resources/actions.rb:7:in `index'
  actionpack (4.0.2) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.0.2) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.0.2) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.0.2) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (4.0.2) lib/active_support/callbacks.rb:433:in `_run__1207122851295202399__process_action__callbacks'
  activesupport (4.0.2) lib/active_support/callbacks.rb:80:in `run_callbacks'
  actionpack (4.0.2) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (4.0.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.0.2) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.0.2) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.0.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.0.2) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.0.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.0.2) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
  activerecord (4.0.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.0.2) lib/abstract_controller/base.rb:136:in `process'
  actionpack (4.0.2) lib/abstract_controller/rendering.rb:44:in `process'
  actionpack (4.0.2) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.0.2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.0.2) lib/action_controller/metal.rb:231:in `block in action'
  actionpack (4.0.2) lib/action_dispatch/routing/route_set.rb:80:in `call'
  actionpack (4.0.2) lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
  actionpack (4.0.2) lib/action_dispatch/routing/route_set.rb:48:in `call'
  actionpack (4.0.2) lib/action_dispatch/journey/router.rb:71:in `block in call'
  actionpack (4.0.2) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.0.2) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.0.2) lib/action_dispatch/routing/route_set.rb:680:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  actionpack (4.0.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.0.2) lib/action_dispatch/middleware/flash.rb:241:in `call'
  rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.0.2) lib/action_dispatch/middleware/cookies.rb:486:in `call'
  activerecord (4.0.2) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.0.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
  actionpack (4.0.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.0.2) lib/active_support/callbacks.rb:373:in `_run__3523342720925726845__call__callbacks'
  activesupport (4.0.2) lib/active_support/callbacks.rb:80:in `run_callbacks'
  actionpack (4.0.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.0.2) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  actionpack (4.0.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.0.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.0.2) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.0.2) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.0.2) lib/active_support/tagged_logging.rb:67:in `block in tagged'
  activesupport (4.0.2) lib/active_support/tagged_logging.rb:25:in `tagged'
  activesupport (4.0.2) lib/active_support/tagged_logging.rb:67:in `tagged'
  railties (4.0.2) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.0.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.0.2) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  railties (4.0.2) lib/rails/engine.rb:511:in `call'
  railties (4.0.2) lib/rails/application.rb:97:in `call'
  unicorn (4.8.2) lib/unicorn/http_server.rb:572:in `process_client'
  unicorn (4.8.2) lib/unicorn/http_server.rb:666:in `worker_loop'
  unicorn (4.8.2) lib/unicorn/http_server.rb:521:in `spawn_missing_workers'
  unicorn (4.8.2) lib/unicorn/http_server.rb:532:in `maintain_worker_count'
  unicorn (4.8.2) lib/unicorn/http_server.rb:290:in `join'
  unicorn (4.8.2) bin/unicorn:126:in `<top (required)>'
  /home/bonto/apps/mac/shared/bundle/ruby/2.2.0/bin/unicorn:23:in `load'
  /home/bonto/apps/mac/shared/bundle/ruby/2.2.0/bin/unicorn:23:in `<main>'
```

Is there any solution to my problem? 
Might it be that is the db not on sync?

**Comment by bontoJR** [comment]
Solved, it seems the problem was my gemset being completely screwed.
