### ISSUE TITLE
Error filtering counter cache columns: undefined method `type' for nil:NilClass 

### ISSUE THREAD

**Issue by rmvenancio** [activeadmin/activeadmin#4179]
I created a counter_cache column for my model. 

This is working and the values are visible on my view.  The values are sortable and everything is working fine, except searching. 

I created a filter for this particular column. 

```
filter :subjects_count
```

When I search for records using a filter for this particular column, I get the following error: 
Example: Equals to 0, or Greater than 1 

```
undefined method `type' for nil:NilClass

Extracted source (around line #31)

  raise "No table named #{table} exists"
          end
          connection.schema_cache.columns_hash(table)[name].type
        end

        def evaluate(search, opts = {})
```

```
NoMethodError (undefined method `type' for nil:NilClass):
  ransack (1.7.0) lib/ransack/adapters/active_record/context.rb:31:in `type_for'
  ransack (1.7.0) lib/ransack/nodes/attribute.rb:32:in `type'
  ransack (1.7.0) lib/ransack/nodes/condition.rb:215:in `default_type'
  ransack (1.7.0) lib/ransack/nodes/condition.rb:24:in `extract'
  ransack (1.7.0) lib/ransack/nodes/grouping.rb:180:in `write_attribute'
  ransack (1.7.0) lib/ransack/nodes/grouping.rb:120:in `method_missing'
  ransack (1.7.0) lib/ransack/search.rb:43:in `block in build'
  actionpack (4.2.0) lib/action_controller/metal/strong_parameters.rb:183:in `each_pair'
  actionpack (4.2.0) lib/action_controller/metal/strong_parameters.rb:183:in `each_pair'
  ransack (1.7.0) lib/ransack/search.rb:39:in `build'
  ransack (1.7.0) lib/ransack/search.rb:31:in `initialize'
  ransack (1.7.0) lib/ransack/adapters/active_record/base.rb:15:in `new'
  ransack (1.7.0) lib/ransack/adapters/active_record/base.rb:15:in `ransack'
  activerecord (4.2.0) lib/active_record/relation/delegation.rb:70:in `block in ransack'
  activerecord (4.2.0) lib/active_record/relation.rb:302:in `scoping'
  activerecord (4.2.0) lib/active_record/relation/delegation.rb:70:in `ransack'
```

This is a strange behaviour because if I (hard) refresh the page, the correct values are shown. 
It seems the error only happens on the first run of the query. 

Any suggestions ?

**Comment by seanlinsley** [comment]
This seems like a bug with Ransack, not with Active Admin.

Have you tried specifying `as:`? For example:
```ruby
filter :subjects_count, as: :numeric
```

**Comment by rmvenancio** [comment]
Hi @seanlinsley. 
I forgot that I had this open. It was a problem with my migration. This is working. 

Thanks a lot for your support and sorry for the misunderstanding.
