### ISSUE TITLE
Support Rubinius

### ISSUE THREAD

**Issue by seanlinsley** [activeadmin/activeadmin#4212]
The Travis errors that #3742 provided:

``` ruby
Failures:

  1) ActiveAdmin::Page it should behave like ActiveAdmin::Resource Naming implements #resource_label
     Failure/Error: expect { config.resource_label }.to_not raise_error
       expected no Exception, got #<ArgumentError: invalid byte sequence in US-ASCII> with backtrace:
         # kernel/common/splitter.rb:17:in `valid_encoding?'
         # kernel/common/splitter.rb:56:in `split'
         # kernel/common/string.rb:512:in `split'
         # ./bundle/rbx/2.1/gems/i18n-0.7.0/lib/i18n.rb:330:in `normalize_key'
         # ./bundle/rbx/2.1/gems/i18n-0.7.0/lib/i18n.rb:271:in `normalize_keys'
         # ./bundle/rbx/2.1/gems/i18n-0.7.0/lib/i18n/backend/simple.rb:72:in `lookup'
         # ./bundle/rbx/2.1/gems/i18n-0.7.0/lib/i18n/backend/base.rb:26:in `translate'
         # ./bundle/rbx/2.1/gems/i18n-0.7.0/lib/i18n.rb:158:in `translate'
         # kernel/bootstrap/proc.rb:20:in `call'
         # kernel/common/throw_catch.rb:30:in `catch'
         # kernel/common/throw_catch.rb:8:in `register'
         # kernel/common/throw_catch.rb:29:in `catch'
         # ./bundle/rbx/2.1/gems/i18n-0.7.0/lib/i18n.rb:154:in `t (translate)'
         # ./lib/active_admin/resource/naming.rb:49:in `translate'
         # ./lib/active_admin/resource/naming.rb:19:in `resource_label'
         # ./spec/unit/config_shared_examples.rb:25:in `__script__'
         # kernel/bootstrap/proc.rb:20:in `call'
         # ./spec/unit/config_shared_examples.rb:25:in `__script__'
         # kernel/common/eval.rb:101:in `instance_exec'
         # kernel/bootstrap/array.rb:97:in `map'
         # kernel/bootstrap/array.rb:97:in `map'
         # kernel/bootstrap/array.rb:97:in `map'
         # kernel/bootstrap/array.rb:97:in `map'
         # kernel/delta/code_loader.rb:66:in `load_script'
         # kernel/delta/code_loader.rb:152:in `load_script'
         # kernel/loader.rb:645:in `script'
         # kernel/loader.rb:799:in `main'
     Shared Example Group: "ActiveAdmin::Resource" called from ./spec/unit/page_spec.rb:9
     # ./spec/unit/config_shared_examples.rb:25:in `__script__'
     # kernel/common/eval.rb:101:in `instance_exec'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/delta/code_loader.rb:66:in `load_script'
     # kernel/delta/code_loader.rb:152:in `load_script'
     # kernel/loader.rb:645:in `script'
     # kernel/loader.rb:799:in `main'

  2) display_name when no display name method is defined on a Rails model should show the model name
     Failure/Error: expect(display_name subject).to eq "This model"

       expected: "This model"
            got: "#<ThisModel:0x1cfad4>"

       (compared using ==)
     # ./spec/unit/view_helpers/display_name_spec.rb:52:in `__script__'
     # kernel/common/eval.rb:101:in `instance_exec'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/delta/code_loader.rb:66:in `load_script'
     # kernel/delta/code_loader.rb:152:in `load_script'
     # kernel/loader.rb:645:in `script'
     # kernel/loader.rb:799:in `main'

  3) display_name when no display name method is defined on a Rails model should show the model name, plus the ID if in use
     Failure/Error: expect(display_name subject).to eq "Tagging #1"

       expected: "Tagging #1"
            got: "#<Tagging:0x1cfc34>"

       (compared using ==)
     # ./spec/unit/view_helpers/display_name_spec.rb:57:in `__script__'
     # kernel/common/eval.rb:101:in `instance_exec'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/delta/code_loader.rb:66:in `load_script'
     # kernel/delta/code_loader.rb:152:in `load_script'
     # kernel/loader.rb:645:in `script'
     # kernel/loader.rb:799:in `main'

  4) display_name when no display name method is defined on a Rails model should translate the model name
     Failure/Error: expect(display_name subject).to eq "Different #1"

       expected: "Different #1"
            got: "#<Tagging:0x1cfcdc>"

       (compared using ==)
     # ./spec/unit/view_helpers/display_name_spec.rb:63:in `__script__'
     # ./spec/rails_helper.rb:85:in `with_translation'
     # ./spec/unit/view_helpers/display_name_spec.rb:61:in `__script__'
     # kernel/common/eval.rb:101:in `instance_exec'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/delta/code_loader.rb:66:in `load_script'
     # kernel/delta/code_loader.rb:152:in `load_script'
     # kernel/loader.rb:645:in `script'
     # kernel/loader.rb:799:in `main'

Finished in 5 minutes 52 seconds (files took 2 minutes 0.1 seconds to load)
1317 examples, 4 failures

Failed examples:

rspec ./spec/unit/config_shared_examples.rb:24 # ActiveAdmin::Page it should behave like ActiveAdmin::Resource Naming implements #resource_label
rspec ./spec/unit/view_helpers/display_name_spec.rb:47 # display_name when no display name method is defined on a Rails model should show the model name
rspec ./spec/unit/view_helpers/display_name_spec.rb:55 # display_name when no display name method is defined on a Rails model should show the model name, plus the ID if in use
rspec ./spec/unit/view_helpers/display_name_spec.rb:60 # display_name when no display name method is defined on a Rails model should translate the model name
Warning: coverage data provided by Coverage [180] exceeds number of lines in /home/travis/build/activeadmin/activeadmin/lib/active_admin/resource_dsl.rb [178]
Coverage report generated for RSpec to /home/travis/build/activeadmin/activeadmin/coverage. 3418 / 3502 LOC (97.6%) covered.
Warning: coverage data provided by Coverage [180] exceeds number of lines in /home/travis/build/activeadmin/activeadmin/lib/active_admin/resource_dsl.rb [178]
/home/travis/.rvm/rubies/rbx/bin/rbx -I/home/travis/build/activeadmin/activeadmin/bundle/rbx/2.1/gems/rspec-core-3.1.7/lib:/home/travis/build/activeadmin/activeadmin/bundle/rbx/2.1/gems/rspec-support-3.1.2/lib /home/travis/build/activeadmin/activeadmin/bundle/rbx/2.1/gems/rspec-core-3.1.7/exe/rspec --pattern spec/unit/\*\*/\*_spec.rb failed
```

**Comment by varyonic** [comment]
Rubinius support for inherited_resources has been [abandoned](https://github.com/activeadmin/inherited_resources/pull/389).  Absent any PR I would like to see this closed.
