### ISSUE TITLE
Can't create a resource with a certain name

### ISSUE THREAD

**Issue by IMhide** [activeadmin/activeadmin#4237]
Hi,

My issue is pretty weird.
I have a model called `AcceptedCurrency`, I've created my activeadmin resource through the generator like this `rails generate active_admin:resource AcceptedCurrency`. But when I start my server, i get this following error 
```
/ruby-2.1.1/gems/devise-3.5.2/lib/devise/rails/routes.rb:485:in `raise_no_devise_method_error!': Admin does not respond to 'devise' method. This usually means you haven't loaded your ORM file or it's being loaded too late. To fix it, be sure to require 'devise/orm/YOUR_ORM' inside 'config/initializers/devise.rb' or before your application definition in 'config/application.rb' (RuntimeError)
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/devise-3.5.2/lib/devise/rails/routes.rb:227:in `block in devise_for'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/devise-3.5.2/lib/devise/rails/routes.rb:223:in `each'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/devise-3.5.2/lib/devise/rails/routes.rb:223:in `devise_for'
	from /Users/hide/CapSens/actuasyl/config/routes.rb:4:in `block in <top (required)>'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:434:in `instance_exec'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:434:in `eval_block'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:412:in `draw'
	from /Users/hide/CapSens/actuasyl/config/routes.rb:1:in `<top (required)>'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:40:in `each'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.3/lib/active_support/file_update_checker.rb:75:in `call'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.3/lib/active_support/file_update_checker.rb:75:in `execute'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/railties-4.2.3/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `run'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/railties-4.2.3/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/hide/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
	from /Users/hide/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/hide/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
	from /Users/hide/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/hide/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:345:in `each'
	from /Users/hide/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:345:in `call'
	from /Users/hide/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/hide/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
	from /Users/hide/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/railties-4.2.3/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/railties-4.2.3/lib/rails/application.rb:352:in `initialize!'
	from /Users/hide/CapSens/actuasyl/config/environment.rb:5:in `<top (required)>'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/hide/CapSens/actuasyl/config.ru:3:in `block in <main>'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from /Users/hide/CapSens/actuasyl/config.ru:in `new'
	from /Users/hide/CapSens/actuasyl/config.ru:in `<main>'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/railties-4.2.3/lib/rails/commands/server.rb:61:in `app'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/railties-4.2.3/lib/rails/commands/server.rb:139:in `log_to_stdout'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/railties-4.2.3/lib/rails/commands/server.rb:78:in `start'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/hide/.rvm/gems/ruby-2.1.1/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:9:in `require'
	from bin/rails:9:in `<main>'
```

And when I delete it and create a resource `Post` for my `Post` model. Everything is OK, and my server starts well.

It's pretty weird.

**Comment by seanlinsley** [comment]
This is coming from line 485 in your routes file. What code do you have there?

**Comment by seanlinsley** [comment]
The exception itself is coming from Devise: https://github.com/plataformatec/devise/issues/1597

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
