### ISSUE TITLE
rails generate active_admin:install raises "undefined method `devise_for' for main:Object (NoMethodError)" error

### ISSUE THREAD

**Issue by oveits** [activeadmin/activeadmin#4295]
##### Issue
After installing: the gems 'devise' and 'activeadmin' with version 1.0.0.pre2, and running ```rails generate active_admin:install```, I run into the error ```NoMethodError: undefined method "devise_for" for main:Object```

I have found out that the generator has placed the following lines into ```config/routes.rb``` twice: 
```ruby
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
```
once in the beginning of the ```config/routes.rb``` file:
```ruby
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
```
and once at the very end of the file:
```ruby
...
end # scope(path: baseURL) do
end # Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

```
The latter entry has lead to the following error message:
```ruby

       config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }

     In production, :host should be set to the actual host of your application.

  2. Ensure you have defined root_url to *something* in your config/routes.rb.
     For example:

       root to: "home#index"

  3. Ensure you have flash messages in app/views/layouts/application.html.erb.
     For example:

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

  4. If you are deploying on Heroku with Rails 3.2 only, you may want to set:

       config.assets.initialize_on_precompile = false

     On config/application.rb forcing your application to not access the DB
     or load models when precompiling your assets.

  5. You can copy Devise views (for customization) to your app by running:

       rails g devise:views

===============================================================================
      invoke    active_record
      create      db/migrate/20160201231005_devise_create_admin_users.rb
      create      app/models/admin_user.rb
      invoke      rspec
      create        spec/models/admin_user_spec.rb
      insert      app/models/admin_user.rb
       route    devise_for :admin_users
        gsub    app/models/admin_user.rb
        gsub    config/routes.rb
      create  config/initializers/active_admin.rb
      create  app/admin
      create  app/admin/dashboard.rb
      create  app/admin/admin_user.rb
      insert  config/routes.rb
    generate  active_admin:assets
/home/ubuntu/workspace/config/routes.rb:159:in `<top (required)>': undefined method `devise_for' for main:Object (NoMethodError)
        from /usr/local/rvm/gems/ruby-2.2.4/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `load'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `block in load'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `load'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/railties-4.2.5.1/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/railties-4.2.5.1/lib/rails/application/routes_reloader.rb:40:in `each'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/railties-4.2.5.1/lib/rails/application/routes_reloader.rb:40:in `load_paths'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/railties-4.2.5.1/lib/rails/application/routes_reloader.rb:16:in `reload!'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/railties-4.2.5.1/lib/rails/application/routes_reloader.rb:26:in `block in updater'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/activesupport-4.2.5.1/lib/active_support/file_update_checker.rb:75:in `call'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/activesupport-4.2.5.1/lib/active_support/file_update_checker.rb:75:in `execute'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/railties-4.2.5.1/lib/rails/application/routes_reloader.rb:27:in `updater'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/railties-4.2.5.1/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/railties-4.2.5.1/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/railties-4.2.5.1/lib/rails/initializable.rb:30:in `instance_exec'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/railties-4.2.5.1/lib/rails/initializable.rb:30:in `run'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/railties-4.2.5.1/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
        from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
        from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
        from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `each'
        from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `call'
        from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
        from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
        from /usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/railties-4.2.5.1/lib/rails/initializable.rb:54:in `run_initializers'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/railties-4.2.5.1/lib/rails/application.rb:352:in `initialize!'
        from /home/ubuntu/workspace/config/environment.rb:5:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/railties-4.2.5.1/lib/rails/application.rb:328:in `require_environment!'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:128:in `generate_or_destroy'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:50:in `generate'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/railties-4.2.5.1/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
      create  db/migrate/20160201231018_create_active_admin_comments.rb
```

##### Workaround:
Interestingly, the problem has disappeared after a ```git stash``` and retrying the whole process, after I had removed the two empty lines I had had at the end of the ```config/routes.rb``` file. It seems like the rails generator is confused by any empty lines after the last ```end``` statement in the file and will the excess statements at the end of the file. 

Here is the full listing of the Gemfile:
```Ruby
source 'https://rubygems.org'
#ruby '2.1.3'
# >= is not supported in tis context:
#ruby ENV['CUSTOM_RUBY_VERSION'] || '>= 2.0.0'
# commented out again and we set the ruby version externally, e.g. in .travis.yml etc.
#ruby ENV['CUSTOM_RUBY_VERSION'] || '2.0.0'
#ruby ENV['CUSTOM_RUBY_VERSION'] || '2.2.4'

gem 'devise'
gem 'activeadmin', '1.0.0.pre2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 4.2.4'
gem 'bootstrap-sass'
group :development, :test do
  # Use sqlite3 as the database for Active Record
  gem 'sqlite3'
  #gem 'rspec-core'
  gem 'rspec-rails', '>= 2.13.1'
  gem 'rspec-its'
  gem 'byebug'
end

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-turbolinks'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# OV: temporarily commented out because bundle install did not work:
#gem 'debugger', group: [:development, :test]

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin]

# OV added:
#gem 'ruby-debug-base' 
#gem 'ruby-debug-ide'

# OV added:
gem 'activemodel-globalid'
#gem 'activejob'
gem 'delayed_job_active_record'
#gem 'delayed_job_active_record', '~> 4.0.6'
#gem 'delayed_job_active_record','4.0.6' #, '4.0.6' #, '4.1.1'

gem "delayed_job_web", '1.2.5'

# OV added to be able to start rake jobs:work as daemon:
gem "daemons"

# OV for making synchronous calls to provisioning.deliver non-blocking:
# note: this requires curl to be installed. See 
#gem 'typhoeus'
#gem 'ethon'

gem 'em-http-request'

# OV needed for JRuby, see https://devcenter.heroku.com/articles/moving-an-existing-rails-app-to-run-on-jruby
#ruby '1.9.3', :engine => 'jruby', :engine_version => '1.7.1'
#ruby '1.9.3', :engine => 'jruby', :engine_version => '1.7.1'
#gem 'puma'
# or alternatively, but has higher memory footprint: 
# gem 'trinidad'

# OV: needed for heroku (see https://www.railstutorial.org/book/beginning#sec-heroku_setup)
group :production do
  gem 'pg', '0.15.1'
  gem 'rails_12factor', '0.0.2'
end

gem 'seed_dump'

group :test do
  gem 'selenium-webdriver', '2.35.1'
  gem 'capybara' #, '~> 2.1.0'
  # OV to get rid of a warning during running 
  gem "minitest"
  # OV was needed after upgrade to ruby v2.2.4 (see https://github.com/rspec/rspec-rails/issues/1273 or https://github.com/rails/rails/issues/18572):
  gem 'test-unit'
end

# OV for speeding up rspec test startup:
group :development, :test do
  gem 'spork-rails', '4.0.0'
  #gem 'guard-spork', '1.5.0'
  #gem 'childprocess', '0.3.6'
end

# OV: pre-populate the test database
group :test do
  gem 'factory_girl_rails', '4.2.0'
end

gem 'figaro'
#gem "figaro", "~> 0.7.0"

# OV does not work (introduces wrong path to /javascripts/respond.js instead of /assets/respond.js and even /assets/respond.js is not installed...); see https://github.com/RouL/respond-js-rails
#gem 'respond-js-rails'
# may be better? See https://github.com/gevans/respond-rails:
gem "respond-rails", "~> 1.0"

# OV for automatic creation of UML-like class diagrams (see http://rails-erd.rubyforge.org/)
group :development do
  gem "rails-erd"
end

gem 'activesupport'

gem 'kaminari'

# does not follow redirects, therefore cannot be used here:
#gem 'rawler'

# better than rawler?
# I had some trouble to install link-checker: it has me required to remove gem capybara first, then 'sudo apt-get install libxslt-dev libxml2-dev', then 'gem install nokogiri -v '1.5.11'', then re-add capybara and 'bundle install':
# see e.g. https://github.com/sparklemotion/nokogiri.org-tutorials/blob/8c8175021a09ff39285f558a3d435076ba624c72/content/installing_nokogiri.md
# OV: does not find any broken links it seems:
#gem 'link-checker'
# best soluton so far (see http://stackoverflow.com/questions/5403708/testing-for-broken-links-in-a-rails-application)
# wget --spider -r -l 1 --header='User-Agent: Mozilla/5.0' http://example.com 2>&1 | grep -B 2 '404'
# and
# wget --spider -r -l 1 --header='User-Agent: Mozilla/5.0' http://example.com 2>&1 | grep -B 2 '500'
```
and of the ```config/routes.rb``` file before the generator is applied:
```ruby
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :text_documents

  #root 'welcome#index'
  #root 'customers#index'
    # OV added. See http://stackoverflow.com/questions/13303695/rails-assets-path-incorrect-in-a-scoped-production-application
if ENV["WEBPORTAL_BASEURL"] == "false" || ENV["WEBPORTAL_BASEURL"].nil?
  baseURL = '/'
else
  baseURL = ENV["WEBPORTAL_BASEURL"]
end

#abort baseURL
#baseURL = '/'

scope(path: baseURL) do
  
  root 'application#root'
  
  # allow for a possibility to remove all provisionins using a single button press:
  # see http://stackoverflow.com/questions/21489528/unable-to-delete-all-records-in-rails-4-through-link-to
#  resources :provisionings, except: [:destroy] do
#   collection do
#     delete :removeAll
#   end
#   member do
#     delete :stop
#   end 
#  end
  
  # OV replaced by:
  #resources :customers, :sites, :users, :provisionings, except: [:destroy] do
  # only supported for customers and provisionings yet:
  resources :targets, :customers, :sites, :users, :provisionings, except: [:destroy, :update] do
   collection do
     delete :removeAll
   end 
  end

  resources :targets, :customers, :sites, :users , except: [:destroy, :update] do
    collection do
      #patch :synchronizeAll
      patch :synchronize
    end
  end

    #resources :customers
   # not tested; trying to use synchronize instead
  #resources :customers, except: [:patch] do
  resources :targets, :customers, :sites, :users do
    resources :provisionings, :member => { :deliver => :post}
    collection do
      #patch :synchronizeAll
      patch :synchronize
    end
    member do
     patch :synchronize
     patch :provision
     patch :deprovision
    end
  end
 
  
  resources :provisionings do
    member do
      put 'deliver'
    end
  end

#  not needed anymore: e.g. targets/3/customers is now replaced /customers?target_id=3; in this method, it can be used for filtering in the index
#  resources :targets do
#    resources :customers, :sites, :users
#  end

  resources :customers do
    # TODO: OV: what is needed this for?
    #get :index, :controller => :sites

    resources :sites, :users
  end

  resources :sites do
    resources :users
  end
  

  # TODO: is this needed? See http://stackoverflow.com/questions/21489528/unable-to-delete-all-records-in-rails-4-through-link-to
  resources  :provisionings, except: [:destroy] do
    member do
      delete :stop
    end
  end

  #require 'delayed_job_web'
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]



  # The priority is based upon order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  #root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end # scope(path: baseURL) do
end # Rails.application.routes.draw do
... (empty line)...
... (empty line)...
```
with two empty lines after the last end. If those lines are removed, the generator works as expected.

**Comment by timoschilling** [comment]
Your problem is not the empty line, it is the comment after the last end
```
end # Rails.application.routes.draw do
```

**Comment by oveits** [comment]
Hi Timo,
That makes sense: the generator is just looking for the pattern /Rails.application.routes.draw do/ (or similar) and is placing the commands into the lines thereafter, right?
Interesting that it works without problems if the empty lines are removed. I guess, this is, because the pattern ends with an EOF instead of a line ending and the command is inserted after the next line ending, which is not present?

Okay, the best solution would be for the generator to ignore any comments. I understand that the effort might not be worth it because we have a good workaround available...
Thanks a lot for the quick clarification.
Thanks,
Oliver

Von meinem iPhone gesendet

Am 02.02.2016 um 12:35 schrieb Timo Schilling <notifications@github.com<mailto:notifications@github.com>>:


Your problem is not the empty line, it is the comment after the last end

end # Rails.application.routes.draw do

**Comment by timoschilling** [comment]
After reading this [code](https://github.com/activeadmin/activeadmin/blob/master/lib/generators/active_admin/install/install_generator.rb#L28):
```ruby
      def setup_routes
        if options[:users] # Ensure Active Admin routes occur after Devise routes so that Devise has higher priority
          # before this code, devise runs something like `route devise_for :admin_users`
          inject_into_file "config/routes.rb", "\n  ActiveAdmin.routes(self)", after: /devise_for .*, ActiveAdmin::Devise\.config/
        else
          route "ActiveAdmin.routes(self)"
        end
      end
```
I think the problem is in Rails, while in both cases the route is inserted by the Rails `route` command.
