### ISSUE TITLE
[Routing Error] uninitialized constant Admin::Admin

### ISSUE THREAD

**Issue by mac-adam-chaieb** [activeadmin/activeadmin#4353]
__Context__
My `active_admin.rb` looks like this:

```ruby
config.default_namespace = :admin

config.namespace :volunteer_portal do |portal|
  portal.authentication_method = :authenticate_volunteer!
  portal.current_user_method = :current_volunteer
  portal.logout_link_path = :destroy_volunteer_session_path
  portal.root_to = 'volunteer_portal/volunteers#index'
end

config.namespace :admin do |admin|
  admin.authentication_method = :authenticate_administrator!
  admin.current_user_method = :current_administrator
  admin.logout_link_path = :destroy_administrator_session_path
  admin.root_to = 'admin/new_students#index'
end
```

My `routes.rb` looks like this:

```ruby
Rails.application.routes.draw do
  root to: 'pages#index'

  devise_for :administrators, ActiveAdmin::Devise.config
  devise_for :volunteers, ActiveAdmin::Devise.config.merge({ path: 'volunteer_portal/' })
  ActiveAdmin.routes(self)

  # Irrelevant to our discussion
  resources :volunteers, only: [:new, :create]
  resources :new_students, only: [:new, :create]

  get 'welcome', to: 'pages#index'
end
```

All my resources are defined in `app/admin`.

What I want to accomplish is one `admin` namespace where login is required that has access to a bunch of other resources (this is pretty much God mode.) None of my resources in `app/admin` define a namespace explicitly because the default namespace is `admin`.

The second namespace, which is `volunteer_portal` only has access to a `volunteer#edit` page and therefore I have registered the resource with two namespaces:

```ruby
ActiveAdmin.register Volunteer do
  # Stuff here...
end

ActiveAdmin.register Volunteer, namespace: :volunteer_portal do
  # More stuff here...
end
```

Finally, I set up Devise with the `Volunteer` model by running

```rails g active_admin:install User```

And skipping all the `conflicts` and re-writing `active_admin.rb` myself as shown above.

__The Problem__

When I authenticate using the login page for the volunteer portal at `/volunteer_portal/login`, I get redirected to the login page for the `admin` namespace: `/admin/login` with the message 'You need to sign in or sign up before continuing', which is confusing as it should redirect to `'volunteer_portal/volunteers#index' as I set it as the root page of that namespace.

When I try to authenticate using an administrator in the `admin` namespace, I get the following screen, and all future requests to `volunteer_portal/login` get redirected to `admin/`.

![image](https://cloud.githubusercontent.com/assets/4356939/13835208/0f112f7a-ebcc-11e5-8438-bcba30e655c4.png)

Here's the full stack trace:

```
ActionController::RoutingError (uninitialized constant Admin::Admin):
  activesupport (4.2.4) lib/active_support/inflector/methods.rb:276:in `const_get'
  activesupport (4.2.4) lib/active_support/inflector/methods.rb:276:in `block in constantize'
  activesupport (4.2.4) lib/active_support/inflector/methods.rb:259:in `each'
  activesupport (4.2.4) lib/active_support/inflector/methods.rb:259:in `inject'
  activesupport (4.2.4) lib/active_support/inflector/methods.rb:259:in `constantize'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:72:in `controller_reference'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:62:in `controller'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:41:in `serve'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:821:in `call'
  warden (1.2.4) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.4) lib/warden/manager.rb:34:in `catch'
  warden (1.2.4) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.4) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.4) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.2.1) lib/web_console/middleware.rb:39:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.4) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.4) lib/rails/engine.rb:518:in `call'
  railties (4.2.4) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /Users/Moe/.rbenv/versions/2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /Users/Moe/.rbenv/versions/2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /Users/Moe/.rbenv/versions/2.2.3/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

I've tried disabling namespaces completely, I tried setting up the config of `admin` outside of  a `config.namespace` block and the one of `volunteer_portal` inside one. Nothing seems to work. I'm very confused.

please help @seanlinsley @gregbell @timoschilling @pcreux @mattvague

**Comment by seanlinsley** [comment]
Please post the stack trace

**Comment by mac-adam-chaieb** [comment]
Fixed the issue! I disabled default namespaces and set my own custom login and logout redirects in `ApplicationController` through `after_sign_in_path_for` and `after_sign_out_path_for`. 

Sorry for the ping, I was quite desperate last night haha :smile:
