### ISSUE TITLE
mass data upload

### ISSUE THREAD

**Issue by kvokka** [activeadmin/activeadmin#4363]
Hello,
I want to attach to my model few images(which have mandatory field title), and do it in ActiveAdmin interface. As upload processor I use Carrierwave
ActiveAdmin and Carrierwave- last versions, Rails 4.2.6, Ruby 2.3.0
So, my models:

```
class Album < ActiveRecord::Base
  has_many :pictures
  accepts_nested_attributes_for :pictures, allow_destroy: true
end

class Picture < ActiveRecord::Base
  belongs_to :album
  mount_uploader :image, ImageUploader
end
```

ActiveAdmin model config

```
ActiveAdmin.register Album do
  permit_params :in_media, :title, :weight, :description, :logo_id , pictures: []

  form do |f|
    f.inputs t("activerecord.models.album") do
      f.input :title
      f.input :description
           f.input :pictures,
                    as: :file,
                    input_html: { multiple: true },
                    hint: I18n.t( 'active_admin.hint.album.multiple_images')
    f.actions
  end
  end
```

And when I try to areate new album I got this trace. Sorry, but I do no know what to do now. A really can not understand, is it my fault, or ActiveAdmin bug. Stackiserflow gives no answer.

```
Started PATCH "/admin/albums/15" for 127.0.0.1 at 2016-03-26 04:00:11 +0100
Processing by Admin::AlbumsController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"CyDm1qMzm3OEa4lgBkbgune64Vl2UiFFhE1cPp32mEuhaUGHnMQuFQ13g7l9lPl7YJhpHCIB0IQksaBz+V8pOw==", "album"=>{"weight"=>"95", "in_media"=>"1", "title"=>"next generation1747998047", "description"=>"parse", "pictures"=>[#<ActionDispatch::Http::UploadedFile:0x007f0ef3650690 @tempfile=#<Tempfile:/tmp/RackMultipart20160326-2805-l6ldhf.jpg>, @original_filename="xs_561a10354a82d4414ee95ed9392b06fc.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"album[pictures][]\"; filename=\"xs_561a10354a82d4414ee95ed9392b06fc.jpg\"\r\nContent-Type: image/jpeg\r\n">, #<ActionDispatch::Http::UploadedFile:0x007f0ef3650668 @tempfile=#<Tempfile:/tmp/RackMultipart20160326-2805-1orqthi.jpg>, @original_filename="xs_jslwsaoizqc.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"album[pictures][]\"; filename=\"xs_jslwsaoizqc.jpg\"\r\nContent-Type: image/jpeg\r\n">, #<ActionDispatch::Http::UploadedFile:0x007f0ef3650640 @tempfile=#<Tempfile:/tmp/RackMultipart20160326-2805-1a0x0ba.jpg>, @original_filename="xs_test-image-big.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"album[pictures][]\"; filename=\"xs_test-image-big.jpg\"\r\nContent-Type: image/jpeg\r\n">]}, "commit"=>"Обновить", "id"=>"15"}
  AdminUser Load (0.4ms)  SELECT  "admin_users".* FROM "admin_users" WHERE "admin_users"."id" = $1  ORDER BY "admin_users"."id" ASC LIMIT 1  [["id", 1]]
  Album Load (0.4ms)  SELECT  "albums".* FROM "albums" WHERE "albums"."id" = $1 LIMIT 1  [["id", 15]]
Completed 500 Internal Server Error in 9ms (ActiveRecord: 0.8ms)

ActiveRecord::AssociationTypeMismatch - Picture(#47130202177820) expected, got ActionDispatch::Http::UploadedFile(#47130139228260):
  activerecord (4.2.6) lib/active_record/associations/association.rb:218:in `raise_on_type_mismatch!'
  activerecord (4.2.6) lib/active_record/associations/collection_association.rb:365:in `block in replace'
  activerecord (4.2.6) lib/active_record/associations/collection_association.rb:365:in `replace'
  activerecord (4.2.6) lib/active_record/associations/collection_association.rb:47:in `writer'
  activerecord (4.2.6) lib/active_record/associations/builder/association.rb:123:in `pictures='
  activerecord (4.2.6) lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
  activerecord (4.2.6) lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
  actionpack (4.2.6) lib/action_controller/metal/strong_parameters.rb:185:in `each_pair'
  activerecord (4.2.6) lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
   () home/kvokka/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-18fd1c23fc60/lib/active_admin/resource_controller/data_access.rb:301:in `assign_attributes'
   () home/kvokka/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-18fd1c23fc60/lib/active_admin/resource_controller/data_access.rb:175:in `update_resource'
  inherited_resources (1.6.0) lib/inherited_resources/actions.rb:45:in `update'
  actionpack (4.2.6) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.6) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.6) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.6) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.6) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.6) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.6) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.6) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.6) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.6) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.6) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.6) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.6) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.6) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.6) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.6) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.6) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.6) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.6) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:817:in `call'
  bullet (5.0.0) lib/bullet/rack.rb:12:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.6) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.6) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.6) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (3.1.1) lib/web_console/middleware.rb:131:in `call_app'
  web-console (3.1.1) lib/web_console/middleware.rb:28:in `block in call'
  web-console (3.1.1) lib/web_console/middleware.rb:18:in `call'
  rack-contrib (1.4.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.4.0) lib/meta_request/middlewares/headers.rb:16:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.6) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  request_store (1.3.0) lib/request_store/middleware.rb:9:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.6) lib/rails/engine.rb:518:in `call'
  railties (4.2.6) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /home/kvokka/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /home/kvokka/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /home/kvokka/.rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

**Comment by seanlinsley** [comment]
There are a number of problems with your approach. The biggest one is that you're attempting to set the attachment association with an image. You set `accepts_nested_attributes_for`, but you're not actually using it. This is what the form fields would look like, when they're built correctly:

```html
<input name="album[pictures_attributes][0][image]" type="file">
```

When the form is submitted, Rails turns it into this:
```ruby
{
  album: {
    pictures_attributes: [
      {
        image: # an instance of ActionDispatch::Http::UploadedFile
      }
    ]
  }
}
```
To deal with updating an existing image without creating it as a duplicate, it's common to also send down the ID as a hidden field.
```html
<input name="album[pictures_attributes][0][id]" type="hidden" value="1">
```

And it make it possible to delete existing associations, `accepts_nested_attributes_for` also allows you to send `_destroy` in the form, which is usually rendered as a checkbox.

```html
<input name="album[pictures_attributes][0][_destroy]" value="1" type="checkbox">
```

That's all stuff that Rails provides, but you'd still have to build the form yourself. Luckily, Active Admin provides [`f.has_many`](https://github.com/activeadmin/activeadmin/blob/master/docs/5-forms.md#nested-resources) to do most of that for you.

However, I myself have a number of customizations to improve the experience for image uploads:

```ruby
permit_params pictures_attributes: [:id, :_destroy, :image]

form do |f|
  f.inputs do
    f.has_many :pictures, allow_destroy: true do |p|
      p.input :image, as: :file, hint: p.object.image.url ? image_tag(p.object.image.url) : ''
    end
  end
end

show do
  panel 'Pictures' do
    resource.pictures.each do |p|
      div style: 'display: inline-block' do
        a href: p.image.url, target: :_blank do
          img src: p.image.url
        end
      end
    end
  end
end
```

```scss
.admin_albums {
  img {
    max-width: 150px;
    max-height: 150px;
  }

  .has_many_container.pictures {
    input[type=file] {
      display: none; // hide for existing, show for new (via JS)
    }
  }
}
```
```coffee
$ ->
  if $('form.album').length
    $(document).on 'has_many_add:after', '.has_many_container.pictures', (e, fieldset)->
      fieldset.find('input[type=file]').show() # show when dynamically added

    $('.has_many_container.pictures li.input.error input').show() # show on validation error
```

**Comment by kvokka** [comment]
Thank you a lot. I implement this logic and it works good. I leave my code here, may be I can be useful for somebody.
```
  permit_params :title, :description, pictures_attributes: [:image, :title, :description, :weight, :id, :_destroy]
...
  form do |f|
    f.inputs t("activerecord.models.album") do
      f.input :title
      f.input :description
      f.has_many :pictures, allow_destroy: true do |ff|
        ff.input :image, as:   :file, hint: ff&.object&.image&.url ? image_tag(ff.object.image_url(:thumb)) : ''
        ff.input :title
        ff.input :description
        ff.input :weight
      end
      f.actions
    end
  end
```

But also I wanted to ask, Is it possible to add nested attributes with multiple selection(`<input type="file" multiple>`) and add nested fields for it, which will be calculated in some foo? 
Now I implement this logic with addition panel in Pictures section (where user select Album and multiple images), maybe it is the best solution.
Sorry for my annoying, but I just try to find out the best implementation

And thank you again for you full answer, it really helps and open my eyes on nested attributes logic.

**Comment by seanlinsley** [comment]
That is definitely possible, but you would have to build the form yourself instead of relying on `f.has_many`. I also haven't dealt with multi-file uploads so I wouldn't be much help.

Here's an example that I found: https://gist.github.com/iqbalhasnan/24905170bdfd182cd631

Happy to help :smile: I'm going to close this ticket since you have a working solution.
