### ISSUE TITLE
ActionController::UrlGenerationError in Admin::Comments#index

### ISSUE THREAD

**Issue by yohn89** [activeadmin/activeadmin#4401]
I got this error in production server 

worked well in development server

```
Showing /home/app/foo/foo/vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre1/app/views/active_admin/resource/index.html.arb where line #2 raised:

No route matches {:action=>"index", :scope=>"all"}
Extracted source (around line #46):

              
        message << " missing required keys: #{missing_keys.sort.inspect}" unless missing_keys.empty?

        raise ActionController::UrlGenerationError, message
      end

      def clear







Showing /home/app/foo/foo/vendor/bundle/ruby/.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/journey/formatter.rb:46:in `generate'
r/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `instrument'
vendor/bundle/ruby/2.2.0/gems/actionview-4.2.5.2/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
vendor/bundle/ruby/2.2.0/gems/actionview-4.2.5.2/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
vendor/bundle/ruby/2.2.0/gems/actionview-4.2.5.2/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
vendor/bundle/ruby/2.2.0/gems/actionview-4.2.5.2/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
vendor/bundle/ruby/2.2.0/gems/actionview-4.2.5.2/lib/action_view/renderer/template_renderer.rb:14:in `render'
vendor/bundle/ruby/2.2.0/gems/actionview-4.2.5.2/lib/action_view/renderer/renderer.rb:46:in `render_template'
vendor/bundle/ruby/2.2.0/gems/actionview-4.2.5.2/lib/action_view/renderer/renderer.rb:27:in `render'
vendor/bundle/ruby/2.2.0/gems/actionview-4.2.5.2/lib/action_view/rendering.rb:100:in `_render_template'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/streaming.rb:217:in `_render_template'
vendor/bundle/ruby/2.2.0/gems/actionview-4.2.5.2/lib/action_view/rendering.rb:83:in `render_to_body'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/abstract_controller/rendering.rb:25:in `render'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/rendering.rb:16:in `render'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/core_ext/benchmark.rb:12:in `ms'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/instrumentation.rb:43:in `render'
vendor/bundle/ruby/2.2.0/gems/remotipart-1.2.1/lib/remotipart/render_overrides.rb:14:in `render_with_remotipart'
vendor/bundle/ruby/2.2.0/gems/responders-2.1.2/lib/action_controller/responder.rb:238:in `default_render'
vendor/bundle/ruby/2.2.0/gems/responders-2.1.2/lib/action_controller/responder.rb:170:in `to_html'
vendor/bundle/ruby/2.2.0/gems/responders-2.1.2/lib/responders/flash_responder.rb:107:in `to_html'
vendor/bundle/ruby/2.2.0/gems/responders-2.1.2/lib/action_controller/responder.rb:163:in `respond'
vendor/bundle/ruby/2.2.0/gems/responders-2.1.2/lib/action_controller/responder.rb:156:in `call'
vendor/bundle/ruby/2.2.0/gems/responders-2.1.2/lib/action_controller/respond_with.rb:205:in `respond_with'
vendor/bundle/ruby/2.2.0/gems/inherited_resources-1.6.0/lib/inherited_resources/actions.rb:7:in `index'
vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre1/lib/active_admin/resource_controller/streaming.rb:12:in `index'
vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
vendor/bundle/ruby
                                          vendor/bundle/ruby/.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:750:in `generate'
                                          r/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/rendering.rb:10:in `process_action'
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
                                          vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:117:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:117:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
                                          vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:505:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
                                          vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
                                          vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/abstract_controller/callbacks.rb:19:in `process_action'
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/rescue.rb:29:in `process_action'
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
                                          vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `block in instrument'
                                          vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
                                          vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:164:in `instrument'
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
                                          vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/abstract_controller/base.rb:137:in `process'
                                          vendor/bundle/ruby/2.2.0/gems/actionview-4.2.5.2/lib/action_view/rendering.rb:30:in `process'
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_controller/metal.rb:196:in `dispatch'
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_controller/metal.rb:237:in `block in action'
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:74:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:43:in `serve'
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/journey/router.rb:43:in `block in serve'
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/journey/router.rb:30:in `each'
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/journey/router.rb:30:in `serve'
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:815:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/rack-pjax-0.8.0/lib/rack/pjax.rb:12:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
                                          vendor/bundle/ruby/2.2.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
                                          vendor/bundle/ruby/2.2.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/remotipart-1.2.1/lib/remotipart/middleware.rb:27:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/flash.rb:260:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
                                          vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/cookies.rb:560:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/query_cache.rb:36:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
                                          vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
                                          vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
                                          vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/rack/logger.rb:38:in `call_app'
                                          vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/rack/logger.rb:20:in `block in call'
                                          vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/tagged_logging.rb:68:in `block in tagged'
                                          vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/tagged_logging.rb:26:in `tagged'
                                          vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/tagged_logging.rb:68:in `tagged'
                                          vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/rack/logger.rb:20:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/request_id.rb:21:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/engine.rb:518:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.2/lib/rails/application.rb:165:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
                                          vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
                                          /usr/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
                                          /usr/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
                                          /usr/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
                                          Request

                                          Parameters:

                                          None
                                          Toggle session dump
                                          Toggle env dump
                                          Response

                                          Headers:

                                          None
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/route_set.rb:797:in `url_for'
                                          vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/routing/url_for.rb:156:in `url_for'
                                          vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre1/lib/active_admin/view_helpers/download_format_links_helper.rb:10:in `block (2 levels) in build_download_format_links'
                                          vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre1/lib/active_admin/view_helpers/download_format_links_helper.rb:9:in `each'
                                          vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre1/lib/active_admin/view_helpers/download_format_links_helper.rb:9:in `block in build_download_format_links'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/context.rb:92:in `with_current_arbre_element'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:26:in `build_tag'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:14:in `div'
                                          vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre1/lib/active_admin/view_helpers/download_format_links_helper.rb:7:in `build_download_format_links'
                                          vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre1/lib/active_admin/views/components/paginated_collection.rb:76:in `block in build_pagination_with_formats'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/context.rb:92:in `with_current_arbre_element'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:26:in `build_tag'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:14:in `div'
                                          vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre1/lib/active_admin/views/components/paginated_collection.rb:66:in `build_pagination_with_formats'
                                          vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre1/lib/active_admin/views/components/paginated_collection.rb:50:in `build'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/context.rb:92:in `with_current_arbre_element'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:26:in `build_tag'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:14:in `paginated_collection'
                                          vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre1/lib/active_admin/views/pages/index.rb:132:in `render_index'
                                          vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre1/lib/active_admin/views/pages/index.rb:50:in `build_collection'
                                          vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre1/lib/active_admin/views/pages/index.rb:28:in `block in main_content'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/context.rb:92:in `with_current_arbre_element'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:26:in `build_tag'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:14:in `batch_action_form'
                                          vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre1/lib/active_admin/views/pages/index.rb:36:in `wrap_with_batch_action_form'
                                          vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre1/lib/active_admin/views/pages/index.rb:26:in `main_content'
                                          vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre1/lib/active_admin/views/pages/base.rb:87:in `block (2 levels) in build_main_content_wrapper'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/context.rb:92:in `with_current_arbre_element'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:26:in `build_tag'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:14:in `div'
                                          vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre1/lib/active_admin/views/pages/base.rb:86:in `block in build_main_content_wrapper'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/context.rb:92:in `with_current_arbre_element'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:26:in `build_tag'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:14:in `div'
                                          vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre1/lib/active_admin/views/pages/base.rb:85:in `build_main_content_wrapper'
                                          vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre1/lib/active_admin/views/pages/base.rb:71:in `block in build_page_content'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/context.rb:92:in `with_current_arbre_element'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:26:in `build_tag'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:14:in `div'
                                          vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre1/lib/active_admin/views/pages/base.rb:70:in `build_page_content'
                                          vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre1/lib/active_admin/views/pages/base.rb:48:in `block (2 levels) in build_page'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/context.rb:92:in `with_current_arbre_element'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:26:in `build_tag'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:14:in `div'
                                          vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre1/lib/active_admin/views/pages/base.rb:44:in `block in build_page'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/context.rb:92:in `with_current_arbre_element'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
                                          vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre1/lib/active_admin/views/pages/base.rb:43:in `build_page'
                                          vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre1/lib/active_admin/views/pages/base.rb:10:in `build'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/context.rb:92:in `with_current_arbre_element'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:26:in `build_tag'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/element/builder_methods.rb:39:in `insert_tag'
                                          vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre1/app/views/active_admin/resource/index.html.arb:2:in `block in _vendor_bundle_ruby_______gems_activeadmin_______pre__app_views_active_admin_resource_index_html_arb___1466611533310830163_70205423159500'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/context.rb:45:in `instance_eval'
                                          vendor/bundle/ruby/2.2.0/gems/arbre-1.0.3/lib/arbre/context.rb:45:in `initialize'
                                          vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre1/app/views/active_admin/resource/index.html.arb:1:in `new'
                                          vendor/bundle/ruby/2.2.0/gems/activeadmin-1.0.0.pre1/app/views/active_admin/resource/index.html.arb:1:in `_vendor_bundle_ruby_______gems_activeadmin_______pre__app_views_active_admin_resource_index_html_arb___1466611533310830163_70205423159500'
                                          vendor/bundle/ruby/2.2.0/gems/actionview-4.2.5.2/lib/action_view/template.rb:145:in `block in render'
                                          vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.2/lib/active_support/notifications.rb:166:in `instrument'
                                          vendor/bundle/ruby/2.2.0/gems/actionview-4.2.5.2/lib/action_view/template.rb:333:in `instrument'
                                          vendor/bundle/ruby/2.2.0/gems/actionview-4.2.5.2/lib/action_view/template.rb:143:in `render'
                                          vendor/bundle/ruby/2.2.0/gems/actionview-4.2.5.2/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
                                          vendor/bundle/ruby/2.2.0/gems/actionview-4.2.5.2/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
                                          vendor/bundle/ruby
```

**Comment by yohn89** [comment]
The solution: 
http://stackoverflow.com/questions/20660604/using-the-correct-url-for-method-in-a-rails-engine-spec

I was including the line  `Rails.application.routes.url_helpers` in one controller, remove that line it works.

T
