### ISSUE TITLE
Multiple active_admin interfaces: does not respond to 'devise' method

### ISSUE THREAD

**Issue by mikes01** [activeadmin/activeadmin#4402]
Hello,

I would create two active_admin interfaces for two different models: AdminUser and ClinicAdmin.
In **ActiveAdmin setup**:
```
ActiveAdmin.setup do |config|
  config.site_title = 'Ziwm'

  config.namespace :admin_user do |admin_user|
    admin_user.authentication_method = :authenticate_admin_user!
    admin_user.current_user_method = :current_admin_user
    admin_user.logout_link_path = :destroy_admin_user_session_path
    admin_user.root_to = 'admin_user#index'
  end

  config.namespace :clinic_admin do |clinic_admin|
    clinic_admin.authentication_method = :authenticate_clinic_admin!
    clinic_admin.current_user_method = :current_clinic_admin
    clinic_admin.logout_link_path = :destroy_clinic_admin_user_session_path
    clinic_admin.root_to = 'clinic_admin#index'
  end
end
```

In **routes.rb**:
```
Rails.application.routes.draw do
  devise_for :clinic_admins, ActiveAdmin::Devise.config
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end
```

When I try start app i get the error:
```
ClinicAdmin does not respond to 'devise' method. This usually means you haven't loaded your ORM file or it's being loaded too late. To fix it, be sure to require 'devise/orm/YOUR_ORM' inside 'config/initializers/devise.rb' or before your application definition in 'config/application.rb'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/devise-4.0.0/lib/devise/rails/routes.rb:508:in `raise_no_devise_method_error!'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/devise-4.0.0/lib/devise/rails/routes.rb:244:in `block in devise_for'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/devise-4.0.0/lib/devise/rails/routes.rb:240:in `each'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/devise-4.0.0/lib/devise/rails/routes.rb:240:in `devise_for'
/home/mikolaj/rails/ziwm/config/routes.rb:2:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:410:in `draw'
/home/mikolaj/rails/ziwm/config/routes.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:40:in `each'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:40:in `load_paths'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:16:in `reload!'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:26:in `block in updater'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/activesupport-4.2.6/lib/active_support/file_update_checker.rb:75:in `execute'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:27:in `updater'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/railties-4.2.6/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
/home/mikolaj/rails/ziwm/config/environment.rb:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/railties-4.2.6/lib/rails/application.rb:328:in `require_environment!'
/usr/local/rvm/gems/ruby-2.3.0@ziwm/gems/railties-4.2.6/lib/rails/application.rb:457:in `block in run_tasks_blocks'
Tasks: TOP => routes => environment
(See full trace by running task with --trace)
```

How can I setup multiple active_admin interfaces?

**Comment by mbiqbal** [comment]
Hi @mikes01, 
Just wanted to know if you were able to solve this problem. I would really appreciate the help.
Thanks

**Comment by mikes01** [comment]
Hi @mbiqbal,
Yes, I resolved it. It was a problem with names conflict. I had a model ClinicAdmin and a namespace :clinic_admin in active_admin config. I renamed the model to ClinicAdminUser then the issue disappear.

**Comment by mbiqbal** [comment]
Thanks a lot @mikes01 
:)
