### ISSUE TITLE
Error after Rails 4.2 upgrade

### ISSUE THREAD

**Issue by koeckc** [activeadmin/activeadmin#4431]
after upgrading to Rails 4.2.6 and using 1.0.0.pre2 i allways get 

```
NoMethodError (undefined method `call' for InheritedResources::Responder:Class
Did you mean?  caller):
  responders (2.2.0) lib/action_controller/respond_with.rb:205:in `respond_with'
  inherited_resources (1.6.0) lib/inherited_resources/actions.rb:7:in `index'
  activeadmin (1.0.0.pre2) lib/active_admin/resource_controller/streaming.rb:12:in `index'
  actionpack (4.2.6) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.6) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.6) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.6) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.6) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.6) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.6) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.6) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.6) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.6) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.6) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.6) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.6) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.6) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.6) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.6) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.6) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.6) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.6) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:817:in `call'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
```

I removed all my active admin model classes and tried also only with an empty ressource but the error comes permanently

**Comment by timoschilling** [comment]
From which rails / active admin version did you updated?

**Comment by koeckc** [comment]
Rails was 4.1.14 and active_admin was already 1.0.0.pre2 .

Im sitting now since hours .. must come from InheritedResources::Responder:Class somehow ..

**Comment by koeckc** [comment]
I played with versions from InheritedResources gem and responders Gem nothing helps its always the same error i have another app where i use active admin with rails 4.2 there i have no issues

**Comment by koeckc** [comment]
I found the problem:
The issue was with the 'rails_aslx' gem that changes something in rails responders that casused activeadmin to fail with that error.
