### ISSUE TITLE
lib/rack/builder.rb:146:in `to_app': missing run or map statement (RuntimeError)

### ISSUE THREAD

**Issue by siwakotisurya** [activeadmin/activeadmin#4530]
Hey Guys, thanks for this awesome gem. I just want to notify that I stumbled upon this issue today morning and thought I need to inform the community.

## Problem
When I fixed/locked the gem version with github's tag as 
```
gem 'activeadmin', tag: 'v1.0.0.pre2', github: 'activeadmin'
``` 
I got this error. This error occured whenever I run `bundle exec ...` or `rake ...` or `rspec ...`. 

previously I had 
```
gem 'activeadmin', github: 'activeadmin'
```

## Solution
I solved this problem by reverting back to previous state.

---

## Necessary Backtrace

```bash
/Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/rack-1.6.4/lib/rack/builder.rb:146:in `to_app': missing run or map statement (RuntimeError)
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/rack-1.6.4/lib/rack/builder.rb:160:in `block in generate_map'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/rack-1.6.4/lib/rack/builder.rb:160:in `each'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/rack-1.6.4/lib/rack/builder.rb:160:in `generate_map'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/rack-1.6.4/lib/rack/builder.rb:145:in `to_app'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/capybara-2.7.1/lib/capybara/rails.rb:13:in `<top (required)>'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/rspec-rails-3.5.1/lib/rspec/rails/vendor/capybara.rb:7:in `<top (required)>'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/rspec-rails-3.5.1/lib/rspec/rails.rb:14:in `<top (required)>'
	from /Users/suryasiwakoti/Desktop/work/kantid/spec/spec_helper.rb:4:in `require'
	from /Users/suryasiwakoti/Desktop/work/kantid/spec/spec_helper.rb:4:in `<top (required)>'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1394:in `require'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1394:in `block in requires='
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1394:in `each'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1394:in `requires='
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/rspec-core-3.5.1/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/rspec-core-3.5.1/lib/rspec/core/configuration_options.rb:111:in `each'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/rspec-core-3.5.1/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/rspec-core-3.5.1/lib/rspec/core/configuration_options.rb:21:in `configure'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:99:in `setup'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:86:in `run'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:71:in `run'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/gems/rspec-core-3.5.1/exe/rspec:4:in `<top (required)>'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/bin/rspec:23:in `load'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/bin/rspec:23:in `<main>'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/bin/ruby_executable_hooks:15:in `eval'
	from /Users/suryasiwakoti/.rvm/gems/ruby-2.3.1@kantid/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by timoschilling** [comment]
Is this still a issue?

**Comment by timoschilling** [comment]
Why is this issue related to active admin?

**Comment by siwakotisurya** [comment]
I have not checked this issue still exists because I rollback as mention above and continue working.
 
I encounter this issue when I used tag in my gem file. Might be that version is incompatible with other gem or the problem was on active admin.
