### ISSUE TITLE
Inherited Resource Conflicting with MailyHerald

### ISSUE THREAD

**Issue by awais545** [activeadmin/activeadmin#4532]
Hi

I am upgrading my application from Rails 4.2 to Rails 5, but unfortunately active admin is conflicting with MailyHeraldWebUI gem. It seems like inherited resource is making an issue.

here is my stacktrace.

```ruby
/home/awais/.rvm/gems/ruby-2.3.1/bundler/gems/activeadmin-4a6bca440cf6/lib/active_admin/namespace.rb:217:in `eval': Unable to autoload constant Engine, expected /home/awais/.rvm/gems/ruby-2.3.1/gems/maily_herald-webui-0.9.0/lib/maily_herald/webui/engine.rb to define it (LoadError)
	from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:203:in `const_missing'
	from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:543:in `load_missing_constant'
	from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:203:in `const_missing'
	from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/inflector/methods.rb:270:in `const_get'
	from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/inflector/methods.rb:270:in `block in constantize'
	from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/inflector/methods.rb:266:in `each'
	from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/inflector/methods.rb:266:in `inject'
	from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/inflector/methods.rb:266:in `constantize'
	from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/core_ext/string/inflections.rb:67:in `constantize'
	from /home/awais/.rvm/gems/ruby-2.3.1/bundler/gems/inherited_resources-d50b05f7e9e3/lib/inherited_resources/class_methods.rb:370:in `block in initialize_resources_class_accessors!'
	from /home/awais/.rvm/gems/ruby-2.3.1/bundler/gems/inherited_resources-d50b05f7e9e3/lib/inherited_resources/class_methods.rb:368:in `delete_if'
	from /home/awais/.rvm/gems/ruby-2.3.1/bundler/gems/inherited_resources-d50b05f7e9e3/lib/inherited_resources/class_methods.rb:368:in `initialize_resources_class_accessors!'
	from /home/awais/.rvm/gems/ruby-2.3.1/bundler/gems/inherited_resources-d50b05f7e9e3/lib/inherited_resources/class_methods.rb:404:in `inherited'
```

No offence, but It seems like ActiveAdmin does not fully support Rails 5.

**Comment by Frexuz** [comment]
I have the exact same problem :/

**Comment by timoschilling** [comment]
@awais545 
1. Please provide a full stacktrace.
2. Does it happen on boot or run time?
3. Does it happen in dev or/and production env (please test).
4. Do you show any MailyHerald Data in ActiveAdmin, if yes pleas post the code

**Comment by awais545** [comment]
@timoschilling 

- Full stacktrace
```ruby
/home/awais/.rvm/gems/ruby-2.3.1/bundler/gems/activeadmin-85ab3f5961e1/lib/active_admin/namespace.rb:217:in `eval': Unable to autoload constant Engine, expected /home/awais/.rvm/gems/ruby-2.3.1/gems/maily_herald-webui-0.9.0/lib/maily_herald/webui/engine.rb to define it (LoadError)
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:203:in `const_missing'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:543:in `load_missing_constant'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:203:in `const_missing'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/inflector/methods.rb:270:in `const_get'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/inflector/methods.rb:270:in `block in constantize'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/inflector/methods.rb:266:in `each'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/inflector/methods.rb:266:in `inject'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/inflector/methods.rb:266:in `constantize'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
  from /home/awais/.rvm/gems/ruby-2.3.1/bundler/gems/inherited_resources-ba9467db4817/lib/inherited_resources/class_methods.rb:370:in `block in initialize_resources_class_accessors!'
  from /home/awais/.rvm/gems/ruby-2.3.1/bundler/gems/inherited_resources-ba9467db4817/lib/inherited_resources/class_methods.rb:368:in `delete_if'
  from /home/awais/.rvm/gems/ruby-2.3.1/bundler/gems/inherited_resources-ba9467db4817/lib/inherited_resources/class_methods.rb:368:in `initialize_resources_class_accessors!'
  from /home/awais/.rvm/gems/ruby-2.3.1/bundler/gems/inherited_resources-ba9467db4817/lib/inherited_resources/class_methods.rb:404:in `inherited'
  from /home/awais/.rvm/gems/ruby-2.3.1/bundler/gems/activeadmin-85ab3f5961e1/lib/active_admin/resource_controller.rb:38:in `inherited'
  from (eval):1:in `register_resource_controller'
  from /home/awais/.rvm/gems/ruby-2.3.1/bundler/gems/activeadmin-85ab3f5961e1/lib/active_admin/namespace.rb:217:in `eval'
  from /home/awais/.rvm/gems/ruby-2.3.1/bundler/gems/activeadmin-85ab3f5961e1/lib/active_admin/namespace.rb:217:in `register_resource_controller'
  from /home/awais/.rvm/gems/ruby-2.3.1/bundler/gems/activeadmin-85ab3f5961e1/lib/active_admin/namespace.rb:47:in `register'
  from /home/awais/.rvm/gems/ruby-2.3.1/bundler/gems/activeadmin-85ab3f5961e1/lib/active_admin/application.rb:158:in `register'
  from /home/awais/.rvm/gems/ruby-2.3.1/bundler/gems/activeadmin-85ab3f5961e1/lib/active_admin.rb:75:in `register'
  from /home/awais/Projects/staging-zeebra.net/app/admin/answer.rb:1:in `<top (required)>'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `block in load'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
  from /home/awais/.rvm/gems/ruby-2.3.1/bundler/gems/activeadmin-85ab3f5961e1/lib/active_admin/application.rb:216:in `block in load'
  from /home/awais/.rvm/gems/ruby-2.3.1/bundler/gems/activeadmin-85ab3f5961e1/lib/active_admin/error.rb:41:in `capture'
  from /home/awais/.rvm/gems/ruby-2.3.1/bundler/gems/activeadmin-85ab3f5961e1/lib/active_admin/application.rb:216:in `load'
  from /home/awais/.rvm/gems/ruby-2.3.1/bundler/gems/activeadmin-85ab3f5961e1/lib/active_admin/application.rb:208:in `block in load!'
  from /home/awais/.rvm/gems/ruby-2.3.1/bundler/gems/activeadmin-85ab3f5961e1/lib/active_admin/application.rb:208:in `each'
  from /home/awais/.rvm/gems/ruby-2.3.1/bundler/gems/activeadmin-85ab3f5961e1/lib/active_admin/application.rb:208:in `load!'
  from /home/awais/.rvm/gems/ruby-2.3.1/bundler/gems/activeadmin-85ab3f5961e1/lib/active_admin/application.rb:230:in `routes'
  from /home/awais/.rvm/gems/ruby-2.3.1/bundler/gems/activeadmin-85ab3f5961e1/lib/active_admin.rb:79:in `routes'
  from /home/awais/Projects/staging-zeebra.net/config/routes.rb:8:in `block in <top (required)>'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0/lib/action_dispatch/routing/route_set.rb:389:in `instance_exec'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0/lib/action_dispatch/routing/route_set.rb:389:in `eval_block'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/actionpack-5.0.0/lib/action_dispatch/routing/route_set.rb:371:in `draw'
  from /home/awais/Projects/staging-zeebra.net/config/routes.rb:3:in `<top (required)>'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `block in load'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/application/routes_reloader.rb:40:in `each'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/application/routes_reloader.rb:40:in `load_paths'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/application/routes_reloader.rb:16:in `reload!'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/application/routes_reloader.rb:26:in `block in updater'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/file_update_checker.rb:77:in `execute'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/application/routes_reloader.rb:27:in `updater'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/application/finisher.rb:119:in `block in <module:Finisher>'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `instance_exec'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `run'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/initializable.rb:55:in `block in run_initializers'
  from /home/awais/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
  from /home/awais/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  from /home/awais/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
  from /home/awais/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
  from /home/awais/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
  from /home/awais/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
  from /home/awais/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
  from /home/awais/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
  from /home/awais/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/initializable.rb:54:in `run_initializers'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/application.rb:352:in `initialize!'
  from /home/awais/Projects/staging-zeebra.net/config/environment.rb:5:in `<top (required)>'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/skylight-0.10.5/lib/skylight/probes.rb:81:in `require'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/skylight-0.10.5/lib/skylight/probes.rb:81:in `require'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
  from /home/awais/Projects/staging-zeebra.net/config.ru:3:in `block in <main>'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
  from /home/awais/Projects/staging-zeebra.net/config.ru:in `new'
  from /home/awais/Projects/staging-zeebra.net/config.ru:in `<main>'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/server.rb:318:in `build_app_and_options_from_config'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/server.rb:218:in `app'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/server.rb:59:in `app'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/server.rb:353:in `wrapped_app'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/server.rb:124:in `log_to_stdout'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/server.rb:77:in `start'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:90:in `block in server'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:85:in `tap'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:85:in `server'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
  from /home/awais/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
  from bin/rails:8:in `require'
  from bin/rails:8:in `<main>'
```

- It happens while **booting**.
- Both in dev and production
- No, we are not showing MailyHerald Data in ActiveAdmin.

**Comment by awais545** [comment]
@Frexuz I am really stuck with it if you get chance to resolve it, please let me know also. Thank you

**Comment by timoschilling** [comment]
@awais545 Please post your `admin/answer.rb` and `model/answer.rb` file

**Comment by awais545** [comment]
@timoschilling 

```ruby
ActiveAdmin.register Answer do
  # See permitted parameters documentation:
  # https://github.com/activeadmin/activeadmin/blob/master/docs/2-resource-customization.md#setting-up-strong-parameters
  #
  # permit_params :list, :of, :attributes, :on, :model
  #
  # or
  #
  # permit_params do
  #   permitted = [:permitted, :attributes]
  #   permitted << :other if params[:action] == 'create' && current_user.admin?
  #   permitted
  # end
end
```

```ruby
class Answer < ApplicationRecord

  validates :custom_text, presence: true
  
  def sort_answers
    order('id DESC')
  end
end
```

```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end
```

**Comment by StanZhuravlev** [comment]
I have similar issue, but with another engine gem. I have message: "Unable to autoload constant Engine"

Do any have resolve solution?

**Comment by timoschilling** [comment]
@StanZhuravlev which gem and how does your error looks like?

**Comment by StanZhuravlev** [comment]
It's my own gem. Now I make monkey patch, and resolve it issue: I added in my engine.rb two first line:

```ruby
class Engine
end

module StRoutes
  class Engine < ::Rails::Engine
    isolate_namespace StRoutes
  end
end
```

**Comment by timoschilling** [comment]
Your engine works without that monkey patch and ActiveAdmin?

**Comment by timoschilling** [comment]
Which namespace name do you use?

**Comment by StanZhuravlev** [comment]
I have not tried without ActiveAdmin. :( All namespace I use by default name: ActiveAdmin and StRoutes for my gem

**Comment by timoschilling** [comment]
No that is not what I mean. I mean on which namespace do you have configured ActiveAdmin? https://github.com/activeadmin/activeadmin/blob/1c85c5654a2ce1d43d4c64d98b928ff133d46406/docs/1-general-configuration.md#namespaces

**Comment by brentmulligan** [comment]
@timoschilling FYI - I am seeing the same issue when using ActiveAdmin 1.0.0.pre4 and the [Knock](https://github.com/nsarno/knock) gem which is an engine. I created a [project](https://github.com/brentmulligan/aa-knock-issue) to replicate the issue. This is a rails 5 api only project (created it that way by mistake) but it works without Knock installed. Here is [stack trace](https://gist.github.com/brentmulligan/ad2ff32b27c3a20b0c9db8e5acd90ca7) of the error.

**Comment by timoschilling** [comment]
This is not a ActiveAdmin issue, that's a InheritedResources problem with Rails 5.
I will open a Issue or PR on InheritedResources and link it here, there you can see what's wrong.

**Comment by timoschilling** [comment]
please update to the latest version of https://github.com/activeadmin/inherited_resources

**Comment by timoschilling** [comment]
Please update to the latest version of https://github.com/activeadmin/inherited_resources
It should fix the bug in inherited_resources.

**Comment by brentmulligan** [comment]
Ok thanks

**Comment by lionel02218** [comment]
so How can I solve this issue?
