### ISSUE TITLE
Admin::Engine (NameError) when installing

### ISSUE THREAD

**Issue by kjellberg** [activeadmin/activeadmin#4596]
I keep getting this error when trying to install Active Admin

I've tried with both rvm and rbenv and different versions but still can't install. It worked perfect 2 days ago. Any ideas? 

Generating assets works before install, but everything breaks after (and when) installing:
```
bundle exec rails generate active_admin:assets
```

### What I'm trying to do
```
bundle exec rails generate active_admin:install
```

### Gemfile
```ruby
gem 'devise'
gem 'activeadmin', github: 'activeadmin'
gem 'inherited_resources', github: 'activeadmin/inherited_resources'
```

### Error message

```
/Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-fcc5a60e01c5/lib/active_admin/namespace.rb:217:in `eval': uninitialized constant Admin::Engine (NameError)
```

### Full error log:

```
$ bundle exec rails generate active_admin:install
/Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-fcc5a60e01c5/lib/active_admin/namespace.rb:217:in `eval': uninitialized constant Admin::Engine (NameError)
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/inflector/methods.rb:270:in `block in constantize'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/inflector/methods.rb:266:in `each'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/inflector/methods.rb:266:in `inject'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/inflector/methods.rb:266:in `constantize'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/inherited_resources-46e3f139885b/lib/inherited_resources/class_methods.rb:370:in `block in initialize_resources_class_accessors!'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/inherited_resources-46e3f139885b/lib/inherited_resources/class_methods.rb:368:in `delete_if'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/inherited_resources-46e3f139885b/lib/inherited_resources/class_methods.rb:368:in `initialize_resources_class_accessors!'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/inherited_resources-46e3f139885b/lib/inherited_resources/class_methods.rb:404:in `inherited'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-fcc5a60e01c5/lib/active_admin/resource_controller.rb:38:in `inherited'
	from (eval):1:in `register_resource_controller'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-fcc5a60e01c5/lib/active_admin/namespace.rb:217:in `eval'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-fcc5a60e01c5/lib/active_admin/namespace.rb:217:in `register_resource_controller'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-fcc5a60e01c5/lib/active_admin/namespace.rb:47:in `register'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-fcc5a60e01c5/lib/active_admin/application.rb:158:in `register'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-fcc5a60e01c5/lib/active_admin.rb:75:in `register'
	from /Users/rasmus/Documents/DEV/Rails/fakeshareapp/app/admin/admin_user.rb:1:in `<top (required)>'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-fcc5a60e01c5/lib/active_admin/application.rb:216:in `block in load'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-fcc5a60e01c5/lib/active_admin/error.rb:41:in `capture'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-fcc5a60e01c5/lib/active_admin/application.rb:216:in `load'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-fcc5a60e01c5/lib/active_admin/application.rb:208:in `block in load!'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-fcc5a60e01c5/lib/active_admin/application.rb:208:in `each'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-fcc5a60e01c5/lib/active_admin/application.rb:208:in `load!'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-fcc5a60e01c5/lib/active_admin/application.rb:230:in `routes'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-fcc5a60e01c5/lib/active_admin.rb:79:in `routes'
	from /Users/rasmus/Documents/DEV/Rails/fakeshareapp/config/routes.rb:3:in `block in <top (required)>'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:389:in `instance_exec'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:389:in `eval_block'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:371:in `draw'
	from /Users/rasmus/Documents/DEV/Rails/fakeshareapp/config/routes.rb:1:in `<top (required)>'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:40:in `each'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/file_update_checker.rb:77:in `execute'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application/finisher.rb:119:in `block in <module:Finisher>'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `run'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application.rb:352:in `initialize!'
	from /Users/rasmus/Documents/DEV/Rails/fakeshareapp/config/environment.rb:5:in `<top (required)>'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:92:in `preload'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:143:in `serve'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:131:in `block in run'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:125:in `loop'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:125:in `run'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/rasmus/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

Thank you!

**Comment by feliperoveran** [comment]
Same thing here

**Comment by alestuber** [comment]
I'm having the same problem

**Comment by timoschilling** [comment]
please rebundle, fetch https://github.com/activeadmin/inherited_resources @ 4434f0a
