### ISSUE TITLE
NoMethodError (undefined method `to_encryptor' for nil:NilClass)

### ISSUE THREAD

**Issue by claudinosilva** [activeadmin/activeadmin#4601]
Good morning, I have this error message will not let me create an enterprise, can help me?

Started POST "/admin/enterprises" for 180.239.23.70 at 2016-08-24 17:06:20 -0300
Processing by Admin::EnterprisesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"wZ+9FQm6VQbYzNJ+wdHVqN1yiEdfYHU0U0wvLUCnpPc=", "enterprise"=>{"name"=>"Santander SSO-DEV", "allowed_ips"=>"172.16.133.30"}, "commit"=>"Create Enterprise"}
Completed 500 Internal Server Error in 291.9ms

NoMethodError (undefined method `to_encryptor' for nil:NilClass):
  app/models/key.rb:23:in`encrypt_dek'
  app/models/encryptable.rb:22:in `save_key'

**Comment by timoschilling** [comment]
I have never heard about a method named `to_encryptor`.

Please post the complete stacktrace and the related models.

**Comment by claudinosilva** [comment]
Every time I try to create it returns me this error in the log, there is a setting to increase the level of the log?

Started GET "/admin/enterprises" for 180.239.23.74 at 2016-08-25 11:14:55 -0300
Processing by Admin::EnterprisesController#index as HTML
  Rendered vendor/bundle/ruby/2.2.0/gems/activeadmin-0.6.6/app/views/active_admin/resource/index.html.arb (138.0ms)
Completed 200 OK in 142.4ms (Views: 138.1ms | ActiveRecord: 2.1ms)
Started GET "/admin/enterprises/new" for 180.239.23.74 at 2016-08-25 11:15:00 -0300
Processing by Admin::EnterprisesController#new as HTML
  Rendered vendor/bundle/ruby/2.2.0/gems/activeadmin-0.6.6/app/views/active_admin/resource/new.html.arb (43.2ms)
Completed 200 OK in 47.2ms (Views: 43.8ms | ActiveRecord: 1.1ms)
Started POST "/admin/enterprises" for 180.239.23.74 at 2016-08-25 11:15:05 -0300
Processing by Admin::EnterprisesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"wZ+9FQm6VQbYzNJ+wdHVqN1yiEdfYHU0U0wvLUCnpPc=", "enterprise"=>{"name"=>"Santander SSO-DEV", "allowed_ips"=>"172.16.133.30"}, "commit"=>"Create Enterprise"}
Completed 500 Internal Server Error in 45.2ms

NoMethodError (undefined method `to_encryptor' for nil:NilClass):
  app/models/key.rb:23:in `encrypt_dek'
  app/models/encryptable.rb:22:in `save_key'

**Comment by timoschilling** [comment]
Yes, increase the level of the log. And please post the models.

**Comment by claudinosilva** [comment]
Tell me where I can raise the level of the log?

**Comment by claudinosilva** [comment]
I do not know where to increase the level of logging, can you help me?

**Comment by timoschilling** [comment]
http://lmgtfy.com/?q=rails+log+level

**Comment by claudinosilva** [comment]
2016-08-25 14:50:25 INFO Processing by Admin::EnterprisesController#create as HTML
2016-08-25 14:50:25 INFO   Parameters: {"utf8"=>"✓", "authenticity_token"=>"L8bUrx8M7dckesj6+xXzq2Cy3uQ51eBiGCcciZdpBOk=", "enterprise"=>{"name"=>"Santander SSO-DEV", "allowed_ips"=>"172.16.133.30"}, "commit"=>"Create Enterprise"}
2016-08-25 14:50:25 DEBUG   AdminUser Load (1.2ms)  SELECT `admin_users`.* FROM `admin_users` WHERE `admin_users`.`id` = 1 LIMIT 1
2016-08-25 14:50:25 DEBUG    (0.5ms)  BEGIN
2016-08-25 14:50:25 DEBUG   Enterprise Exists (1.0ms)  SELECT 1 AS one FROM `enterprises` WHERE `enterprises`.`name` = BINARY 'Santander SSO-DEV' LIMIT 1
2016-08-25 14:50:25 DEBUG   Enterprise Exists (0.6ms)  SELECT 1 AS one FROM `enterprises` WHERE `enterprises`.`public_key` IS NULL LIMIT 1
2016-08-25 14:50:25 DEBUG   SQL (1.0ms)  INSERT INTO `enterprises` (`allowed_ips`, `created_at`, `name`, `public_key`, `updated_at`) VALUES ('172.16.133.30', '2016-08-25 17:50:25', 'Santander SSO-DEV', 'xn2pbYAZ3eifkHsY35CohoGY', '2016-08-25 17:50:25')
2016-08-25 14:50:25 DEBUG    (10.8ms)  ROLLBACK
2016-08-25 14:50:25 INFO Completed 500 Internal Server Error in 47.7ms

**Comment by abhiQmar** [comment]
@claudinosilva As you can see in the logs, ` INSERT INTO enterprises` has failed (`DEBUG (10.8ms) ROLLBACK`)

I think this has nothing to do with ActiveAdmin. We can close this issue.

**Comment by Fivell** [comment]
@claudinosilva , according to your logs you have an error somewhere in model callbacks or something like this, not error related to activeadmin was detected. 
so please recheck your
```
app/models/key.rb
```
file
