### ISSUE TITLE
NoMethodError: undefined method `delete_if' for "#<ActionController::Parameters:0x007fd273f58848>":String

### ISSUE THREAD

**Issue by Frexuz** [activeadmin/activeadmin#4604]
When I use a batch action

Admin model

```
  config.batch_actions = true

  batch_action :approve, confirm: 'Are you sure?' do |ids|
    collection = EpisodeDeletion.find(ids)
    collection.each do |episode_deletion|
      episode_deletion.approve
    end
    redirect_to collection_path(q: params[:q]), alert: "#{collection.size} episodes were successfully approved for deletion."
  end

  batch_action :dismiss, confirm: 'Are you sure?' do |ids|
    collection = EpisodeDeletion.find(ids)
    collection.each do |episode_deletion|
      episode_deletion.dismiss
    end
    redirect_to collection_path(q: params[:q]), alert: "#{collection.size} episodes were successfully dismissed from deletion."
  end
```

Stacktrace

```
NoMethodError: undefined method `delete_if' for "#<ActionController::Parameters:0x007fd273f58848>":String
  from active_admin/resource_controller/data_access.rb:232:in `clean_search_params'
  from active_admin/resource_controller/data_access.rb:225:in `apply_filtering'
  from active_admin/resource_controller/data_access.rb:58:in `block in find_collection'
  from active_admin/resource_controller/data_access.rb:57:in `each'
  from active_admin/resource_controller/data_access.rb:57:in `find_collection'
  from active_admin/resource_controller/data_access.rb:42:in `collection'
  from inherited_resources/actions.rb:7:in `index'
  from active_admin/resource_controller/streaming.rb:12:in `index'
  from action_controller/metal/basic_implicit_render.rb:4:in `send_action'
  from abstract_controller/base.rb:188:in `process_action'
  from action_controller/metal/rendering.rb:30:in `process_action'
  from abstract_controller/callbacks.rb:20:in `block in process_action'
  from active_support/callbacks.rb:126:in `call'
  from active_support/callbacks.rb:506:in `block (2 levels) in compile'
  from active_support/callbacks.rb:455:in `call'
  from active_support/callbacks.rb:448:in `block (2 levels) in around'
  from active_support/callbacks.rb:286:in `block (2 levels) in halting'
  from route_translator/extensions/action_controller.rb:27:in `set_locale_from_url'
  from active_support/callbacks.rb:382:in `block in make_lambda'
  from active_support/callbacks.rb:285:in `block in halting'
  from active_support/callbacks.rb:447:in `block in around'
  from active_support/callbacks.rb:455:in `call'
  from active_support/callbacks.rb:101:in `__run_callbacks__'
  from active_support/callbacks.rb:750:in `_run_process_action_callbacks'
  from active_support/callbacks.rb:90:in `run_callbacks'
  from abstract_controller/callbacks.rb:19:in `process_action'
  from action_controller/metal/rescue.rb:20:in `process_action'
  from action_controller/metal/instrumentation.rb:32:in `block in process_action'
  from active_support/notifications.rb:164:in `block in instrument'
  from active_support/notifications/instrumenter.rb:21:in `instrument'
  from active_support/notifications.rb:164:in `instrument'
  from action_controller/metal/instrumentation.rb:30:in `process_action'
  from action_controller/metal/params_wrapper.rb:248:in `process_action'
  from active_record/railties/controller_runtime.rb:18:in `process_action'
  from scout_apm/instruments/action_controller_rails_3_rails4.rb:80:in `process_action'
  from abstract_controller/base.rb:126:in `process'
  from action_view/rendering.rb:30:in `process'
  from action_controller/metal.rb:190:in `dispatch'
  from action_controller/metal.rb:262:in `dispatch'
  from action_dispatch/routing/route_set.rb:50:in `dispatch'
  from action_dispatch/routing/route_set.rb:32:in `serve'
  from action_dispatch/journey/router.rb:39:in `block in serve'
  from action_dispatch/journey/router.rb:26:in `each'
  from action_dispatch/journey/router.rb:26:in `serve'
  from action_dispatch/routing/route_set.rb:725:in `call'
  from scout_apm/instruments/rails_router.rb:23:in `call_with_scout_instruments'
  from omniauth/strategy.rb:186:in `call!'
  from omniauth/strategy.rb:164:in `call'
  from omniauth/strategy.rb:186:in `call!'
  from omniauth/strategy.rb:164:in `call'
  from scout_apm/middleware.rb:15:in `call'
  from warden/manager.rb:35:in `block in call'
  from warden/manager.rb:34:in `catch'
  from warden/manager.rb:34:in `call'
  from rack/etag.rb:25:in `call'
  from rack/conditional_get.rb:25:in `call'
  from rack/head.rb:12:in `call'
  from rack/session/abstract/id.rb:222:in `context'
  from rack/session/abstract/id.rb:216:in `call'
  from action_dispatch/middleware/cookies.rb:613:in `call'
  from action_dispatch/middleware/callbacks.rb:38:in `block in call'
  from active_support/callbacks.rb:97:in `__run_callbacks__'
  from active_support/callbacks.rb:750:in `_run_call_callbacks'
  from active_support/callbacks.rb:90:in `run_callbacks'
  from action_dispatch/middleware/callbacks.rb:36:in `call'
  from action_dispatch/middleware/remote_ip.rb:79:in `call'
  from action_dispatch/middleware/debug_exceptions.rb:49:in `call'
  from action_dispatch/middleware/show_exceptions.rb:31:in `call'
  from rails/rack/logger.rb:36:in `call_app'
  from rails/rack/logger.rb:24:in `block in call'
  from active_support/tagged_logging.rb:70:in `block in tagged'
  from active_support/tagged_logging.rb:26:in `tagged'
  from active_support/tagged_logging.rb:70:in `tagged'
  from rails/rack/logger.rb:24:in `call'
  from request_store/middleware.rb:9:in `call'
  from action_dispatch/middleware/request_id.rb:24:in `call'
  from rack/method_override.rb:22:in `call'
  from rack/runtime.rb:22:in `call'
  from active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  from action_dispatch/middleware/executor.rb:12:in `call'
  from rack/sendfile.rb:111:in `call'
  from raven/integrations/rack.rb:50:in `call'
  from scout_apm/instruments/middleware_summary.rb:44:in `call'
  from rails/engine.rb:522:in `call'
  from rails/railtie.rb:193:in `public_send'
  from rails/railtie.rb:193:in `method_missing'
  from unicorn/http_server.rb:562:in `process_client'
  from unicorn/http_server.rb:658:in `worker_loop'
  from scout_apm/server_integrations/unicorn.rb:52:in `call'
  from scout_apm/server_integrations/unicorn.rb:52:in `block (2 levels) in install'
  from unicorn/http_server.rb:508:in `spawn_missing_workers'
  from unicorn/http_server.rb:132:in `start'
  from /var/www/episodecalendar.com/production/shared/bundle/ruby/2.3.0/gems/unicorn-5.1.0/bin/unicorn:126:in `<top (required)>'
  from /var/www/episodecalendar.com/production/shared/bundle/ruby/2.3.0/bin/unicorn:23:in `load'
  from /var/www/episodecalendar.com/production/shared/bundle/ruby/2.3.0/bin/unicorn:23:in `<main>'
```

gem 'rails', github: "rails/rails", branch: '5-0-stable'
gem 'activeadmin', github: 'activeadmin'

**Comment by timoschilling** [comment]
which inherited_resources do you use?

**Comment by Frexuz** [comment]
gem 'inherited_resources', github: 'activeadmin/inherited_resources'

**Comment by deivid-rodriguez** [comment]
@Frexuz Are you still getting this problem? Are you able to try against latest master? I feel this might have been fixed by @Fivell recently.

**Comment by Fivell** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
