### ISSUE TITLE
Getting error: undefined method `add_as_source' for nil:NilClass

### ISSUE THREAD

**Issue by victorbstan** [activeadmin/activeadmin#4659]
I'm getting the error "undefined method `add_as_source' for nil:NilClass`" after I generated active admin resource: `rails generate active_admin:resource user`

`Showing /Users/victorstan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-3a16a1fc4596/app/views/active_admin/resource/index.html.arb where line #2 raised:`

```
 def collect_join_reflections(seed)
        a = source_reflection.add_as_source seed
        if options[:source_type]
          through_reflection.add_as_polymorphic_through self, a
        else
```

trace

```

activerecord (5.0.0.1) lib/active_record/reflection.rb:951:in `collect_join_reflections'
activerecord (5.0.0.1) lib/active_record/reflection.rb:774:in `collect_join_chain'
activerecord (5.0.0.1) lib/active_record/reflection.rb:248:in `chain'
/Users/victorstan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-3a16a1fc4596/lib/active_admin/filters/resource_extension.rb:131:in `block in default_association_filters'
/Users/victorstan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-3a16a1fc4596/lib/active_admin/filters/resource_extension.rb:131:in `reject!'
/Users/victorstan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-3a16a1fc4596/lib/active_admin/filters/resource_extension.rb:131:in `default_association_filters'
/Users/victorstan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-3a16a1fc4596/lib/active_admin/filters/resource_extension.rb:111:in `default_filters'
/Users/victorstan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-3a16a1fc4596/lib/active_admin/filters/resource_extension.rb:96:in `filter_lookup'
/Users/victorstan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-3a16a1fc4596/lib/active_admin/filters/resource_extension.rb:25:in `filters'
/Users/victorstan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-3a16a1fc4596/lib/active_admin/filters/resource_extension.rb:154:in `block in filters_sidebar_section'
/Users/victorstan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-3a16a1fc4596/lib/active_admin/helpers/optional_display.rb:25:in `instance_exec'
/Users/victorstan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-3a16a1fc4596/lib/active_admin/helpers/optional_display.rb:25:in `display_on?'
/Users/victorstan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-3a16a1fc4596/lib/active_admin/resource/sidebars.rb:17:in `block in sidebar_sections_for'
/Users/victorstan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-3a16a1fc4596/lib/active_admin/resource/sidebars.rb:17:in `select'
/Users/victorstan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-3a16a1fc4596/lib/active_admin/resource/sidebars.rb:17:in `sidebar_sections_for'
/Users/victorstan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-3a16a1fc4596/lib/active_admin/views/pages/base.rb:112:in `sidebar_sections_for_action'
/Users/victorstan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-3a16a1fc4596/lib/active_admin/views/pages/base.rb:136:in `skip_sidebar?'
/Users/victorstan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-3a16a1fc4596/lib/active_admin/views/pages/base.rb:74:in `build_page_content'
/Users/victorstan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-3a16a1fc4596/lib/active_admin/views/pages/base.rb:52:in `block (2 levels) in build_page'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:14:in `div'
/Users/victorstan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-3a16a1fc4596/lib/active_admin/views/pages/base.rb:48:in `block in build_page'
arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
/Users/victorstan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-3a16a1fc4596/lib/active_admin/views/pages/base.rb:47:in `build_page'
/Users/victorstan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-3a16a1fc4596/lib/active_admin/views/pages/base.rb:10:in `build'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
/Users/victorstan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-3a16a1fc4596/app/views/active_admin/resource/index.html.arb:2:in `block in ___sers_victorstan__rbenv_versions_______lib_ruby_gems_______bundler_gems_activeadmin__a__a_fc_____app_views_active_admin_resource_index_html_arb___2749713096878486414_70295644617380'
arbre (1.1.1) lib/arbre/context.rb:45:in `instance_eval'
arbre (1.1.1) lib/arbre/context.rb:45:in `initialize'
/Users/victorstan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-3a16a1fc4596/app/views/active_admin/resource/index.html.arb:1:in `new'
/Users/victorstan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-3a16a1fc4596/app/views/active_admin/resource/index.html.arb:1:in `___sers_victorstan__rbenv_versions_______lib_ruby_gems_______bundler_gems_activeadmin__a__a_fc_____app_views_active_admin_resource_index_html_arb___2749713096878486414_70295644617380'
actionview (5.0.0.1) lib/action_view/template.rb:158:in `block in render'
activesupport (5.0.0.1) lib/active_support/notifications.rb:166:in `instrument'
actionview (5.0.0.1) lib/action_view/template.rb:348:in `instrument'
actionview (5.0.0.1) lib/action_view/template.rb:156:in `render'
actionview (5.0.0.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
actionview (5.0.0.1) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `instrument'
actionview (5.0.0.1) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
actionview (5.0.0.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
actionview (5.0.0.1) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
actionview (5.0.0.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (5.0.0.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (5.0.0.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (5.0.0.1) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.0.0.1) lib/action_view/rendering.rb:103:in `_render_template'
actionpack (5.0.0.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (5.0.0.1) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (5.0.0.1) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.0.0.1) lib/action_controller/metal/renderers.rb:144:in `render_to_body'
actionpack (5.0.0.1) lib/abstract_controller/rendering.rb:26:in `render'
actionpack (5.0.0.1) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (5.0.0.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/victorstan/.rbenv/versions/2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
activesupport (5.0.0.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (5.0.0.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
responders (2.3.0) lib/action_controller/responder.rb:238:in `default_render'
responders (2.3.0) lib/action_controller/responder.rb:170:in `to_html'
responders (2.3.0) lib/responders/flash_responder.rb:107:in `to_html'
responders (2.3.0) lib/action_controller/responder.rb:163:in `respond'
responders (2.3.0) lib/action_controller/responder.rb:156:in `call'
responders (2.3.0) lib/action_controller/respond_with.rb:205:in `respond_with'
/Users/victorstan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/inherited_resources-4434f0ae72f7/lib/inherited_resources/actions.rb:7:in `index'
/Users/victorstan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-3a16a1fc4596/lib/active_admin/resource_controller/streaming.rb:12:in `index'
actionpack (5.0.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.0.1) lib/abstract_controller/base.rb:188:in `process_action'
actionpack (5.0.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (5.0.0.1) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.0.1) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.0.1) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.0.1) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
omniauth (1.3.1) lib/omniauth/strategy.rb:186:in `call!'
omniauth (1.3.1) lib/omniauth/strategy.rb:164:in `call'
warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
warden (1.2.6) lib/warden/manager.rb:34:in `catch'
warden (1.2.6) lib/warden/manager.rb:34:in `call'
rack (2.0.1) lib/rack/etag.rb:25:in `call'
rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.1) lib/rack/head.rb:12:in `call'
rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.0.0.1) lib/active_record/migration.rb:552:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
web-console (3.1.1) lib/web_console/middleware.rb:131:in `call_app'
web-console (3.1.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.1.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.1.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `block in tagged'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `tagged'
railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
railties (5.0.0.1) lib/rails/engine.rb:522:in `call'
puma (3.4.0) lib/puma/configuration.rb:224:in `call'
puma (3.4.0) lib/puma/server.rb:569:in `handle_request'
puma (3.4.0) lib/puma/server.rb:406:in `process_client'
puma (3.4.0) lib/puma/server.rb:271:in `block in run'
puma (3.4.0) lib/puma/thread_pool.rb:114:in `block in spawn_thread'

```

**Comment by darkbls** [comment]
Why did you close it? What did you do?

**Comment by Perpherior** [comment]
Same error here. When I register model name as 'Business', the error occurs. But other names are fine

**Comment by zaidakram** [comment]
Same error here. Did you guys came up with a solution?

**Comment by Theopaps** [comment]
I got the same error. Did anyone find a solution for this?

**Comment by Perpherior** [comment]
In my case, I set a wrong association name on the admin model. After corrected it, all good.

**Comment by jpkk623** [comment]
Same error here.

**Comment by jpkk623** [comment]
In my case, After I added filter such as `filter :created_at`, the error doesn't show anymore.

**Comment by groeneveld91** [comment]
For me I have isolated the issue to defining a HMT with a non-standard name and therefore using `source:` to define the model type. For instance:

`has_many :castle_dragons, through: :castles, source: :dragon`

or

`has_many :castle_dragons, through: :castles, source_type: "Dragon"`
 (not sure if there is a functional difference here)

The standard naming would go something like:
`has_many :dragons, through: :castles`

But that is already taken. Any ideas?

**Comment by takuma7** [comment]
Same here.

**Comment by buren** [comment]
I got this error when I had a has many through relationship where the model "in between" lacked a `has_many` definition.

```ruby
class Customer < ApplicationRecord; end

class CustomerDatabase < ApplicationRecord
  belongs_to :customer
  has_many :report_importers # This was the line that was missing
end

class ReportImporter < ApplicationRecord
  belongs_to :customer_database
end
```

**Comment by DataDaoDe** [comment]
Just saying I got this same error, and for me @buren's solution worked.

**Comment by hakunin** [comment]
For debugging, it would be super nice to know on which relationship, from which model it failed.
That would make it a very quick matter to resolve.

**Comment by volonterx** [comment]
I had this problem with a model that uses active storage's has_one_attached. The issue lies in activeadmin trying to create a filter for the attachment. If your admin file for this model is empty, AA automatically generates filters, including a filter for this relation. Given that I don't need this filter at all, I simply added a list of filters manually, and the error disappeared

`class Book < ApplicationRecord
  has_one_attached :file`
  
  `ActiveAdmin.register Book do
  filter :name
  filter :user
  filter :created_at
  filter :updated_at
end`

**Comment by timoshik** [comment]
In my case, after I added `config.filters = false`, the error doesn't show anymore.
