### ISSUE TITLE
Sprockets::FileNotFound: couldn't find file 'jquery-ui/datepicker' after upgrade to jquery-ui-rails 6.0

### ISSUE THREAD

**Issue by wojtha** [activeadmin/activeadmin#4672]
**After recent upgrade of gem jquery-ui-rails to 6.0.0** I got the following error during `rake assets:precompile` deployment phase:

```
Sprockets::FileNotFound: couldn't find file 'jquery-ui/datepicker'
  (in /home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/bundler/gems/active_admin-78324a83fa01/app/assets/javascripts/active_admin/jquery_ui.js.erb)
```

**Workaround:**

Lock gem 'jquery-ui-rails' at 5.x:

```ruby
# Gemfile
gem 'jquery-ui-rails', '~> 5.0.5'
```

**Full stacktrace:**

<details>

```
Sprockets::FileNotFound: couldn't find file 'jquery-ui/datepicker'
  (in /home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/bundler/gems/active_admin-78324a83fa01/app/assets/javascripts/active_admin/jquery_ui.js.erb)
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/context.rb:106:in `resolve'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/context.rb:146:in `require_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/bundler/gems/active_admin-78324a83fa01/app/assets/javascripts/active_admin/jquery_ui.js.erb:7:in `block in singleton class'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/bundler/gems/active_admin-78324a83fa01/app/assets/javascripts/active_admin/jquery_ui.js.erb:-5:in `instance_eval'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/bundler/gems/active_admin-78324a83fa01/app/assets/javascripts/active_admin/jquery_ui.js.erb:-5:in `singleton class'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/bundler/gems/active_admin-78324a83fa01/app/assets/javascripts/active_admin/jquery_ui.js.erb:-7:in `__tilt_47083840041220'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/context.rb:197:in `block in evaluate'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/context.rb:194:in `each'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/context.rb:194:in `evaluate'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:12:in `initialize'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:374:in `new'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:374:in `block in build_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:395:in `circular_call_protection'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:373:in `build_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:94:in `block in build_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/caching.rb:58:in `cache_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:93:in `build_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:287:in `find_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:61:in `find_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:111:in `block in resolve_dependencies'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:105:in `each'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:105:in `resolve_dependencies'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:97:in `build_required_assets'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:16:in `initialize'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:374:in `new'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:374:in `block in build_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:395:in `circular_call_protection'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:373:in `build_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:94:in `block in build_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/caching.rb:58:in `cache_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:93:in `build_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:287:in `find_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:61:in `find_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:111:in `block in resolve_dependencies'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:105:in `each'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:105:in `resolve_dependencies'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:97:in `build_required_assets'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:16:in `initialize'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:374:in `new'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:374:in `block in build_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:395:in `circular_call_protection'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:373:in `build_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:94:in `block in build_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/caching.rb:58:in `cache_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:93:in `build_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:287:in `find_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:61:in `find_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/bundled_asset.rb:37:in `init_with'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/asset.rb:24:in `from_hash'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/caching.rb:54:in `cache_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:93:in `build_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:287:in `find_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/index.rb:61:in `find_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:211:in `block in find_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:257:in `benchmark'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:210:in `find_asset'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:119:in `block in compile'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:118:in `each'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:118:in `compile'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-2.12.4/lib/rake/sprocketstask.rb:146:in `with_logger'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/airbrake-5.6.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
/home/inm/apps/inm_portal/shared/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/home/inm/.rbenv/versions/2.3.1/bin/bundle:22:in `load'
/home/inm/.rbenv/versions/2.3.1/bin/bundle:22:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```
</details>

**Comment by haitaochen** [comment]
I meet the similar problem.How about your 'application.js' file,maybe you should add 
> //= require jquery-ui

in it.

**Comment by MatayoshiMariano** [comment]
Same problem here, any solution?

**Comment by vernistage** [comment]
I also had to revert from v. 6 to v. 5 to work around this issue.
