### ISSUE TITLE
rake db:migrate rake aborted!

### ISSUE THREAD

**Issue by jegedeolamide99** [activeadmin/activeadmin#4869]
i get this error whenever i run `rake db:migrate`

```
LoadError: cannot load such file -- rails/test_unit/sub_test_task
/var/lib/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
/var/lib/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
/var/lib/gems/2.3.0/gems/draper-2.1.0/lib/draper/tasks/test.rake:7:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
/var/lib/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `block in load'
/var/lib/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
/var/lib/gems/2.3.0/gems/draper-2.1.0/lib/draper/railtie.rb:67:in `block (2 levels) in <class:Railtie>'
/var/lib/gems/2.3.0/gems/draper-2.1.0/lib/draper/railtie.rb:67:in `each'
/var/lib/gems/2.3.0/gems/draper-2.1.0/lib/draper/railtie.rb:67:in `block in <class:Railtie>'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/railtie.rb:239:in `instance_exec'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/railtie.rb:239:in `block in run_tasks_blocks'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/railtie.rb:247:in `each'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/railtie.rb:247:in `each_registered_block'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/railtie.rb:239:in `run_tasks_blocks'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/application.rb:442:in `block in run_tasks_blocks'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/engine/railties.rb:13:in `each'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/engine/railties.rb:13:in `each'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/application.rb:442:in `run_tasks_blocks'
/var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/engine.rb:457:in `load_tasks'
/root/Desktop/my_fast_cash/Rakefile:6:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by deivid-rodriguez** [comment]
@jegedeolamide99 I don't see activeadmin in the backtrace or the command. Also, draper 2.1 is incompatible with Rails 5. Can you upgrade to draper 3.0.0.pre1 and try again?

**Comment by varyonic** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
