### ISSUE TITLE
Undefined method 'before_filter' for commits 9f83674 (3/18/17) and after

### ISSUE THREAD

**Issue by clairity** [activeadmin/activeadmin#4873]
For commits 9f83674 (committed on 3/18/17) and after, I get the following error (found by running `rails c` with the `pry` interpreter):
```
~/.rvm/gems/ruby-2.4.0@default/bundler/gems/activeadmin-9f83674d3f05/lib/active_admin/resource_controller.rb:62:in `<class:ResourceController>': undefined method `before_filter' for ActiveAdmin::ResourceController:Class
Did you mean?  before_build (NoMethodError)
  from ~/.rvm/gems/ruby-2.4.0@default/bundler/gems/activeadmin-9f83674d3f05/lib/active_admin/resource_controller.rb:12:in `<module:ActiveAdmin>'
  from ~/.rvm/gems/ruby-2.4.0@default/bundler/gems/activeadmin-9f83674d3f05/lib/active_admin/resource_controller.rb:9:in `<top (required)>'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:292:in `require'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:292:in `block in require'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:258:in `load_dependency'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:292:in `require'
  from ~/app/config/initializers/active_admin.rb:118:in `block in <top (required)>'
  from ~/.rvm/gems/ruby-2.4.0@default/bundler/gems/activeadmin-9f83674d3f05/lib/active_admin.rb:72:in `setup'
  from ~/app/config/initializers/active_admin.rb:1:in `<top (required)>'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:286:in `load'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:286:in `block in load'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:258:in `load_dependency'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:286:in `load'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/railties-5.1.0.rc1/lib/rails/engine.rb:655:in `block in load_config_initializer'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/activesupport-5.1.0.rc1/lib/active_support/notifications.rb:166:in `instrument'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/railties-5.1.0.rc1/lib/rails/engine.rb:654:in `load_config_initializer'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/railties-5.1.0.rc1/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/railties-5.1.0.rc1/lib/rails/engine.rb:611:in `each'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/railties-5.1.0.rc1/lib/rails/engine.rb:611:in `block in <class:Engine>'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/railties-5.1.0.rc1/lib/rails/initializable.rb:30:in `instance_exec'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/railties-5.1.0.rc1/lib/rails/initializable.rb:30:in `run'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/railties-5.1.0.rc1/lib/rails/initializable.rb:59:in `block in run_initializers'
  from ~/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
  from ~/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  from ~/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
  from ~/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
  from ~/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/railties-5.1.0.rc1/lib/rails/initializable.rb:48:in `each'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/railties-5.1.0.rc1/lib/rails/initializable.rb:48:in `tsort_each_child'
  from ~/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:415:in `call'
  from ~/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:415:in `each_strongly_connected_component_from'
  from ~/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
  from ~/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:347:in `each'
  from ~/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:347:in `call'
  from ~/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
  from ~/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
  from ~/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/railties-5.1.0.rc1/lib/rails/initializable.rb:58:in `run_initializers'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/railties-5.1.0.rc1/lib/rails/application.rb:353:in `initialize!'
  from ~/app/config/environment.rb:5:in `<top (required)>'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:292:in `require'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:292:in `block in require'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:258:in `load_dependency'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/activesupport-5.1.0.rc1/lib/active_support/dependencies.rb:292:in `require'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/spring-2.0.1/lib/spring/application.rb:92:in `preload'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/spring-2.0.1/lib/spring/application.rb:143:in `serve'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/spring-2.0.1/lib/spring/application.rb:131:in `block in run'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/spring-2.0.1/lib/spring/application.rb:125:in `loop'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/spring-2.0.1/lib/spring/application.rb:125:in `run'
  from ~/.rvm/gems/ruby-2.4.0@default/gems/spring-2.0.1/lib/spring/application/boot.rb:19:in `<top (required)>'
  from ~/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from ~/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from -e:1:in `<main>'
```

**Comment by varyonic** [comment]
AA does not have Rails 5.1 support yet.  [before_filters syntax are deprecated in Rails 5.0 and will be removed in Rails 5.1](http://stackoverflow.com/questions/16519828/rails-4-before-filter-vs-before-action)

**Comment by clairity** [comment]
awesome, thanks! i figured it was something like that but wanted to report it just in case.

**Comment by Fivell** [comment]
@varyonic , I'll take a look
