### ISSUE TITLE
ActiveAdmin::OrderClause initialize error.

### ISSUE THREAD

**Issue by songlang1994** [activeadmin/activeadmin#4936]
I got this error when I upgraded ActiveAdmin to 1.0.0.pre5.

    Failure/Error: order_clause = ActiveAdmin::OrderClause.new params[:order]
 
     ArgumentError:
       wrong number of arguments (given 1, expected 2)
     # /Users/rsong/.rvm/gems/ruby-2.3.0@real-answers/gems/activeadmin-1.0.0.pre5/lib/active_admin/order_clause.rb:5:in `initialize'
     # ./app/admin/question.rb:231:in `new'
     # ./app/admin/question.rb:231:in `apply_sorting'
     # /Users/rsong/.rvm/gems/ruby-2.3.0@real-answers/gems/activeadmin-1.0.0.pre5/lib/active_admin/resource_controller/data_access.rb:58:in `block in find_collection'
     # /Users/rsong/.rvm/gems/ruby-2.3.0@real-answers/gems/activeadmin-1.0.0.pre5/lib/active_admin/resource_controller/data_access.rb:57:in `each'
     # /Users/rsong/.rvm/gems/ruby-2.3.0@real-answers/gems/activeadmin-1.0.0.pre5/lib/active_admin/resource_controller/data_access.rb:57:in `find_collection'
     # /Users/rsong/.rvm/gems/ruby-2.3.0@real-answers/gems/activeadmin-1.0.0.pre5/lib/active_admin/resource_controller/data_access.rb:42:in `collection'
     # /Users/rsong/.rvm/gems/ruby-2.3.0@real-answers/gems/inherited_resources-1.7.1/lib/inherited_resources/actions.rb:7:in `index'
     # /Users/rsong/.rvm/gems/ruby-2.3.0@real-answers/gems/activeadmin-1.0.0.pre5/lib/active_admin/resource_controller/streaming.rb:12:in `index'
     # /Users/rsong/.rvm/gems/ruby-2.3.0@real-answers/gems/rails-controller-testing-1.0.1/lib/rails/controller/testing/template_assertions.rb:61:in `process'
     # /Users/rsong/.rvm/gems/ruby-2.3.0@real-answers/gems/gon-6.1.0/lib/gon/spec_helpers.rb:15:in `process'
     # /Users/rsong/.rvm/gems/ruby-2.3.0@real-answers/gems/rails-controller-testing-1.0.1/lib/rails/controller/testing/integration.rb:12:in `block (2 levels) in <module:Integration>'
     # ./spec/admin/question_spec.rb:15:in `block (4 levels) in <top (required)>'

**Comment by timoschilling** [comment]
From where did you are upgrading. Please post the file `app/admin/question.rb`.

**Comment by songlang1994** [comment]
I just added `gem 'activeadmin', '~> 1.0.0.pre5'` to my Gemfile for upgrading.

I think it's throwed by `apply_sorting`.

```ruby
ActiveAdmin.register Question do
  # ...
  # ...

  controller do
    # ...
    # ...

    def apply_sorting(chain)
      order_clause = ActiveAdmin::OrderClause.new params[:order]
      if %w(trending_ranking total_answers).include? order_clause.field
        chain.reorder("#{order_clause.field} #{order_clause.order} NULLS LAST")
      else
        super
      end
    end
  end
end
```

The whole `app/admin/question.rb` is

```ruby
ActiveAdmin.register Question do
  permit_params answers_attributes: [:user_id, :body]
  scope :all
  scope('Trending Unanswered', &:with_no_premium_answer_or_no_answer)
  scope('Moderation') { |scope| scope.unpublished.undeleted }
  scope('Published', default: true, &:published)

  filter :id, label: 'Question ID'
  filter :user_username_contains, label: 'Username', input_html: { placeholder: 'Search by username/display_name' }
  filter :slug
  filter :title_contains, label: 'Question Title', input_html: { placeholder: 'Search by title' }
  filter :body
  filter :category, collection: Category.all.select { |c| c.parent_id != -1 }
  filter :topics, collection: proc {
    @topics = ActsAsTaggableOn::Tag.all
    @categories = Category.all
    if params['q'] && params['q']['category_id_eq']
      category = @categories.find(params['q']['category_id_eq'])
      if category.parent_id == -1
        @topics.where!(category_id: params['q']['category_id_eq'])
      else
        @topics.where!(category_id: category.parent_id)
      end
    end
  }
  filter :is_searchable
  filter :is_published
  filter :is_featured
  filter :deleted_at_not_null, as: :boolean, label: 'IS DELETED'

  form partial: 'form'

  index do
    selectable_column
    column :id do |q|
      link_to q.id, "#{resource_path(q)}?#{request.env['QUERY_STRING']}"
    end
    column :title
    column :body
    column :topics do |q|
      q.topics.join(', ') if q.topics.present?
    end
    column :suggested_topics do |q|
      q.auto_topics.join(', ') if q.auto_topics.present?
    end
    column :created_at, :created_at
    column 'Trending', :trending_ranking
    column 'Number of Answers', :total_answers
    column 'category/stage', :category
    column :actions do |q|
      link = link_to I18n.t('active_admin.edit'), "#{edit_resource_path(q)}?#{request.env['QUERY_STRING']}", class: :member_link
      link += if q.deleted_at?
                content_tag(:span, 'Delete', class: :action_disable)
              else
                link_to 'Delete', resource_path(q), remote: true, 'data-type' => :json, method: :delete, class: :member_link
              end
      link += unless q.deleted_at?
                content_tag(:span, 'Delete', class: :action_hide, style: 'display:none')
              end
      if q.is_published
        link += content_tag(:span, 'Publish', class: :action_disable)
      else
        link += link_to 'Publish',
                        admin_question_path(q, question: { is_searchable: true, is_published: true }, from_index: true),
                        remote: true,
                        'data-type' => :json,
                        method: :put,
                        class: :member_link
        link += content_tag(:span, 'Publish', class: :action_hide, style: 'display:none')
      end
      link += link_to('Answer', new_admin_answer_path(answer: { question_id: q.id, user_id: current_active_admin_user.id }), class: :member_link)
      link += if q.deleted_at?
                content_tag(:span, 'Live Page', class: :member_link)
              else
                link_to('Live Page', "#{ENV['REAL_ANSWERS_ROOT']}/questions/#{q.slug}", target: '_blank', class: [:member_link, :question_live_link])
              end
      unless q.is_published? || q.tag_counts_on(:topics).count.positive?
        auto_topic_count = q.tag_counts_on(:auto_topics).count.zero?
        link += link_to 'Auto Tag',
                        admin_question_path(q, question: { id: q.id }, tag_type: 'auto_tag'),
                        remote: true,
                        'data-type' => :json,
                        method: :put,
                        class: :member_link,
                        style: "display: #{!auto_topic_count ? 'none' : 'inline'}"
        link += link_to 'Cancel Auto Tag',
                        admin_question_path(q, question: { id: q.id }, tag_type: 'unauto_tag'),
                        remote: true,
                        'data-type' => :json,
                        method: :put,
                        class: :member_link,
                        style: "display: #{auto_topic_count ? 'none' : 'inline'}"
      end
      link
    end
  end

  config.clear_action_items!
  action_item :new, only: :index do
    link_to('New Question', "#{ENV['REAL_ANSWERS_ROOT']}/admin/questions/new")
  end
  action_item :edit, only: :show do |q|
    link_to('Edit Question', "#{edit_resource_path(q)}?#{request.env['QUERY_STRING']}")
  end
  action_item :destroy, only: :show do |q|
    link_to('Delete Question', "#{resource_path(q)}?#{request.env['QUERY_STRING']}", method: :delete)
  end

  show do
    default_main_content do
      row :user_email do |r|
        r.user.email
      end
    end
  end

  batch_action :publish do |ids|
    Question.with_deleted.find(ids).each(&:publish!)
    redirect_to index_full_url, notice: 'The questions have been published.'
  end

  batch_action :restore do |ids|
    Question.with_deleted.find(ids).each do |q|
      q.update_attributes(deleted_at: nil) if q.paranoia_destroyed?
    end
    redirect_to index_full_url, notice: 'The questions have been restored.'
  end

  batch_action :feature do |ids|
    Question.with_deleted.find(ids).each(&:feature!)
    redirect_to index_full_url, notice: 'The questions have been featured.'
  end

  batch_action :autoTagTopics do |ids|
    Question.with_deleted.find(ids).each(&:auto_tag)
    redirect_to index_full_url, notice: 'The questions have been auto Tagged.'
  end

  batch_action :cancel_auto_tag_topics do |ids|
    Question.with_deleted.find(ids).each(&:untag)
    redirect_to index_full_url, notice: 'The questions have been cancelled auto Tagged.'
  end

  controller do
    def scoped_collection
      Question.with_deleted
    end

    def permitted_params
      params.permit!
    end

    def change_topics
      q = Question.with_deleted.find(params[:id])
      topic_ids = params[:question][:topic_ids]
      topic_ids = ActsAsTaggableOn::Tag.where(id: topic_ids, category_id: q.category.parent_id).map(&:id) if q.category
      q.change_topics_with_ids(topic_ids)
      params[:question].delete(:topic_ids)
    end

    def update
      change_topics if params[:question][:topic_ids]
      return unless find_question.user_id

      if params[:tag_type] && params[:question][:id]
        auto_tag_topic
        super do |success, _failure|
          success.json { render status: 200, json: suggest_topics.to_json }
        end
        return
      end

      old_topics = find_question.auto_topics
      if !params[:question]['answers_attributes']
        super do |success, _failure|
          chk_auto_tags(old_topics)
          success.html { redirect_to index_full_url }
          success.json { render status: 200, json: @question }
        end
      else
        question_answers_update
        super do |success, failure|
          chk_auto_tags(old_topics)
          success.html { redirect_to index_full_url }
          failure.html { redirect_to action: :update }

          if success.present? && @answers_text.present?
            create_answer_track(@answers_type, @answers_text)
          end
        end
      end
    end

    def question_answers_update
      answers_attributes = params[:question].require(:answers_attributes).map(&:last)
      @answers_type = User.with_deleted.find(answers_attributes[0]['user_id']).role
      @answers_text = answers_attributes[0]['body']
      body_empty = false
      answers_attributes.each { |a| body_empty = true if a['body'].blank? }
      params[:question].delete :answers_attributes if body_empty
    end

    def create_answer_track(answers_type, answers_text)
      Analytics.track(
        anonymous_id: SecureRandom.uuid,
        event: 'Answer Question',
        properties: {
          product: 'bump',
          platform: 'desktop web',
          appBrowserView: false,
          questionId: @question.id,
          timeSinceAsked: ((Time.new - @question.created_at) / 1.hour).round,
          answerType: answers_type,
          answerText: answers_text,
          userDecisionArea: 'admin'
        }
      )
    end

    def destroy
      @question = Question.with_deleted.find(params[:id])
      @question.update_attributes!(deleted_at: Time.now)

      respond_to do |format|
        format.html { redirect_to "#{collection_path}?#{request.env['QUERY_STRING']}" }
        format.json { render json: @question }
      end
    end

    def apply_sorting(chain)
      order_clause = ActiveAdmin::OrderClause.new params[:order]
      if %w(trending_ranking total_answers).include? order_clause.field
        chain.reorder("#{order_clause.field} #{order_clause.order} NULLS LAST")
      else
        super
      end
    end

    def apply_filtering(chain)
      if params[:q].try(:[], :has_featured_answers)
        has_premium = params[:q][:has_featured_answers] == 'true' ? 1 : 0
        chain = chain.with_no_premium_answer_or_no_answer(has_premium)
      end
      if (has_answers = params[:q].try(:[], :has_answers))
        chain = has_answers == 'true' ? chain.with_answers : chain.with_no_answer
      end
      super
    end

    private

    def suggest_topics
      find_question.tag_counts_on(:auto_topics).join(',')
    end

    def auto_tag_topic
      q = find_question
      case params[:tag_type]
      when 'auto_tag'
        q.auto_tag
      when 'unauto_tag'
        q.untag
      end
    end

    def chk_auto_tags(old_suggested_topics)
      q = find_question
      # admin remove all topics in auto tag filed, then update reason field in questions table
      q.untag if q.tag_counts_on(:auto_topics).count.zero?

      # if the question already published
      # then after admin confirm the topics which were suggested by system
      # when update those questions,system will auto transfer the tags from 'auto tag' to 'topics'
      q.remove_auto_tag_from_topics(old_suggested_topics)
      return unless q.is_published && q.tag_counts_on(:auto_topics).count.positive?

      q.auto_tag_to_topics
    end

    def obtain_query_string
      request.env['HTTP_REFERER'].split('?')[1] || ''
    end

    def index_full_url
      "#{collection_path}?#{obtain_query_string}"
    end

    def find_question
      Question.with_deleted.find(params[:id])
    end
  end
end
```

**Comment by Fivell** [comment]
@songlang1994 , try this https://github.com/activeadmin/activeadmin/blob/6fe4013d3463135183b50f73fd8d5113c4ca89c4/docs/3-index-pages/index-as-table.md#custom-sorting

**Comment by Fivell** [comment]
```ActiveAdmin::OrderClause``` is  now pluggable and expect 2 parameters for constructor 
https://github.com/activeadmin/activeadmin/blob/ab72c3351a5ed0c08f760dc13f58d2daeaa1d1f9/lib/active_admin/order_clause.rb

**Comment by songlang1994** [comment]
@Fivell Thank you! It seems that I shouldn't use `ActiveAdmin::OrderClause` directly.
