### ISSUE TITLE
Rails 5 throw(:abort) causes active admin to crash

### ISSUE THREAD

**Issue by vraravam** [activeadmin/activeadmin#5079]
[Please follow the guidelines for creating a bug report](https://github.com/activeadmin/activeadmin/blob/master/CONTRIBUTING.md#4-did-you-find-a-bug).

The issue tracker is only for bugs and feature requests. If you need general
help please post to
[StackOverflow](http://stackoverflow.com/questions/tagged/activeadmin).

### Expected behavior

When I have the following kind of code (as recommended by [Rails 5](http://guides.rubyonrails.org/5_0_release_notes.html#active-record-deprecations)):
```ruby
class Foo < ApplicationRecord
  before_save -> { throw :abort unless new_record? }
end
```
I would expect the exception to have been caught and the errors shown in the form page of the registered object.

### Actual behavior
I get an exception in the browser.

### How to reproduce

The code above should reproduce it.

### Exception message:
This is the exception message that I get:

```ruby
NoMethodError (undefined method `job_sheet_url' for #<Admin::JobSheetsController:0x007fe510c78b28>):
```

**Comment by zorab47** [comment]
Can you provide some of the admin for JobSheet? What version of ActiveAdmin are you using?

**Comment by etspring** [comment]
This code reproduces this error
`ActiveAdmin.register Vacancy do
  permit_params :id, :title
  before_save do |vacancy|
    vacancy.errors.add :base, "You can't do that!"
    throw(:abort)
  end
end`

**Comment by zorab47** [comment]
Can you share the stacktrace too?

**Comment by etspring** [comment]
```
UncaughtThrowError in Admin::VacanciesController#create
uncaught throw :abort
Extracted source (around line #7):

```

```
5.  before_save do |vacancy|
6.    vacancy.errors.add :base, "You can't do that!
7.     throw(:abort)
8.  end

```
```
app/admin/vacancy.rb:7:in `throw'
app/admin/vacancy.rb:7:in `block (2 levels) in <top (required)>'
/Users/administrator/.rvm/gems/ruby-2.4.1/bundler/gems/activeadmin-f28a4e0fb315/lib/active_admin/callbacks.rb:19:in `instance_exec'
/Users/administrator/.rvm/gems/ruby-2.4.1/bundler/gems/activeadmin-f28a4e0fb315/lib/active_admin/callbacks.rb:19:in `run_callback'
/Users/administrator/.rvm/gems/ruby-2.4.1/bundler/gems/activeadmin-f28a4e0fb315/lib/active_admin/callbacks.rb:78:in `block (3 levels) in define_active_admin_callbacks'
/Users/administrator/.rvm/gems/ruby-2.4.1/bundler/gems/activeadmin-f28a4e0fb315/lib/active_admin/callbacks.rb:78:in `each'
/Users/administrator/.rvm/gems/ruby-2.4.1/bundler/gems/activeadmin-f28a4e0fb315/lib/active_admin/callbacks.rb:78:in `block (2 levels) in define_active_admin_callbacks'
/Users/administrator/.rvm/gems/ruby-2.4.1/bundler/gems/activeadmin-f28a4e0fb315/lib/active_admin/resource_controller/data_access.rb:150:in `save_resource'
/Users/administrator/.rvm/gems/ruby-2.4.1/bundler/gems/activeadmin-f28a4e0fb315/lib/active_admin/resource_controller/data_access.rb:140:in `block in create_resource'
activesupport (5.1.4) lib/active_support/core_ext/object/try.rb:17:in `public_send'
activesupport (5.1.4) lib/active_support/core_ext/object/try.rb:17:in `try!'
activesupport (5.1.4) lib/active_support/core_ext/object/try.rb:6:in `try'
/Users/administrator/.rvm/gems/ruby-2.4.1/bundler/gems/activeadmin-f28a4e0fb315/lib/active_admin/callbacks.rb:79:in `block (2 levels) in define_active_admin_callbacks'
/Users/administrator/.rvm/gems/ruby-2.4.1/bundler/gems/activeadmin-f28a4e0fb315/lib/active_admin/resource_controller/data_access.rb:139:in `create_resource'
inherited_resources (1.7.2) lib/inherited_resources/actions.rb:33:in `create'
actionpack (5.1.4) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.1.4) lib/abstract_controller/base.rb:186:in `process_action'
actionpack (5.1.4) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.1.4) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.1.4) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.1.4) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.1.4) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.1.4) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.4) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.4) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.1.4) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
activerecord (5.1.4) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
actionpack (5.1.4) lib/abstract_controller/base.rb:124:in `process'
actionview (5.1.4) lib/action_view/rendering.rb:30:in `process'
actionpack (5.1.4) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (5.1.4) lib/action_controller/metal.rb:253:in `dispatch'
actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (5.1.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:834:in `call'
omniauth (1.7.1) lib/omniauth/strategy.rb:190:in `call!'
omniauth (1.7.1) lib/omniauth/strategy.rb:168:in `call'
omniauth (1.7.1) lib/omniauth/builder.rb:63:in `call'
rack-cors (1.0.1) lib/rack/cors.rb:93:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.1.4) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.4) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.5.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.4) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.4) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.4) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.4) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.1.4) lib/rails/engine.rb:522:in `call'
puma (3.10.0) lib/puma/configuration.rb:225:in `call'
puma (3.10.0) lib/puma/server.rb:605:in `handle_request'
puma (3.10.0) lib/puma/server.rb:437:in `process_client'
puma (3.10.0) lib/puma/server.rb:301:in `block in run'
puma (3.10.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by etspring** [comment]
i have no idea, i just moved validation to the model in my situation

**Comment by abhi121** [comment]
any update on this without moving validation to model?

**Comment by JorgeLeites** [comment]
I have a `before_create` callback to upload some files to S3.
I ended up fixing it by overriding the create method:
```rb
  controller do
    def create
      @scan = Scan.new(scan_params)

      if @scan.save
        redirect_to admin_scan_path(@scan)
      else
        render :new
      end
    end

    private

    def scan_params
      params.require(:scan).permit(:user_id, :folder, :obj_file, :mtl_file, :texture_file)
    end
  end
```
