### ISSUE TITLE
401 UNAUTHORIZED

### ISSUE THREAD

**Issue by akshay18496** [activeadmin/activeadmin#5175]
Expected behavior

active admin not working in rails (Rails 5)

Actual behavior

In terminal
Started GET "/admin" for 127.0.0.1 at 2017-09-13 20:52:14 +0300
Processing by Admin::DashboardController#index as HTML
Completed 401 Unauthorized in 79ms

Started GET "/admin/login" for 127.0.0.1 at 2017-09-13 20:52:16 +0300
Processing by ActiveAdmin::Devise::SessionsController#new as HTML
Rendering C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-acff8334b3c3/app/views/active_admin/devise/sessions/new.html.erb within layouts/active_admin_logged_out
Completed 500 Internal Server Error in 3761ms (ActiveRecord: 10.0ms)

System configuration

Rails version:
Rails 5.1.4
Ruby version:
ruby 2.2.6p396 (2016-11-15 revision 56800) [i386-mingw32]

**Comment by emilioeduardob** [comment]
Same here with Rails `5.1.4` and ActiveAdmin `master`, `1.0`, `1.1.0`.
Getting `ActionView::Template::Error (no implicit conversion of String into Integer):` (with no additional stacktrace =( )
It works fine with Rails `5.1.3`

**Comment by varyonic** [comment]
Tests are [passing with 5.1.4](https://travis-ci.org/activeadmin/activeadmin/builds/277096604). @emilioeduardob you said 'same here' then provide a different error message?

**Comment by emilioeduardob** [comment]
I meant `same her`e because I also can't log in

Here are the logs in the console.
```
=> Booting Puma
=> Rails 5.1.4 application starting in development
=> Run `rails server -h` for more startup options
/Users/emilio/src/platanus/rhinobird-api/config/initializers/koala.rb:2: warning: already initialized constant OpenSSL::SSL::VERIFY_PEER
Using Prometheus API Registry: #<Prometheus::Client::Registry:0x007f83e7bb4de8>
Puma starting in single mode...
* Version 3.8.2 (ruby 2.3.1-p112), codename: Sassy Salamander
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
Started GET "/admin" for 127.0.0.1 at 2017-09-19 08:58:59 -0400
   (2.3ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by Admin::DashboardController#index as HTML
Completed 401 Unauthorized in 22ms (ActiveRecord: 5.2ms)


   (0.3ms)  BEGIN
   (0.2ms)  COMMIT
Started GET "/admin/login" for 127.0.0.1 at 2017-09-19 08:58:59 -0400
Processing by ActiveAdmin::Devise::SessionsController#new as HTML
  Rendering /Users/emilio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activeadmin-1.0.0/app/views/active_admin/devise/sessions/new.html.erb within layouts/active_admin_logged_out
  Rendered /Users/emilio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activeadmin-1.0.0/app/views/active_admin/devise/shared/_links.erb (1.4ms)
  Rendered /Users/emilio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activeadmin-1.0.0/app/views/active_admin/devise/sessions/new.html.erb within layouts/active_admin_logged_out (45.4ms)
Completed 500 Internal Server Error in 575ms (ActiveRecord: 3.5ms)



ActionView::Template::Error (no implicit conversion of String into Integer):
```

If I downgrade to Rails `5.1.3` I works again just fine. 
The stacktrace isn't really helpful

**Comment by emilioeduardob** [comment]
I just tried loggin in with Rails 5.1.3, then upgrading to 5.1.4 (to maintain the session). And accessing a resource, it still errors. So, I guess is not an exclusive error with the login process.

```
=> Booting Puma
=> Rails 5.1.4 application starting in development
=> Run `rails server -h` for more startup options
/Users/emilio/src/platanus/rhinobird-api/config/initializers/koala.rb:2: warning: already initialized constant OpenSSL::SSL::VERIFY_PEER
Using Prometheus API Registry: #<Prometheus::Client::Registry:0x007ff334544f50>
Puma starting in single mode...
* Version 3.8.2 (ruby 2.3.1-p112), codename: Sassy Salamander
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
Started GET "/admin/channels" for 127.0.0.1 at 2017-09-19 09:02:18 -0400
   (2.4ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by Admin::ChannelsController#index as HTML
  AdminUser Load (0.7ms)  SELECT  "admin_users".* FROM "admin_users" WHERE "admin_users"."id" = $1 ORDER BY "admin_users"."id" ASC LIMIT $2  [["id", 19], ["LIMIT", 1]]
  Rendering /Users/emilio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activeadmin-1.0.0/app/views/active_admin/resource/index.html.arb
  Rendered /Users/emilio/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activeadmin-1.0.0/app/views/active_admin/resource/index.html.arb (458.1ms)
Completed 500 Internal Server Error in 531ms (ActiveRecord: 14.3ms)



ActionView::Template::Error (no implicit conversion of String into Integer):
```

**Comment by emilioeduardob** [comment]
I got where it fails.
```
sprockets (4.0.0.beta5) lib/sprockets/source_map_utils.rb:47:in `[]'
sprockets (4.0.0.beta5) lib/sprockets/source_map_utils.rb:47:in `format_source_map'
sprockets (4.0.0.beta5) lib/sprockets/coffee_script_processor.rb:33:in `call'
sprockets (4.0.0.beta5) lib/sprockets/processor_utils.rb:84:in `call_processor'
sprockets (4.0.0.beta5) lib/sprockets/processor_utils.rb:66:in `block in call_processors'
sprockets (4.0.0.beta5) lib/sprockets/processor_utils.rb:65:in `reverse_each'
sprockets (4.0.0.beta5) lib/sprockets/processor_utils.rb:65:in `call_processors'
```
The `map` seems to be an array instead of a Hash
```
      "version"  => 3,
        "file"     => file,
        "mappings" => map["mappings"], 
        "sources"  => map["sources"].map do |source|
          source = URIUtils.split_file_uri(source)[2] if source.start_with? "file://"
          source = PathUtils.join(File.dirname(filename), source) unless PathUtils.absolute_path?(source)
```

**Comment by varyonic** [comment]
Try sprockets 3.7.

**Comment by emilioeduardob** [comment]
That solved it! thanks @varyonic

**Comment by varyonic** [comment]
@akshay18496 I don't have enough information to give you a good response, but my guess is you have not populated an admin user.

**Comment by akshay18496** [comment]
it works well and smooth in windows 7 and also Mac,  But not work well in windows10
