### ISSUE TITLE
RoutingError: No route matches [GET] "/active_admin/datepicker/datepicker-input-icon.png"

### ISSUE THREAD

**Issue by lsarni** [activeadmin/activeadmin#5202]
I'm using activeadmin 1.1.0 with formadmin 0.2.0 and it's throwing this error:

```
Started GET "/active_admin/datepicker/datepicker-input-icon.png" for 127.0.0.1 at 2017-10-12 09:13:41 -0300

ActionController::RoutingError (No route matches [GET] "/active_admin/datepicker/datepicker-input-icon.png"):

actionpack (5.1.3) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.3) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.3) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.3) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.3) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.3) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.3) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.3) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.3) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.3) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.3) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.3) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.3) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.1.3) lib/rails/engine.rb:522:in `call'
puma (3.10.0) lib/puma/configuration.rb:225:in `call'
puma (3.10.0) lib/puma/server.rb:605:in `handle_request'
puma (3.10.0) lib/puma/server.rb:437:in `process_client'
puma (3.10.0) lib/puma/server.rb:301:in `block in run'
puma (3.10.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

Maybe the problem isn't with activeadmin but with formadmin, but the error backtrace doesn't help much.

### How to reproduce
I have a this where `created_at` is a date:
```
ActiveAdmin.register Payment do
  ...
  filter :created_at
end
```

The date_picker itself works. The image was there in the [branch 0-6-stable](https://github.com/activeadmin/activeadmin/blob/0-6-stable/app/assets/images/active_admin/datepicker/datepicker-input-icon.png)

### Workaround
As a workaround I downloaded the image from 6-0-stable and added it to my app at `assets/images/active_admin/datepicker/datepicker-input-icon.png`

**Comment by javierjulio** [comment]
Because the date picker icon image was removed in v1.1 (https://github.com/activeadmin/activeadmin/pull/4988). I'm not sure though why formadmin would fail as it should be referencing the image at all and doesn't appear too.

**Comment by lsarni** [comment]
I just checked and formadmin is using the file [here](https://github.com/formaweb/formadmin/blob/7154c2f619600cbce5a398fe0b1dee46a5baa6df/app/assets/stylesheets/formadmin/components/_form.scss#L348)

So I'm moving this to formadmin
