### ISSUE TITLE
Rails 5.2

### ISSUE THREAD

**Issue by Onumis** [activeadmin/activeadmin#5254]
### Expected behavior

ActiveAdmin to just work wonderfully on Rails 5.2

### Actual behavior

Error booting app:

```
$ rails s
/home/nuno/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19:in `require': cannot load such file -- polyamorous/activerecord_5.2_ruby_2/join_association (LoadError)
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `block in require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:249:in `load_dependency'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/polyamorous-1.3.1/lib/polyamorous.rb:41:in `block in <main>'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/polyamorous-1.3.1/lib/polyamorous.rb:40:in `each'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/polyamorous-1.3.1/lib/polyamorous.rb:40:in `<main>'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `block in require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:249:in `load_dependency'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/ransack-1.8.4/lib/ransack/adapters/active_record/context.rb:3:in `<main>'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `block in require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:249:in `load_dependency'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/ransack-1.8.4/lib/ransack/adapters/active_record.rb:14:in `<main>'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `block in require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:249:in `load_dependency'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/ransack-1.8.4/lib/ransack/adapters.rb:23:in `require_adapter'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/ransack-1.8.4/lib/ransack.rb:27:in `<main>'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `block in require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:249:in `load_dependency'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/activeadmin-1.1.0/lib/active_admin.rb:4:in `<main>'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `block in require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:249:in `load_dependency'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/activeadmin-1.1.0/lib/activeadmin.rb:1:in `<main>'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.0/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.0/lib/bundler/runtime.rb:76:in `each'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.0/lib/bundler/runtime.rb:76:in `block in require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in `each'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in `require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.0/lib/bundler.rb:114:in `require'
  from /home/nuno/projects/rails5.2/config/application.rb:18:in `<main>'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `block in require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:249:in `load_dependency'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/railties-5.2.0.beta2/lib/rails/commands/server/server_command.rb:145:in `block in perform'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/railties-5.2.0.beta2/lib/rails/commands/server/server_command.rb:142:in `tap'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/railties-5.2.0.beta2/lib/rails/commands/server/server_command.rb:142:in `perform'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/railties-5.2.0.beta2/lib/rails/command/base.rb:65:in `perform'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/railties-5.2.0.beta2/lib/rails/command.rb:46:in `invoke'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/railties-5.2.0.beta2/lib/rails/commands.rb:18:in `<main>'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/bootsnap-1.1.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `block in require'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:249:in `load_dependency'
  from /home/nuno/.rvm/gems/ruby-2.4.1/gems/activesupport-5.2.0.beta2/lib/active_support/dependencies.rb:283:in `require'
  from bin/rails:4:in `<main>'
```

### How to reproduce

- Create new project using `Rails 5.2.0.beta2`
- add gem 'active_admin' (currently you also need to [tell bundler how to avoid conflicts](https://github.com/activeadmin/inherited_resources/issues/442))
- `rails s`

**Comment by Onumis** [comment]
Saw now  that actual problem is with https://github.com/activerecord-hackery/polyamorous/issues/26 (ransack dependency).

**Comment by varyonic** [comment]
See https://travis-ci.org/activeadmin/activeadmin/builds/309285935

**Comment by seanfcarroll** [comment]
Cheers, will look into it.

**Comment by seanfcarroll** [comment]
Any suggestions on how to fix this?

**Comment by wspurgin** [comment]
Creating the file for rails 5.2 is the first step I'd guess. Like what https://github.com/activerecord-hackery/polyamorous/pull/28 has started. Stuff *has* changed in AR since 5.1, but I can't tell with certainty if polyamorous needs any changes to account for that. The diff should be found here https://github.com/rails/rails/compare/v5.1.4...v5.2.0.beta2#diff-06059df8d3dee3101718fb2c01151ad0

... but I think because the tag-to-tag comparison is so big, that individual diff doesn't load..... (I told GitHub that I think it was broken). Anyway if you fallback on manual methods, you can go to the "files changed" and search for `join_dependency` and get to that diff.

**Comment by seanfcarroll** [comment]
https://github.com/activerecord-hackery/polyamorous/pull/28

**Comment by zorab47** [comment]
Is this now resolved with https://github.com/activerecord-hackery/polyamorous/pull/28 being merged?

**Comment by Onumis** [comment]
I confirm the original issue is no longer present with `polyamorous >= 1.3.2`

**Comment by zorab47** [comment]
Closing because upstream dependencies is fix.

**Comment by SxDx** [comment]
https://github.com/activerecord-hackery/ransack/issues/853 is still open, so activeadmin is not yet compatible with rails 5.2

**Comment by t2** [comment]
Would this be a good issue to report compatibility issues or are you guys and gals already aware of what needs to be worked on? Can I help?

**Comment by Onumis** [comment]
Imo if there are issues with rails 5.2 compatibility strictly related to AA, it's easier to organize with several GH issues and a tag / milestone. 

Afaik, the only problems so far are with dependencies:

- [x] polyamorous dependency: https://github.com/activerecord-hackery/polyamorous/issues/26
- [ ] ransack dependency: https://github.com/activerecord-hackery/ransack/issues/853

**Comment by t2** [comment]
@Onumis Agreed. If that is the case, this task is technically closed and a new one should be open for ransack? That is the one I am experiencing.

**Comment by varyonic** [comment]
Branch [rails-5.2](https://github.com/activeadmin/activeadmin/commits/rails-5.2) is [still failing](https://travis-ci.org/activeadmin/activeadmin/builds/336309080?utm_source=github_status&utm_medium=notification). I don't see a reason to close this until we merge a passing pull request.

**Comment by t2** [comment]
@varyonic Ok. I will catch up on this and see where I can help.

**Comment by SxDx** [comment]
https://github.com/activerecord-hackery/ransack/issues/853 is closed and ransack 1.8.7 released. AA should be rails 5.2 compatible now.

**Comment by lbrito1** [comment]
Hi @varyonic , how are we on this? Master and rails-5.2 branches both still have `railties < 5.2` in  the [gemspec](https://github.com/activeadmin/activeadmin/blob/rails-5.2/activeadmin.gemspec).

**Comment by varyonic** [comment]
Thanks, I bumped `railties to '<= 5.2.x'` on `rails-5.2`.  `bundle` was [working fine for the demo app](https://github.com/activeadmin/demo.activeadmin.info/commit/55a242f4a27f1e103f8818cc2c229441336efeee) with `rails 5.2.0.rc1` but I guess it would have broken with the final release.

There's an [open PR for has_scope](https://github.com/plataformatec/has_scope/pull/91), please add your voice there.

The only other [issue I know](https://github.com/activeadmin/activeadmin/blob/rails-5.2/gemfiles/rails_52.gemfile) of is in devise, which is currently fixed on master.
