### ISSUE TITLE
Rails 5.1.4 and Active Admin 1.2.0 - active_admin:install Fails 

### ISSUE THREAD

**Issue by ravensnowbird** [activeadmin/activeadmin#5294]
### Step
```
rails g active_admin:install
```

### Error

```
/home/vivek/.rvm/gems/ruby-2.4.2@hermes/gems/railties-5.1.4/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `assets' for #<Rails::Application::Configuration:0x00000000035c60e0>
Did you mean?  asset_host (NoMethodError)
	from /home/vivek/.rvm/gems/ruby-2.4.2@hermes/gems/activeadmin-1.2.0/lib/active_admin/engine.rb:5:in `block (2 levels) in <class:Engine>'
	from /home/vivek/.rvm/gems/ruby-2.4.2@hermes/gems/activeadmin-1.2.0/lib/active_admin/engine.rb:4:in `each'
	from /home/vivek/.rvm/gems/ruby-2.4.2@hermes/gems/activeadmin-1.2.0/lib/active_admin/engine.rb:4:in `block in <class:Engine>'
	from /home/vivek/.rvm/gems/ruby-2.4.2@hermes/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/vivek/.rvm/gems/ruby-2.4.2@hermes/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
	from /home/vivek/.rvm/gems/ruby-2.4.2@hermes/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
	from /home/vivek/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
	from /home/vivek/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/vivek/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/vivek/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/vivek/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:347:in `each'
	from /home/vivek/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:347:in `call'
	from /home/vivek/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/vivek/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
	from /home/vivek/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
	from /home/vivek/.rvm/gems/ruby-2.4.2@hermes/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
	from /home/vivek/.rvm/gems/ruby-2.4.2@hermes/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
	from /home/vivek/Projects/hermes-old/config/environment.rb:5:in `<top (required)>'
	from /home/vivek/.rvm/gems/ruby-2.4.2@hermes/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /home/vivek/.rvm/gems/ruby-2.4.2@hermes/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
	from /home/vivek/.rvm/gems/ruby-2.4.2@hermes/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /home/vivek/.rvm/gems/ruby-2.4.2@hermes/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /home/vivek/.rvm/gems/ruby-2.4.2@hermes/gems/spring-2.0.2/lib/spring/application.rb:102:in `preload'
	from /home/vivek/.rvm/gems/ruby-2.4.2@hermes/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
	from /home/vivek/.rvm/gems/ruby-2.4.2@hermes/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /home/vivek/.rvm/gems/ruby-2.4.2@hermes/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /home/vivek/.rvm/gems/ruby-2.4.2@hermes/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /home/vivek/.rvm/gems/ruby-2.4.2@hermes/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /home/vivek/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/vivek/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

What actually happens?
Just a fresh application with rails 5.1.4 with active admin 1.2.0 fails. 

###Gemfile
```
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'pg'
gem 'activerecord-postgis-adapter'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.4'
# Use sqlite3 as the database for Active Record
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'sqlite3'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]


gem 'sidekiq'
gem 'activeadmin'
gem 'devise'
gem 'draper'
gem 'pundit'

```

**Comment by varyonic** [comment]
Did you install Rails with `--api` perhaps?

**Comment by jeremiahlukus** [comment]
Same problem yes I did with -api

**Comment by varyonic** [comment]
There may be blog articles that show how to use ActiveAdmin with --api but my advise is simply to not do that.

**Comment by jeremiahlukus** [comment]
I ended up using `gem "administrate"` I think if you are using rails api just use that it was pretty straightforward.
