### ISSUE TITLE
undefined method beginning_of_day for string with ransacker

### ISSUE THREAD

**Issue by kashifnaseer** [activeadmin/activeadmin#5416]
I'm getting following error. Any idea - why I'm getting this error ?
 
      undefined method `beginning_of_day' for "2018-01-01":String
       /lib/ransack_ext.rb
       config.add_predicate old, arel_predicate: current
       end
        config.add_predicate 'gteq_datetime',
        arel_predicate: 'gteq',
        formatter: ->(v) { v.beginning_of_day }

**Code:**
Projects.rb (ActiveAdmin)
      filter :project_event_date, label: 'By Project Event Date', as: :date_range

Project.rb(model)

       has_many :project_events, dependent: :destroy
       
       ransacker :project_event_date do
         "project_events.event_date"
       end

**Comment by varyonic** [comment]
Cross posted from [StackOverflow](https://stackoverflow.com/questions/50502421/undefined-method-beginning-of-day-for-string-with-ransacker-custom-filter)

**Comment by kashifnaseer** [comment]
@varyonic yes but I didnt get any help on this yet. any idea how i can fix it ?

I choose date range and hit Filter button. Though, i get above mentioned 500 error but This is what I'm getting  in **URL** 

     project_event_date_gteq_datetime%5D=2018-04- 
    01&q%5Bproject_event_date_lteq_datetime%5D=2018-06-30&commit=Filter&order=id_desc

As _project_events.event_date_ is a date field, why by default URL is appending **project_event_date_gteq_datetime**, should it not only pick something like **project_event_date_gteq_date (without time)**

if I remove Time from URL and make it **project_event_date_gteq_date**, it seems to be working fine. 

can i modify following code to just get **project_event_date_gteq_date**  in URL ?
  
    filter :project_event_date, label: 'By Project Event Date', as: :date_range

**Comment by kashifnaseer** [comment]
Any suggestion/Help regarding this will be appreciated.

**Comment by senid231** [comment]
hi @kashifnaseer 

```ruby
ransacker :project_event_date, type: :date do
     "project_events.event_date"
   end
```
did you try to do like this?
I think you've got this king of an error because you treated this field as `date` but custom ransack field `project_event_date` was defined as `string`

**Comment by kashifnaseer** [comment]
@senid231 I tried this and getting below mentioned error.

    NoMethodError - undefined method `gteq' for "date(project_events.event_date)":String:
    appsignal (2.5.0) lib/appsignal/rack/rails_instrumentation.rb:17:in `call'

**Comment by senid231** [comment]
@kashifnaseer ok, then
```ruby
ransacker :project_event_date, type: :date do
  Arel.sql("project_events.event_date")
end
```
will do the trick for you

**Comment by kashifnaseer** [comment]
@senid231  I did it and getting this error mow 

     ActiveRecord::StatementInvalid - PG::UndefinedTable: ERROR:  missing FROM-clause entry for table 
     "project_events"
      LINE 1: ...projects" WHERE "projects"."is_deleted" = $1 AND (project_ev...
                                                             ^
      : SELECT COUNT(*) FROM "projects" WHERE "projects"."is_deleted" = $1 AND 
       (project_events.event_date >= '2018-05-31 20:00:00' AND project_events.event_date < '2018-06-29'):
      appsignal (2.6.1) lib/appsignal/rack/rails_instrumentation.rb:19:in `call'

**Comment by senid231** [comment]
@kashifnaseer just replace `project_events` in `Arel.sql("project_events.event_date")` with correct table_name

**Comment by seankovacs** [comment]
@senid231 That wont work either because he's trying to do a date range between a date field in an associated model. 

My use case is even more nuanced because I need to do a date range within an inner join'ed distinct subquery, which if I'm understanding op's model correctly, he will need the same so as not to return duplicated Projects.
