### ISSUE TITLE
Error loading the 'sqlite3' Active Record adapter.

### ISSUE THREAD

**Issue by RyunosukeKoyama** [activeadmin/activeadmin#5680]
### Expected behavior

Following files are generated without errors.
```
app/admin/dashboard.rb
app/assets/javascripts/active_admin.js
app/assets/stylesheets/active_admin.scss
config/initializers/active_admin.rb
```

### Actual behavior

An error occurred.
```
/Users/ryunosuke.koyama/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/rubygems_integration.rb:404:in `block (2 levels) in replace_gem': Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.3.6), already activated sqlite3-1.4.0. Make sure all dependencies are added to Gemfile. (LoadError)
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/activerecord-5.2.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:12:in `<main>'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/activerecord-5.2.2/lib/active_record/connection_adapters/connection_specification.rb:191:in `spec'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:952:in `establish_connection'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/activerecord-5.2.2/lib/active_record/connection_handling.rb:60:in `establish_connection'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/activerecord-5.2.2/lib/active_record/railtie.rb:136:in `block (2 levels) in <class:Railtie>'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:42:in `each'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:42:in `on_load'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/activerecord-5.2.2/lib/active_record/railtie.rb:132:in `block in <class:Railtie>'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/ryunosuke.koyama/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	from /Users/ryunosuke.koyama/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/ryunosuke.koyama/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/ryunosuke.koyama/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/ryunosuke.koyama/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each'
	from /Users/ryunosuke.koyama/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `call'
	from /Users/ryunosuke.koyama/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/ryunosuke.koyama/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	from /Users/ryunosuke.koyama/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
	from /Users/ryunosuke.koyama/first/config/environment.rb:5:in `<main>'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/spring-2.0.2/lib/spring/application.rb:102:in `preload'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /Users/ryunosuke.koyama/first/vendor/bundle/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/ryunosuke.koyama/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Users/ryunosuke.koyama/.rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from -e:1:in `<main>'
```

### How to reproduce

1. mkdir ~/tmp
1. cd ~/tmp
1. gem install rails
1. rails new first
1. cd first
1. Add these gems to Gemfile (refer to: https://activeadmin.info/0-installation.html)
     ```
    gem 'activeadmin'
    
    # Plus integrations with:
    gem 'devise'
    gem 'cancan' # or cancancan
    gem 'draper'
    gem 'pundit' 
    ```
1. bundle install
1. bundle exec rails g active_admin:install

#### Environment
* Rails 5.2.2
* ruby 2.5.3p105
* macOS Mojave 10.14.3
* MacBook Pro 15-inch

**Comment by varyonic** [comment]
See https://github.com/rails/rails/issues/35153#issuecomment-460455573
