### ISSUE TITLE
cannot load such file -- coffee_script on 2.0.0.rc1

### ISSUE THREAD

**Issue by dkniffin** [activeadmin/activeadmin#5734]
I just tried to bump one of my app's AA versions to `2.0.0.rc1` (because I'm working on a new PR that should be incoming shortly). But when I started up the app, I got this error: `cannot load such file -- coffee_script`. I've searched my whole codebase and there's no reference to `coffee` anywhere in it, nor are there any `.coffee` files. 

Here's the full stacktrace:
```
activesupport (5.1.6.2) lib/active_support/dependencies.rb:292:in `require'
activesupport (5.1.6.2) lib/active_support/dependencies.rb:292:in `block in require'
activesupport (5.1.6.2) lib/active_support/dependencies.rb:258:in `load_dependency'
activesupport (5.1.6.2) lib/active_support/dependencies.rb:292:in `require'
sprockets (3.7.2) lib/sprockets/autoload/coffee_script.rb:1:in `<top (required)>'
activesupport (5.1.6.2) lib/active_support/dependencies.rb:292:in `require'
activesupport (5.1.6.2) lib/active_support/dependencies.rb:292:in `block in require'
activesupport (5.1.6.2) lib/active_support/dependencies.rb:258:in `load_dependency'
activesupport (5.1.6.2) lib/active_support/dependencies.rb:292:in `require'
sprockets (3.7.2) lib/sprockets/coffee_script_processor.rb:15:in `cache_key'
sprockets (3.7.2) lib/sprockets/processor_utils.rb:93:in `processor_cache_key'
sprockets (3.7.2) lib/sprockets/cached_environment.rb:22:in `block in initialize'
sprockets (3.7.2) lib/sprockets/cached_environment.rb:53:in `processor_cache_key'
sprockets (3.7.2) lib/sprockets/processor_utils.rb:102:in `block in processors_cache_keys'
sprockets (3.7.2) lib/sprockets/processor_utils.rb:102:in `map'
sprockets (3.7.2) lib/sprockets/processor_utils.rb:102:in `processors_cache_keys'
sprockets (3.7.2) lib/sprockets/processing.rb:159:in `resolve_processors_cache_key_uri'
sprockets (3.7.2) lib/sprockets.rb:162:in `block in <module:Sprockets>'
sprockets (3.7.2) lib/sprockets/dependencies.rb:67:in `resolve_dependency'
sprockets (3.7.2) lib/sprockets/cached_environment.rb:23:in `block in initialize'
sprockets (3.7.2) lib/sprockets/cached_environment.rb:59:in `resolve_dependency'
sprockets (3.7.2) lib/sprockets/loader.rb:268:in `block in resolve_dependencies'
sprockets (3.7.2) lib/sprockets/loader.rb:268:in `map'
sprockets (3.7.2) lib/sprockets/loader.rb:268:in `resolve_dependencies'
sprockets (3.7.2) lib/sprockets/loader.rb:55:in `block in load'
sprockets (3.7.2) lib/sprockets/loader.rb:311:in `block in fetch_asset_from_dependency_cache'
sprockets (3.7.2) lib/sprockets/loader.rb:307:in `each'
sprockets (3.7.2) lib/sprockets/loader.rb:307:in `each_with_index'
sprockets (3.7.2) lib/sprockets/loader.rb:307:in `fetch_asset_from_dependency_cache'
sprockets (3.7.2) lib/sprockets/loader.rb:44:in `load'
sprockets (3.7.2) lib/sprockets/cached_environment.rb:20:in `block in initialize'
sprockets (3.7.2) lib/sprockets/cached_environment.rb:47:in `load'
sprockets (3.7.2) lib/sprockets/base.rb:66:in `find_asset'
sprockets (3.7.2) lib/sprockets/base.rb:73:in `find_all_linked_assets'
sprockets (3.7.2) lib/sprockets/manifest.rb:134:in `block in find'
sprockets (3.7.2) lib/sprockets/manifest.rb:133:in `each'
sprockets (3.7.2) lib/sprockets/manifest.rb:133:in `find'
sprockets-rails (3.2.1) lib/sprockets/railtie.rb:50:in `each'
sprockets-rails (3.2.1) lib/sprockets/railtie.rb:50:in `map'
sprockets-rails (3.2.1) lib/sprockets/railtie.rb:50:in `precompiled_assets'
sprockets-rails (3.2.1) lib/sprockets/railtie.rb:35:in `asset_precompiled?'
sprockets-rails (3.2.1) lib/sprockets/railtie.rb:251:in `block (3 levels) in <class:Railtie>'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:359:in `precompiled?'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:363:in `raise_unless_precompiled_asset'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:348:in `find_debug_asset'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:229:in `block in lookup_debug_asset'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:242:in `block in resolve_asset'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:241:in `each'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:241:in `detect'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:241:in `resolve_asset'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:228:in `lookup_debug_asset'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:170:in `block in stylesheet_link_tag'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:169:in `map'
sprockets-rails (3.2.1) lib/sprockets/rails/helper.rb:169:in `stylesheet_link_tag'
arbre (1.2.0) lib/arbre/element.rb:193:in `block in helper_capture'
arbre (1.2.0) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.2.0) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.2.0) lib/arbre/element.rb:193:in `helper_capture'
arbre (1.2.0) lib/arbre/element.rb:181:in `method_missing'
activeadmin (2.0.0.rc1) lib/active_admin/views/pages/base.rb:32:in `block (2 levels) in build_active_admin_head'
activeadmin (2.0.0.rc1) lib/active_admin/views/pages/base.rb:31:in `each'
activeadmin (2.0.0.rc1) lib/active_admin/views/pages/base.rb:31:in `block in build_active_admin_head'
arbre (1.2.0) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.2.0) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
activeadmin (2.0.0.rc1) lib/active_admin/views/pages/base.rb:26:in `build_active_admin_head'
activeadmin (2.0.0.rc1) lib/active_admin/views/pages/base.rb:8:in `build'
arbre (1.2.0) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
arbre (1.2.0) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.2.0) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.2.0) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
activeadmin (2.0.0.rc1) app/views/active_admin/resource/index.html.arb:2:in `block in ___sers_dkniffin__rbenv_versions_______lib_ruby_gems_______gems_activeadmin_______rc__app_views_active_admin_resource_index_html_arb___4010533189254960385_70340885825200'
arbre (1.2.0) lib/arbre/context.rb:45:in `instance_eval'
arbre (1.2.0) lib/arbre/context.rb:45:in `initialize'
activeadmin (2.0.0.rc1) app/views/active_admin/resource/index.html.arb:1:in `new'
activeadmin (2.0.0.rc1) app/views/active_admin/resource/index.html.arb:1:in `___sers_dkniffin__rbenv_versions_______lib_ruby_gems_______gems_activeadmin_______rc__app_views_active_admin_resource_index_html_arb___4010533189254960385_70340885825200'
actionview (5.1.6.2) lib/action_view/template.rb:157:in `block in render'
activesupport (5.1.6.2) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.1.6.2) lib/action_view/template.rb:352:in `instrument_render_template'
actionview (5.1.6.2) lib/action_view/template.rb:155:in `render'
actionview (5.1.6.2) lib/action_view/renderer/template_renderer.rb:52:in `block (2 levels) in render_template'
actionview (5.1.6.2) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
activesupport (5.1.6.2) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.6.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.6.2) lib/active_support/notifications.rb:166:in `instrument'
actionview (5.1.6.2) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
actionview (5.1.6.2) lib/action_view/renderer/template_renderer.rb:51:in `block in render_template'
actionview (5.1.6.2) lib/action_view/renderer/template_renderer.rb:59:in `render_with_layout'
actionview (5.1.6.2) lib/action_view/renderer/template_renderer.rb:50:in `render_template'
actionview (5.1.6.2) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (5.1.6.2) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (5.1.6.2) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.1.6.2) lib/action_view/rendering.rb:103:in `_render_template'
actionpack (5.1.6.2) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (5.1.6.2) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (5.1.6.2) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.1.6.2) lib/action_controller/metal/renderers.rb:141:in `render_to_body'
actionpack (5.1.6.2) lib/abstract_controller/rendering.rb:24:in `render'
actionpack (5.1.6.2) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.1.6.2) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (5.1.6.2) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/dkniffin/.rbenv/versions/2.4.0/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
activesupport (5.1.6.2) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (5.1.6.2) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (5.1.6.2) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (5.1.6.2) lib/active_record/railties/controller_runtime.rb:29:in `cleanup_view_runtime'
actionpack (5.1.6.2) lib/action_controller/metal/instrumentation.rb:43:in `render'
responders (2.4.0) lib/action_controller/responder.rb:238:in `default_render'
responders (2.4.0) lib/action_controller/responder.rb:170:in `to_html'
responders (2.4.0) lib/responders/flash_responder.rb:107:in `to_html'
responders (2.4.0) lib/action_controller/responder.rb:163:in `respond'
responders (2.4.0) lib/action_controller/responder.rb:156:in `call'
responders (2.4.0) lib/action_controller/respond_with.rb:211:in `respond_with'
inherited_resources (1.8.0) lib/inherited_resources/actions.rb:7:in `index'
activeadmin (2.0.0.rc1) lib/active_admin/resource_controller/streaming.rb:12:in `index'
actionpack (5.1.6.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.1.6.2) lib/abstract_controller/base.rb:186:in `process_action'
actionpack (5.1.6.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.1.6.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.1.6.2) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.1.6.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.1.6.2) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.1.6.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.1.6.2) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.6.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.6.2) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.6.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.1.6.2) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
activerecord (5.1.6.2) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
actionpack (5.1.6.2) lib/abstract_controller/base.rb:124:in `process'
actionview (5.1.6.2) lib/action_view/rendering.rb:30:in `process'
actionpack (5.1.6.2) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (5.1.6.2) lib/action_controller/metal.rb:253:in `dispatch'
actionpack (5.1.6.2) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (5.1.6.2) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (5.1.6.2) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (5.1.6.2) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.6.2) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.6.2) lib/action_dispatch/routing/route_set.rb:844:in `call'
rack (2.0.7) lib/rack/etag.rb:25:in `call'
rack (2.0.7) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.7) lib/rack/head.rb:12:in `call'
rack (2.0.7) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.7) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.6.2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.1.6.2) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.6.2) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.6.2) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.6.2) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.6.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
airbrake (7.3.5) lib/airbrake/rack/middleware.rb:48:in `call'
actionpack (5.1.6.2) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.5.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.1.6.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.6.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.6.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.6.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.6.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.6.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.6.2) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.6.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
request_store (1.4.0) lib/request_store/middleware.rb:19:in `call'
actionpack (5.1.6.2) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.7) lib/rack/method_override.rb:22:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.6.2) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.6.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.6.2) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
railties (5.1.6.2) lib/rails/engine.rb:522:in `call'
puma (3.10.0) lib/puma/configuration.rb:225:in `call'
puma (3.10.0) lib/puma/server.rb:605:in `handle_request'
puma (3.10.0) lib/puma/server.rb:437:in `process_client'
puma (3.10.0) lib/puma/server.rb:301:in `block in run'
puma (3.10.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
This error occurred while loading the following files:
   sprockets/autoload/coffee_script
   coffee_script
```

Rails version: 5.1.3
AA version: 2.0.0.rc1

Let me know if you need any more info.

**Comment by javierjulio** [comment]
@dkniffin details on how to fix that are in the [changelog for that release](https://github.com/activeadmin/activeadmin/blob/master/CHANGELOG.md#removals).

**Comment by dkniffin** [comment]
@javierjulio yes, I read that, but as far as I can tell, my application does _not_ use coffeescript. I will see if I can replicate this on a new rails repo.

**Comment by deivid-rodriguez** [comment]
Can you post your Gemfile? Maybe one of your dependencies uses coffe-script but was relying on activeadmin to provide the dependency.

**Comment by dkniffin** [comment]
Here's my `Gemfile.lock`:

```
GIT
  remote: https://github.com/dkniffin/formtastic.git
  revision: 6bb48dac292bc0ca71f6ec5432c1f39955d112cb
  branch: datetime_selected
  specs:
    formtastic (3.2.0.pre)
      actionpack (>= 4.1.0)

PATH
  remote: /Users/dkniffin/repos/activeadmin
  specs:
    activeadmin (2.0.0.rc1)
      arbre (~> 1.2)
      formtastic (~> 3.1)
      formtastic_i18n (~> 0.4)
      inherited_resources (~> 1.7)
      jquery-rails (~> 4.2)
      kaminari (~> 1.0, >= 1.0.1)
      railties (>= 5.0, < 6.0)
      ransack (~> 2.1, >= 2.1.1)
      sass (~> 3.4)
      sprockets (>= 3.0, < 4.1)
      sprockets-es6 (~> 0.9, >= 0.9.2)

GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.1.6.2)
      actionpack (= 5.1.6.2)
      nio4r (~> 2.0)
      websocket-driver (~> 0.6.1)
    actionmailer (5.1.6.2)
      actionpack (= 5.1.6.2)
      actionview (= 5.1.6.2)
      activejob (= 5.1.6.2)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.1.6.2)
      actionview (= 5.1.6.2)
      activesupport (= 5.1.6.2)
      rack (~> 2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.1.6.2)
      activesupport (= 5.1.6.2)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    active_interaction (3.5.2)
      activemodel (>= 4, < 6)
    active_model_serializers (0.10.5)
      actionpack (>= 4.1, < 6)
      activemodel (>= 4.1, < 6)
      case_transform (>= 0.2)
      jsonapi-renderer (>= 0.1.1.beta1, < 0.2)
    activejob (5.1.6.2)
      activesupport (= 5.1.6.2)
      globalid (>= 0.3.6)
    activemodel (5.1.6.2)
      activesupport (= 5.1.6.2)
    activemodel-serializers-xml (1.0.2)
      activemodel (> 5.x)
      activesupport (> 5.x)
      builder (~> 3.1)
    activerecord (5.1.6.2)
      activemodel (= 5.1.6.2)
      activesupport (= 5.1.6.2)
      arel (~> 8.0)
    activesupport (5.1.6.2)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.5.2)
      public_suffix (>= 2.0.2, < 4.0)
    airbrake (7.3.5)
      airbrake-ruby (~> 2.10)
    airbrake-ruby (2.11.0)
    annotate (2.7.2)
      activerecord (>= 3.2, < 6.0)
      rake (>= 10.4, < 13.0)
    arbre (1.2.0)
      activesupport (>= 3.0.0)
    arel (8.0.0)
    ast (2.3.0)
    awesome_print (1.8.0)
    babel-source (5.8.35)
    babel-transpiler (0.7.0)
      babel-source (>= 4.0, < 6)
      execjs (~> 2.0)
    bindex (0.5.0)
    brakeman (3.7.0)
    builder (3.2.3)
    bundler-audit (0.6.0)
      bundler (~> 1.2)
      thor (~> 0.18)
    byebug (9.0.6)
    case_transform (0.2)
      activesupport
    chronic (0.10.2)
    codeclimate-test-reporter (1.0.8)
      simplecov (<= 0.13)
    coderay (1.1.1)
    colorize (0.8.1)
    concurrent-ruby (1.1.5)
    crass (1.0.4)
    database_cleaner (1.6.1)
    diff-lcs (1.3)
    docile (1.1.5)
    domain_name (0.5.20170404)
      unf (>= 0.0.5, < 1.0.0)
    draper (3.0.0)
      actionpack (~> 5.0)
      activemodel (~> 5.0)
      activemodel-serializers-xml (~> 1.0)
      activesupport (~> 5.0)
      request_store (~> 1.0)
    erubi (1.8.0)
    execjs (2.7.0)
    factory_girl (4.8.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.8.0)
      factory_girl (~> 4.8.0)
      railties (>= 3.0.0)
    faker (1.9.1)
      i18n (>= 0.7)
    ffi (1.9.25)
    foreman (0.84.0)
      thor (~> 0.19.1)
    formtastic_i18n (0.6.0)
    globalid (0.4.2)
      activesupport (>= 4.2.0)
    has_scope (0.7.1)
      actionpack (>= 4.1, < 5.2)
      activesupport (>= 4.1, < 5.2)
    http-cookie (1.0.3)
      domain_name (~> 0.5)
    i18n (1.6.0)
      concurrent-ruby (~> 1.0)
    inherited_resources (1.8.0)
      actionpack (>= 4.2, <= 5.2)
      has_scope (~> 0.6)
      railties (>= 4.2, <= 5.2)
      responders
    jquery-rails (4.3.3)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    json (2.1.0)
    jsonapi-renderer (0.1.2)
    kaminari (1.1.1)
      activesupport (>= 4.1.0)
      kaminari-actionview (= 1.1.1)
      kaminari-activerecord (= 1.1.1)
      kaminari-core (= 1.1.1)
    kaminari-actionview (1.1.1)
      actionview
      kaminari-core (= 1.1.1)
    kaminari-activerecord (1.1.1)
      activerecord
      kaminari-core (= 1.1.1)
    kaminari-core (1.1.1)
    launchy (2.4.3)
      addressable (~> 2.3)
    letter_opener (1.6.0)
      launchy (~> 2.2)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.2.3)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    mailgun_rails (0.9.0)
      actionmailer (>= 3.2.13)
      json (>= 1.7.7)
      rest-client (>= 1.6.7)
    method_source (0.8.2)
    mime-types (3.2.2)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2018.0812)
    mini_mime (1.0.1)
    mini_portile2 (2.4.0)
    minitest (5.11.3)
    netrc (0.11.0)
    nio4r (2.3.1)
    nokogiri (1.10.2)
      mini_portile2 (~> 2.4.0)
    parallel (1.12.0)
    parser (2.4.0.2)
      ast (~> 2.3)
    pg (0.21.0)
    powerpack (0.1.1)
    pry (0.10.4)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    pry-byebug (3.4.2)
      byebug (~> 9.0)
      pry (~> 0.10)
    public_suffix (3.0.2)
    puma (3.10.0)
    pundit (1.1.0)
      activesupport (>= 3.0.0)
    pundit-matchers (1.4.1)
      pundit (~> 1.1, >= 1.1.0)
      rspec-rails (>= 3.0.0)
    rack (2.0.7)
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (5.1.6.2)
      actioncable (= 5.1.6.2)
      actionmailer (= 5.1.6.2)
      actionpack (= 5.1.6.2)
      actionview (= 5.1.6.2)
      activejob (= 5.1.6.2)
      activemodel (= 5.1.6.2)
      activerecord (= 5.1.6.2)
      activesupport (= 5.1.6.2)
      bundler (>= 1.3.0)
      railties (= 5.1.6.2)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.0.4)
      loofah (~> 2.2, >= 2.2.2)
    railties (5.1.6.2)
      actionpack (= 5.1.6.2)
      activesupport (= 5.1.6.2)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rainbow (2.2.2)
      rake
    rake (12.3.2)
    ransack (2.1.1)
      actionpack (>= 5.0)
      activerecord (>= 5.0)
      activesupport (>= 5.0)
      i18n
    rb-fsevent (0.10.2)
    rb-inotify (0.9.10)
      ffi (>= 0.5.0, < 2)
    request_store (1.4.0)
      rack (>= 1.4)
    responders (2.4.0)
      actionpack (>= 4.2.0, < 5.3)
      railties (>= 4.2.0, < 5.3)
    rest-client (2.0.2)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 4.0)
      netrc (~> 0.8)
    rolify (5.1.0)
    rspec-core (3.6.0)
      rspec-support (~> 3.6.0)
    rspec-expectations (3.6.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.6.0)
    rspec-mocks (3.6.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.6.0)
    rspec-rails (3.6.1)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.6.0)
      rspec-expectations (~> 3.6.0)
      rspec-mocks (~> 3.6.0)
      rspec-support (~> 3.6.0)
    rspec-support (3.6.0)
    rubocop (0.51.0)
      parallel (~> 1.10)
      parser (>= 2.3.3.1, < 3.0)
      powerpack (~> 0.1)
      rainbow (>= 2.2.2, < 3.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (~> 1.0, >= 1.0.1)
    ruby-progressbar (1.9.0)
    ruby-saml (1.7.0)
      nokogiri (>= 1.5.10)
    ruby_dep (1.5.0)
    sass (3.7.4)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    shoulda-matchers (3.1.2)
      activesupport (>= 4.0.0)
    simplecov (0.13.0)
      docile (~> 1.1.0)
      json (>= 1.8, < 3)
      simplecov-html (~> 0.10.0)
    simplecov-html (0.10.2)
    slack-notifier (1.5.1)
    slop (3.6.0)
    smashing_docs (1.3.6)
    spring (2.0.2)
      activesupport (>= 4.2)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-es6 (0.9.2)
      babel-source (>= 5.8.11)
      babel-transpiler
      sprockets (>= 3.0.0)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    taperole (2.1.1)
      colorize (~> 0.8.1)
      slack-notifier (~> 1.5)
      thor (~> 0.19.1)
    thor (0.19.4)
    thread_safe (0.3.6)
    timecop (0.9.1)
    tzinfo (1.2.5)
      thread_safe (~> 0.1)
    uglifier (3.2.0)
      execjs (>= 0.3.0, < 3)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.5)
    unicode-display_width (1.3.0)
    web-console (3.5.1)
      actionview (>= 5.0)
      activemodel (>= 5.0)
      bindex (>= 0.4.0)
      railties (>= 5.0)
    websocket-driver (0.6.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.3)
    whenever (0.10.0)
      chronic (>= 0.6.3)

PLATFORMS
  ruby

DEPENDENCIES
  active_interaction
  active_model_serializers (~> 0.10.0)
  activeadmin!
  airbrake (~> 7.3)
  annotate
  awesome_print
  brakeman (~> 3.5)
  bundler-audit
  codeclimate-test-reporter (~> 1.0.0)
  database_cleaner
  draper
  factory_girl_rails
  faker
  foreman
  formtastic!
  inherited_resources (~> 1.7)
  kaminari
  letter_opener
  listen (>= 3.0.5, < 3.2)
  mailgun_rails
  pg
  pry-byebug
  puma (~> 3.7)
  pundit
  pundit-matchers (~> 1.4.1)
  rails (~> 5.1.3)
  ransack
  rolify
  rspec-rails
  rubocop
  ruby-saml
  shoulda-matchers
  simplecov
  smashing_docs
  spring
  spring-watcher-listen (~> 2.0.0)
  taperole (~> 2.0)
  timecop
  uglifier (>= 1.3.0)
  web-console (>= 3.3.0)
  whenever

BUNDLED WITH
   1.17.0
```

**Comment by dkniffin** [comment]
I was not able to reproduce this with a brand new rails 5.2.2 app. Next I'm going to try 5.1

**Comment by deivid-rodriguez** [comment]
Try installing your Gemfile on a local path `bundle install --path vendor/bundle`, and then look for ".coffee" files in there. Something must be triggering the sprockets autoload.

**Comment by deivid-rodriguez** [comment]
Also, maybe try clearing your cache? `bin/rake tmp:cache:clear` I think

**Comment by dkniffin** [comment]
Clearing the cache worked 💯Thank you! I'll have a PR coming your way for a new config option soon :)

**Comment by oskarpearson** [comment]
Thanks @deivid-rodriguez for this comment from 2019 :)

It helped me track down this issue https://github.com/activeadmin-plugins/active_admin_scoped_collection_actions/issues/42#issue-1898054039

I'm linking it here in case anyone else finds this issue when searching for `LoadError (cannot load such file -- coffee_script)` after upgrading to ActiveAdmin 3
