### ISSUE TITLE
throws error on rails assets:precompile -> PG::ConnectionBad: could not translate host name "postgres" to address: Name or service not known

### ISSUE THREAD

**Issue by srghma** [activeadmin/activeadmin#5737]
### How to reproduce

with 

```
  remote: https://github.com/activeadmin/activeadmin.git
  revision: 9303e131839a1b1f56b66a3d224081d8dc9cd33a

```

on

```
bundle exec rake assets:precompile
```

### Expected behavior

should not try to connect to postgres

### Actual behavior

it throws error 

```
Step 6/6 : RUN RAILS_ENV=production   RAKE_ENV=production   ASSET_HOST=https://api-stage.myapp-app.com   ACTION_CABLE_REDIS_URL=redis://dummy_redis:6380/1   SECRET_KEY_BASE=dummy   OAUTH_TOKEN_TTL_HOURS=42   SMTP_USER=dummy@gmail.com   SMTP_PASSWORD=dummy   DATABASE_URL=postgres://dummy_user:dummy_password@postgres:5432/dummy_db   CARRIER_WAVE_AWS_REGION=dummy   CARRIER_WAVE_AWS_ACCESS_KEY_ID=dummy   CARRIER_WAVE_AWS_SECRET_ACCESS_KEY=dummy   CARRIER_WAVE_FOG_DIRECTORY=dummy   bundle exec rake assets:precompile
 ---> Running in ac60d9e05a7a
rake aborted!
PG::ConnectionBad: could not translate host name "postgres" to address: Name or service not known
/usr/local/bundle/gems/pg-0.21.0/lib/pg.rb:56:in `initialize'
/usr/local/bundle/gems/pg-0.21.0/lib/pg.rb:56:in `new'
/usr/local/bundle/gems/pg-0.21.0/lib/pg.rb:56:in `connect'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_adapters/postgresql_adapter.rb:705:in `connect'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_adapters/postgresql_adapter.rb:229:in `initialize'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_adapters/postgresql_adapter.rb:46:in `new'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_adapters/postgresql_adapter.rb:46:in `postgresql_connection'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:761:in `new_connection'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:805:in `checkout_new_connection'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:784:in `try_to_checkout_new_connection'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:745:in `acquire_connection'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:502:in `checkout'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:376:in `connection'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:933:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_handling.rb:116:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-5.1.7/lib/active_record/connection_handling.rb:88:in `connection'
/usr/local/bundle/gems/activerecord-sortable-0.0.8/lib/activerecord/sortable/acts_as_sortable.rb:45:in `sortable_relation_provide_accessor_values'
/usr/local/bundle/gems/activerecord-sortable-0.0.8/lib/activerecord/sortable/acts_as_sortable.rb:21:in `acts_as_sortable'
/app/app/models/publication_site.rb:22:in `<class:PublicationSite>'
/app/app/models/publication_site.rb:15:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `require'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `block in require'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:258:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `require'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:379:in `block in require_or_load'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:36:in `block in load_interlock'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies/interlock.rb:11:in `loading'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:36:in `load_interlock'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:357:in `require_or_load'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:511:in `load_missing_constant'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:202:in `const_missing'
/app/app/admin/publication_site.rb:1:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:286:in `load'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:286:in `block in load'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:258:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:286:in `load'
/usr/local/bundle/bundler/gems/activeadmin-9303e131839a/lib/active_admin/application.rb:124:in `block in load'
/usr/local/bundle/bundler/gems/activeadmin-9303e131839a/lib/active_admin/error.rb:41:in `capture'
/usr/local/bundle/bundler/gems/activeadmin-9303e131839a/lib/active_admin/application.rb:124:in `load'
/usr/local/bundle/bundler/gems/activeadmin-9303e131839a/lib/active_admin/application.rb:116:in `block in load!'
/usr/local/bundle/bundler/gems/activeadmin-9303e131839a/lib/active_admin/application.rb:116:in `each'
/usr/local/bundle/bundler/gems/activeadmin-9303e131839a/lib/active_admin/application.rb:116:in `load!'
/usr/local/bundle/bundler/gems/activeadmin-9303e131839a/lib/active_admin/application.rb:142:in `routes'
/usr/local/bundle/bundler/gems/activeadmin-9303e131839a/lib/active_admin.rb:76:in `routes'
/app/config/routes.rb:4:in `block in <top (required)>'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:436:in `instance_exec'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:436:in `eval_block'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:418:in `draw'
/app/config/routes.rb:1:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:286:in `load'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:286:in `block in load'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:258:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:286:in `load'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/application/routes_reloader.rb:39:in `block in load_paths'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/application/routes_reloader.rb:39:in `each'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/application/routes_reloader.rb:39:in `load_paths'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/application/routes_reloader.rb:18:in `reload!'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/application/routes_reloader.rb:28:in `block in updater'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/file_update_checker.rb:81:in `execute'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/application/routes_reloader.rb:8:in `execute'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/application/finisher.rb:128:in `block in <module:Finisher>'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/initializable.rb:30:in `run'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/initializable.rb:59:in `block in run_initializers'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/initializable.rb:58:in `run_initializers'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/application.rb:353:in `initialize!'
/app/config/environment.rb:5:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `require'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `block in require'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:258:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `require'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/application.rb:329:in `require_environment!'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/application.rb:445:in `block in run_tasks_blocks'
/usr/local/bundle/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
/usr/local/bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/bundle:104:in `load'
/usr/local/bundle/bin/bundle:104:in `<main>'
Tasks: TOP => environment
(See full trace by running task with --trace)

```

### Temporary fix

```
  ACTIVE_ADMIN_DISABLE_ROUTE=true  bundle exec rake assets:precompile
```

```
# config/routes.rb
Rails.application.routes.draw do
  # fix issue
  # PG::ConnectionBad: could not translate host name "postgres" to address: Name or service not known
  # on rails assets:precompile
  ActiveAdmin.routes(self) if ENV["ACTIVE_ADMIN_DISABLE_ROUTE"] != "true"
end
```

### Probable cause

when I remove model file to make it throw error

```
~/projects/myapp-dockerfiles/myapp-backend   master ✚  rm app/models/publication_site.rb
rm: remove regular file 'app/models/publication_site.rb'? y
~/projects/myapp-dockerfiles/myapp-backend   master ●✚  ..
~/projects/myapp-dockerfiles   master ●✚  make build_be_with_deps
docker build \
       -t "myapp_be_with_deps" \
       -f docker/Dockerfiles/be_with_deps.Dockerfile myapp-backend
Sending build context to Docker daemon  2.381MB
Step 1/6 : FROM srghma/stretch-ruby24-postgres10-node9:latest
---> 3e7b167a79c2
Step 2/6 : WORKDIR /app
---> Using cache
---> f629955b4372
Step 3/6 : COPY Gemfile Gemfile.lock /app/
---> Using cache
---> c206514016f5
Step 4/6 : RUN bundle install --jobs 4
---> Using cache
---> 8abdb7ca4a2e
Step 5/6 : COPY . /app
---> ba5531d717da
Step 6/6 : RUN RAILS_ENV=production   RAKE_ENV=production   ASSET_HOST=https://api-stage.myappapp.com   ACTION_CABLE_REDIS_URL=redis://dummy_redis:6380/1   SECRET_KEY_BASE=dummy   OAUTH_TOKEN_TTL_HOURS=42   SMTP_USER=dummy@gmail.com   SMTP_PASSWORD=dummy   DATABASE_URL=postgres://dummy_user:dummy_password@postgres:5432/dummy_db   CARRIER_WAVE_AWS_REGION=dummy   CARRIER_WAVE_AWS_ACCESS_KEY_ID=dummy   CARRIER_WAVE_AWS_SECRET_ACCESS_KEY=dummy   CARRIER_WAVE_FOG_DIRECTORY=dummy   ACTIVE_ADMIN_DISABLE_ROUTE=true   bundle exec rake assets:precompile
---> Running in 861e51e83ef1
rake aborted!
NameError: uninitialized constant PublicationSite
/app/app/admin/publication_site.rb:1:in `<top (required)>'
/usr/local/bundle/bundler/gems/activeadmin-9303e131839a/lib/active_admin/application.rb:124:in `block in load'
/usr/local/bundle/bundler/gems/activeadmin-9303e131839a/lib/active_admin/error.rb:41:in `capture'
/usr/local/bundle/bundler/gems/activeadmin-9303e131839a/lib/active_admin/application.rb:124:in `load'
/usr/local/bundle/bundler/gems/activeadmin-9303e131839a/lib/active_admin/application.rb:116:in `block in load!'
/usr/local/bundle/bundler/gems/activeadmin-9303e131839a/lib/active_admin/application.rb:116:in `each'
/usr/local/bundle/bundler/gems/activeadmin-9303e131839a/lib/active_admin/application.rb:116:in `load!'
/usr/local/bundle/bundler/gems/activeadmin-9303e131839a/lib/active_admin/application.rb:142:in `routes'
/usr/local/bundle/bundler/gems/activeadmin-9303e131839a/lib/active_admin.rb:76:in `routes'
/app/config/routes.rb:7:in `block in <top (required)>'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:436:in `instance_exec'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:436:in `eval_block'
/usr/local/bundle/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:418:in `draw'
/app/config/routes.rb:1:in `<top (required)>'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/application/routes_reloader.rb:39:in `block in load_paths'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/application/routes_reloader.rb:39:in `each'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/application/routes_reloader.rb:39:in `load_paths'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/application/routes_reloader.rb:18:in `reload!'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/application/routes_reloader.rb:28:in `block in updater'
/usr/local/bundle/gems/activesupport-5.1.7/lib/active_support/file_update_checker.rb:81:in `execute'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/application/routes_reloader.rb:8:in `execute'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/application/finisher.rb:128:in `block in <module:Finisher>'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/initializable.rb:30:in `run'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/initializable.rb:59:in `block in run_initializers'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/initializable.rb:58:in `run_initializers'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/application.rb:353:in `initialize!'
/app/config/environment.rb:5:in `<top (required)>'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/application.rb:329:in `require_environment!'
/usr/local/bundle/gems/railties-5.1.7/lib/rails/application.rb:445:in `block in run_tasks_blocks'
/usr/local/bundle/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
/usr/local/bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/bundle:104:in `load'
/usr/local/bundle/bin/bundle:104:in `<main>'
Tasks: TOP => environment
(See full trace by running task with --trace)
The command '/bin/sh -c RAILS_ENV=production   RAKE_ENV=production   ASSET_HOST=https://api-stage.myappapp.com   ACTION_CABLE_REDIS_URL=redis://dummy_redis:6380/1   SECRET_KEY_BASE=dummy   OAUTH_TOKEN_TTL_HOURS=42   SMTP_USER=dummy@gmail.com   SMTP_PASSWORD=dummy   DATABASE_URL=postgres://dummy_user:dummy_password@postgres:5432/dummy_db   CARRIER_WAVE_AWS_REGION=dummy   CARRIER_WAVE_AWS_ACCESS_KEY_ID=dummy   CARRIER_WAVE_AWS_SECRET_ACCESS_KEY=dummy   CARRIER_WAVE_FOG_DIRECTORY=dummy   ACTIVE_ADMIN_DISABLE_ROUTE=true   bundle exec rake assets:precompile' returned a non-zero code: 1
make: *** [Makefile.d/common/build.mk:12: build_be_with_deps] Error 1
```

shows that error occurs somewhere at /lib/active_admin/application.rb:124

**Comment by varyonic** [comment]
Are you sure this is ActiveAdmin specific? See https://stackoverflow.com/questions/8997226/rake-assetsprecompile-attempting-to-connect-to-database and http://blog.zeit.io/use-a-fake-db-adapter-to-play-nice-with-rails-assets-precompilation/

**Comment by srghma** [comment]
@varyonic 

1. `config.assets.initialize_on_precompile = false` doesnt help
2. I think the activerecord-nulldb-adapter normally should not be used, this gem is more like last resort
3. as I said when I disable active_admin the error disappears

**Comment by longkt90** [comment]
I have a same problem with latest version of active admin, but it doesn't break assets precompile though, I can confirm that remove  `ActiveAdmin.routes(self)` in routes files make the error disappear. 

@srghma  `initialize_on_precompile` is no longer an option from rails 4. Rails by default don't connect to the database when precompiling assets but if your application load any code that does it will

**Comment by ernestoe** [comment]
Don't know how related this might be, but I just got a similar error when including a `filter` config in admin page such as:
```
filter :description, as: :select, collection: QualityError.distinct.pluck(:description)
```
If this line is commented... no error.

`nulldb` didn't work either.

**Comment by umbrellait-alexey-stroevskiy** [comment]
Hello everyone!
Are there any updates or solutions?
I get the same error until I delete the `collection`
`filter :some_filter, collection: User.some_scope`

**Comment by umbrellait-alexey-stroevskiy** [comment]
> Don't know how related this might be, but I just got a similar error when including a `filter` config in admin page such as:
> 
> ```
> filter :description, as: :select, collection: QualityError.distinct.pluck(:description)
> ```
> 
> If this line is commented... no error.
> 
> `nulldb` didn't work either.

Hello @ernestoe!
To fix this issue you need to use like this:
`filter :description, as: :select, collection: proc { QualityError.distinct.pluck(:description) }`
or 
`filter :description, as: :select, collection: proc { QualityError.distinct.map { |qe| [qe.description, qe.id] } }`
