### ISSUE TITLE
On install: 

### ISSUE THREAD

**Issue by erikhSSI** [activeadmin/activeadmin#6080]
### Did you find a bug?

Yes. Lots of error messages on first time installation on local development environment that:

- already has an existing /admin/ path in routes used with a pre-existing codebase (none of which should be touched by ActiveAdmin).   

- User model and Devise are already being used and working fine before activeadmin install

- Intending to install/use ActiveAdmin in path `/admin3/`

Following https://activeadmin.info/0-installation.html I did:

`$ rails g active_admin:install User`

So I suppose I should somehow have run the install defining a different path than 'admin'?  How?

(I have not done the `rake db:migrate` and `rake db:seed` steps yet.)

### My dev environment ###

Rail 5.0.6
 
$ ruby -v
ruby 2.4.9p362 (2019-10-02 revision 67824) [x86_64-linux]

### Expected behavior & Actual behavior

Install activeadmin with a list of files it added or modified, which it did, but it also spit out a bunch of error messages and I don't know what they mean.

Here is the full dump

```
$ rails g active_admin:install User
Running via Spring preloader in process 4986
      invoke  devise
    generate    No need to install devise, already done.
      invoke    active_record
      create      db/migrate/20200204141735_add_devise_to_users.rb
      insert      app/models/user.rb
       route    devise_for :users
        gsub    app/models/user.rb
        gsub    config/routes.rb
      append    db/seeds.rb
      create  config/initializers/active_admin.rb
      create  app/admin
      create  app/admin/dashboard.rb
      create  app/admin/users.rb
      insert  config/routes.rb
    generate  active_admin:assets
/home/vagrant/OURAPP/app/controllers/application_controller.rb:2:in `alias_method': undefined method `current_recruit' for class `ApplicationController' (NameError)
        from /home/vagrant/OURAPP/app/controllers/application_controller.rb:2:in `<class:ApplicationController>'
        from /home/vagrant/OURAPP/app/controllers/application_controller.rb:1:in `<top (required)>'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:477:in `load'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:477:in `block in load_file'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:662:in `new_constants_in'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:476:in `load_file'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:375:in `block in require_or_load'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:37:in `block in load_interlock'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/concurrency/share_lock.rb:150:in `exclusive'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies/interlock.rb:11:in `loading'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:37:in `load_interlock'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:358:in `require_or_load'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:511:in `load_missing_constant'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:203:in `const_missing'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/inflector/methods.rb:268:in `const_get'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/inflector/methods.rb:268:in `block in constantize'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/inflector/methods.rb:266:in `each'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/inflector/methods.rb:266:in `inject'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/inflector/methods.rb:266:in `constantize'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/devise-4.3.0/app/controllers/devise_controller.rb:2:in `<top (required)>'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:477:in `load'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:477:in `block in load_file'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:662:in `new_constants_in'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:476:in `load_file'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:375:in `block in require_or_load'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:37:in `block in load_interlock'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/concurrency/share_lock.rb:150:in `exclusive'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies/interlock.rb:11:in `loading'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:37:in `load_interlock'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:358:in `require_or_load'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:511:in `load_missing_constant'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:203:in `const_missing'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/devise-4.3.0/app/controllers/devise/sessions_controller.rb:1:in `<top (required)>'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:477:in `load'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:477:in `block in load_file'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:662:in `new_constants_in'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:476:in `load_file'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:375:in `block in require_or_load'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:37:in `block in load_interlock'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/concurrency/share_lock.rb:150:in `exclusive'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies/interlock.rb:11:in `loading'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:37:in `load_interlock'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:358:in `require_or_load'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:511:in `load_missing_constant'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:203:in `const_missing'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activeadmin-2.4.0/lib/active_admin/devise.rb:53:in `<module:Devise>'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activeadmin-2.4.0/lib/active_admin/devise.rb:6:in `<module:ActiveAdmin>'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activeadmin-2.4.0/lib/active_admin/devise.rb:5:in `<top (required)>'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `block in require'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
        from /home/vagrant/OURAPP/config/routes.rb:5:in `block in <top (required)>'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/routing/route_set.rb:391:in `instance_exec'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/routing/route_set.rb:391:in `eval_block'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/routing/route_set.rb:373:in `draw'
        from /home/vagrant/OURAPP/config/routes.rb:3:in `<top (required)>'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `load'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `block in load'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `load'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/railties-5.0.6/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/railties-5.0.6/lib/rails/application/routes_reloader.rb:40:in `each'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/railties-5.0.6/lib/rails/application/routes_reloader.rb:40:in `load_paths'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/railties-5.0.6/lib/rails/application/routes_reloader.rb:16:in `reload!'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/railties-5.0.6/lib/rails/application/routes_reloader.rb:26:in `block in updater'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/file_update_checker.rb:77:in `execute'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/railties-5.0.6/lib/rails/application/routes_reloader.rb:27:in `updater'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/railties-5.0.6/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/railties-5.0.6/lib/rails/application/finisher.rb:119:in `block in <module:Finisher>'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/railties-5.0.6/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/railties-5.0.6/lib/rails/initializable.rb:30:in `run'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/railties-5.0.6/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/2.4.0/tsort.rb:347:in `each'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/2.4.0/tsort.rb:347:in `call'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/railties-5.0.6/lib/rails/initializable.rb:54:in `run_initializers'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/railties-5.0.6/lib/rails/application.rb:352:in `initialize!'
        from /home/vagrant/OURAPP/config/environment.rb:5:in `<top (required)>'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `block in require'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:102:in `preload'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'
      create  db/migrate/20200204141745_create_active_admin_comments.rb
```

 

### How to reproduce

Now when I run

`$ rails c`

```
$ rails c
/home/vagrant/OURAPP/app/controllers/application_controller.rb:2:in `alias_method': undefined method `current_recruit' for class `ApplicationController' (NameError)
        from /home/vagrant/OURAPP/app/controllers/application_controller.rb:2:in `<class:ApplicationController>'
        from /home/vagrant/OURAPP/app/controllers/application_controller.rb:1:in `<top (required)>'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:477:in `load'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:477:in `block in load_file'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:662:in `new_constants_in'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:476:in `load_file'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:375:in `block in require_or_load'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:37:in `block in load_interlock'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
        from /home/vagrant/.rbenv/versions/2.4.9/lib/ruby/gems/2.4.0/gems/activesupport-5.0.6/lib/active_support/concurrency/share_lock.rb:150:in `exclusive'
```
[snip]

Thanks, looking forward to using ActiveAdmin!

**Comment by erikhSSI** [comment]
BTW, to be clear, when I said above that we already have /admin/ routes, I should add that:

- We do NOT have /app/admin/ in Rails
- But we DO have /app/views/admin/ and /app/controllers/admin/  and /app/helpers/admin/   in our Rails code  (and in /app/assets/ paths)

**Comment by erikhSSI** [comment]
I see that a file was created:

db/migrate/20200204141735_add_devise_to_users.rb

But we are already using devise with table users and want to use it.  So maybe I should have used

`rails g active_admin:install --skip-users`

or 

`rails g active_admin:install User --skip-users`

???

**Comment by erikhSSI** [comment]
BTW, the error above

`/home/vagrant/OURAPP/app/controllers/application_controller.rb:2:in `alias_method': undefined method `current_recruit' for class `ApplicationController' (NameError)`

refers to this line:
```
class ApplicationController < ActionController::Base
  alias_method :devise_current_recruit, :current_recruit
```

Which I guess is/was a bug in OURAPP (that I just fixed), but FWIW doesn't cause an error in our normal running of rails s/rails c.

## Overall question ##

So what to do at this point to get ActiveAdmin working?  

1.  I assume activeadmin was supposed to generate assets (and failed) -- that is what the original error seems to be saying.   Should I run the install routine again with different arguments?  Or am I only missing assets?  Maybe these?
```
app/assets/javascripts/active_admin.js
app/assets/stylesheets/active_admin.scss
```

2. Remove the migration to add devise to users (since we already use Users for admin users)

3. Correct routes.rb -- this was in the file twice... is that ok?
```
  devise_for :users, ActiveAdmin::Devise.config
ActiveAdmin.routes(self)
```

4. change namespace to use `admin3` (since we already use `admin`) following
https://activeadmin.info/1-general-configuration.html#namespaces

5. Maybe other than the missing assets I am ready to do the rake db:migrate and rake db:seed steps ?

6. And then Follow "Setting up your own AuthorizationAdapter" ?
https://activeadmin.info/13-authorization-adapter.html#setting-up-your-own-authorizationadapter
