### ISSUE TITLE
ActiveAdmin routes not working on production mode

### ISSUE THREAD

**Issue by omsoft** [activeadmin/activeadmin#6376]
I have a perfectly running ActiveAdmin application with Rails 6 on the development machine.

But, as soon as I switch to **production mode** (with RAILS_ENV=production rails s) and visit **/admin**, Rails doesn't seem to recognize ActiveAdmin routes anymore and leaves me with a standard 404 error page: "The page you were looking for doesn't exist."

screenshot: https://freeimage.host/i/dIneYF

Logs report this:

```
I, [2020-07-24T18:12:15.755637 #16044]  INFO -- : [ae708ad2-cb30-4247-889c-c8a39dbb3a01] Started GET "/admin" for 127.0.0.1 at 2020-07-24 18:12:15 +0200
F, [2020-07-24T18:12:15.756846 #16044] FATAL -- : [ae708ad2-cb30-4247-889c-c8a39dbb3a01]   
[ae708ad2-cb30-4247-889c-c8a39dbb3a01] ActionController::RoutingError (No route matches [GET] "/admin"):
[ae708ad2-cb30-4247-889c-c8a39dbb3a01]   
[ae708ad2-cb30-4247-889c-c8a39dbb3a01] actionpack (6.0.3) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
[ae708ad2-cb30-4247-889c-c8a39dbb3a01] actionpack (6.0.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[ae708ad2-cb30-4247-889c-c8a39dbb3a01] railties (6.0.3) lib/rails/rack/logger.rb:37:in `call_app'
[ae708ad2-cb30-4247-889c-c8a39dbb3a01] railties (6.0.3) lib/rails/rack/logger.rb:26:in `block in call'
[ae708ad2-cb30-4247-889c-c8a39dbb3a01] activesupport (6.0.3) lib/active_support/tagged_logging.rb:80:in `block in tagged'
[ae708ad2-cb30-4247-889c-c8a39dbb3a01] activesupport (6.0.3) lib/active_support/tagged_logging.rb:28:in `tagged'
[ae708ad2-cb30-4247-889c-c8a39dbb3a01] activesupport (6.0.3) lib/active_support/tagged_logging.rb:80:in `tagged'
[ae708ad2-cb30-4247-889c-c8a39dbb3a01] railties (6.0.3) lib/rails/rack/logger.rb:26:in `call'
[ae708ad2-cb30-4247-889c-c8a39dbb3a01] actionpack (6.0.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[ae708ad2-cb30-4247-889c-c8a39dbb3a01] request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
[ae708ad2-cb30-4247-889c-c8a39dbb3a01] actionpack (6.0.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
[ae708ad2-cb30-4247-889c-c8a39dbb3a01] rack (2.2.2) lib/rack/method_override.rb:24:in `call'
[ae708ad2-cb30-4247-889c-c8a39dbb3a01] rack (2.2.2) lib/rack/runtime.rb:22:in `call'
[ae708ad2-cb30-4247-889c-c8a39dbb3a01] activesupport (6.0.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[ae708ad2-cb30-4247-889c-c8a39dbb3a01] actionpack (6.0.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
[ae708ad2-cb30-4247-889c-c8a39dbb3a01] actionpack (6.0.3) lib/action_dispatch/middleware/static.rb:126:in `call'
[ae708ad2-cb30-4247-889c-c8a39dbb3a01] rack (2.2.2) lib/rack/sendfile.rb:110:in `call'
[ae708ad2-cb30-4247-889c-c8a39dbb3a01] actionpack (6.0.3) lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
[ae708ad2-cb30-4247-889c-c8a39dbb3a01] rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
[ae708ad2-cb30-4247-889c-c8a39dbb3a01] railties (6.0.3) lib/rails/engine.rb:527:in `call'
[ae708ad2-cb30-4247-889c-c8a39dbb3a01] puma (4.3.3) lib/puma/configuration.rb:228:in `call'
[ae708ad2-cb30-4247-889c-c8a39dbb3a01] puma (4.3.3) lib/puma/server.rb:682:in `handle_request'
[ae708ad2-cb30-4247-889c-c8a39dbb3a01] puma (4.3.3) lib/puma/server.rb:472:in `process_client'
[ae708ad2-cb30-4247-889c-c8a39dbb3a01] puma (4.3.3) lib/puma/server.rb:328:in `block in run'
[ae708ad2-cb30-4247-889c-c8a39dbb3a01] puma (4.3.3) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

I can't figure out why.. any idea?

**Comment by omsoft** [comment]
Solved. The problem was a mistype error on a constraint file.

In my routes I have:
```
constraints Admin::Subdomain do
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
end
```

Inside the _Admin::Subdomain_ class I check the subdomain and expect only certain kind of domain to activate the admin interface. The URL was incorrect and I didn't noticed it. :-)
