### ISSUE TITLE
incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by qx** [activeadmin/activeadmin#6407]
![player](https://user-images.githubusercontent.com/648406/91374621-2fc74080-e84b-11ea-8fcd-23beaf54e019.png)
![WX20200827-095515](https://user-images.githubusercontent.com/648406/91374747-76b53600-e84b-11ea-88ca-c2f41dfa325f.png)
![error](https://user-images.githubusercontent.com/648406/91374632-35248b00-e84b-11ea-8140-9721af4e01c6.png)

```
gem 'devise'
gem 'pg', '>= 0.18', '< 2.0'
gem "rolify"
gem 'cancancan' # or cancancan
gem 'activeadmin'
gem 'acts-as-taggable-on', '~> 6.0'

# Plus integrations with:
gem 'draper'
gem 'pundit'
# Use Puma as the app server
gem 'puma', '~> 4.1'
```
```
    activeadmin (2.7.0)
      arbre (~> 1.2, >= 1.2.1)
      formtastic (~> 3.1)
      formtastic_i18n (~> 0.4)
      inherited_resources (~> 1.7)
      jquery-rails (~> 4.2)
      kaminari (~> 1.0, >= 1.0.1)
      railties (>= 5.2, < 6.1)
      ransack (~> 2.1, >= 2.1.1)
      sassc-rails (~> 2.1)
      sprockets (>= 3.0, < 4.1)
    pg (1.2.3)
    pg (1.2.3-x64-mingw32)
    pg (1.2.3-x86-mingw32)
```
path: http://127.0.0.1:3000/admin/players

**Comment by qx** [comment]
I don't know what happened, it works after  4 hours later, maybe have relation with setting     `config.encoding = "utf-8"`
 in application.rb,and then insert new record to database fix this problem. not exactly

**Comment by senid231** [comment]
I had same situation with database in ascii

this error came and goes away unpredictable for some `id_column` statements on some index pages

**Comment by Fivell** [comment]
me too, finally we have an issue where we can share out backtrace with this error 😄

**Comment by deivid-rodriguez** [comment]
Uggh, I have no idea how to go about this or even try to reproduce it :grimacing:.

**Comment by senid231** [comment]
@deivid-rodriguez @Fivell here's bug report that reproduces an issue

```ruby
require "bundler/inline"
STDOUT.sync = true

gemfile(true) do
  source "https://rubygems.org"

  # Use local changes or ActiveAdmin master.
  if ENV["ACTIVE_ADMIN_PATH"]
    gem "activeadmin", path: ENV["ACTIVE_ADMIN_PATH"], require: false
  else
    gem "activeadmin", github: "activeadmin/activeadmin", require: false
  end

  # Change Rails version if necessary.
  gem "rails", "6.0.0"

  gem "sprockets", "3.7.2"
  gem "sassc-rails", "2.1.2"
  gem "pg"
end

require "active_record"

# postgres=# \l+ template_ascii
# List of databases
# -[ RECORD 1 ]-----+---------------
# Name              | template_ascii
# Owner             | postgres
# Encoding          | SQL_ASCII
# Collate           | en_US.UTF-8
# Ctype             | en_US.UTF-8
# Access privileges |
# Size              | 6298 kB
# Tablespace        | pg_default
# Description       |
system(%q{psql -p 5432 -c "DROP DATABASE IF EXISTS active_admin_ascii_bug;"})
system(%q{psql -p 5432 -c "CREATE DATABASE active_admin_ascii_bug WITH TEMPLATE template_ascii;"})
ActiveRecord::Base.establish_connection(
    adapter: 'postgresql',
    encoding: 'SQL_ASCII',
    database: 'active_admin_ascii_bug',
    pool: 10,
    port: 5432
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :active_admin_comments, force: true do |_t|
  end

  create_table :users, force: true do |t|
    t.string :full_name
  end
end

require "action_controller/railtie"
require "action_view/railtie"
require "active_admin"

class TestApp < Rails::Application
  config.root = __dir__
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_token = "secret_token"
  secrets.secret_key_base = "secret_key_base"

  config.eager_load = false
  config.logger = Logger.new(STDOUT)

  config.hosts = "www.example.com"
end

class ApplicationController < ActionController::Base
  include Rails.application.routes.url_helpers
end

class User < ActiveRecord::Base
end

ActiveAdmin.setup do |config|
  # Authentication disabled by default. Override if necessary.
  config.authentication_method = false
  config.current_user_method = false
end

Rails.application.initialize!

ActiveAdmin.register_page "Dashboard" do
  menu priority: 1, label: proc { I18n.t("active_admin.dashboard") }
  content do
    "Test Me"
  end
end

ActiveAdmin.register User do
end

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
end

require "minitest/autorun"
require "rack/test"
require "rails/test_help"

# Replace this with the code necessary to make your test fail.
class BugTest < ActionDispatch::IntegrationTest

  def test_admin_root_success?
    get admin_root_url
    assert_match "Test Me", response.body # has content
    assert_match "Users", response.body # has 'Your Models' in menu
    assert_response :success
  end

  def test_admin_users
    User.create! full_name: "John Doe"
    get admin_users_url
    assert_match "John Doe", response.body # has created row
    assert_response :success
  end

  def test_admin_user
    user = User.create! full_name: "John Doe"
    get admin_user_url(user.id)
    assert_match "John Doe", response.body # has created row
    assert_response :success
  end

  private

  def app
    Rails.application
  end
end
```

```
I, [2020-09-10T10:59:26.494220 #31234]  INFO -- : Started GET "/admin/users" for 127.0.0.1 at 2020-09-10 10:59:26 +0300
I, [2020-09-10T10:59:26.498398 #31234]  INFO -- : Processing by Admin::UsersController#index as HTML
I, [2020-09-10T10:59:26.505903 #31234]  INFO -- :   Rendering /home/senid/.rvm/gems/ruby-2.5.5@bug-report/bundler/gems/activeadmin-2c33e97d1128/app/views/active_admin/resource/index.html.arb
DEPRECATION WARNING: The asset "active_admin.css" is not present in the asset pipeline.Falling back to an asset that may be in the public folder.
This behavior is deprecated and will be removed.
To bypass the asset pipeline and preserve this behavior,
use the `skip_pipeline: true` option.
 (called from block (2 levels) in build_active_admin_head at /home/senid/.rvm/gems/ruby-2.5.5@bug-report/bundler/gems/activeadmin-2c33e97d1128/lib/active_admin/views/pages/base.rb:32)
DEPRECATION WARNING: The asset "active_admin.js" is not present in the asset pipeline.Falling back to an asset that may be in the public folder.
This behavior is deprecated and will be removed.
To bypass the asset pipeline and preserve this behavior,
use the `skip_pipeline: true` option.
 (called from block (2 levels) in build_active_admin_head at /home/senid/.rvm/gems/ruby-2.5.5@bug-report/bundler/gems/activeadmin-2c33e97d1128/lib/active_admin/views/pages/base.rb:41)
D, [2020-09-10T10:59:26.826591 #31234] DEBUG -- :    (0.7ms)  SELECT COUNT(*) FROM (SELECT 1 AS one FROM "users" LIMIT $1 OFFSET $2) subquery_for_count  [["LIMIT", 30], ["OFFSET", 0]]
D, [2020-09-10T10:59:26.829169 #31234] DEBUG -- :    (0.5ms)  SELECT COUNT(*) FROM (SELECT 1 AS one FROM "users" LIMIT $1 OFFSET $2) subquery_for_count  [["LIMIT", 30], ["OFFSET", 0]]
D, [2020-09-10T10:59:26.831555 #31234] DEBUG -- :    (0.4ms)  SELECT COUNT(*) FROM "users"
D, [2020-09-10T10:59:26.836081 #31234] DEBUG -- :    (0.4ms)  SELECT COUNT(*) FROM (SELECT 1 AS one FROM "users" LIMIT $1 OFFSET $2) subquery_for_count  [["LIMIT", 30], ["OFFSET", 0]]
D, [2020-09-10T10:59:26.839285 #31234] DEBUG -- :   User Load (0.6ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" desc LIMIT $1 OFFSET $2  [["LIMIT", 30], ["OFFSET", 0]]
I, [2020-09-10T10:59:26.842598 #31234]  INFO -- :   Rendered /home/senid/.rvm/gems/ruby-2.5.5@bug-report/bundler/gems/activeadmin-2c33e97d1128/app/views/active_admin/resource/index.html.arb (Duration: 336.6ms | Allocations: 301963)
I, [2020-09-10T10:59:26.843047 #31234]  INFO -- : Completed 500 Internal Server Error in 344ms (Allocations: 305601)


F, [2020-09-10T10:59:26.848073 #31234] FATAL -- :   
ActionView::Template::Error (Can not transliterate strings with ASCII-8BIT encoding):
    1: insert_tag renderer_for(:index)
  
activesupport (6.0.0) lib/active_support/inflector/transliterate.rb:67:in `transliterate'
activesupport (6.0.0) lib/active_support/inflector/transliterate.rb:123:in `parameterize'
activesupport (6.0.0) lib/active_support/core_ext/string/inflections.rb:196:in `parameterize'
activeadmin (2c33e97d1128) lib/active_admin/views/components/table_for.rb:151:in `initialize'
activeadmin (2c33e97d1128) lib/active_admin/views/components/table_for.rb:34:in `new'
activeadmin (2c33e97d1128) lib/active_admin/views/components/table_for.rb:34:in `column'
activeadmin (2c33e97d1128) lib/active_admin/views/index_as_table.rb:295:in `id_column'
arbre (1.3.0) lib/arbre/element.rb:178:in `method_missing'
activeadmin (2c33e97d1128) lib/active_admin/views/index_as_table.rb:260:in `block in default_table'
activeadmin (2c33e97d1128) lib/active_admin/views/index_as_table.rb:249:in `instance_exec'
activeadmin (2c33e97d1128) lib/active_admin/views/index_as_table.rb:249:in `block in build'
arbre (1.3.0) lib/arbre/element.rb:34:in `build'
arbre (1.3.0) lib/arbre/html/tag.rb:19:in `build'
activeadmin (2c33e97d1128) lib/active_admin/views/components/table_for.rb:21:in `build'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:28:in `block in build_tag'
arbre (1.3.0) lib/arbre/context.rb:93:in `with_current_arbre_element'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
activeadmin (2c33e97d1128) lib/active_admin/views/index_as_table.rb:254:in `table_for'
activeadmin (2c33e97d1128) lib/active_admin/views/index_as_table.rb:247:in `build'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
arbre (1.3.0) lib/arbre/context.rb:93:in `with_current_arbre_element'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
activeadmin (2c33e97d1128) lib/active_admin/views/pages/index.rb:140:in `block (2 levels) in render_index'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.3.0) lib/arbre/context.rb:93:in `with_current_arbre_element'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:14:in `div'
activeadmin (2c33e97d1128) lib/active_admin/views/pages/index.rb:139:in `block in render_index'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.3.0) lib/arbre/context.rb:93:in `with_current_arbre_element'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:14:in `paginated_collection'
activeadmin (2c33e97d1128) lib/active_admin/views/pages/index.rb:133:in `render_index'
activeadmin (2c33e97d1128) lib/active_admin/views/pages/index.rb:50:in `build_collection'
activeadmin (2c33e97d1128) lib/active_admin/views/pages/index.rb:28:in `block in main_content'
activeadmin (2c33e97d1128) lib/active_admin/views/pages/index.rb:38:in `wrap_with_batch_action_form'
activeadmin (2c33e97d1128) lib/active_admin/views/pages/index.rb:26:in `main_content'
activeadmin (2c33e97d1128) lib/active_admin/views/pages/base.rb:101:in `block (2 levels) in build_main_content_wrapper'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.3.0) lib/arbre/context.rb:93:in `with_current_arbre_element'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:14:in `div'
activeadmin (2c33e97d1128) lib/active_admin/views/pages/base.rb:100:in `block in build_main_content_wrapper'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.3.0) lib/arbre/context.rb:93:in `with_current_arbre_element'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:14:in `div'
activeadmin (2c33e97d1128) lib/active_admin/views/pages/base.rb:99:in `build_main_content_wrapper'
activeadmin (2c33e97d1128) lib/active_admin/views/pages/base.rb:83:in `block in build_page_content'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.3.0) lib/arbre/context.rb:93:in `with_current_arbre_element'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:14:in `div'
activeadmin (2c33e97d1128) lib/active_admin/views/pages/base.rb:82:in `build_page_content'
activeadmin (2c33e97d1128) lib/active_admin/views/pages/base.rb:59:in `block (2 levels) in build_page'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.3.0) lib/arbre/context.rb:93:in `with_current_arbre_element'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:14:in `div'
activeadmin (2c33e97d1128) lib/active_admin/views/pages/base.rb:55:in `block in build_page'
arbre (1.3.0) lib/arbre/context.rb:93:in `with_current_arbre_element'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
activeadmin (2c33e97d1128) lib/active_admin/views/pages/base.rb:54:in `build_page'
activeadmin (2c33e97d1128) lib/active_admin/views/pages/base.rb:9:in `build'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
arbre (1.3.0) lib/arbre/context.rb:93:in `with_current_arbre_element'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.3.0) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
activeadmin (2c33e97d1128) app/views/active_admin/resource/index.html.arb:2
arbre (1.3.0) lib/arbre/context.rb:46:in `instance_eval'
arbre (1.3.0) lib/arbre/context.rb:46:in `initialize'
activeadmin (2c33e97d1128) app/views/active_admin/resource/index.html.arb:1:in `new'
activeadmin (2c33e97d1128) app/views/active_admin/resource/index.html.arb:1
actionview (6.0.0) lib/action_view/base.rb:274:in `_run'
actionview (6.0.0) lib/action_view/template.rb:185:in `block in render'
activesupport (6.0.0) lib/active_support/notifications.rb:182:in `instrument'
actionview (6.0.0) lib/action_view/template.rb:386:in `instrument_render_template'
actionview (6.0.0) lib/action_view/template.rb:183:in `render'
actionview (6.0.0) lib/action_view/renderer/template_renderer.rb:59:in `block (2 levels) in render_template'
actionview (6.0.0) lib/action_view/renderer/abstract_renderer.rb:89:in `block in instrument'
activesupport (6.0.0) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.0) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.0) lib/active_support/notifications.rb:180:in `instrument'
actionview (6.0.0) lib/action_view/renderer/abstract_renderer.rb:88:in `instrument'
actionview (6.0.0) lib/action_view/renderer/template_renderer.rb:58:in `block in render_template'
actionview (6.0.0) lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
actionview (6.0.0) lib/action_view/renderer/template_renderer.rb:57:in `render_template'
actionview (6.0.0) lib/action_view/renderer/template_renderer.rb:13:in `render'
actionview (6.0.0) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
actionview (6.0.0) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
actionview (6.0.0) lib/action_view/rendering.rb:118:in `block in _render_template'
actionview (6.0.0) lib/action_view/base.rb:304:in `in_rendering_context'
actionview (6.0.0) lib/action_view/rendering.rb:117:in `_render_template'
actionpack (6.0.0) lib/action_controller/metal/streaming.rb:219:in `_render_template'
actionview (6.0.0) lib/action_view/rendering.rb:103:in `render_to_body'
actionpack (6.0.0) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (6.0.0) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (6.0.0) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (6.0.0) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (6.0.0) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (6.0.0) lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
/home/senid/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
activesupport (6.0.0) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (6.0.0) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (6.0.0) lib/action_controller/metal/instrumentation.rb:85:in `cleanup_view_runtime'
actionpack (6.0.0) lib/action_controller/metal/instrumentation.rb:43:in `render'
responders (3.0.1) lib/action_controller/responder.rb:240:in `default_render'
responders (3.0.1) lib/action_controller/responder.rb:172:in `to_html'
responders (3.0.1) lib/responders/flash_responder.rb:109:in `to_html'
responders (3.0.1) lib/action_controller/responder.rb:165:in `respond'
responders (3.0.1) lib/action_controller/responder.rb:158:in `call'
responders (3.0.1) lib/action_controller/respond_with.rb:213:in `respond_with'
inherited_resources (1.11.0) lib/inherited_resources/actions.rb:7:in `index'
activeadmin (2c33e97d1128) lib/active_admin/resource_controller/streaming.rb:12:in `index'
actionpack (6.0.0) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.0) lib/abstract_controller/base.rb:196:in `process_action'
actionpack (6.0.0) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.0) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.0) lib/active_support/callbacks.rb:135:in `run_callbacks'
actionpack (6.0.0) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.0) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.0) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.0) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.0) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.0) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.0) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.0) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
actionpack (6.0.0) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.0) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.0) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (6.0.0) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (6.0.0) lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
actionpack (6.0.0) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.0) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.0) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.0) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.0) lib/action_dispatch/routing/route_set.rb:837:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (6.0.0) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/cookies.rb:648:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.0) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.0) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.0) lib/rails/rack/logger.rb:28:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
railties (6.0.0) lib/rails/engine.rb:526:in `call'
rack-test (1.1.0) lib/rack/mock_session.rb:29:in `request'
rack-test (1.1.0) lib/rack/test.rb:266:in `process_request'
rack-test (1.1.0) lib/rack/test.rb:119:in `request'
actionpack (6.0.0) lib/action_dispatch/testing/integration.rb:270:in `process'
actionpack (6.0.0) lib/action_dispatch/testing/integration.rb:18:in `get'
actionpack (6.0.0) lib/action_dispatch/testing/integration.rb:357:in `block (2 levels) in <module:Runner>'
active_admin_ascii_bug.rb:109:in `test_admin_users'
```

**Comment by senid231** [comment]
here's the root of problem

```ruby
0> User.human_attribute_name(User.primary_key)
=> "Id"

0> User.human_attribute_name(User.primary_key).encoding
=> #<Encoding:ASCII-8BIT>

0> ActiveSupport::Inflector.transliterate User.human_attribute_name(User.primary_key)
=> Can not transliterate strings with ASCII-8BIT encoding
```

**Comment by deivid-rodriguez** [comment]
Nice investigation @senid231, thanks!

I tried to run the repro, but I can't get it to succeed since I can't create a DB with SQL_ASCII encoding on my system :grimacing:. It will keep telling me that it doesn't match my system's i18n configuration.

```
ERROR:  la codificación «SQL_ASCII» no coincide con la configuración regional «es_ES.UTF-8»
DETAIL:  El parámetro LC_CTYPE escogido requiere la codificación «UTF8».
```

Also, I can't seem to get the raw errors in English (I tried LC_ALL=C, LANG=C, and similar, but no luck). Anyways, that's another story.

I'm unsure what we should do here, we could use `force_encoding("UTF-8")`, but I'm guessing if people are using "binary encodings" such as `SQL_ASCII` the reason is probably that they don't know the encoding of their data or that they have a weird encoding mix, so assuming "UTF-8" seems wrong. Should we instead encode the string as UTF-8, replacing or ignoring any invalid stuff?

I'm guessing this is a problem all through your apps whenever you `parameterize` or `transliterate` stuff from the DB, right? What solution are you using in other places?

**Comment by javierjulio** [comment]
To confirm, is the database with the issue using SQL_ASCII encoding or was that to force an error in the repro? I'm not familiar with this but anything I find is about converting a SQL_ASCII database to one using UTF-8 instead. Are you sure this is not related to the database configuration instead of it being an ActiveAdmin issue? 

What else I can make out is that there is no exact conversion between SQL_ASCII and UTF-8 and you'd have to use the appropriate SQL method to convert to desired encoding. Further, Postgres doesn't suggest using SQL_ASCII either.

> The SQL_ASCII setting behaves considerably differently from the other settings. When the server character set is SQL_ASCII, the server interprets byte values 0-127 according to the ASCII standard, while byte values 128-255 are taken as uninterpreted characters. No encoding conversion will be done when the setting is SQL_ASCII. Thus, this setting is not so much a declaration that a specific encoding is in use, as a declaration of ignorance about the encoding. In most cases, if you are working with any non-ASCII data, it is unwise to use the SQL_ASCII setting because PostgreSQL will be unable to help you by converting or validating non-ASCII characters.

**Comment by Fivell** [comment]
https://github.com/rails/rails/blob/6af50a90671e0a713da929bf83ec641f4552335e/activesupport/lib/active_support/inflector/transliterate.rb#L8
