### ISSUE TITLE
private method `redirect_to' called for #<ActiveAdmin::Devise::SessionsController:0x000055b0814934c8> Did you mean? redirect_back

### ISSUE THREAD

**Issue by mhenrixon** [activeadmin/activeadmin#6442]
### Did you find a bug?

I believe I have found some type of bug. It is hard to say exactly what is going wrong. I have a couple of difference scenarios. In the documentation it says to use a `before_action :set_admin_locale` to manage locale for activeadmin. 

```ruby
def set_admin_locale
  I18n.locale = admin_request? ? :en : :de
end
```

The problem is that a before_action actually changes a global setting which affects the tests of other parts of the code base. From what I can tell we want an `around_action :set_admin_locale` that takes the block that is the action and we then use to scope the action on a per request basis.

```ruby
def set_admin_locale(&action) # rubocop:disable Naming/AccessorMethodName
  locale = admin_request? ? :en : :de

  I18n.with_locale(locale, &action)
end
```

After signing in as an admin user I have this specific error.

```
 vendor/bundle/ruby/2.6.0/gems/responders-3.0.1/lib/action_controller/responder.rb:147:in `redirect_to': private method `redirect_to' called for #<ActiveAdmin::Devise::SessionsController:0x0000562f625f8e70>
 Did you mean?  redirect_back (NoMethodError)
     from vendor/bundle/ruby/2.6.0/gems/responders-3.0.1/lib/action_controller/responder.rb:207:in `navigation_behavior'
     from vendor/bundle/ruby/2.6.0/gems/responders-3.0.1/lib/action_controller/responder.rb:174:in `rescue in to_html'
     from vendor/bundle/ruby/2.6.0/gems/responders-3.0.1/lib/action_controller/responder.rb:171:in `to_html'
     from vendor/bundle/ruby/2.6.0/gems/responders-3.0.1/lib/action_controller/responder.rb:165:in `respond'
     from vendor/bundle/ruby/2.6.0/gems/responders-3.0.1/lib/action_controller/responder.rb:158:in `call'
     from vendor/bundle/ruby/2.6.0/gems/responders-3.0.1/lib/action_controller/respond_with.rb:213:in `respond_with'
     from vendor/bundle/ruby/2.6.0/gems/devise-4.7.2/app/controllers/devise/sessions_controller.rb:23:in `create'
     from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
     from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/abstract_controller/base.rb:194:in `process_action'
     from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
     from vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `block in instrument'
     from vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
     from vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `instrument'
     from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
     from vendor/bundle/ruby/2.6.0/gems/ddtrace-0.37.0/lib/ddtrace/contrib/action_pack/action_controller/instrumentation.rb:118:in `process_action'
     from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/rendering.rb:30:in `process_action'
     from vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.4/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
     from vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
     from vendor/bundle/ruby/2.6.0/gems/react-rails-2.6.1/lib/react/rails/controller_lifecycle.rb:31:in `use_react_component_helper'
     from vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
     from vendor/bundle/ruby/2.6.0/gems/i18n-0.9.5/lib/i18n.rb:268:in `with_locale'
     from app/controllers/application_controller.rb:118:in `set_admin_locale'


Caused by: vendor/bundle/ruby/2.6.0/gems/actionview-5.2.4.4/lib/action_view/path_set.rb:48:in `find': Missing template active_admin/devise/sessions/create, devise/sessions/create, devise/create, application/create with {:locale=>[:en, :de], :formats=>[:html], :variants=>[:arbeitnehmersteuererklaerung], :handlers=>[:raw, :erb, :html, :builder, :ruby, :arb, :coffee]}. Searched in:
  * "/app/app/views"
  * "/app/vendor/bundle/ruby/2.6.0/gems/devise-4.7.2/app/views"
  * "/app/vendor/bundle/ruby/2.6.0/gems/activeadmin-2.8.0/app/views"
  * "/app/vendor/bundle/ruby/2.6.0/gems/kaminari-core-1.2.1/app/views"
  * "/app/vendor/bundle/ruby/2.6.0/gems/ablab-0.4.2/app/views"
 (ActionView::MissingTemplate)
```

It seems that the `include ActionController::MimeResponds` is somehow private in the devise/session_controller.rb

```ruby
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end
````

### Expected behavior

I expect to be redirected to the correct `after_sign_in_path_for`

### Actual behavior

A `NoMethodError` is raised

### How to reproduce

The problem is that I don't know what is going wrong, is it code loading order? 

I have the following configuration:

```ruby
# config/initializers/devise.rb
Devise.setup do |config|
  config.parent_controller = 'ApplicationController'
  config.mailer_sender = 'tech@email.com'
  require 'devise/orm/active_record'
  config.case_insensitive_keys = [:email]
  config.strip_whitespace_keys = [:email]
  config.skip_session_storage = [:http_auth]
  config.stretches = Rails.env.test? ? 1 : 11
  config.reconfirmable = true
  config.expire_all_remember_me_on_sign_out = true
  config.password_length = 6..128
  config.email_regexp = /\A[^@\s]+@[^@\s]+\z/
  config.reset_password_within = 6.hours
  config.sign_out_via = :delete
  config.sign_in_after_change_password = true
end
```

```ruby
# config/initializers/active_admin.rb
ActiveAdmin.setup do |config|
  config.default_namespace = :backoffice
  config.around_action :set_admin_locale

  config.namespace :backoffice do |ns_config|
    ns_config.site_title = 'My title'
    ns_config.authorization_adapter = AdminAuthorization
    ns_config.download_links = false
    ns_config.comments = true
    ns_config.route_options = {
      constraints: lambda { |request|
        ENV['BACKOFFICE_DOMAIN'].nil? || request.host == ENV['BACKOFFICE_DOMAIN']
      },
    }
  end

  config.namespace :affiliate_admin do |ns_config|
    ns_config.site_title = 'Affiliate'
    ns_config.authorization_adapter = AffiliateAdminAuthorization
    ns_config.comments = false
    ns_config.download_links = false
    ns_config.route_options = {
      constraints: lambda { |request|
        ENV['BACKOFFICE_DOMAIN'].nil? || request.host == ENV['BACKOFFICE_DOMAIN']
      },
    }
  end

  config.authentication_method = :authenticate_admin_user!
  config.on_unauthorized_access = :redirect_unauthorized_admin_access
  config.current_user_method = :current_admin_user
  config.logout_link_path = :destroy_admin_user_session_path
  config.batch_actions = true
  config.filter_attributes = %i[encrypted_password password password_confirmation]
  config.localize_format = :long
  config.favicon = "#{ENV['RAILS_RELATIVE_URL_ROOT']}/admin-favicon.ico"
end
```

**Gem versions:**

- Rails 5.2.4.4
- Devise 4.7.2
- ActiveAdmin 2.8.0

Let me know if there is any information that I can provide to help:

**EDIT:**

I found this https://stackoverflow.com/questions/56573533/active-admin-resources-missing-template-after-upgrade-to-v1-1-0 but I'm not sure what to make of this considering this is not a controller I have defined.

**Comment by mhenrixon** [comment]
When placing this in an initializer it works like I would have expected and no errors are thrown:

```ruby
class ActiveAdmin::Devise::SessionsController # rubocop:disable Style/ClassAndModuleChildren
  include ActionController::MimeResponds

  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)

    yield resource if block_given?

    redirect_to after_sign_in_path_for(resource)
  end
end
```
