### ISSUE TITLE
undefined local variable or method `current_user'

### ISSUE THREAD

**Issue by heaven** [activeadmin/activeadmin#6831]
I have the following in `initializers/rails_admin.rb`:
```
config.authorization_adapter = ActiveAdmin::CanCanAdapter
config.cancan_ability_class = "Ability"
config.current_user_method = :current_admin
```
When adding a link in `table_for` and trying to check `can? :destroy, seat` getting this error:
```
cancancan (3.2.1) lib/cancan/controller_additions.rb:354:in `current_ability'
cancancan (3.2.1) lib/cancan/controller_additions.rb:377:in `can?'
cancancan (3.2.1) lib/cancan/controller_additions.rb:298:in `can?'
arbre (1.4.0) lib/arbre/element.rb:182:in `method_missing'
app/admin/organizations.rb:45:in `block (6 levels) in <main>'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.4.0) lib/arbre/context.rb:93:in `with_current_arbre_element'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:14:in `div'
app/admin/organizations.rb:43:in `block (5 levels) in <main>'
activeadmin (2.9.0) lib/active_admin/view_helpers/display_helper.rb:58:in `find_value'
activeadmin (2.9.0) lib/active_admin/view_helpers/display_helper.rb:45:in `format_attribute'
activeadmin (2.9.0) lib/active_admin/views/components/table_for.rb:102:in `block in build_table_cell'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.4.0) lib/arbre/context.rb:93:in `with_current_arbre_element'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:14:in `td'
activeadmin (2.9.0) lib/active_admin/views/components/table_for.rb:101:in `build_table_cell'
activeadmin (2.9.0) lib/active_admin/views/components/table_for.rb:45:in `block (2 levels) in column'
```

**Comment by heaven** [comment]
I've figured out that I can use `authorized? :destroy, seat`, which works fine.

**Comment by deivid-rodriguez** [comment]
Should I close this, then?

**Comment by heaven** [comment]
Hi @deivid-rodriguez, I think so, if that's the correct use of the `authorized?`. I didn't find it in the docs and guides.
