### ISSUE TITLE
ActionController::InvalidAuthenticityToken

### ISSUE THREAD

**Issue by interpegasus** [activeadmin/activeadmin#6882]
### Did you find a bug?
After upgrading **rails**, **activeadmin**, and **devise** to latest versions, the following error is returned on login screen. Right after pressing the login button:
`ActionController::InvalidAuthenticityToken`

### Expected behavior
Login should work as usual

### Actual behavior

`{"status":500,"exception_message":"ActionController::InvalidAuthenticityToken","exception_backtrace":["/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_controller/metal/request_forgery_protection.rb:211:in `handle_unverified_request'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_controller/metal/request_forgery_protection.rb:243:in `handle_unverified_request'","/home/ubuntu/.rvm/gems/ruby-2.6.1/bundler/gems/devise-e8e0c275999d/lib/devise/controllers/helpers.rb:255:in `handle_unverified_request'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_controller/metal/request_forgery_protection.rb:238:in `verify_authenticity_token'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:427:in `block in make_lambda'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in \u003cmodule:Callbacks\u003e'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:199:in `block in halting'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:512:in `block in invoke_before'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:512:in `each'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:512:in `invoke_before'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:115:in `block in run_callbacks'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:137:in `run_callbacks'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/abstract_controller/callbacks.rb:41:in `process_action'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_controller/metal/rescue.rb:22:in `process_action'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/activesupport-6.1.3.1/lib/active_support/notifications.rb:203:in `block in instrument'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/activesupport-6.1.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/activesupport-6.1.3.1/lib/active_support/notifications.rb:203:in `instrument'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_controller/metal/instrumentation.rb:33:in `process_action'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/activerecord-6.1.3.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/abstract_controller/base.rb:165:in `process'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionview-6.1.3.1/lib/action_view/rendering.rb:39:in `process'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_controller/metal.rb:190:in `dispatch'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_controller/metal.rb:254:in `dispatch'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_dispatch/routing/route_set.rb:33:in `serve'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_dispatch/routing/mapper.rb:19:in `block in \u003cclass:Constraints\u003e'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_dispatch/routing/mapper.rb:49:in `serve'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_dispatch/journey/router.rb:50:in `block in serve'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_dispatch/journey/router.rb:32:in `each'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_dispatch/journey/router.rb:32:in `serve'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_dispatch/routing/route_set.rb:842:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/rack/browser_monitoring.rb:33:in `traced_call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_dispatch/http/permissions_policy.rb:22:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_dispatch/http/content_security_policy.rb:18:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/cookies.rb:689:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/activesupport-6.1.3.1/lib/active_support/callbacks.rb:98:in `run_callbacks'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/executor.rb:14:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/railties-6.1.3.1/lib/rails/rack/logger.rb:37:in `call_app'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/railties-6.1.3.1/lib/rails/rack/logger.rb:26:in `block in call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/activesupport-6.1.3.1/lib/active_support/tagged_logging.rb:99:in `block in tagged'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/activesupport-6.1.3.1/lib/active_support/tagged_logging.rb:37:in `tagged'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/activesupport-6.1.3.1/lib/active_support/tagged_logging.rb:99:in `tagged'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/railties-6.1.3.1/lib/rails/rack/logger.rb:26:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/sprockets-rails-3.2.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/request_id.rb:26:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/activesupport-6.1.3.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/executor.rb:14:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/static.rb:24:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/actionpack-6.1.3.1/lib/action_dispatch/middleware/host_authorization.rb:92:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/webpacker-5.2.1/lib/webpacker/dev_server_proxy.rb:25:in `perform_request'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/railties-6.1.3.1/lib/rails/engine.rb:539:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/newrelic_rpm-6.15.0/lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/puma-5.2.2/lib/puma/configuration.rb:248:in `call'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/puma-5.2.2/lib/puma/request.rb:76:in `block in handle_request'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/puma-5.2.2/lib/puma/thread_pool.rb:337:in `with_force_shutdown'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/puma-5.2.2/lib/puma/request.rb:75:in `handle_request'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/puma-5.2.2/lib/puma/server.rb:431:in `process_client'","/home/ubuntu/.rvm/gems/ruby-2.6.1/gems/puma-5.2.2/lib/puma/thread_pool.rb:145:in `block in spawn_thread'"],"request":"http://dev.myserver.com:8080/admin/login","email_sent":false}`

### How to reproduce
Upgrading **rails**, **activeadmin**, and **devise** to latest versions

**Comment by interpegasus** [comment]
Gemfile

```
# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

ruby '2.6.1'
gem 'rails', '~>6.1.3'

gem 'active_material'
gem 'activeadmin', git: "https://github.com/activeadmin/activeadmin"
gem 'aws-sdk-s3'
gem "best_in_place", git: "https://github.com/mmotherwell/best_in_place"
gem 'colorize'
gem 'country_select'
gem 'coffee-rails'
gem 'devise', git: "https://github.com/heartcombo/devise"
gem 'execjs'
gem 'fcm'
gem 'figaro'
gem 'font-awesome-sass'
gem 'foundation-rails'
gem 'geocoder'
gem 'httparty'
gem 'imgkit'
gem 'inherited_resources'
gem 'jquery-fileupload-rails'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'mailgun-ruby'
gem 'newrelic_rpm'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'paperclip'
gem 'paypal-sdk-merchant'
gem 'pg'
gem 'rabl'
gem 'rack-ssl-enforcer'
gem 'rails-jquery-autocomplete'
gem 'ransack'
gem 'react-rails'
gem 'redis-rails'
gem 'rest-client'
gem 'rubocop'
gem 'sass-rails'
gem 'shortener'
gem 'sidekiq'
gem 'sidekiq-failures'
gem 'sidekiq-uniq'
gem "sidekiq-cron"
gem 'therubyracer'
gem 'timezone'
gem 'turbolinks'
gem 'twitter'
gem 'twitter-text'
gem 'tzinfo-data'
gem 'yt'
gem "passenger"
gem "webpacker"
gem 'uglifier'

group :development, :test do
  gem 'sqlite3'
  gem 'puma'
  gem 'bundle'
  gem 'byebug', platform: :mri
  gem 'faker'
  gem 'listen'
  gem 'railroady'
  gem 'rubocop-performance'
  gem 'solargraph'
  gem 'spring'
  gem 'spring-watcher-listen'
end
```

**Comment by interpegasus** [comment]
<img width="650" alt="Screen Shot 2021-03-31 at 4 03 48 PM" src="https://user-images.githubusercontent.com/934795/113211957-c3c31580-923b-11eb-86f4-7301b68182ca.png">

**Comment by interpegasus** [comment]
In case it helps anyone. Just Solved via:
**Gemfile**
`gem 'rack',"2.2.2"`
**Terminal**
`$ bundle update`
Now it works as expected
