### ISSUE TITLE
Activeadmin 2.9.0 has incompatibilities Rails 6.1.3.2: polymorphic routes

### ISSUE THREAD

**Issue by bdezonia** [activeadmin/activeadmin#6950]
I have an activeadmin 2.9.0 app running on rails 6.1.3.1 just fine. When I upgrade to rails 6.1.3.2 (released two days ago) my tests start failing throwing exceptions.

Error message:

Showing /home/bdezonia/.rvm/gems/ruby-2.7.3@corrie/gems/activeadmin-2.9.0/app/views/active_admin/resource/index.html.arb where line #2 raised: 

Please use symbols for polymorphic route arguments.

Trace:

```
actionpack (6.1.3.2) lib/action_dispatch/routing/polymorphic_routes.rb:295:in `block in handle_list'
actionpack (6.1.3.2) lib/action_dispatch/routing/polymorphic_routes.rb:290:in `map'
actionpack (6.1.3.2) lib/action_dispatch/routing/polymorphic_routes.rb:290:in `handle_list'
actionpack (6.1.3.2) lib/action_dispatch/routing/polymorphic_routes.rb:218:in `polymorphic_method'
actionpack (6.1.3.2) lib/action_dispatch/routing/polymorphic_routes.rb:139:in `polymorphic_path'
activeadmin (2.9.0) lib/active_admin/resource_controller/polymorphic_routes.rb:12:in `polymorphic_path'
actionpack (6.1.3.2) lib/action_dispatch/routing/polymorphic_routes.rb:165:in `polymorphic_path_for_action'
actionpack (6.1.3.2) lib/action_dispatch/routing/polymorphic_routes.rb:154:in `new_polymorphic_path'
inherited_resources (1.12.0) lib/inherited_resources/url_helpers.rb:237:in `block in define_helper_method'
inherited_resources (1.12.0) app/controllers/inherited_resources/base.rb:25:in `new_resource_path'
arbre (1.4.0) lib/arbre/element.rb:182:in `method_missing'
activeadmin (2.9.0) lib/active_admin/resource/action_items.rb:69:in `block in add_default_new_action_item'
activeadmin (2.9.0) lib/active_admin/views/action_items.rb:9:in `instance_exec'
activeadmin (2.9.0) lib/active_admin/views/action_items.rb:9:in `block (2 levels) in build'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.4.0) lib/arbre/context.rb:93:in `with_current_arbre_element'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:14:in `span'
activeadmin (2.9.0) lib/active_admin/views/action_items.rb:8:in `block in build'
activeadmin (2.9.0) lib/active_admin/views/action_items.rb:7:in `each'
activeadmin (2.9.0) lib/active_admin/views/action_items.rb:7:in `build'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
arbre (1.4.0) lib/arbre/context.rb:93:in `with_current_arbre_element'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
activeadmin (2.9.0) lib/active_admin/views/title_bar.rb:50:in `build_action_items'
activeadmin (2.9.0) lib/active_admin/views/title_bar.rb:24:in `block in build_titlebar_right'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.4.0) lib/arbre/context.rb:93:in `with_current_arbre_element'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:14:in `div'
activeadmin (2.9.0) lib/active_admin/views/title_bar.rb:23:in `build_titlebar_right'
activeadmin (2.9.0) lib/active_admin/views/title_bar.rb:10:in `build'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
arbre (1.4.0) lib/arbre/context.rb:93:in `with_current_arbre_element'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:14:in `title_bar'
activeadmin (2.9.0) lib/active_admin/views/pages/base.rb:58:in `block (2 levels) in build_page'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.4.0) lib/arbre/context.rb:93:in `with_current_arbre_element'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:14:in `div'
activeadmin (2.9.0) lib/active_admin/views/pages/base.rb:55:in `block in build_page'
arbre (1.4.0) lib/arbre/context.rb:93:in `with_current_arbre_element'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
activeadmin (2.9.0) lib/active_admin/views/pages/base.rb:54:in `build_page'
activeadmin (2.9.0) lib/active_admin/views/pages/base.rb:9:in `build'
activeadmin_addons (1.7.1) lib/activeadmin_addons/active_admin_config.rb:5:in `build'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
arbre (1.4.0) lib/arbre/context.rb:93:in `with_current_arbre_element'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.4.0) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
activeadmin (2.9.0) app/views/active_admin/resource/index.html.arb:2
arbre (1.4.0) lib/arbre/context.rb:46:in `instance_eval'
arbre (1.4.0) lib/arbre/context.rb:46:in `initialize'
activeadmin (2.9.0) app/views/active_admin/resource/index.html.arb:1:in `new'
activeadmin (2.9.0) app/views/active_admin/resource/index.html.arb:1
actionview (6.1.3.2) lib/action_view/base.rb:247:in `public_send'
actionview (6.1.3.2) lib/action_view/base.rb:247:in `_run'
actionview (6.1.3.2) lib/action_view/template.rb:154:in `block in render'
activesupport (6.1.3.2) lib/active_support/notifications.rb:205:in `instrument'
actionview (6.1.3.2) lib/action_view/template.rb:345:in `instrument_render_template'
actionview (6.1.3.2) lib/action_view/template.rb:152:in `render'
actionview (6.1.3.2) lib/action_view/renderer/template_renderer.rb:61:in `block (2 levels) in render_template'
activesupport (6.1.3.2) lib/active_support/notifications.rb:203:in `block in instrument'
activesupport (6.1.3.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.1.3.2) lib/active_support/notifications.rb:203:in `instrument'
actionview (6.1.3.2) lib/action_view/renderer/template_renderer.rb:56:in `block in render_template'
actionview (6.1.3.2) lib/action_view/renderer/template_renderer.rb:75:in `render_with_layout'
actionview (6.1.3.2) lib/action_view/renderer/template_renderer.rb:55:in `render_template'
actionview (6.1.3.2) lib/action_view/renderer/template_renderer.rb:11:in `render'
actionview (6.1.3.2) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
actionview (6.1.3.2) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
actionview (6.1.3.2) lib/action_view/rendering.rb:117:in `block in _render_template'
actionview (6.1.3.2) lib/action_view/base.rb:273:in `in_rendering_context'
actionview (6.1.3.2) lib/action_view/rendering.rb:116:in `_render_template'
actionpack (6.1.3.2) lib/action_controller/metal/streaming.rb:218:in `_render_template'
actionview (6.1.3.2) lib/action_view/rendering.rb:103:in `render_to_body'
actionpack (6.1.3.2) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (6.1.3.2) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (6.1.3.2) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (6.1.3.2) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (6.1.3.2) lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
/home/bdezonia/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
activesupport (6.1.3.2) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (6.1.3.2) lib/action_controller/metal/instrumentation.rb:46:in `block in render'
actionpack (6.1.3.2) lib/action_controller/metal/instrumentation.rb:86:in `cleanup_view_runtime'
activerecord (6.1.3.2) lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
actionpack (6.1.3.2) lib/action_controller/metal/instrumentation.rb:45:in `render'
wicked_pdf (2.1.0) lib/wicked_pdf/pdf_helper.rb:46:in `call'
wicked_pdf (2.1.0) lib/wicked_pdf/pdf_helper.rb:46:in `render_with_wicked_pdf'
wicked_pdf (2.1.0) lib/wicked_pdf/pdf_helper.rb:30:in `render'
responders (3.0.1) lib/action_controller/responder.rb:240:in `default_render'
responders (3.0.1) lib/action_controller/responder.rb:172:in `to_html'
responders (3.0.1) lib/responders/flash_responder.rb:109:in `to_html'
responders (3.0.1) lib/action_controller/responder.rb:165:in `respond'
responders (3.0.1) lib/action_controller/responder.rb:158:in `call'
responders (3.0.1) lib/action_controller/respond_with.rb:213:in `respond_with'
inherited_resources (1.12.0) lib/inherited_resources/actions.rb:7:in `index'
activeadmin (2.9.0) lib/active_admin/resource_controller/streaming.rb:12:in `index'
actionpack (6.1.3.2) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.1.3.2) lib/abstract_controller/base.rb:228:in `process_action'
actionpack (6.1.3.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.1.3.2) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.1.3.2) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
react-rails (2.6.1) lib/react/rails/controller_lifecycle.rb:31:in `use_react_component_helper'
activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
actiontext (6.1.3.2) lib/action_text/rendering.rb:20:in `with_renderer'
actiontext (6.1.3.2) lib/action_text/engine.rb:55:in `block (4 levels) in <class:Engine>'
activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `instance_exec'
activesupport (6.1.3.2) lib/active_support/callbacks.rb:126:in `block in run_callbacks'
activesupport (6.1.3.2) lib/active_support/callbacks.rb:137:in `run_callbacks'
actionpack (6.1.3.2) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.1.3.2) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.1.3.2) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (6.1.3.2) lib/active_support/notifications.rb:203:in `block in instrument'
activesupport (6.1.3.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.1.3.2) lib/active_support/notifications.rb:203:in `instrument'
actionpack (6.1.3.2) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
actionpack (6.1.3.2) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
activerecord (6.1.3.2) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.1.3.2) lib/abstract_controller/base.rb:165:in `process'
actionview (6.1.3.2) lib/action_view/rendering.rb:39:in `process'
actionpack (6.1.3.2) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (6.1.3.2) lib/action_controller/metal.rb:254:in `dispatch'
actionpack (6.1.3.2) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (6.1.3.2) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.1.3.2) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (6.1.3.2) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.1.3.2) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.1.3.2) lib/action_dispatch/routing/route_set.rb:842:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (6.1.3.2) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
actionpack (6.1.3.2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.1.3.2) lib/action_dispatch/middleware/cookies.rb:689:in `call'
activerecord (6.1.3.2) lib/active_record/migration.rb:601:in `call'
actionpack (6.1.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.3.2) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.1.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.1.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.3.2) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.3.2) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.3.2) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.3.2) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.1.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
actionpack (6.1.3.2) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.3.2) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.3.2) lib/action_dispatch/middleware/host_authorization.rb:98:in `call'
rack-mini-profiler (2.3.2) lib/mini_profiler/profiler.rb:384:in `call'
webpacker (5.2.1) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.1.3.2) lib/rails/engine.rb:539:in `call'
puma (5.2.2) lib/puma/configuration.rb:248:in `call'
puma (5.2.2) lib/puma/request.rb:76:in `block in handle_request'
puma (5.2.2) lib/puma/thread_pool.rb:337:in `with_force_shutdown'
puma (5.2.2) lib/puma/request.rb:75:in `handle_request'
puma (5.2.2) lib/puma/server.rb:431:in `process_client'
puma (5.2.2) lib/puma/thread_pool.rb:145:in `block in spawn_thread' 

```
Please let me know if there is anything you need me to provide.

**Comment by deivid-rodriguez** [comment]
Run `bundle update inherited_resources` and you should be ok.
