### ISSUE TITLE
Running `bin/rake` immediately after `git clone` and `bundle install` causes "pg is not part of the bundle" error

### ISSUE THREAD

**Issue by vfonic** [activeadmin/activeadmin#7639]
### Did you find a bug?

> Error loading the 'postgresql' Active Record adapter. Missing a gem it depends on? pg is not part of the bundle. Add it to your Gemfile.

<details>
<summary>
Here's the full output
</summary>

```
> bundle exec rake       
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
Using -d=postgresql --skip-test --skip-system-test --javascript=esbuild --css=tailwind from /Users/viktor/.railsrc
      create  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  .gitattributes
      create  Gemfile
         run  git init from "."
Initialized empty Git repository in /Users/viktor/Developer/gems/activeadmin/tmp/test_apps/rails_70/.git/
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images
      create  app/assets/images/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/cable.yml
      create  config/puma.rb
      create  config/storage.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/assets.rb
      create  config/initializers/content_security_policy.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/new_framework_defaults_7_0.rb
      create  config/initializers/permissions_policy.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/master.key
      append  .gitignore
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  tmp
      create  tmp/.keep
      create  tmp/pids
      create  tmp/pids/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor
      create  vendor/.keep
      create  storage
      create  storage/.keep
      create  tmp/storage
      create  tmp/storage/.keep
      remove  config/initializers/cors.rb
      remove  config/initializers/new_framework_defaults_7_0.rb
       apply  /Users/viktor/Developer/gems/activeadmin/spec/support/rails_template.rb
      create    app/assets/stylesheets/some-random-css.css
      create    app/assets/javascripts/some-random-js.js
      create    app/assets/images/a/favicon.ico
      create    db/migrate/20225015125000_create_posts.rb
      create    app/models/post.rb
      create    app/models/post_decorator.rb
      create    app/models/post_poro_decorator.rb
      create    db/migrate/20225015125001_create_blog_posts.rb
      create    app/models/blog/post.rb
      create    db/migrate/20225015125002_create_profiles.rb
      create    app/models/user.rb
      create    db/migrate/20225015125003_create_users.rb
      create    app/models/profile.rb
      create    app/models/publisher.rb
      create    db/migrate/20225015125004_create_categories.rb
      create    app/models/category.rb
      create    app/models/store.rb
      create    db/migrate/20225015125005_create_stores.rb
      create    db/migrate/20225015125006_create_tags.rb
      create    app/models/tag.rb
      create    db/migrate/20225015125007_create_taggings.rb
      create    app/models/tagging.rb
      create    app/helpers/time_helper.rb
        gsub    config/environments/test.rb
      insert    config/environments/test.rb
        gsub    config/boot.rb
    generate    active_admin:install
       rails    generate active_admin:install 
/Users/viktor/.rvm/gems/ruby-3.1.2/gems/bundler-2.3.12/lib/bundler/rubygems_integration.rb:291:in `block (2 levels) in replace_gem': Error loading the 'postgresql' Active Record adapter. Missing a gem it depends on? pg is not part of the bundle. Add it to your Gemfile. (LoadError)
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:3:in `<top (required)>'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract/connection_handler.rb:268:in `resolve_pool_config'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract/connection_handler.rb:129:in `establish_connection'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/activerecord-7.0.2.3/lib/active_record/connection_handling.rb:52:in `establish_connection'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/activerecord-7.0.2.3/lib/active_record/railtie.rb:278:in `block (2 levels) in <class:Railtie>'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:42:in `each'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:42:in `on_load'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/activerecord-7.0.2.3/lib/active_record/railtie.rb:272:in `block in <class:Railtie>'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/railties-7.0.2.3/lib/rails/initializable.rb:32:in `instance_exec'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/railties-7.0.2.3/lib/rails/initializable.rb:32:in `run'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/railties-7.0.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /Users/viktor/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
        from /Users/viktor/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /Users/viktor/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /Users/viktor/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /Users/viktor/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `each'
        from /Users/viktor/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `call'
        from /Users/viktor/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
        from /Users/viktor/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
        from /Users/viktor/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/railties-7.0.2.3/lib/rails/initializable.rb:60:in `run_initializers'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/railties-7.0.2.3/lib/rails/application.rb:372:in `initialize!'
        from /Users/viktor/Developer/gems/activeadmin/tmp/test_apps/rails_70/config/environment.rb:5:in `<top (required)>'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/railties-7.0.2.3/lib/rails/application.rb:348:in `require_environment!'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/railties-7.0.2.3/lib/rails/command/actions.rb:28:in `require_environment!'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/railties-7.0.2.3/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/railties-7.0.2.3/lib/rails/commands/generate/generate_command.rb:21:in `perform'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/railties-7.0.2.3/lib/rails/command/base.rb:87:in `perform'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/railties-7.0.2.3/lib/rails/command.rb:48:in `invoke'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/railties-7.0.2.3/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
/Users/viktor/.rvm/gems/ruby-3.1.2/gems/bundler-2.3.12/lib/bundler/rubygems_integration.rb:291:in `block (2 levels) in replace_gem': pg is not part of the bundle. Add it to your Gemfile. (Gem::LoadError)
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:3:in `<top (required)>'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract/connection_handler.rb:268:in `resolve_pool_config'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract/connection_handler.rb:129:in `establish_connection'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/activerecord-7.0.2.3/lib/active_record/connection_handling.rb:52:in `establish_connection'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/activerecord-7.0.2.3/lib/active_record/railtie.rb:278:in `block (2 levels) in <class:Railtie>'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:42:in `each'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/activesupport-7.0.2.3/lib/active_support/lazy_load_hooks.rb:42:in `on_load'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/activerecord-7.0.2.3/lib/active_record/railtie.rb:272:in `block in <class:Railtie>'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/railties-7.0.2.3/lib/rails/initializable.rb:32:in `instance_exec'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/railties-7.0.2.3/lib/rails/initializable.rb:32:in `run'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/railties-7.0.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /Users/viktor/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
        from /Users/viktor/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /Users/viktor/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /Users/viktor/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /Users/viktor/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `each'
        from /Users/viktor/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `call'
        from /Users/viktor/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
        from /Users/viktor/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
        from /Users/viktor/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/railties-7.0.2.3/lib/rails/initializable.rb:60:in `run_initializers'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/railties-7.0.2.3/lib/rails/application.rb:372:in `initialize!'
        from /Users/viktor/Developer/gems/activeadmin/tmp/test_apps/rails_70/config/environment.rb:5:in `<top (required)>'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/railties-7.0.2.3/lib/rails/application.rb:348:in `require_environment!'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/railties-7.0.2.3/lib/rails/command/actions.rb:28:in `require_environment!'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/railties-7.0.2.3/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/railties-7.0.2.3/lib/rails/commands/generate/generate_command.rb:21:in `perform'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/railties-7.0.2.3/lib/rails/command/base.rb:87:in `perform'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/railties-7.0.2.3/lib/rails/command.rb:48:in `invoke'
        from /Users/viktor/.rvm/gems/ruby-3.1.2/gems/railties-7.0.2.3/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```
</details>

### Expected behavior

Tests should run and pass.

### Actual behavior

Error is shown.

### How to reproduce

```sh
> git clone https://github.com/activeadmin/activeadmin
> cd activeadmin
> gem uninstall pg --all
> bundle install
> bundle exec rake
```

**Comment by vfonic** [comment]
It's really difficult to execute tests. Now, even if I add `gem 'pg'` to my `Gemfile`, the default rake task does not try to create the test application anymore, because it already created it. However, it also assumes that it created the database (this is the step that failed) and doesn't try to create the database anymore. This now causes the rake task to fail because there's no database.

So I git-cloned the repo again, added `gem 'pg'` to `Gemfile`, ran `bundle install`, and now I'm getting another error:

<details>

```
> bundle exec rake
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
test app tmp/test_apps/rails_70 already exists; skipping test app generation
bin/parallel_rspec
10 processes for 98 specs, ~ 9 specs per process

bin/rspec --color --tty -O .rspec_parallel spec/unit/collection_decorator_spec.rb spec/unit/form_builder_spec.rb spec/unit/page_controller_spec.rb spec/unit/resource/pagination_spec.rb spec/unit/resource/scopes_spec.rb

An error occurred while loading ./spec/unit/collection_decorator_spec.rb.
Failure/Error:
  RSpec.describe ActiveAdmin::CollectionDecorator do
    describe "#decorated_collection" do
      subject { collection.decorated_collection }
      let(:collection) { ActiveAdmin::CollectionDecorator.decorate((1..10).to_a, with: NumberDecorator) }

      it "returns an array of decorated objects" do
        expect(subject).to all(be_a(NumberDecorator))
      end
    end

NameError:
  uninitialized constant ActiveAdmin::CollectionDecorator

  RSpec.describe ActiveAdmin::CollectionDecorator do
                            ^^^^^^^^^^^^^^^^^^^^^
# ./spec/unit/collection_decorator_spec.rb:14:in `<top (required)>'
Run options:
  include {:focus=>true}
  exclude {:changes_filesystem=>true}

All examples were filtered out; ignoring {:focus=>true}


Finished in 0.00008 seconds (files took 4.61 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples


bin/rspec --color --tty -O .rspec_parallel spec/requests/memory_spec.rb spec/unit/action_builder_spec.rb spec/unit/auto_link_spec.rb spec/unit/batch_actions/resource_spec.rb spec/unit/filters/active_spec.rb spec/unit/pundit_adapter_spec.rb spec/unit/resource/attributes_spec.rb spec/unit/views/components/panel_spec.rb spec/unit/views/components/table_for_spec.rb spec/unit/views/pages/base_spec.rb
```
</details>

I don't have the time nor expertise to figure all these errors out. I wanted to submit a `||` => `&&` fix in JS and now I'm just going down the rabbit hole. I'll submit the PR for the changes I've made without testing them as I don't want to invest half of a day trying to run the test suite. :/
This should be fixed as it would help other devs help the project.

Thanks!

**Comment by javierjulio** [comment]
This is likely an issue with your setup as we don't use Postgres for the test app, just SQLite. The arguments listed in the output are incorrect for the test app generated as we don't use those.
