### ISSUE TITLE
Wrong arguments are passed to custom Ransack scope

### ISSUE THREAD

**Issue by dssjoblom** [activeadmin/activeadmin#7802]
### Did you find a bug?

Yes, this looks like a bug.

When defining a custom scope for a model, e.g.

```
  scope :by_pickup_station_id, ->(id) { (id == 'none' ? where(pickup_station_id: nil) : where(pickup_station_id: id)) }

  def self.ransackable_scopes(_auth_object = nil)
    [:by_pickup_station_id]
  end
```

and then using this in the AA page:

```
  filter :by_pickup_station_id, label: 'Pickup Station', as: :select, collection: -> {
    [['None', 'none']] + Station.sorted.map { |s| [s.name, s.id] }
  }
```

It seems like what arguments are passed to the scope depend on the value selected by ther user (?). For example, the following request is successful (id=6):

```
13:42:25 rails.1   | [127.0.0.1] Started GET "/admin/orders?q%5Bby_pickup_station_id%5D=6&commit=Filter&order=id_desc" for 127.0.0.1 at 2023-02-21 13:42:25 +0200
13:42:25 rails.1   | [127.0.0.1] Processing by Admin::OrdersController#index as HTML
13:42:25 rails.1   | [127.0.0.1]   Parameters: {"q"=>{"by_pickup_station_id"=>"6"}, "commit"=>"Filter", "order"=>"id_desc"}
13:42:25 rails.1   | [127.0.0.1] Default processing will use database mini_corona_development
13:42:25 rails.1   | 6
13:42:25 rails.1   | [127.0.0.1] Completed 200 OK in 225ms (Views: 195.0ms | ActiveRecord: 18.2ms | Allocations: 198797)
```

, while if the id=1, this happens instead:

```
13:42:30 rails.1   | [127.0.0.1] Started GET "/admin/orders?q%5Bby_pickup_station_id%5D=1&commit=Filter&order=id_desc" for 127.0.0.1 at 2023-02-21 13:42:30 +0200
13:42:30 rails.1   | [127.0.0.1] Processing by Admin::OrdersController#index as HTML
13:42:30 rails.1   | [127.0.0.1]   Parameters: {"q"=>{"by_pickup_station_id"=>"1"}, "commit"=>"Filter", "order"=>"id_desc"}
13:42:30 rails.1   | [127.0.0.1] Default processing will use database mini_corona_development
13:42:30 rails.1   | [127.0.0.1] Completed 500 Internal Server Error in 17ms (ActiveRecord: 5.8ms | Allocations: 2413)
13:42:30 rails.1   | 
13:42:30 rails.1   | 
13:42:30 rails.1   | [127.0.0.1] wrong number of arguments (given 0, expected 1)
13:42:30 rails.1   | [127.0.0.1] /home/daniel/projects/myapp/app/models/order.rb:166:in `block in <class:Order>'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/activerecord-6.1.7.1/lib/active_record/relation.rb:411:in `instance_exec'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/activerecord-6.1.7.1/lib/active_record/relation.rb:411:in `block in _exec_scope'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/activerecord-6.1.7.1/lib/active_record/relation.rb:804:in `_scoping'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/activerecord-6.1.7.1/lib/active_record/relation.rb:411:in `_exec_scope'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/activerecord-6.1.7.1/lib/active_record/scoping/named.rb:176:in `block in scope'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/activerecord-6.1.7.1/lib/active_record/relation/delegation.rb:67:in `block in by_pickup_station_id'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/activerecord-6.1.7.1/lib/active_record/relation.rb:406:in `block in scoping'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/activerecord-6.1.7.1/lib/active_record/relation.rb:804:in `_scoping'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/activerecord-6.1.7.1/lib/active_record/relation.rb:406:in `scoping'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/activerecord-6.1.7.1/lib/active_record/relation/delegation.rb:67:in `by_pickup_station_id'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/ransack-2.6.0/lib/ransack/context.rb:50:in `public_send'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/ransack-2.6.0/lib/ransack/context.rb:50:in `chain_scope'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/ransack-2.6.0/lib/ransack/search.rb:140:in `add_scope'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/ransack-2.6.0/lib/ransack/search.rb:49:in `block in build'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/ransack-2.6.0/lib/ransack/search.rb:43:in `each'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/ransack-2.6.0/lib/ransack/search.rb:43:in `build'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/ransack-2.6.0/lib/ransack/search.rb:35:in `initialize'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/ransack-2.6.0/lib/ransack/adapters/active_record/base.rb:18:in `new'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/ransack-2.6.0/lib/ransack/adapters/active_record/base.rb:18:in `ransack'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/activerecord-6.1.7.1/lib/active_record/relation/delegation.rb:67:in `block in ransack'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/activerecord-6.1.7.1/lib/active_record/relation.rb:406:in `block in scoping'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/activerecord-6.1.7.1/lib/active_record/relation.rb:804:in `_scoping'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/activerecord-6.1.7.1/lib/active_record/relation.rb:406:in `scoping'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/activerecord-6.1.7.1/lib/active_record/relation/delegation.rb:67:in `ransack'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/activeadmin-2.13.1/lib/active_admin/resource_controller/data_access.rb:218:in `apply_filtering'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/activeadmin-2.13.1/lib/active_admin/resource_controller/data_access.rb:60:in `block in find_collection'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/activeadmin-2.13.1/lib/active_admin/resource_controller/data_access.rb:59:in `each'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/activeadmin-2.13.1/lib/active_admin/resource_controller/data_access.rb:59:in `find_collection'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/activeadmin-2.13.1/lib/active_admin/resource_controller/data_access.rb:45:in `collection'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/inherited_resources-1.13.1/lib/inherited_resources/actions.rb:7:in `index'
13:42:30 rails.1   | /home/daniel/.rvm/gems/ruby-3.1.3/gems/activeadmin-2.13.1/lib/active_admin/resource_controller/streaming.rb:13:in `index'
```

### Expected behavior

I expect the arguments to be passed consistently to the scope.

### Actual behavior

The arguments are passed differently depending on what the value is.

### How to reproduce

See the  sample code.

**Comment by dssjoblom** [comment]
I tested this a bit more, and the magic value for which this doesn't work correctly is 1 (e.g. id=1).

**Comment by harunkumars** [comment]
@dssjoblom not 100% sure but could it be this: https://activerecord-hackery.github.io/ransack/going-further/other-notes/#:~:text=you%20do%20not%20want%20Ransack%20to%20convert%201 that is causing the problem?

**Comment by dssjoblom** [comment]
@harunkumars that was it. Thanks a lot, this was driving me insane. 

I guess this issue can be closed now, but it would be nice if it was mentioned in the documentation for AA somewhere. Although it seems like custom filtering is completely missing from https://activeadmin.info/3-index-pages.html, so there's no good place for it right now.

**Comment by javierjulio** [comment]
Ransack is mentioned on that page for the "Index Filters" section. https://github.com/activeadmin/activeadmin/blob/3dcb1834620f38f73ac5c1f550f37986d486f29c/docs/3-index-pages.md#index-filters

We'd be open to a PR to improve those docs and for adding some info around this. That would be helpful. Thanks!
