### ISSUE TITLE
Defining Actions in Index as a Table (4.0.0.beta3)

### ISSUE THREAD

**Issue by thibaudgg** [activeadmin/activeadmin#8233]
I'm giving a try to v4 beta 3 on [my app](https://github.com/acp-admin/acp-admin) which is making use of the custom actions in the index as a table index page.

[Example](https://github.com/acp-admin/acp-admin/blob/master/app/admin/delivery.rb):
``` ruby
ActiveAdmin.register Delivery do
  index do
    # ...
    actions defaults: true, class: "col-actions-6" do |delivery|
      # Custom links on top of the defaults one
      link_to("CSV", baskets_path(q: { delivery_id_eq: delivery.id }, format: :csv), class: "csv_link") +
      link_to("XLSX", delivery_path(delivery, format: :xlsx), class: "xlsx_link") +
        link_to("PDF", delivery_path(delivery, format: :pdf), class: "pdf_link", target: "_blank")
    end
  end
end
```

This currently raises the following issue on 4.0.0.beta3:
```
undefined method `actions' for an instance of ActiveAdmin::Views::IndexAsTable

arbre (2.0.0) lib/arbre/element.rb:185:in `method_missing'
app/admin/delivery.rb:37:in `block (2 levels) in <main>'
config/initializers/active_admin.rb:459:in `instance_exec'
config/initializers/active_admin.rb:459:in `block in build'
arbre (2.0.0) lib/arbre/element.rb:35:in `build'
arbre (2.0.0) lib/arbre/html/tag.rb:20:in `build'
config/initializers/active_admin.rb:480:in `build'
arbre (2.0.0) lib/arbre/element/builder_methods.rb:28:in `block in build_tag'
arbre (2.0.0) lib/arbre/context.rb:93:in `with_current_arbre_element'
arbre (2.0.0) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (2.0.0) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (2.0.0) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (2.0.0) lib/arbre/element/builder_methods.rb:14:in `table_for'
config/initializers/active_admin.rb:457:in `build'
arbre (2.0.0) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
arbre (2.0.0) lib/arbre/context.rb:93:in `with_current_arbre_element'
arbre (2.0.0) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (2.0.0) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
activeadmin (4.0.0.beta3) app/views/active_admin/resource/index.html.arb:87:in `block in render_index'
arbre (2.0.0) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (2.0.0) lib/arbre/context.rb:93:in `with_current_arbre_element'
arbre (2.0.0) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (2.0.0) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (2.0.0) lib/arbre/element/builder_methods.rb:14:in `paginated_collection'
activeadmin (4.0.0.beta3) app/views/active_admin/resource/index.html.arb:80:in `render_index'
activeadmin (4.0.0.beta3) app/views/active_admin/resource/index.html.arb:24:in `build_collection'
activeadmin (4.0.0.beta3) app/views/active_admin/resource/index.html.arb:94
arbre (2.0.0) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (2.0.0) lib/arbre/context.rb:93:in `with_current_arbre_element'
arbre (2.0.0) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (2.0.0) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
activeadmin (4.0.0.beta3) app/views/active_admin/resource/index.html.arb:5:in `wrap_with_batch_action_form'
activeadmin (4.0.0.beta3) app/views/active_admin/resource/index.html.arb:92
arbre (2.0.0) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (2.0.0) lib/arbre/context.rb:93:in `with_current_arbre_element'
arbre (2.0.0) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (2.0.0) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (2.0.0) lib/arbre/element/builder_methods.rb:14:in `div'
activeadmin (4.0.0.beta3) app/views/active_admin/resource/index.html.arb:91
arbre (2.0.0) lib/arbre/context.rb:46:in `instance_eval'
arbre (2.0.0) lib/arbre/context.rb:46:in `initialize'
activeadmin (4.0.0.beta3) app/views/active_admin/resource/index.html.arb:1:in `new'
activeadmin (4.0.0.beta3) app/views/active_admin/resource/index.html.arb:1
actionview (7.1.2) lib/action_view/base.rb:264:in `public_send'
actionview (7.1.2) lib/action_view/base.rb:264:in `_run'
actionview (7.1.2) lib/action_view/template.rb:261:in `block in render'
activesupport (7.1.2) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.1.2) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
activesupport (7.1.2) lib/active_support/notifications.rb:206:in `instrument'
actionview (7.1.2) lib/action_view/template.rb:549:in `instrument_render_template'
actionview (7.1.2) lib/action_view/template.rb:249:in `render'
actionview (7.1.2) lib/action_view/renderer/template_renderer.rb:66:in `block (2 levels) in render_template'
activesupport (7.1.2) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.1.2) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
activesupport (7.1.2) lib/active_support/notifications.rb:206:in `instrument'
actionview (7.1.2) lib/action_view/renderer/template_renderer.rb:60:in `block in render_template'
actionview (7.1.2) lib/action_view/renderer/template_renderer.rb:76:in `block in render_with_layout'
activesupport (7.1.2) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.1.2) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
activesupport (7.1.2) lib/active_support/notifications.rb:206:in `instrument'
actionview (7.1.2) lib/action_view/renderer/template_renderer.rb:75:in `render_with_layout'
actionview (7.1.2) lib/action_view/renderer/template_renderer.rb:59:in `render_template'
actionview (7.1.2) lib/action_view/renderer/template_renderer.rb:11:in `render'
actionview (7.1.2) lib/action_view/renderer/renderer.rb:63:in `render_template_to_object'
actionview (7.1.2) lib/action_view/renderer/renderer.rb:31:in `render_to_object'
actionview (7.1.2) lib/action_view/rendering.rb:135:in `block in _render_template'
actionview (7.1.2) lib/action_view/base.rb:291:in `in_rendering_context'
actionview (7.1.2) lib/action_view/rendering.rb:134:in `_render_template'
actionpack (7.1.2) lib/action_controller/metal/streaming.rb:256:in `_render_template'
actionview (7.1.2) lib/action_view/rendering.rb:121:in `render_to_body'
actionpack (7.1.2) lib/action_controller/metal/rendering.rb:158:in `render_to_body'
actionpack (7.1.2) lib/action_controller/metal/renderers.rb:141:in `render_to_body'
actionpack (7.1.2) lib/abstract_controller/rendering.rb:27:in `render'
actionpack (7.1.2) lib/action_controller/metal/rendering.rb:139:in `render'
actionpack (7.1.2) lib/action_controller/metal/instrumentation.rb:29:in `block (2 levels) in render'
/Users/thibaudgg/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/benchmark.rb:313:in `realtime'
activesupport (7.1.2) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (7.1.2) lib/action_controller/metal/instrumentation.rb:29:in `block in render'
actionpack (7.1.2) lib/action_controller/metal/instrumentation.rb:98:in `cleanup_view_runtime'
activerecord (7.1.2) lib/active_record/railties/controller_runtime.rb:39:in `cleanup_view_runtime'
actionpack (7.1.2) lib/action_controller/metal/instrumentation.rb:28:in `render'
responders (3.1.1) lib/action_controller/responder.rb:245:in `default_render'
responders (3.1.1) lib/action_controller/responder.rb:175:in `to_html'
responders (3.1.1) lib/responders/flash_responder.rb:105:in `to_html'
responders (3.1.1) lib/action_controller/responder.rb:168:in `respond'
responders (3.1.1) lib/action_controller/responder.rb:161:in `call'
responders (3.1.1) lib/action_controller/respond_with.rb:216:in `respond_with'
inherited_resources (1.14.0) lib/inherited_resources/actions.rb:7:in `index'
activeadmin (4.0.0.beta3) app/controllers/active_admin/resource_controller/streaming.rb:13:in `index'
actionpack (7.1.2) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (7.1.2) lib/abstract_controller/base.rb:224:in `process_action'
actionpack (7.1.2) lib/action_controller/metal/rendering.rb:165:in `process_action'
actionpack (7.1.2) lib/abstract_controller/callbacks.rb:259:in `block in process_action'
activesupport (7.1.2) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
actiontext (7.1.2) lib/action_text/rendering.rb:23:in `with_renderer'
actiontext (7.1.2) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
activesupport (7.1.2) lib/active_support/callbacks.rb:130:in `instance_exec'
activesupport (7.1.2) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
sentry-rails (5.16.1) lib/sentry/rails/controller_transaction.rb:28:in `block in sentry_around_action'
sentry-ruby (5.16.1) lib/sentry/hub.rb:102:in `with_child_span'
sentry-ruby (5.16.1) lib/sentry-ruby.rb:478:in `with_child_span'
sentry-rails (5.16.1) lib/sentry/rails/controller_transaction.rb:14:in `sentry_around_action'
activesupport (7.1.2) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
activesupport (7.1.2) lib/active_support/callbacks.rb:141:in `run_callbacks'
actionpack (7.1.2) lib/abstract_controller/callbacks.rb:258:in `process_action'
actionpack (7.1.2) lib/action_controller/metal/rescue.rb:25:in `process_action'
actionpack (7.1.2) lib/action_controller/metal/instrumentation.rb:74:in `block in process_action'
activesupport (7.1.2) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.1.2) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
activesupport (7.1.2) lib/active_support/notifications.rb:206:in `instrument'
actionpack (7.1.2) lib/action_controller/metal/instrumentation.rb:73:in `process_action'
actionpack (7.1.2) lib/action_controller/metal/params_wrapper.rb:261:in `process_action'
activerecord (7.1.2) lib/active_record/railties/controller_runtime.rb:32:in `process_action'
actionpack (7.1.2) lib/abstract_controller/base.rb:160:in `process'
actionview (7.1.2) lib/action_view/rendering.rb:40:in `process'
actionpack (7.1.2) lib/action_controller/metal.rb:227:in `dispatch'
actionpack (7.1.2) lib/action_controller/metal.rb:309:in `dispatch'
actionpack (7.1.2) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (7.1.2) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (7.1.2) lib/action_dispatch/journey/router.rb:51:in `block in serve'
actionpack (7.1.2) lib/action_dispatch/journey/router.rb:131:in `block in find_routes'
actionpack (7.1.2) lib/action_dispatch/journey/router.rb:124:in `each'
actionpack (7.1.2) lib/action_dispatch/journey/router.rb:124:in `find_routes'
actionpack (7.1.2) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.1.2) lib/action_dispatch/routing/route_set.rb:882:in `call'
lib/tenant/middleware.rb:12:in `block in call'
lib/tenant.rb:28:in `switch'
lib/tenant/middleware.rb:12:in `call'
bullet (7.1.5) lib/bullet/rack.rb:17:in `call'
rack (3.0.8) lib/rack/tempfile_reaper.rb:20:in `call'
rack (3.0.8) lib/rack/etag.rb:29:in `call'
rack (3.0.8) lib/rack/conditional_get.rb:31:in `call'
rack (3.0.8) lib/rack/head.rb:15:in `call'
actionpack (7.1.2) lib/action_dispatch/http/permissions_policy.rb:36:in `call'
actionpack (7.1.2) lib/action_dispatch/http/content_security_policy.rb:33:in `call'
rack-session (2.0.0) lib/rack/session/abstract/id.rb:272:in `context'
rack-session (2.0.0) lib/rack/session/abstract/id.rb:266:in `call'
actionpack (7.1.2) lib/action_dispatch/middleware/cookies.rb:689:in `call'
activerecord (7.1.2) lib/active_record/migration.rb:654:in `call'
actionpack (7.1.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (7.1.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (7.1.2) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
actionpack (7.1.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.1.2) lib/action_dispatch/middleware/actionable_exceptions.rb:16:in `call'
sentry-rails (5.16.1) lib/sentry/rails/rescued_exception_interceptor.rb:12:in `call'
actionpack (7.1.2) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
web-console (4.2.1) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.2.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.2.1) lib/web_console/middleware.rb:17:in `catch'
web-console (4.2.1) lib/web_console/middleware.rb:17:in `call'
sentry-ruby (5.16.1) lib/sentry/rack/capture_exceptions.rb:28:in `block (2 levels) in call'
sentry-ruby (5.16.1) lib/sentry/hub.rb:251:in `with_session_tracking'
sentry-ruby (5.16.1) lib/sentry-ruby.rb:391:in `with_session_tracking'
sentry-ruby (5.16.1) lib/sentry/rack/capture_exceptions.rb:19:in `block in call'
sentry-ruby (5.16.1) lib/sentry/hub.rb:59:in `with_scope'
sentry-ruby (5.16.1) lib/sentry-ruby.rb:371:in `with_scope'
sentry-ruby (5.16.1) lib/sentry/rack/capture_exceptions.rb:18:in `call'
actionpack (7.1.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (7.1.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (7.1.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (7.1.2) lib/active_support/tagged_logging.rb:135:in `block in tagged'
activesupport (7.1.2) lib/active_support/tagged_logging.rb:39:in `tagged'
activesupport (7.1.2) lib/active_support/tagged_logging.rb:135:in `tagged'
activesupport (7.1.2) lib/active_support/broadcast_logger.rb:240:in `method_missing'
railties (7.1.2) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (7.1.2) lib/action_dispatch/middleware/remote_ip.rb:92:in `call'
request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'
actionpack (7.1.2) lib/action_dispatch/middleware/request_id.rb:28:in `call'
rack (3.0.8) lib/rack/method_override.rb:28:in `call'
rack (3.0.8) lib/rack/runtime.rb:24:in `call'
actionpack (7.1.2) lib/action_dispatch/middleware/server_timing.rb:59:in `block in call'
actionpack (7.1.2) lib/action_dispatch/middleware/server_timing.rb:24:in `collect_events'
actionpack (7.1.2) lib/action_dispatch/middleware/server_timing.rb:58:in `call'
actionpack (7.1.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.1.2) lib/action_dispatch/middleware/static.rb:25:in `call'
rack (3.0.8) lib/rack/sendfile.rb:114:in `call'
actionpack (7.1.2) lib/action_dispatch/middleware/host_authorization.rb:141:in `call'
rack-cors (2.0.1) lib/rack/cors.rb:102:in `call'
railties (7.1.2) lib/rails/engine.rb:529:in `call'
rack-status (1.0.0) lib/rack/status.rb:13:in `call'
puma (6.4.2) lib/puma/configuration.rb:272:in `call'
puma (6.4.2) lib/puma/request.rb:100:in `block in handle_request'
puma (6.4.2) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
puma (6.4.2) lib/puma/request.rb:99:in `handle_request'
puma (6.4.2) lib/puma/server.rb:464:in `process_client'
puma (6.4.2) lib/puma/server.rb:245:in `block in run'
puma (6.4.2) lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

**Comment by javierjulio** [comment]
@thibaudgg this is due to the monkey patch based on the stack trace which would make sense. This isn't reproducible for us. These actions do work so you should be good once the monkey patch is addressed or updated.

**Comment by thibaudgg** [comment]
Whoops, my bad, I was able to fix my monkey patch and make it work. I will try to submit it as PR when I have some time.

**Comment by javierjulio** [comment]
No worries. Ok great, thank you!
