### ISSUE TITLE
Feature: Rails 8.0 support

### ISSUE THREAD

**Issue by tagliala** [activeadmin/activeadmin#8499]
### Errors

```
NameError:
  uninitialized constant ActiveAdmin::CollectionDecorator
# ./spec/unit/collection_decorator_spec.rb:14:in `<top (required)>'
```

```
NameError:
  uninitialized constant ActiveAdmin::BatchActions
# ./spec/unit/batch_actions/resource_spec.rb:4:in `<top (required)>'
```

#### Bisect

Ref: https://github.com/rails/rails/pull/51614
Commit: rails/rails@e54f869e431372ba30bb6a00c8b58cbba692de7e

Should be a problem only when eager_load is false. Let's see on the CI

### Failures

```
rspec ./spec/unit/csv_builder_spec.rb[1:12:5] # ActiveAdmin::CSVBuilder csv injection prepends a single quote when column starts with a - character
rspec ./spec/unit/csv_builder_spec.rb[1:12:6] # ActiveAdmin::CSVBuilder csv injection accounts for the field separator when character - is used to inject a formula
rspec ./spec/unit/csv_builder_spec.rb[1:12:2] # ActiveAdmin::CSVBuilder csv injection accounts for the field separator when character = is used to inject a formula
rspec ./spec/unit/csv_builder_spec.rb[1:12:4] # ActiveAdmin::CSVBuilder csv injection accounts for the field separator when character + is used to inject a formula
rspec ./spec/unit/csv_builder_spec.rb[1:12:3] # ActiveAdmin::CSVBuilder csv injection prepends a single quote when column starts with a + character
rspec ./spec/unit/csv_builder_spec.rb[1:12:8] # ActiveAdmin::CSVBuilder csv injection accounts for the field separator when character @ is used to inject a formula
rspec ./spec/unit/csv_builder_spec.rb[1:12:10] # ActiveAdmin::CSVBuilder csv injection accounts for the field separator when character 	 is used to inject a formula
rspec ./spec/unit/csv_builder_spec.rb[1:12:9] # ActiveAdmin::CSVBuilder csv injection prepends a single quote when column starts with a 	 character
 characterec/unit/csv_builder_spec.rb[1:12:11] # ActiveAdmin::CSVBuilder csv injection prepends a single quote when column starts with a 
rspec ./spec/unit/csv_builder_spec.rb[1:12:7] # ActiveAdmin::CSVBuilder csv injection prepends a single quote when column starts with a @ character
rspec ./spec/unit/csv_builder_spec.rb[1:12:1] # ActiveAdmin::CSVBuilder csv injection prepends a single quote when column starts with a = character
 is used to inject a formular_spec.rb[1:12:12] # ActiveAdmin::CSVBuilder csv injection accounts for the field separator when character 
rspec ./spec/unit/csv_builder_spec.rb:257 # ActiveAdmin::CSVBuilder build csv using specified encoding and encoding_options Shift-JIS with options encodes the CSV
rspec ./spec/unit/csv_builder_spec.rb:271 # ActiveAdmin::CSVBuilder build csv using specified encoding and encoding_options ASCII with options encodes the CSV without errors
rspec ./spec/unit/csv_builder_spec.rb:227 # ActiveAdmin::CSVBuilder build csv using the supplied order should generate data with the supplied order
rspec ./spec/unit/application_spec.rb:143 # ActiveAdmin::Application#namespace should not pollute the global app
```

```
rspec ./spec/unit/batch_actions/settings_spec.rb:35 # Batch Actions Settings should be settable at the resource level
rspec ./spec/unit/batch_actions/settings_spec.rb:51 # Batch Actions Settings should inherit the setting from the namespace when set to nil
rspec ./spec/unit/batch_actions/settings_spec.rb:9 # Batch Actions Settings should be disabled globally by default
rspec ./spec/unit/batch_actions/settings_spec.rb:41 # Batch Actions Settings should inherit the setting on the resource from the namespace
```

```
rspec ./spec/unit/comments_spec.rb:153 # Comments ActiveAdmin::Comment Commenting on resource with string id should allow commenting
rspec ./spec/unit/comments_spec.rb:59 # Comments ActiveAdmin::Comment.find_for_resource_in_namespace should return a comment for the resource in the same namespace
rspec ./spec/unit/comments_spec.rb:74 # Comments ActiveAdmin::Comment.find_for_resource_in_namespace should return the most recent comment first by default
rspec ./spec/unit/comments_spec.rb:63 # Comments ActiveAdmin::Comment.find_for_resource_in_namespace should not return a comment for the same resource in a different namespace
rspec ./spec/unit/comments_spec.rb:69 # Comments ActiveAdmin::Comment.find_for_resource_in_namespace should not return a comment for a different resource
rspec ./spec/unit/comments_spec.rb:104 # Comments ActiveAdmin::Comment.find_for_resource_in_namespace when custom ordering configured should return the correctly ordered comments
rspec ./spec/unit/comments_spec.rb:168 # Comments ActiveAdmin::Comment commenting on child of STI resource should assign child class as commented resource
rspec ./spec/unit/resource/comments_spec.rb:15 # ActiveAdmin Comments #destroy success deletes comments and redirects to root fallback
rspec ./spec/unit/resource/comments_spec.rb:21 # ActiveAdmin Comments #destroy success deletes comments and redirects back
rspec ./spec/unit/resource/comments_spec.rb:41 # ActiveAdmin Comments #destroy failure does not delete comment on error and redirects back
rspec ./spec/unit/resource/comments_spec.rb:31 # ActiveAdmin Comments #destroy failure does not delete comment on error and redirects to root fallback
```

**Comment by javierjulio** [comment]
Is this still an issue? Reviewing the linked PR, it was also reverted. Although sounds like that was before the Rails 7.2 release so maybe this is reintroduced on 8.0 beta? The tests are passing in CI. Do you mean you only encounter that error when running the tests locally?

**Comment by tagliala** [comment]
It's still a problem locally on the current main branch as far as I can tell

I will close here for the moment, let's reopen at a later stage of rails development
