### ISSUE TITLE
New Rails 8 + activeadmin:master  `The asset 'active_admin.css' was not found in the load path.`

### ISSUE THREAD

**Issue by krtschmr** [activeadmin/activeadmin#8537]
- App running on Rails 8.1-alpha app
- added active admin with skip-user
- rails s

💥 

```
Started GET "/admin" for ::1 at 2024-11-12 17:20:05 +0100
Processing by Admin::DashboardController#index as HTML
  Rendering layout /usr/share/rvm/gems/ruby-3.3.1/bundler/gems/activeadmin-25a6b3668e0e/app/views/layouts/active_admin.html.erb
  Rendering /usr/share/rvm/gems/ruby-3.3.1/bundler/gems/activeadmin-25a6b3668e0e/app/views/active_admin/page/index.html.arb within layouts/active_admin
  Rendered /usr/share/rvm/gems/ruby-3.3.1/bundler/gems/activeadmin-25a6b3668e0e/app/views/active_admin/page/index.html.arb within layouts/active_admin (Duration: 0.5ms | GC: 0.0ms)
  Rendered /usr/share/rvm/gems/ruby-3.3.1/bundler/gems/activeadmin-25a6b3668e0e/app/views/active_admin/_html_head.html.erb (Duration: 0.5ms | GC: 0.0ms)
  Rendered layout /usr/share/rvm/gems/ruby-3.3.1/bundler/gems/activeadmin-25a6b3668e0e/app/views/layouts/active_admin.html.erb (Duration: 1.5ms | GC: 0.0ms)
Completed 500 Internal Server Error in 25ms (ActiveRecord: 0.0ms (0 queries, 0 cached) | GC: 0.0ms)


  
ActionView::Template::Error (The asset 'active_admin.css' was not found in the load path.)
Caused by: Propshaft::MissingAssetError (The asset 'active_admin.css' was not found in the load path.)

Information for: ActionView::Template::Error (The asset 'active_admin.css' was not found in the load path.):
    1: <%= stylesheet_link_tag "active_admin" %>
    2: <meta name="viewport" content="width=device-width,initial-scale=1">
    3: <%= csrf_meta_tags %>
    4: <%= csp_meta_tag %>
  
propshaft (1.1.0) lib/propshaft/helper.rb:4:in `compute_asset_path'
rails (852d0cd41234) actionview/lib/action_view/helpers/asset_url_helper.rb:204:in `asset_path'
rails (852d0cd41234) actionview/lib/action_view/helpers/asset_url_helper.rb:349:in `stylesheet_path'
rails (852d0cd41234) actionview/lib/action_view/helpers/asset_tag_helper.rb:213:in `block in stylesheet_link_tag'
rails (852d0cd41234) actionview/lib/action_view/helpers/asset_tag_helper.rb:212:in `map'
rails (852d0cd41234) actionview/lib/action_view/helpers/asset_tag_helper.rb:212:in `stylesheet_link_tag'
propshaft (1.1.0) lib/propshaft/helper.rb:16:in `stylesheet_link_tag'
activeadmin (25a6b3668e0e) app/views/active_admin/_html_head.html.erb:1
rails (852d0cd41234) actionview/lib/action_view/base.rb:281:in `public_send'
rails (852d0cd41234) actionview/lib/action_view/base.rb:281:in `_run'

```

unsure how to fix, but following the guides (https://activeadmin.info/0-installation.html) seems broken.

**Comment by krtschmr** [comment]
* activeadmin (4.0.0.beta13 25a6b36)
  * rails (8.1.0.alpha 852d0cd)
